- applications/luci-mjpg-streamer/Makefile
- applications/luci-mjpg-streamer/ipkg/postinst
- applications/luci-mjpg-streamer/luasrc/controller/mjpg-streamer.lua
- applications/luci-mjpg-streamer/luasrc/model/cbi/mjpg-streamer.lua
- applications/luci-mjpg-streamer/root/etc/uci-defaults/luci-mjpg-streamer
- contrib/package/luci-addons/Makefile
- po/templates/mjpg-streamer.pot
Signed-off-by: Ted Hess <thess@kitschensync.net>
> luci-app-mjpg-streamer: Add new module for mjpg-streamer management

- applications/luci-ocserv/luasrc/model/cbi/ocserv/main.lua
> Print the ocserv's certificate hash and key ID

- luci.mk
Sample:
old: "Deutsch (German)"
new: "Translation for luci-app-ddns - Deutsch (German)"
Signed-off-by: Christian Schoenebeck <christian.schoenebeck@gmail.com>
> luci.mk: cosmetic change for translation description

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/detail_lvalue.htm
- applications/luci-app-ddns/luasrc/view/ddns/detail_value.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_startstop.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
- applications/luci-app-ddns/po/de/ddns.po
- applications/luci-app-ddns/po/templates/ddns.pot
- adaption Makefile to changed luci.mk
- description in Makefile for correct version handling
- modified handling to detect and display installed version
- new functions ipkg_ver_installed() and ipkg_ver_compare()
- correct wrong spellings
- updated language template and German translation
> luci-app-ddns: Update to version 2.1.1-0

- applications/luci-app-ocserv/luasrc/controller/ocserv.lua
- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/users.lua
> luci-app-ocserv: modified match to apply to newer versions of occtl

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/luasrc/controller/privoxy.lua
- applications/luci-app-privoxy/luasrc/model/cbi/privoxy/apperror.lua
- applications/luci-app-privoxy/luasrc/model/cbi/privoxy/detail.lua
- applications/luci-app-privoxy/luasrc/view/privoxy/detail_logview.htm
- applications/luci-app-privoxy/luasrc/view/privoxy/detail_startstop.htm
- applications/luci-app-privoxy/po/de/privoxy.po
- applications/luci-app-privoxy/po/templates/privoxy.pot
- applications/luci-app-privoxy/root/etc/uci-defaults/luci-privoxy
* move from openwrt/packages to openwrt/luci
* adaption to new LuCI subdirectory structure
* fix error handling
* modified version handling
* fixed translations
> luci-app-privoxy: move from openwrt/packages to openwrt/luci

- protocols/luci-proto-openconnect/luasrc/model/cbi/admin_network/proto_openconnect.lua
> openconnect: ask for the output interface name

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua
Implements "Back to Overview" button on interface details page
> admin_network: interface details, implement "Back to Overview" button

- applications/luci-app-asterisk/Makefile
Signed-off-by: Jonathan McCrohan <jmccrohan@gmail.com>
> luci-app-asterisk: fix typo in package description

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
> wifi.lua: add "Back to Overview" button

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/global_value.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
- applications/luci-app-ddns/po/de/ddns.po
- applications/luci-app-ddns/po/templates/ddns.pot
- implement new option bind_interface
- fixes problems when updating status displays (i.e. showing Software update needed)
- new links to OpenWrt wiki
- new screen to set global settings
- implements global option use_curl
> luci-app-ddns: update to version 2.2.0-1

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
remove usage of opkg via system call for version handling.
thanks to Jo-Philipp Wich #335
remove special handling of bootstrap theme #298 #334
> luci-app-ddns: patches for #298 #334 #335

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
fix dispatcher and validation errors in global.lua
> luci-app-ddns: fix errors in global.lua

- protocols/luci-proto-openconnect/luasrc/model/cbi/admin_network/proto_openconnect.lua
> luci-proto-openconnect: Added option for default gateway

- applications/luci-app-ddns/po/zh-cn/ddns.po
Simplified Chinese translation for luci-app-ddns has been broken for long.I translated this application these day and created this pull request.
> luci-app-ddns:Fix Simplified Chinese translation.

- applications/luci-app-ddns/po/zh-cn/ddns.po
Reverts openwrt/luci#367
Missing Signed-off-by on original commit/pull request.
> Revert "luci-app-ddns:Fix Simplified Chinese translation."

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/fstab.lua
SWAP section was showing an error. Fixed it to display the devices/size properly.
> luci-mod-admin-full: mount points SWAP fix

- applications/luci-app-ddns/po/zh-cn/ddns.po
- modules/luci-base/po/zh-cn/base.po
This pull request adds Simplified Chinese translation for luci-app-ddns and completes most of the Simplified Chinese translation for luci-base.
Signed-off-by: 郭传鈜 <gch981213@gmail.com>
> Fix some Simplified Chinese translations in luci.

- applications/luci-app-ddns/po/zh-cn/ddns.po
fix typos and elegant zh_CN translations
> luci-app-ddns: fix Simplified Chinese translations

- applications/luci-app-radicale/Makefile
- applications/luci-app-radicale/luasrc/controller/radicale.lua
- applications/luci-app-radicale/luasrc/model/cbi/radicale.lua
- applications/luci-app-radicale/luasrc/view/radicale/btn_startstop.htm
- applications/luci-app-radicale/luasrc/view/radicale/ro_value.htm
- applications/luci-app-radicale/po/de/radicale.po
- applications/luci-app-radicale/po/templates/radicale.pot
- applications/luci-app-radicale/root/etc/uci-defaults/luci-radicale
New Application
!!! Dependency not set because there are two packages "radicale-py2" and
"radicale-py3" (currently BROKEN) available !!!
> luci-app-radicale: New app to support Radicale CalDAV/CardDAV server

- applications/luci-app-fwknopd/Makefile
- applications/luci-app-fwknopd/luasrc/model/cbi/fwknopd.lua
- applications/luci-app-fwknopd/luasrc/view/fwknopd-qr.htm
- applications/luci-app-fwknopd/root/usr/sbin/gen-qr.sh
Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>
This commit depends on pull request #1271 on the packages feed.
> luci-app-fwknopd: Add qr code support

- modules/luci-base/root/www/index.html
Signed-off-by: Night Coffee <ydkf@qq.com>
> luci-base: Add cache control in index.html

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/tools/ddns.lua
fixed version checking in function ipkg_ver_compare()
Reported issue #387 and openwrt/packages issue 1285
> luci-app-ddns: fixed version check

- contrib/package/community-profiles/files/etc/config/profile_reihen
Anpassungen für Reihen, damit WLAN wieder funktioniert.
> bssid und ssid scheme Anpassung für kathleen

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/po/zh-cn/privoxy.po
add chinese translations to luci-app-privoxy
> add chinese translations to luci-app-privoxy

- applications/luci-app-fwknopd/luasrc/model/cbi/fwknopd.lua
- applications/luci-app-fwknopd/po/en/fwknopd.po
- applications/luci-app-fwknopd/po/templates/fwknopd.pot
- applications/luci-app-fwknopd/root/etc/uci-defaults/luci-fwknopd
Minor tweaks to uci-defaults
refresh translation files
Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>
> Luci-app-fwknopd:add a couple config options to the interface

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/luasrc/controller/privoxy.lua
- applications/luci-app-privoxy/luasrc/model/cbi/privoxy.lua
- applications/luci-app-privoxy/po/zh-cn/privoxy.po
* fixed function ipkg_ver_compare()
* add chinese translations (thanks to maz-1) taken from #410
> [for-15.05]luci-app-privoxy: update to version 1.0.4-2

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/po/zh-cn/privoxy.po
add chinese translations for luci-app-mjpg-streamer
> add chinese translations for luci-app-mjpg-streamer

- applications/luci-app-olsr/Makefile
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
> luci-app-olsr: depend on luci-lib-json

- applications/luci-app-radicale/Makefile
- applications/luci-app-radicale/luasrc/controller/radicale.lua
- applications/luci-app-radicale/luasrc/model/cbi/radicale.lua
- applications/luci-app-radicale/luasrc/view/radicale/btn_startstop.htm
- applications/luci-app-radicale/luasrc/view/radicale/ro_value.htm
- applications/luci-app-radicale/po/de/radicale.po
- applications/luci-app-radicale/po/templates/radicale.pot
- applications/luci-app-radicale/root/etc/uci-defaults/luci-radicale
Initial release
with fixed function ipkg_ver_compare()
> [for-15.05] luci-app-radicale: copied from master

- applications/luci-app-shadowsocks-libev/Makefile
- applications/luci-app-shadowsocks-libev/luasrc/controller/shadowsocks-libev.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev.lua
- applications/luci-app-shadowsocks-libev/po/templates/shadowsocks-libev.pot
- applications/luci-app-shadowsocks-libev/po/zh-cn/shadowsocks-libev.po
- applications/luci-app-shadowsocks-libev/root/etc/uci-defaults/luci-shadowsocks-libev
This adds support for configuring [shadowsocks-libev](https://github.com/openwrt/packages/tree/master/net/shadowsocks-libev)
Signed-off-by: Jian Chang <aa65535@live.com>
> luci-app-shadowsocks-libev: add package

- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev.lua
- applications/luci-app-shadowsocks-libev/po/templates/shadowsocks-libev.pot
- applications/luci-app-shadowsocks-libev/po/zh-cn/shadowsocks-libev.po
support for shadowsocks-libev v2.2.3
Signed-off-by: Jian Chang <aa65535@live.com>
> luci-app-shadowsocks-libev: update package

- modules/luci-base/luasrc/model/ipkg.lua
- modules/luci-base/luasrc/model/ipkg.luadoc
* minor fix function _list() set to local
* new function compare_version() lua version of opkg compare-version
> ipkg.lua: new function compare_version()

- modules/luci-base/luasrc/model/ipkg.lua
function compare_versions(): replace Lua Math Library call with if clause
> ipkg.lua: compare_versions() Replace Lua Math Library call

- modules/luci-mod-failsafe/luasrc/controller/failsafe/failsafe.lua
Signed-off-by: Ekaitz Zárraga <ekaitz.zarraga@fon.com>
> modules/luci-mod-failsafe: Fix nil file descriptor error

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
fix no password set, Luci displays information is illegible.
> fix luci-theme-material bug

- applications/luci-app-firewall/po/pl/firewall.po
- modules/luci-base/po/pl/base.po
A few changes that better fit the gui.
Signed-off-by: Cezary Jackiewicz <cezary.jackiewicz@gmail.com>
> Cosmetic changes for the Polish language

- gitconfig
- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
fix 
1) textarea font-size too big in firefox
2) Polish text longer bug
3) "logout" text theme error and "unsaved changes" page dislocation.
> luci-theme-material: fix some bug

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
add button select and input theme
> luci-theme-material: add button select and input theme

- applications/luci-app-dump1090/luasrc/model/cbi/dump1090.lua
Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
> applications/luci-dump1090: update config to latest version

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
> luci-theme-material: PR from version 0.2.6

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
> luci-theme-material: fix some style bug in LUCI newest version

- applications/luci-app-dump1090/luasrc/model/cbi/dump1090.lua
ATTN: @Noltari
Signed-off-by: Roger D <rogerdammit@gmail.com>
> dump1090: lat/lon should be floats

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/luasrc/view/themes/material/footer.htm
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
> luci-theme-material: PR from Version 0.2.11

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
- themes/luci-theme-material/luasrc/view/themes/material/footer.htm
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
> luci-theme-material: Synchronized to the LUCI version f9e590a

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
1) fix login style
2) fix text too small in some page
> luci-theme-material: fix some style bugs

- modules/luci-base/luasrc/view/cbi/value.htm
template cbi/value.htm implement already documented property maxlength
> template cbi/value.htm implement documented property maxlength

- applications/luci-app-radicale/Makefile
- applications/luci-app-radicale/luasrc/controller/radicale.lua
remove map.title hack; no longer needed
> luci-app-radicale: remove map.title hack

- contrib/package/freifunk-common/files/usr/bin/neigh.sh
if nameservice-plugin is configured, we read
in all locally known hostnames and show them
in the output:
root@stuttgarter-core:~# neigh.sh
Local          Remote         vTime  LQ       NLQ      Cost Host
10.230.105.241 10.230.105.246 138851 1.000000 1.000000 1024 stuttgarter-rhnk.olsr
10.230.105.241 10.230.105.247 135717 1.000000 1.000000 1024 stuttgarter-emma.olsr
10.230.105.241 10.230.105.244 138309 1.000000 1.000000 1024 stuttgarter-sued.olsr
10.230.105.241 10.230.105.245 136001 1.000000 1.000000 1024 stuttgarter-west.olsr
10.230.105.241 10.230.105.242 134818 1.000000 1.000000 1024 stuttgarter-nord.olsr
10.230.105.241 10.230.105.243 137187 1.000000 1.000000 1024 stuttgarter-ost.olsr
10.230.105.241 10.230.105.250 139984 1.000000 1.000000 1024 stuttgarter-hof2.olsr
10.230.105.241 …
> freifunk-common: neigh.sh - show hostnames

- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/luasrc/http/protocol.lua
- modules/luci-base/luasrc/view/cbi/dynlist.htm
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppossh.lua
- protocols/luci-proto-ppp/luasrc/model/network/proto_ppp.lua
This pull request will add LuCI protocol support for pppossh which has been merged into the OpenWrt packages feed.
While at it, also include an old patch for fixing urlencode which has been sitting in my local tree quite a while.
> Add luci proto pppossh

- applications/luci-app-firewall/luasrc/model/cbi/firewall/rule-details.lua
- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/luasrc/cbi/datatypes.lua
- modules/luci-base/luasrc/view/cbi/mvalue.htm
This series of commits adds the UCI time and date restriction for firewall rules and redirects to LuCI.
> Pull request app firewall timedate

- applications/luci-app-ahcp/po/sv/ahcp.po
> luci-app-ahcp: Edited Swedish translation

- applications/luci-app-wshaper/po/sv/wshaper.po
> luci-app-wshaper: Edited Swedish translation

- protocols/luci-proto-vpnc/Makefile
- protocols/luci-proto-vpnc/luasrc/model/cbi/admin_network/proto_vpnc.lua
- protocols/luci-proto-vpnc/luasrc/model/network/proto_vpnc.lua
Add VPNC as a network protocol in LuCI (UCI already exists).  Note that this pull request assumes the validator pull request has already been applied.
> protocols: vpnc: Add vpnc as a network protocol

- applications/luci-app-mmc-over-gpio/po/sv/mmc_over_gpio.po
> luci-app-mmc-over-gpio: Edited Swedish translation

- applications/luci-app-ntpc/po/sv/ntpc.po
> luci-app-ntpc: Edited Swedish translation

- applications/luci-app-olsr/po/sv/olsr.po
> luci-app-olsr: Edited Swedish translation

- applications/luci-app-p2pblock/po/sv/p2pblock.po
> luci-app-p2pblock: Edited Swedish translation

- applications/luci-app-polipo/po/sv/polipo.po
> luci-app-polipo: Edited Swedish translation

- applications/luci-app-qos/po/sv/qos.po
> luci-app-qos: Edited Swedish translation

- applications/luci-app-pbx-voicemail/po/sv/pbx-voicemail.po
> luci-app-pbx-voicemail: Edited Swedish translation

- applications/luci-app-radvd/po/sv/radvd.po
> luci-app-radvd: Edited Swedish translation

- applications/luci-app-samba/po/sv/samba.po
> luci-app-samba: Edited Swedish translation

- applications/luci-app-ushare/po/sv/ushare.po
> luci-app-ushare: Edited Swedish translation

- applications/luci-app-upnp/po/sv/upnp.po
> luci-app-upnp: Edited Swedish translation

- applications/luci-app-tinyproxy/po/sv/tinyproxy.po
> luci-app-tinyproxy: Edited Swedish translation

- applications/luci-app-transmission/po/sv/transmission.po
> luci-app-transmission: Edited Swedish translation

- applications/luci-app-p910nd/po/sv/p910nd.po
> luci-app-p910nd: Edited Swedish translation

- applications/luci-app-wol/po/sv/wol.po
> luci-app-wol: Edited Swedish translation

- applications/luci-app-watchcat/po/sv/watchcat.po
> luci-app-watchcat: Edited Swedish translation

- applications/luci-app-vnstat/po/sv/vnstat.po
> luci-app-vnstat: Edited Swedish translation

- applications/luci-app-shadowsocks-libev/po/sv/shadowsocks-libev.po
> luci-app-shadowsocks-libev: Edited Swedish translation

- applications/luci-app-statistics/po/sv/statistics.po
> luci-app-statistics: Edited Swedish translation

- applications/luci-app-privoxy/po/sv/privoxy.po
> luci-app-privoxy: Added and edited Swedish translation

- applications/luci-app-radicale/po/sv/radicale.po
> luci-app-radicale: Added and edited Swedish translation

- modules/luci-base/po/zh-cn/base.po
This pull request adds some Simplified Chinese translation for luci-base.
Signed-off-by: Chuanhong Guo <gch981213@gmail.com>
> Add some Simplified Chinese translations

- applications/luci-app-pbx-voicemail/luasrc/model/cbi/pbx-voicemail.lua
- applications/luci-app-pbx/luasrc/model/cbi/pbx-advanced.lua
- applications/luci-app-pbx/luasrc/model/cbi/pbx-voip.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/olsrd.lua
- applications/luci-app-tinyproxy/luasrc/model/cbi/tinyproxy.lua
- applications/luci-app-uhttpd/Makefile
- applications/luci-app-uhttpd/luasrc/controller/uhttpd/uhttpd.lua
- applications/luci-app-uhttpd/luasrc/model/cbi/uhttpd/uhttpd.lua
- applications/luci-app-watchcat/luasrc/model/cbi/watchcat/watchcat.lua
- libs/luci-lib-nixio/src/file.c
- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/luasrc/cbi.lua
- modules/luci-base/luasrc/cbi/datatypes.lua
- modules/luci-base/luasrc/http.lua
- modules/luci-base/luasrc/http/protocol.lua
- modules/luci-base/luasrc/view/cbi/upload.htm
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/system.lua
- protocols/luci-proto-ipv6/luasrc/model/cbi/admin_network/proto_aiccu.lua
- protocols/luci-proto-openconnect/luasrc/model/cbi/admin_network/proto_openconnect.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_l2tp.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppossh.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pptp.lua
This series of commits add a LuCI app for configuring uHTTPs UCI parameters as well as managing the Basic Auth authorization config in /etc/httpd.conf (or whatever is configured in uci config).
> Pull request app uhttpd

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
1) Decrease font and spacing
2) Synchronized to the LUCI version 99f5d4e
> luci-theme-material: Decrease font and spacing

- modules/luci-base/luasrc/view/cbi/map.htm
- modules/luci-base/po/de/base.po
- modules/luci-base/po/templates/base.pot
* fixed tabbed map when using NamedSection of same sectiontype
* add error message on which tab(s) the invalid/required fields are located
> luci-base: fixed tabbed map when using NamedSection of same type

- applications/luci-app-polipo/luasrc/model/cbi/polipo.lua
fix Parent proxy address field check https://dev.openwrt.org/ticket/15680
> luci-app-polipo: fix Parent proxy address field check

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/network.lua
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
This adds some configuration for the DSL line and also shows more statistical values.
This was tested on a VRX200 and depends on recent OpenWrt trunk.
> add configuration for the DSL line

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/df.lua
Disk usage graphing was broken.  This fixes it.
> luci-app-statistics: Fix disk usage graphing

- modules/luci-base/luasrc/util.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
Add (conditional on dnsmasq-full) ability to set DNSSEC options.
> Pull request dnsmasq dnssec

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
Add some missing dnsmasq options.
> luci-mod-admin-full: various dnsmasq options

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
> [luci-app-openvpn] Optimized code and added suggested fix from #650

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/po/de/ddns.po
- fix problem not correctly handling "Bind Network" field #699
- some german translation extensions
> fix problem not correctly handling "Bind Network" field

- documentation/ModulesHowTo.md
Signed-off-by: Guido Lipke <lipkegu@gmail.com>
> ModulesHowTo: Fix typo

- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
* Add po templates
* Add Simplified Chinese translation
> luci-app-adblock: Add translation

- applications/luci-app-aria2/Makefile
- applications/luci-app-aria2/luasrc/controller/aria2.lua
- applications/luci-app-aria2/luasrc/model/cbi/aria2.lua
- applications/luci-app-aria2/luasrc/view/aria2/web_script.htm
- applications/luci-app-aria2/po/templates/aria2.po
- applications/luci-app-aria2/po/zh-cn/aria2.po
- applications/luci-app-aria2/root/etc/uci-defaults/40_luci-aria2
> luci-app-aria2: Add package

- themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm
> luci-theme-bootstrap: Remove jql.min.js which does not exist

- protocols/luci-proto-vpnc/luasrc/model/cbi/admin_network/proto_vpnc.lua
Should fix issues mentioned in 3f95160cbd3b82b8ba32a38347e0d3dcc368e2e9
> Fixed luci-proto-vpnc typos which rendered it unusable

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/po/pt-br/ddns.po
Signed-off-by: Matheus Dal Mago <matheusdalmago10@gmail.com>
> luci-app-ddns: adding pt-br translation

- applications/luci-app-polipo/luasrc/model/cbi/polipo.lua
remove Parent proxy address field check https://dev.openwrt.org/ticket/15680
> [for-15.05] luci-app-polipo: remove Parent proxy address field check

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/luasrc/controller/privoxy.lua
- applications/luci-app-privoxy/luasrc/model/cbi/privoxy.lua
- changed to tabbed display
- modified version detection
- adaption to new function version_compare() in ipkg.lua
- adaption to fixed Flag.parse() in cbi.lua
- add support new option "system.boot_delay"
- also fix #763
> luci-app-privoxy: change to tabbed display

- modules/luci-base/root/etc/config/luci
- modules/luci-mod-admin-full/luasrc/view/admin_network/diagnostics.htm
> luci-mod-admin-full: make diagnostics url customizable

- applications/luci-app-adblock/po/sv_SE/sv.po
> Created sv.po

- modules/luci-base/po/it/base.po
I have fixed some capital letter and add some translation
> Fix and update italian translation

- applications/luci-app-firewall/po/it/firewall.po
- modules/luci-base/po/it/base.po
Hope this time I have done a good work
> Fix some capital and add some translation

- README.md
> docs: link to the developer wiki documentation

- applications/luci-app-aria2/Makefile
- applications/luci-app-aria2/luasrc/model/cbi/aria2.lua
- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
- applications/luci-app-aria2/po/templates/aria2.pot
- applications/luci-app-aria2/po/zh-cn/aria2.po
* Add maintainer info;
* Fix unable save authentication method;
* Use luci.dispatcher.build_url(...) to support Chaos Calmer;
* Add log file and log level options;
* Rename files.
> luci-app-aria2: fix and update

- applications/luci-app-aria2/luasrc/model/cbi/aria2.lua
> luci-app-aria2: fix template name

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
Signed-off-by: Nathan Hintz nlhintz@hotmail.com
> luci: broadcom - add n-mode support

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/routes.lua
Hi,
This pull request adds support for route type selection.
Please consider reviewing and merging it.
> Add support for route types

- applications/luci-app-unbound/luasrc/model/cbi/unbound.lua
> luci-app-unbound: added DNS64 support

- applications/luci-app-adblock/po/ja/adblock.po
・Add Japanese translation
Signed-off-by: musashino205 <musashino.open@gmail.com>
> luci-app-adblock: Add Japanese translation

- modules/luci-base/po/ja/base.po
・Update Japanese translation
Signed-off-by: musashino205 musashino.open@gmail.com
> luci-base: Update Japanese translation

- applications/luci-app-mjpg-streamer/po/ja/mjpg-streamer.po
> luci-app-mjpg-streamer: Add Japanese translation

- applications/luci-app-firewall/luasrc/model/cbi/firewall/custom.lua
> luci-app-firewall: restart firewall on /etc/firewall.user write

- applications/luci-app-statistics/po/ja/statistics.po
Added translations for each plugins.
> luci-app-statistics: Update Japanese translation

- applications/luci-app-wifischedule/po/ja/wifischedule.po
- applications/luci-app-wifischedule/po/templates/wifischedule.pot
Added Japanese translations and po templates.
> luci-app-wifischedule: Add Japanese translation

- applications/luci-app-firewall/po/ja/firewall.po
Added some translations for the schedule settings and others.
> luci-app-firewall: Update Japanese translation

- applications/luci-app-travelmate/po/ja/travelmate.po
> luci-app-travelmate: Add Japanese translation

- applications/luci-app-uhttpd/po/ja/uhttpd.po
- applications/luci-app-uhttpd/po/templates/uhttpd.pot
Added Japanese translation and po templates.
> luci-app-uhttpd: Add Japanese translation

- applications/luci-app-wifischedule/luasrc/controller/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/model/cbi/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/view/wifischedule/file_viewer.htm
- applications/luci-app-wifischedule/po/templates/wifischedule.pot
- applications/luci-app-wifischedule/po/zh-cn/wifischedule.po
* Add more translation.
* Add Simplified Chinese translation.
Tested on luci 3366c250e7f1f49a51025a0801f35229a221d547.
> Luci-app-wifischedule: Update translation

- applications/luci-app-wifischedule/po/ja/wifischedule.po
Added some translations of recently added strings.
> luci-app-wifischedule: Update Japanese translation

- contrib/package/community-profiles/files/etc/config/profile_berlin
since Kathleen-0.2.0 Release there is a new owm-api-url
Signed-off-by: Sven Roederer devel-sven@geroedel.de
> community-profiles: update Berlin

- applications/luci-app-shairplay/po/ja/shairplay.po
- applications/luci-app-shairplay/po/templates/shairplay.pot
Added Japanese translations and po templates.
> luci-app-shairplay: Add Japanese translation

- applications/luci-app-wifischedule/luasrc/controller/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/model/cbi/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/view/wifischedule/file_viewer.htm
- applications/luci-app-wifischedule/po/ja/wifischedule.po
- applications/luci-app-wifischedule/po/templates/wifischedule.pot
- applications/luci-app-wifischedule/po/zh-cn/wifischedule.po
* Formatting codes.
* Move to services sub menu.
* Update Simplified Chinese translation.
* And some other small changes.
Tested in luci trunk version.
> Luci app wifischedule: minor changes

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate.lua
* update gui elements to reflect changes in travelmate 0.3.x
> luci-app-travelmate: update gui elements

- applications/luci-app-travelmate/po/ja/travelmate.po
- applications/luci-app-travelmate/po/templates/travelmate.pot
Synchronized japanese po and po templates with lua sources, and added some translations to Japanese po of recently added strings.
> luci-app-travelmate: Update Japanese translation

- applications/luci-app-firewall/po/ko/firewall.po
- modules/luci-base/po/ko/base.po
Please review my second pull-request.
> Updates korean languages.

- modules/luci-base/htdocs/luci-static/resources/cbi.js
The `cbi_validate_field` should be after data initialized.
Signed-off-by: Jian Chang <aa65535@live.com>
> luci-base:adjust the code order

- applications/luci-app-dynapoint/Makefile
- applications/luci-app-dynapoint/luasrc/controller/dynapoint.lua
- applications/luci-app-dynapoint/luasrc/model/cbi/dynapoint.lua
- applications/luci-app-dynapoint/luasrc/view/dynapoint/cbi_checkbox.htm
- applications/luci-app-dynapoint/luasrc/view/dynapoint/cbi_color.htm
- applications/luci-app-dynapoint/po/de/dynapoint.po
- applications/luci-app-dynapoint/po/templates/dynapoint.pot
- applications/luci-app-dynapoint/root/etc/uci-defaults/40_luci-dynapoint
Maintainer: me
Compile tested: OpenWRT trunk
Run tested: OpenWRT trunk
Description:
LuCI Support for DynaPoint
Dynapoint allows dynamic access point creation
and deletion depending on changes of certain network conditions.
More information: https://github.com/thuehn/dynapoint
Dynapoint Pull request: https://github.com/openwrt/packages/pull/3304
> luci-app-dynapoint: new package

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/fstab/mount.lua
Fixed some display problems where the UUID label of the drop down
list does not exist and the positions of other labels are misplaced
in mount settings page.
> luci-mod-admin-full: Fix display problems of mount

- applications/luci-app-dynapoint/po/ja/dynapoint.po
Added Japanese translations.
Built LEDE-Project firmware including these changes and confirmed that the translations are applied correctly with my router (Buffalo WZR-900DHP).
> luci-app-dynapoint: Add Japanese translation

- applications/luci-app-commands/po/ca/commands.po
- applications/luci-app-commands/po/cs/commands.po
- applications/luci-app-commands/po/de/commands.po
- applications/luci-app-commands/po/el/commands.po
- applications/luci-app-commands/po/en/commands.po
- applications/luci-app-commands/po/es/commands.po
- applications/luci-app-commands/po/fr/commands.po
- applications/luci-app-commands/po/he/commands.po
- applications/luci-app-commands/po/hu/commands.po
- applications/luci-app-commands/po/it/commands.po
- applications/luci-app-commands/po/ja/commands.po
- applications/luci-app-commands/po/ms/commands.po
- applications/luci-app-commands/po/no/commands.po
- applications/luci-app-commands/po/pl/commands.po
- applications/luci-app-commands/po/pt-br/commands.po
- applications/luci-app-commands/po/pt/commands.po
- applications/luci-app-commands/po/ro/commands.po
- applications/luci-app-commands/po/ru/commands.po
- applications/luci-app-commands/po/sk/commands.po
- applications/luci-app-commands/po/sv/commands.po
- applications/luci-app-commands/po/templates/commands.pot
- applications/luci-app-commands/po/tr/commands.po
- applications/luci-app-commands/po/uk/commands.po
- applications/luci-app-commands/po/vi/commands.po
- applications/luci-app-commands/po/zh-cn/commands.po
- applications/luci-app-commands/po/zh-tw/commands.po
Synchronized translation each languages with Lua sources and added some Japanese translations of recently added strings.
> luci-app-commands: Update Japanese translation

- applications/luci-app-unbound/luasrc/model/cbi/unbound.lua
Coordinated Support of openwrt-packages/net/unbound:
https://github.com/openwrt/packages/pull/3873
Reference (not dependent):
https://github.com/lede-project/source/pull/704
> unbound: update UCI for odhcpd and hostname

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/root/etc/uci-defaults/40_luci-vpnbypass
This is a companion to [this pull request against openwrt/packages](https://github.com/openwrt/packages/pull/3903).
> luci-app-vpnbypass: initial commit of companion app to vpnbypass package

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Sorry, forgot to update Makefile when I moved luci-app-vpnbypass into luci tree + initial i18n support.
> luci-app-vpnbypass: luci tree Makefile + i18n support.

- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
> luci-proto-wireguard: fix wrong maximum MTU

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
Minor fixes for makefile & controller.
> luci-app-vpnbypass: makefile fix & controller fix

- modules/luci-base/luasrc/cbi/datatypes.lua
> luci-base: added datatypes `hostid` and `base64`

- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
> luci-proto-wireguard: stricter input validation

- applications/luci-app-e2guardian/Makefile
- applications/luci-app-e2guardian/luasrc/controller/e2guardian.lua
- applications/luci-app-e2guardian/luasrc/model/cbi/e2guardian.lua
This application was moved from the packages repository to luci.
This  PR depends on: https://github.com/openwrt/packages/pull/4013
> luci-app-e2guardian: add e2guardian application

- applications/luci-app-clamav/Makefile
- applications/luci-app-clamav/luasrc/controller/clamav.lua
- applications/luci-app-clamav/luasrc/model/cbi/clamav.lua
This application was moved from the packages repository to luci.
This  PR depends on: https://github.com/openwrt/packages/pull/4013
> luci-app-clamav: added clamav application

- applications/luci-app-wireguard/Makefile
- applications/luci-app-wireguard/luasrc/controller/wireguard.lua
- applications/luci-app-wireguard/luasrc/view/wireguard.htm
This application allows for monitoring of WireGuard interfaces via the
Status menu.
Screenshot (with one online and one offline peer): 
Please review, I'll squash after review.
/cc @p4yne @zx2c4 @zorun
> luci-app-wireguard: initial commit

- applications/luci-app-wireguard/Makefile
> luci-app-wireguard: resolve meta package in depdencies

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
> luci-base: sync translations

- applications/luci-app-wireguard/po/pt-br/wireguard.po
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
> luci-app-wireguard: Add pt-br translation

- applications/luci-app-cshark/Makefile
- applications/luci-app-cshark/luasrc/controller/cshark.lua
- applications/luci-app-cshark/luasrc/model/cbi/admin_network/cshark.lua
- applications/luci-app-cshark/luasrc/view/cshark.htm
Moved over here from the packages repository.
Maintainer: @lperkov
> luci-app-cshark: initial commit

- applications/luci-app-mwan3/Makefile
- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/advanced_hotplugscript.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/advanced_mwanconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/advanced_networkconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/advanced_wirelessconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/member.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/memberconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policyconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/rule.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
- applications/luci-app-mwan3/luasrc/view/admin_status/index/mwan.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_diagnostics.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_hotplugscript.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_mwanconfig.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_networkconfig.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_troubleshooting.htm
- applications/luci-app-mwan3/luasrc/view/mwan/advanced_wirelessconfig.htm
- applications/luci-app-mwan3/luasrc/view/mwan/config_css.htm
- applications/luci-app-mwan3/luasrc/view/mwan/openwrt_overview_status.htm
- applications/luci-app-mwan3/luasrc/view/mwan/overview_detailed.htm
- applications/luci-app-mwan3/luasrc/view/mwan/overview_interface.htm
- applications/luci-app-mwan3/root/etc/hotplug.d/iface/16-mwancustombak
- applications/luci-app-mwan3/root/etc/uci-defaults/60_luci-mwan3
Moved over here from the packages repository.
> luci-app-mwan3: initial commit

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simpleadblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simpleadblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
This is a companion package to simple-adblock (https://github.com/openwrt/packages/pull/3902).
> luci-app-simple-adblock: initial commit 

- applications/luci-app-clamav/po/ja/clamav.po
- applications/luci-app-clamav/po/templates/clamav.pot
Added po templates and Japanese translations.
> luci-app-clamav: Add Japanese translation

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
Fixed display issues when applying translation.
> luci-app-adblock: Fix display issues with translation

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* mute stderr in syscalls
* better suspend/resume button handling
> luci-app-adblock: small fixes in overview tab

- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
Added Japanese translations of recently added strings.
> luci-app-adblock: Update Japanese translation

- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
Added po templates and Japanese translations.
> luci-app-mwan3: Add Japanese translation

- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
Synchronized translations with sources and updated japanese
translations.
> luci-app-mwan3: Update Japanese translation

- applications/luci-app-mwan3/po/zh-cn/mwan3.po
- modules/luci-base/po/zh-cn/base.po
* Update luci-base Simplified Chinese translation
* Add luci-app-mwan3 Simplified Chinese translation
> Update Simplified Chinese translation

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
> luci-app-openvpn: Fix default value for remote_random flag

- applications/luci-app-upnp/root/etc/uci-defaults/40_luci-miniupnp
> luci-app-upnp: fix setting ucitrack init option

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
Maintainer: @arfett
Compile tested: ramips, xiaomi mini, r50082
Run tested: ramips, xiaomi mini, r50082
Add uci parameter to silence errors printed to syslog and append extra redirect of sed error messages to /dev/null.
Signed-off-by: Tomislav Požega <pozega.tomislav@gmail.com>
> luci-app-mwan3: disable uci/sed errors print to syslog

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* add two new extra options
* cosmetics
> luci-app-adblock: sync with 2.6.1

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
preset network "wan", if not configured in ddns config for correct
display system status #1117
> luci-app-ddns: fix to correct system status

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
> luci-app-adblock: fix markup

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/contextswitch.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/contextswitch.lua
- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
Adding support for a useful plug-in and would also like it to be backported to 17.01 branch.
> Support for collectd-mod-contextswitch

- applications/luci-app-upnp/po/zh-cn/upnp.po
Update Chinese translations for unifying translated names.
Signed-off-by: Angus Ding angus.ding@gmail.com
> luci-app-upnp: Update Chinese translation

- themes/luci-theme-material/luasrc/view/themes/material/header.htm
fix some bug and sync some code from luci-theme-bootstrap
Signed-off-by: lutty <lutty@lutty.me>
> luci-theme-material: fix some bug and sync some code from luci-theme-bootstrap

- applications/luci-app-adblock/po/sv/adblock.po
Signed-off-by <hamnisdude@gmail.com>
> Updated adblock

- applications/luci-app-simple-adblock/po/pt-br/simple-adblock.po
- applications/luci-app-simple-adblock/po/pt/simple-adblock.po
Added translations for pt and pt-br.
> luci-app-simple-adblock: pt/pt-br translations.

- applications/luci-app-unbound/luasrc/model/cbi/unbound.lua
This coordinates UCI option 'add_extra_dns' and list 'trigger' with PR https://github.com/openwrt/packages/pull/4361.
**HOLD**
Please wait for review and comments by requester @poranje
> luci-app-unbound: option 'add_extra_dns' and list 'trigger'

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* add new 'Manual mode' option
> luci-app-adblock: sync with adblock 2.7.0

- applications/luci-app-privoxy/Makefile
I do not use this software any more and due to lack of time, I give the
maintenance responsibility back to the community.
> luci-app-privoxy: clear PKG_MAINTAINER

- applications/luci-app-wol/po/sv/wol.po
> Finished translation into Swedish

- applications/luci-app-wireguard/po/sv/wireguard.po
> Finished translation to Swedish

- applications/luci-app-wifischedule/po/sv/wifischedule.po
> Some translation for Swedish done.

- applications/luci-app-watchcat/po/sv/watchcat.po
> Some translations for Swedish done.

- applications/luci-app-commands/po/sv/commands.po
> luci-app-commands: Updated the Swedish translation

- applications/luci-app-clamav/po/sv/clamav.po
> clamav: Added the Swedish language

- applications/luci-app-aria2/po/sv/aria2.po
> luci-app-aria2: Created Swedish translation

- applications/luci-app-diag-core/po/sv/diag_core.po
> luci-app-diag-core: Updated Swedish translation

- applications/luci-app-firewall/po/sv/firewall.po
> luci-app-firewall: Updated Swedish translation

- applications/luci-app-commands/Makefile
- applications/luci-app-firewall/Makefile
- applications/luci-app-qos/Makefile
- collections/luci-ssl/Makefile
- collections/luci/Makefile
- libs/luci-lib-ip/Makefile
- libs/luci-lib-json/Makefile
- libs/luci-lib-nixio/Makefile
- libs/luci-lib-px5g/Makefile
- modules/luci-base/Makefile
- modules/luci-mod-admin-full/Makefile
- modules/luci-mod-rpc/Makefile
- protocols/luci-proto-ipv6/Makefile
- protocols/luci-proto-ppp/Makefile
- themes/luci-theme-bootstrap/Makefile
Add some missing license tags:
> Add license tags

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
> luci-app-adblock: sync with adblock 2.8.1

- modules/luci-base/po/zh-cn/base.po
Line 3021:
msgid "Switch protocol"
sould be:
msgstr "切换协议"
This "Switch protocol" means "Change one protocol to another protocol", not "protocol of switch deivce"(current version)
> luci_base: Update zh_CN base.po, translate fix

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_delete.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* add a wireless station manager to edit and delete existing
interfaces or scan for new uplinks
> luci-app-travelmate: sync with travelmate 0.9.0

- applications/luci-app-shadowsocks-libev/luasrc/controller/shadowsocks-libev.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/instances.lua
- applications/luci-app-shadowsocks-libev/luasrc/view/shadowsocks-libev/add_instance.htm
> luci-app-shadowsocks-libev: auto update instance running state

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* speed up wireless scan
* emphasize active uplink in Station Overview
* mark hidden SSIDs
> luci-app-travelmate: small bugfixes

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_order.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* add re-ordering buttons in Station Overview
* fix possible nil error during wifi scan
> luci-app-travelmate: enhancements & fixes

- applications/luci-app-nlbwmon/Makefile
- applications/luci-app-nlbwmon/luasrc/controller/nlbw.lua
- applications/luci-app-nlbwmon/luasrc/model/cbi/nlbw/config.lua
- applications/luci-app-nlbwmon/luasrc/view/nlbw/backup.htm
- applications/luci-app-nlbwmon/luasrc/view/nlbw/display.htm
- applications/luci-app-nlbwmon/root/etc/uci-defaults/40_luci-nlbwmon
This commit introduces luci-app-nlbwmon, a frontend for nlbwmon, the
lightweight NetLink BandWidth Montor.
The nlbwmon daemon gathers per-host traffic statistics by querying netlink
accounting data. Due to this approach, the executable is very small and does
not rely on libpcap and CPU intensive raw sockets to monitor traffic.
Depends on PR https://github.com/openwrt/packages/pull/4646
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
> luci-app-nlbwmon: new package

- applications/luci-app-nlbwmon/po/ja/nlbwmon.po
- applications/luci-app-nlbwmon/po/templates/nlbwmon.pot
Added po templates and Japanese translation.
> luci-app-nlbwmon: Add Japanese translation

- applications/luci-app-nlbwmon/po/ja/nlbwmon.po
Updated Japanese translations.
> luci-app-nlbwmon: Update Japanese translation

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_delete.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_order.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* various small bugfixes and optimizations
> luci-app-travelmate: small bugfixes & optimizations

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* add preliminary kresd support
* small fixes
> luci-app-adblock: sync with adblock 2.8.5

- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/instance-details.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
> luci-app-shadowsocks-libev: support ss_redir disable_sni option

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_firewall_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_network_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_wireless_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/configuration_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* fix bug in interface wizard during initial setup
* cosmetics
> luci-app-travelmate: bugfix

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
- applications/luci-app-mwan3/root/etc/uci-defaults/60_luci-mwan3
Add new config options which were add in PR https://github.com/openwrt/packages/pull/4688
> luci-app-mwan3: add new options

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_order.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* frontend: add/modify input datatypes in 'extra' section
* frontend: add support to edit/change wpa enterprise key phrases
* frontend: various small fixes
> luci-app-travelmate: sync with 0.9.2

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
since the update server now checks packages for updates the web view
will show all changed package versions. this PR is also important to
support future package transformations of the server
> luci-app-attendedsysupgrade: show updated packages

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/po/templates/mwan3.pot
Add config option for tracking method introduced in openwrt/packages/#4629
Signed-off-by: Marcin Jurkowski <marcin1j@gmail.com>
> luci-app-mwan3: add new config option 'track_method'

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/advanced_hotplugscript.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
- Use mwan3.user for hotplugscript editing
- Add mmx_mask config option (https://github.com/openwrt/packages/pull/4719)
> luci-app-mwan3: use mwan3.user and add global mmx_mask option

- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
* check/add for 'global' section to fix a possible issue with old
(non-default) dnscrypt-proxy config files
* a custom 'resolv-crypt.conf' can now be added in the new "Extra
options" section
* accept IPv4 and IPv6 address as local dnscrypt ip address
> luci-app-dnscrypt-proxy: small fixes & additions

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
the "update_package" option explicitly asks the server to check for
packages updates as well not only upgrades to a new release
@jow- 
> luci-app-attendedsysupgrade: param update_package

- applications/luci-app-adblock/po/sv/adblock.po
> luci-app-adblock: Sync translations

- applications/luci-app-advanced-reboot/po/sv/luci-app-advanced-reboot.po
> luci-app-advanced-reboot: Added Swedish language

- applications/luci-app-aria2/po/sv/aria2.po
> luci-app-aria2: Updated Swedish translation

- applications/luci-app-bcp38/po/sv/bcp38.po
> luci-app-bcp38: Added Swedish translation

- applications/luci-app-openvpn/po/sv/openvpn.po
> luci-app-openvpn: Updated Swedish translation

- applications/luci-app-ddns/po/sv/ddns.po
> luci-app-ddns: Updated Swedish translation

- applications/luci-app-diag-devinfo/po/sv/diag_devinfo.po
> luci-app-diag-devinfo: Updated Swedish translation

- applications/luci-app-adblock/po/pt-br/adblock.po
> Update pt-br translation

- applications/luci-app-clamav/po/sv/clamav.po
> luci-app-clamav: Updated Swedish translation

- applications/luci-app-wireguard/po/sv/wireguard.po
> luci-app-wireguard: Updated Swedish translation

- applications/luci-app-wifischedule/po/it/wifischedule.po
New Italian Translation of wifischedule.po
> luci-app-wifischedule: New Italian Translation

- applications/luci-app-firewall/po/it/firewall.po
Full and correct ITALIAN translation of luci firewall.po
Signed-off-by: Alessio Casagrande <bubu83@gmail.com>
> luci-app-firewall:  Full Italian Translation

- modules/luci-base/po/it/base.po
> luci-base: Updated Italian Translation

- applications/luci-app-wol/po/it/wol.po
> luci-app-wol: Fixed Italian translation

- applications/luci-app-ddns/po/it/ddns.po
> luci-app-ddns: Updated Italian translation

- modules/luci-base/po/ca/base.po
Add missing translations and fix a few typos.
Signed-off-by: Roger Pueyo Centelles <roger.pueyo@guifi.net>
> luci-base: Updated Catalan translation

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* many frontend improvements & Turris Omnia support
> luci-app-adblock: sync with adblock 3.0.0

- applications/luci-app-adblock/po/it/adblock.po
> luci-app-adblock: Full Italian Translation

- applications/luci-app-adblock/po/it/adblock.po
> luci-app-adblock: Fixes for Italian Translation

- modules/luci-base/po/it/base.po
> luci-base: Fixes for Italian Translation

- applications/luci-app-dnscrypt-proxy/po/ja/dnscrypt-proxy.po
- applications/luci-app-dnscrypt-proxy/po/templates/dnscrypt-proxy.pot
Synchronized po/pot and updated Japanese translations.
> luci-app-dnscrypt-proxy: Update Japanese translation

- applications/luci-app-noddos/luasrc/view/noddos/clients.htm
- applications/luci-app-noddos/po/ja/noddos.po
- applications/luci-app-noddos/po/templates/noddos.pot
- Added translation markup to some UI texts
- Added po template and po file for Japanese translations.
> luci-app-noddos: Add po template and Japanese translation

- applications/luci-app-fwknopd/root/etc/uci-defaults/40_luci-fwknopd
Signed-off-by: Jonathan Bennett <JBennett@Incomsystems.biz>
> luci-app-fwknop:  Adds a check to not overwrite user configured keys

- modules/luci-base/po/sv/base.po
> luci-base: Massive Swedish translation

- applications/luci-app-simple-adblock/po/sv/simple-adblock.po
> Created luci-app-simple-adblock.po

- applications/luci-app-adblock/po/sv/adblock.po
> luci-app-adblock: Translated some Swedish

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
add textarea with all to be installed packages, allows user to changes
packages before requesting the image
add button to open build log in
also requesting merging this package in stable lede-17.01
> luci-app-attendedsysupgrade: editable packagelist

- applications/luci-app-noddos/Makefile
- applications/luci-app-noddos/htdocs/cgi-bin/clientdetails
- applications/luci-app-noddos/luasrc/controller/noddos.lua
- applications/luci-app-noddos/luasrc/model/cbi/noddos.lua
- applications/luci-app-noddos/luasrc/view/noddos/clients.htm
- applications/luci-app-noddos/po/ja/noddos.po
- applications/luci-app-noddos/po/templates/noddos.pot
- applications/luci-app-noddos/root/etc/uci-defaults/40_luci-noddos
Noddos is a cloud-powered & device-aware firewall: https://github.com/noddos/noddos. This PR covers the original [PR](https://github.com/openwrt/luci/pull/1375) of noddos to openwrt/luci master branch plus the two commits for Japanese translations.
Signed-off-by: Steven Hessing <steven.hessing@gmail.com>
> luci-app-noddos: backport from master

- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
Same as #1221
But commit to lede-17.01 branch
> luci_base: Update zh_CN zh_TW base.po, translate fix

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/config_css.htm
* add support for new 'whitelist mode'
* fix a small css issue in advanced edit tabs
> luci-app-adblock: sync with adblock 3.1.0

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
- applications/luci-app-attendedsysupgrade/root/etc/uci-defaults/40_luci-attendedsysupgrade
- applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/attendedsysupgrade.json
Add required ubus acls from package rpcd-mod-attendedsysupgrade.
> luci-app-attendedsysupgrade: upgrade to version 2

- contrib/package/meshwizard/files/usr/bin/meshwizard/helpers/setup_olsrd.sh
inside OLSR some plugins recently got newer version numbers (and of course improvements)
Signed-off-by: Ufo <ufo@rund.freifunk.net>
> meshwizard: upgrade version for some olsr-plugins

- applications/luci-app-attendedsysupgrade/Makefile
- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
- applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/attendedsysupgrade.json
> luci-app-attendedsysupgrade: use common package and editable server

- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* fixes for Chaos Calmer compatibility
> luci-app-travelmate: Chaos Calmer bugfixes

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* fix visual issue in runtime section (originally provided by @ansuel)
> luci-app-adblock: fix minor visual issue

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/config_css.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* add support for hidden uplinks
* add support for wpa enterprise uplinks
* various small fixes
> luci-app-travelmate: sync with travelmate 0.9.5

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* Turris omnia compability fixes
* OpenWrt theme fixes
> luci-app-travelmate: sync with travelmate 0.9.6

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* fix wpa enterprise options
* add various wpa / wep options
> luci-app-travelmate: enhance wireless security connection settings

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* Various cleanups & small enhancements
> luci-app-travelmate: sync with travelmate 1.0.0

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
* refine logfile search term
* textarea 'autoscroll down' in logfile view
* left-align blocklist source table plus a more compact design
> luci-app-adblock: sync with adblock 3.4.1

- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/instance-details.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
f1862ce luci-app-shadowsocks-libev: remove option manager_address
1ad3726 luci-app-shadowsocks-libev: support option no_delay
611c14b luci-app-shadowsocks-libev: display disabled state of remote server
> shadowsocks-libev: sync with packages repo

- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
* change csv download url to new maintainer (adapt changes of core-package #5381)
* small fixes
@thess 
> luci-app-dnscrypt-proxy: Updates for new repository/maintainer

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* add 'Download Utility' select box
* add new "running" status
* small visual fixes
> luci-app-adblock: sync with adblock 3.4.3

- modules/luci-base/po/zh-cn/base.po
update Simplified Chinese translation
> luci-base: zh_CN: update Simplified Chinese translation

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
- applications/luci-app-adblock/luasrc/view/adblock/config_css.htm
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
- applications/luci-app-adblock/po/it/adblock.po
- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/ru/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-tw/adblock.po
* bump adblock version in stable tree
> [17.01] luci-app-adblock: release 3.4.3

- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/ru/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
- applications/luci-app-mwan3/po/zh-tw/mwan3.po
Signed-off-by: Vladimir <picfun@ya.ru>
changes by script i18n-scan.pl & i18n-sync.sh
> i18n-sync changes mwan3

- applications/luci-app-ahcp/po/ru/ahcp.po
Signed-off-by: Vladimir <picfun@ya.ru>
> i18n-ru: fixed

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/member.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/memberconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/notify.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policyconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/rule.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_detail.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_diagnostics.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_troubleshooting.htm
Some additional changes:
- Fix dropdown i18n in diagnostics page
- Fix ubus call if no route is defined 
- Add license header
> luci-app-mwan3: refactoring continue 3

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Maintainer: me
Compile tested: mvebu, Linksys WRT3200ACM, 17.01.4
Run tested: ipq806x, Linksys EA8500, 17.01.4 
Description:
- Correctly start/stop/reload from Web UI
> luci-app-vpnbypass: better service start/stop

- applications/luci-app-firewall/po/zh-cn/firewall.po
Update and fix Simplified Chinese translation for luci-app-firewall
> luci-app-firewall: zh-cn: Update Simplified Chinese translation

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simpleadblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Maintainer: me
Compile tested: mvebu, Linksys WRT3200ACM, 17.01.4
Run tested: ipq806x, Linksys EA8500, 17.01.4 
Description:
- Better logic to start/stop/reload from Web UI
> luci-app-simple-adblock: Better logic to start/stop/reload from Web UI

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
> luci-app-adblock: fix XHMTL Markup

- contrib/package/community-profiles/files/etc/config/profile_potsdam
Like PR #1650 for the master branch.
After some discussion in our meetings and on the maling list we decided to
change the SSID to a fixed one.
Signed-off-by: Hannes Fuchs <hannes.fuchs@gmx.org>
> community-profiles: potsdam - changed SSID

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_interface.htm
- Remove module specific css styling
- Remove duplicated javascript to get status informations
- Fix stack trace on interface add
> luci-app-mwan3: fix status pages

- applications/luci-app-travelmate/Makefile
- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* show WiFi QR codes from all configured Access Points
> luci-app-travelmate: sync with release 1.1.3

- modules/luci-base/luasrc/view/cbi/firewall_zonelist.htm
* fix for #1667, tested with all standard themes
this commit only adds an '\<span\>' tag plus indentation changes
> luci-base/firewall_zonelist: fix visual interface/background alignment

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* missed in the last (untested) commit - sorry.
> luci-app-adblock: remaining fixes

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>
> luci-app-attendedsysupgrade: fixup missing package

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Maintainer: me
Tested: OpenWrt master / TL-Archer-C7v2
Description:
LuCI support for https://github.com/openwrt/packages/pull/5787
> unbound: add domain resolution control options

- applications/luci-app-upnp/po/zh-cn/upnp.po
Fix some simplified Chinese translations for luci-app-upnp.
> luci-app-upnp: zh_CN: Update Simplified Chinese translation

- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
**luci-app-mwan3**
- Add mwan3 status boxes again
**luci-theme-material**
- Add missing css status classes success and danger
- Update incorrect warning color from red to yellow
> luci-app-mwan3: add boxes again and update css in luci-theme-material

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/notify.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/rule.lua
- Fix strict XHTML syntax error
- Update notify info page with the new connected/disconnected actions
> luci-app-mwan3: fix syntax error and update notify page

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_detail.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_diagnostics.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_troubleshooting.htm
> luci-app-mwan3: fixes and improvments

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_delete.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
* remove needless 'automatic' and 'trigger' options plus small fixes
> luci-app-travelmate: sync with travelmate 1.2.0

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
* use the form() action to invoke the SimpleForm models
* fix 'wifi_add' input form
> luci-app-travelmate: bugfixes

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- update hint in the interface page
- update hint in the policy page
- show default values in interface page if config is not found
> luci-app-mwan3: fix translation and update defaults

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
* make use of luci.model.uci to fix #1740
> luci-app-mwan3: bugfix

- modules/luci-mod-freifunk/htdocs/luci-static/resources/OSMLatLon.htm
remove some tailing tabs and an empty line in OSMLatLon.htm
Signed-off-by: Sven Roederer <devel-sven@geroedel.de>
> luci-mod-freifunk: align spacing

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
> Fixing small typo

- applications/luci-app-upnp/luasrc/model/cbi/upnp/upnp.lua
When/if https://github.com/openwrt/packages/pull/6001
> luci-app-upnp: support igdv1 run time flag

- modules/luci-base/po/de/base.po
> luci-base: fix i18n de typo for rc.local

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* adapt Adblock to support the new cbi apply workflow
* should be applied to master together with #1769
> luci-app-adblock: support new workflow

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* make sure to update the nw & fw entries only once
> luci-app-travelmate: fix Interface Wizard

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
> luci-app-mwan3: fixes

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- Add quality check options
- Fix ping size dependency. Only valid if tracking method **ping** is selected.
> luci-app-mwan3: add new config options and fix

- modules/luci-base/po/pl/base.po
Updated Polish translations.
Signed-off-by: Rixerx <krystian.kozak20@gmail.com>
> luci-base: update Polish translation

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* respect SimpleForm size limit of 100KB for advanced online editing
> luci-app-adblock: respect SimpleForm size limit

- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* fix ampersand encoding in wireless stations overview
> luci-app-travelmate: fix url ampersand encoding

- applications/luci-app-lxc/luasrc/view/lxc.htm
> luci-app-lxc: remove wrong leftover from last commit

- applications/luci-app-firewall/po/zh-cn/firewall.po
Update Simplified Chinese translation for luci-app-firewall.
> luci-app-firewall: zh_CN: update Simplified Chinese translation

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Tested: TL-Archer-C7v2 OpenWrt master
Description: LuCI updates to support openwrt/packages#6145
>  luci-app-unbound: add root zone file cache option

- applications/luci-app-lxc/luasrc/view/lxc.htm
* fix remaining javascript errors in Chrome
> luci-app-lxc: bugfix

- applications/luci-app-lxc/luasrc/controller/lxc.lua
- applications/luci-app-lxc/luasrc/view/lxc.htm
* wait/lock "create" button until the real end of container creation,
this includes download time plus tar/gz processing time
* cosmetics
> luci-app-lxc: made container creation more reliable

- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
This fix some error from conversion of #1854
@dibdot should be good 
@hnyman also this...
> luci-app-ddns: fix div conversion

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
> luci-app-adblock: sync with adblock 3.5.3

- applications/luci-app-firewall/po/zh-cn/firewall.po
- applications/luci-app-upnp/po/zh-cn/upnp.po
- modules/luci-base/po/zh-cn/base.po
update Openwrt 18.06 Simplified Chinese translation
luci-base
luci-app-firewall
luci-app-upnp
> update Openwrt 18.06 Simplified Chinese translation

- applications/luci-app-firewall/po/uk/firewall.po
- modules/luci-base/po/uk/base.po
Updated Ukrainian translations.
> luci-base & luci-app-firewall: update Ukrainian translation

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
> wireguard: update wireguard url

- applications/luci-app-firewall/po/zh-cn/firewall.po
Use a better translation for offloading
> luci-app-firewall: zh_CN: change better translation for offloading

- applications/luci-app-firewall/po/uk/firewall.po
Updated with the latest synchronization of the translation.
> luci-app-firewall: update Ukrainian translation

- applications/luci-app-bcp38/luasrc/model/cbi/bcp38.lua
Certain types of interface were excluded from bcp38's concept of
upstream wan interface e.g. pppoa-wan
Shameless copy the interface list generation from luci-app-sqm which
solved exactly the same problem and gives additional clues by displaying
the firewall zone (typically wan/lan etc)
Run-tested-on: DGN3500
> luci-app=bcp38: improve interface selection dropdown

- applications/luci-app-rp-pppoe-server/Makefile
> luci-app-rp-pppoe: Fix typo

- luci.mk
- modules/luci-base/Makefile
Tested and works with no problem.
> luci-base: update luasrcdiet

- applications/luci-app-firewall/po/uk/firewall.po
- modules/luci-base/po/uk/base.po
Updated with the latest synchronization of the translation.
> luci-app-firewall & luci-base: update Ukrainian translation

- modules/luci-base/po/zh-cn/base.po
Fix some Chinese translations.
Signed-off-by: Angus Ding <angus.ding@gmail.com>
> base.po: Update chinese translations.

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
And also some cosmetic/error-proofing fixes.
> luci-app-advanced-reboot: support for Linksys WRT32X

- applications/luci-app-upnp/luasrc/controller/upnp.lua
- applications/luci-app-upnp/luasrc/view/upnp_status.htm
This adds the hostname info in the index page of luci.
> luci-app-upnp: add hostname info

- modules/luci-base/po/ru/base.po
> luci-base: fix Russian translation

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
> luci-admin-full: add dnsmasq allservers option

- applications/luci-app-upnp/po/uk/upnp.po
- applications/luci-app-wol/po/uk/wol.po
- modules/luci-base/po/uk/base.po
Updated with the latest resync translation, corrections and additions.
> luci-base, luci-app-upnp, luci-app-wol: update Ukrainian translation

- applications/luci-app-upnp/po/ru/upnp.po
Signed-off-by: Kudratov O <olimko98@gmail.com>
> luci-app-upnp: update Russian translation

- protocols/luci-proto-ncm/luasrc/model/cbi/admin_network/proto_ncm.lua
Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>
> luci-proto-ncm: add pdptype option

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* fix runtime & button translations
> luci-app-adblock: fix translations

- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
* made readonly textarea (logview) scrollable again (bootstrap theme)
* align "Query" input button
> luci-app-adblock: small visual fixes

- applications/luci-app-unbound/luasrc/controller/unbound.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/extended.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/manual.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/server.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/uciedit.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/zones.lua
Tested: TL-Archer-C7v2 OpenWrt master
Description: LuCI to pair with openwrt/packages#657 ... This LuCI application will show the 'zone' section and permit changing 'enabled' and 'fallback' options. Detailed changes to 'zone' secitons will need to use the Edit:UCI tab (text editor).
> luci-app-unbound: add LuCI for forward stub and auth zone clauses

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
Tested with latest 18.06 branch (OpenWrt 18.06-SNAPSHOT, r7175+5-ca0c649a38)
> luci-app-adblock: backport 3.5.4 to 18.06 branch

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_firewall_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_network_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_wireless_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/configuration_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/logread.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
Tested with latest 18.06 branch (OpenWrt 18.06-SNAPSHOT, r7175+5-ca0c649a38)
> luci-app-travelmate: backport 1.2.1 to 18.06 branch

- applications/luci-app-radicale/Makefile
remove myself as PKG_MAINTAINER
> luci-app-radicale: remove myself as PKG_MAINTAINER

- applications/luci-app-radicale/Makefile
remove myself as PKG_MAINTAINER
> luci-app-radicale[18.06]: remove myself as PKG_MAINTAINER

- applications/luci-app-ddns/Makefile
remove myself as PKG_MAINTAINER
> luci-app-ddns: remove myself as PKG_MAINTAINER

- applications/luci-app-ddns/Makefile
remove myself as PKG_MAINTAINER
> luci-app-ddns[18.06]: remove myself as PKG_MAINTAINER

- applications/luci-app-ddns/luasrc/tools/ddns.lua
> luci-app-ddns: fix huge typo in luasrc/tools/ddns.lua

- modules/luci-base/po/zh-cn/base.po
> luci-base: update Chinese translation

- modules/luci-mod-admin-full/luasrc/view/admin_system/applyreboot.htm
- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
- themes/luci-theme-freifunk-generic/htdocs/luci-static/freifunk-generic/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css
This improve applyreboot page and fix problem with luci-nginx that doesn't refresh the page when the router reboot.
> luci-mod-admin-full: improve applyreboot page

- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
* fix logical glitch in forced upgrade logic
> luci-mod-admin-full: fix forced upgrade

- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* fix cornercase issues in runtime information/json parsing
> luci-app-adblock: sync with adblock 3.5.5

- modules/luci-base/po/ru/base.po
> luci-base: update Russian translation

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- Show executed command on diagnostic page
- Use cbi flag template on interface enable option
- Fix physical device lookup for dynamic interface
- Make text translatable in the diagnostic page
> luci-app-mwan3:  fixes and improvements

- applications/luci-app-https_dns_proxy/Makefile
- applications/luci-app-https_dns_proxy/luasrc/controller/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/po/templates/https_dns_proxy.pot
- applications/luci-app-https_dns_proxy/root/etc/uci-defaults/40_luci-https_dns_proxy
Description: Web UI for https_dns_proxy package. Dependent on https://github.com/openwrt/packages/pull/6853.
> luci-app-https_dns_proxy: initial commit

- applications/luci-app-firewall/po/ru/firewall.po
Add missing translations and update existing not quite correct translations.
Removed redundant br tags from translations.
> luci-app-firewall: fix and update Russian translation

- modules/luci-base/po/tr/base.po
Add missing translations.
Signed-off-by: Yusuf Soyipek <yusuf@soyipek.com>
> luci-base: update Turkish translation

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Maintainer: me
Tested: TL-Archer-C7v2 (ath79) master
Description: coordinated with openwrt/packages#7036 and solves #2151
> luci-app-unbound: add protocol=ip4_local option support

- protocols/luci-proto-ipv6/Makefile
> luci-proto-ipv6: fix dependency for IPv6

- applications/luci-app-mosquitto/Makefile
- applications/luci-app-mosquitto/luasrc/controller/mosquitto.lua
- applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua
Originally developed and maintained at https://github.com/remakeelectric/owrt_pub_feeds/tree/master/luci-app-mosquitto
> luci-app-mosquitto: import new application

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
Rework overview page, sync with new style and simplify the code by removing unnecessary check
> luci-app-ddns: various fix

- modules/luci-base/po/de/base.po
> luci-base: fix german translations

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/po/de/mwan3.po
- Start of adding german translation
- Add new max_ttl option see https://github.com/openwrt/packages/commit/c9d8fceb63a425f19fc12bee7ee4191fad514b6e#diff-87268a842bab5effbe181f9f18b2d348
> luci-app-mwan3: start adding german translation a new max_ttl option

- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
This option is usefull to solve some problems with ath10k-ct and random client disconnect
> luci-app-network: add rekey option

- modules/luci-mod-system/luasrc/model/cbi/admin_system/system.lua
This adds option to configure zram size and compression algo
@jow- 
> luci-mod-system: add zram options

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
The i18n translation did not work in the controller as expected, due missing i18n lua requirements.
This PR will fix this issue.
> luci-app-mwan3: fix i18n traceback

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/custom.css
* make font configurable
* fix loading-img view
* fix word wrap on german translation
> luci-theme-material: make font configurable and minor fixes

- modules/luci-base/root/www/index.html
> luci-base: redirect root path to /cgi-bin/luci/

- modules/luci-base/po/uk/base.po
Updated with the latest sync translation, corrections.
> luci-base: update Ukrainian translation

- applications/luci-app-openvpn/luasrc/controller/openvpn.lua
* fix shellquote oversight of the last commit
> luci-app-openvpn: file name fix

- modules/luci-mod-system/luasrc/model/cbi/admin_system/fstab.lua
> luci-mod-system: fstab: "SWAP" section title is made translatable

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* add support for the new 'trm_proactive' option
> luci-app-travelmate: sync with travelmate 1.3.0

- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
- applications/luci-app-olsr-viz/htdocs/luci-static/resources/olsr-viz.js
- applications/luci-app-olsr/luasrc/view/status-olsr/common_js.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/hna.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/smartgw.htm
- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-mod-freifunk/htdocs/luci-static/resources/osm.js
- modules/luci-mod-status/luasrc/view/admin_status/wireless.htm
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
This fixes errors reported by LGTM.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Add missing variable declarations in JavaScript code

- applications/luci-app-olsr-services/luasrc/view/freifunk-services/services.htm
- applications/luci-app-olsr/luasrc/model/cbi/olsr/olsrdplugins.lua
- applications/luci-app-olsr/luasrc/model/cbi/olsr/olsrdplugins6.lua
- applications/luci-app-siitwizard/luasrc/model/cbi/siitwizard.lua
- contrib/package/freifunk-common/files/usr/bin/neigh.sh
- contrib/package/freifunk-common/files/usr/sbin/ff_olsr_watchdog
- contrib/package/freifunk-mapupdate/files/usr/sbin/ff_mapupdate.sh
- contrib/package/meshwizard/files/usr/bin/meshwizard/helpers/setup_olsrd.sh
- modules/luci-mod-freifunk/luasrc/view/freifunk-map/frame.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk-map/map.htm
Signed-off-by: Philipp Borgers <borgers@mi.fu-berlin.de>
> get rid of library version numbers in luci olsrd code

- applications/luci-app-wireguard/Makefile
- protocols/luci-proto-wireguard/Makefile
I tried to find a successor in the last months, but that failed.
Signed-off by Dan Luedtke <mail@danrl.com>
> luci-*-wireguard: Remove inactive maintainer

- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- fix translation related issues
- sync translations
- update Japanese translations
> luci-base: fix issues and update Japanese translation

- applications/luci-app-banip/Makefile
- applications/luci-app-banip/luasrc/controller/banip.lua
- applications/luci-app-banip/luasrc/model/cbi/banip/blacklist_tab.lua
- applications/luci-app-banip/luasrc/model/cbi/banip/configuration_tab.lua
- applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
- applications/luci-app-banip/luasrc/model/cbi/banip/whitelist_tab.lua
- applications/luci-app-banip/luasrc/view/banip/banip_css.htm
- applications/luci-app-banip/luasrc/view/banip/ipsetview.htm
- applications/luci-app-banip/luasrc/view/banip/logview.htm
- applications/luci-app-banip/luasrc/view/banip/ripeview.htm
- applications/luci-app-banip/luasrc/view/banip/runtime.htm
- applications/luci-app-banip/luasrc/view/banip/sourcelist.htm
- applications/luci-app-banip/root/etc/uci-defaults/40_luci-banip
for details & LuCI screenshots see base package description/PR:
https://github.com/openwrt/packages/pull/7373
> luci-app-banip: new package

- applications/luci-app-banip/luasrc/view/banip/ipsetview.htm
- applications/luci-app-banip/luasrc/view/banip/ripeview.htm
* fix JS errors in chromium on ipset- & ripe-view page
> luci-app-banip: fix JS errors in chromium

- applications/luci-app-banip/luasrc/view/banip/banip_css.htm
- applications/luci-app-banip/luasrc/view/banip/runtime.htm
* fix IE Edge rendering issues
* merge remaining external styles in central css
> luci-app-banip: fix remaining css issues

- modules/luci-base/po/zh-cn/base.po
i18n: luca-base: update Simplified Chinese translation
> i18n: luci-base: update Simplified Chinese translation

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
- Declare module variables local
- Remove deprecated option local_source
- Add option rtmon
- Add option rtlookup
> luci-app-mwan3: add/remove options

- modules/luci-base/luasrc/view/cbi/browser.htm
With this change we could set optional default value for the file browser.
> luci-base: allow optional default value for file browser

- applications/luci-app-travelmate/luasrc/view/travelmate/travelmate_css.htm
> luci-app-travelmate: adapt latest css changes

- applications/luci-app-adblock/luasrc/view/adblock/adblock_css.htm
> luci-app-adblock: adapt latest css changes

- applications/luci-app-banip/luasrc/view/banip/banip_css.htm
> luci-app-banip: adapt latest css changes

- modules/luci-mod-system/luasrc/model/cbi/admin_system/fstab.lua
> luci-mod-system: fstab: fix table cell rendering without unmount button

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
htdocs: Modifying the form does not fully display the bug of the dropdown box
htdocs: Match css to implement related styles
Signed-off-by: Yanlan Shen yanlan.shen.@rosinson.com
> luci-theme-rosy: Repair form bug

- applications/luci-app-opkg/po/uk/opkg.po
> opkg.po: update Ukrainian translation

- applications/luci-app-opkg/po/ja/opkg.po
Fixed and updated Japanese translations.
> luci-app-opkg: fix and update Japanese translation

- applications/luci-app-opkg/po/uk/opkg.po
- modules/luci-base/po/uk/base.po
Updated with the latest resync translation, corrections and additions.
> luci-base & luci-app-opkg: update Ukrainian translation

- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
Signed-off-by: Reuben Balik <rsbalik@gmail.com>
> luci-mod-network: Add DAE settings to security tab

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
> luci-theme-material: add the missing modal/progressbar rules.

- applications/luci-app-firewall/luasrc/view/firewall/cbi_addforward.htm
- applications/luci-app-firewall/luasrc/view/firewall/cbi_addrule.htm
Remove firewall hinting as discussed in #2340
> luci-app-firewall: remove hinting

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
htdocs: Modify the color of the button's primary and secondary colors and the bug of the status-overview page.
htdocs: Fixed a drop-down box that doesn't display properly in the table, and fixed a bug where some tables don't display rounded corners properly
Signed-off-by: Yanlan Shen <yanlan.shen.@rosinson.com>
> luci-theme-rosy: Fix related bugs displayed on the page

- applications/luci-app-opkg/po/zh-cn/opkg.po
Signed-off-by: Zheng Qian <sotux82@gmail.com>
> luci-app-opkg: update Simplified Chinese translation

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
luci-theme-rosy: Fixed insufficient container container width
Signed-off-by: Yanlan Shen <yanlan.shen.@rosinson.com>
> luci-theme-rosy: Fixed insufficient container container width

- modules/luci-base/luasrc/view/admin_uci/changelog.htm
> luci-base: fix UCI changelog markup mistake

- modules/luci-base/po/zh-cn/base.po
Signed-off-by: Zheng Qian <sotux82@gmail.com>
> luci-base: update Simplified Chinese translation

- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
- applications/luci-app-ahcp/luasrc/view/ahcp_status.htm
- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
- applications/luci-app-banip/luasrc/view/banip/logview.htm
- applications/luci-app-banip/luasrc/view/banip/runtime.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ltqtapi/luasrc/view/telephony_status.htm
- applications/luci-app-minidlna/luasrc/view/minidlna_status.htm
- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_detail.htm
- applications/luci-app-ocserv/luasrc/view/ocserv_status.htm
- applications/luci-app-privoxy/luasrc/view/privoxy/detail_startstop.htm
- applications/luci-app-radicale/luasrc/view/radicale/btn_startstop.htm
- applications/luci-app-shadowsocks-libev/luasrc/view/shadowsocks-libev/add_instance.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/logread.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-upnp/luasrc/view/upnp_status.htm
- applications/luci-app-wireguard/luasrc/view/wireguard.htm
- modules/luci-base/htdocs/luci-static/resources/xhr.js
- modules/luci-base/luasrc/view/header.htm
- modules/luci-base/luasrc/view/lease_status.htm
- modules/luci-base/luasrc/view/wifi_assoclist.htm
- modules/luci-mod-network/luasrc/view/admin_network/switch_status.htm
- modules/luci-mod-system/luasrc/view/admin_system/clock_status.htm
If an interval configuration option is set under luci.main.interval,
then use this one.
If this is not specified then use the default specified in the source.
> modules: use configurable poll interval

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/view/adblock/report.htm
* use new XHR default on report page
* fix wrong string.find syntax
> luci-app-adblock: minor fixes

- modules/luci-base/po/ja/base.po
> luci-base: fix Japanese translation

- applications/luci-app-wifischedule/po/de/wifischedule.po
New German Translation of wifischedule.po
Signed-of-by: Roland Engert <Roland.Engert@web.de>
> luci-app-wifischedule: New German Translation

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
- applications/luci-app-mwan3/po/de/mwan3.po
- Add tracking method **nping** depends on PR https://github.com/openwrt/packages/pull/7738
- Add uptime/downtime to status page requested by https://github.com/openwrt/packages/issues/7501
- Only show tracking method if the used binary is installed
- Update I18N for de
> luci-app-mwan3: some changes

- applications/luci-app-firewall/po/uk/firewall.po
- applications/luci-app-opkg/po/uk/opkg.po
- modules/luci-base/po/uk/base.po
> Update Ukrainian translation

- applications/luci-app-nut/po/templates/nut.pot
Finally noticed that I had been missing doing i18n stuff, so
add the template for this new package I added.
> luci-app-nut: Add i18n template (pot)

- applications/luci-app-nft-qos/luasrc/controller/nft-qos.lua
rework _action_rate function, make the code cleaner.
> luci-app-nft-qos: rework _action_rate function

- applications/luci-app-unbound/luasrc/controller/unbound.lua
Maintainer: me
Tested: TL-Archer-C7v2 openwrt master
Description: same print overflow protection as adblock configuration...
> luci-app-unbound: protect against printing large cache dump

- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
- documentation/CBI.md
I found 3 instances of "wiki.openwrt.org" in this repository so I updated them to point to their new wiki pages.
Signed-off-by: Leong Hui Wong <wong.leonghui@gmail.com>
> Update docs and packages wiki links

- applications/luci-app-adblock/po/zh-cn/adblock.po
- applications/luci-app-adblock/po/zh-tw/adblock.po
- applications/luci-app-ahcp/po/zh-cn/ahcp.po
- applications/luci-app-ahcp/po/zh-tw/ahcp.po
- applications/luci-app-https_dns_proxy/po/zh-cn/https_dns_proxy.po
- applications/luci-app-https_dns_proxy/po/zh-tw/https_dns_proxy.po
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
- applications/luci-app-mwan3/po/zh-tw/mwan3.po
- applications/luci-app-nft-qos/po/zh-tw/nft-qos.po
- applications/luci-app-nut/po/zh-cn/nut.po
- applications/luci-app-nut/po/zh-tw/nut.po
- applications/luci-app-privoxy/po/zh-tw/privoxy.po
- applications/luci-app-simple-adblock/po/zh-cn/simple-adblock.po
- applications/luci-app-simple-adblock/po/zh-tw/simple-adblock.po
- applications/luci-app-statistics/po/zh-cn/statistics.po
- applications/luci-app-statistics/po/zh-tw/statistics.po
- applications/luci-app-travelmate/po/zh-cn/travelmate.po
- applications/luci-app-travelmate/po/zh-tw/travelmate.po
- applications/luci-app-unbound/po/zh-cn/unbound.po
- applications/luci-app-unbound/po/zh-tw/unbound.po
- applications/luci-app-wireguard/po/zh-cn/wireguard.po
- applications/luci-app-wireguard/po/zh-tw/wireguard.po
> i18n: update Chinese translation

- applications/luci-app-olsr/po/zh-cn/olsr.po
> luci-app-olsr: update Simplified Chinese translation

- modules/luci-mod-freifunk/luasrc/model/cbi/freifunk/basics.lua
> Backport 18.06: luci-mod-freifunk: fix the list of community profiles

- applications/luci-app-openvpn/po/zh-cn/openvpn.po
update Simplified Chinese translation
> luci-app-openvpn: update Simplified Chinese translation

- applications/luci-app-ddns/po/ru/ddns.po
> luci-app-ddns: fix Russian translation

- applications/luci-app-openvpn/po/ru/openvpn.po
> luci-app-openvpn: fix and update Russian translation

- applications/luci-app-opkg/po/ru/opkg.po
> luci-app-opkg: update Russian translation

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/member.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/memberconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/notify.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policyconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/rule.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
Fix local scope in luci-app-mwan3
> luci-app-mwan3: fix cbi local scope

- modules/luci-mod-system/luasrc/model/cbi/admin_system/system.lua
Make pollinterval configurable via LuCI
> luci-mod-system: add pollinterval option

- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- fix package installation **admin/system/packages** does not exist anymore
> luci-app-ddns: fix package installation link

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
- Add new syslog option
- Add prefilled ipset dropdwon on rule configuration
> luci-app-mwan3: add syslog option and prefiil ipset rule dropdown

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
to distinguish between installed packages and requested packages, the
API call is now "installed" instead of "packages".
Also unify "info_box" and "error_box" to "status_box"
> luci-app-attendedsysupgrade: new api, unify status

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
I'd also appreciate a response to my comment in #2383
> luci-theme-material: various css changes

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
Fix possibility to not select an ipset.
#2476
> luci-app-mwan3: fix possibility to not select an ipset

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
to distinguish between installed packages and requested packages, the
API call is now "installed" instead of "packages".
Also unify "info_box" and "error_box" to "status_box"
> 18.06: luci-app-attendedsysupgrade: new api, unify status

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
server does not send full download url but only path
fixup error_box
> luci-app-attendedsysupgrade: fixup server url

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
> luci-app-attendedsysupgrade: fixup error_box

- applications/luci-app-statistics/po/zh-cn/statistics.po
> luci-app-statistics: update Simplified Chinese translation

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- changed procd trigger handling & removed needless apply hook
> luci-app-travelmate: sync with release 1.3.5

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
there was a major rewrite of the database structure
> luci-app-attendedsysupgrade: update to new api

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
there was a major rewrite of the database structure
> 18.06: luci-app-attendedsysupgrade: update to new api

- applications/luci-app-opkg/po/es/opkg.po
Complete update of the app to the Spanish language
> luci-app-opkg: Update of the Spanish language

- applications/luci-app-openvpn/po/es/openvpn.po
Complete update Spanish translation
> luci-app-openvpn: Update Spanish translation

- applications/luci-app-clamav/po/es/clamav.po
> luci-app-clamav: Add Spanish translation

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
luci-theme-rosy: Correcting Writing Errors and Style Errors
Due to the last large-scale update of the code, leaving some bugs, this repair
Signed-off-by: YanlanShen <yanlan.Shen@rosinson.com>
> luci-theme-rosy: Fix typo errors and style errors

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
Signed-off-by: Yanlan Shen <yanlan.shen.@rosinson.com>
> theme: add initial commit for purple theme

- applications/luci-app-firewall/po/es/firewall.po
> luci-app-firewall: Update Spanish translation

- modules/luci-base/po/es/base.po
> luci-base: Update Spanish translation

- applications/luci-app-commands/po/es/commands.po
> luci-app-commands: Update Spanish translation

- applications/luci-app-https_dns_proxy/po/es/https_dns_proxy.po
> luci-app-https_dns_proxy: Add Spanish translation

- applications/luci-app-ddns/po/es/ddns.po
> luci-app-ddns: Update Spanish translation

- applications/luci-app-adblock/po/es/adblock.po
> luci-app-adblock: Add Spanish translation

- applications/luci-app-wifischedule/po/es/wifischedule.po
> luci-app-wifischedule: Add Spanish translation

- applications/luci-app-advanced-reboot/po/es/advanced-reboot.po
> luci-app-advanced-reboot: Add Spanish translation

- modules/luci-base/po/zh-cn/base.po
for msgid "Obtain IPv6-Address" at lede-17
> luci-base: update Chinese translate

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- Fix whitspace issues
- Fix thermal definitions type has changed from temperatur to gauge
> luci-app-statistics: minor fixes

- applications/luci-app-shairplay/po/es/shairplay.po
> luci-app-shairplay: Add Spanish translation

- applications/luci-app-aria2/po/es/aria2.po
> luci-app-aria2: Add Spanish translation

- applications/luci-app-bcp38/po/es/bcp38.po
> luci-app-bcp38: Add Spanish translation

- applications/luci-app-samba4/po/es/samba4.po
> luci-app-samba4: Update Spanish translation

- applications/luci-app-ahcp/po/es/ahcp.po
> luci-app-ahcp: Update Spanish translation

- applications/luci-app-fwknopd/po/es/fwknopd.po
> luci-app-fwknopd: Add Spanish translation

- applications/luci-app-simple-adblock/po/es/simple-adblock.po
> luci-app-simple-adblock: Add Spanish translation

- applications/luci-app-dynapoint/po/es/dynapoint.po
> luci-app-dynapoint: Add Spanish translation

- applications/luci-app-uhttpd/po/es/uhttpd.po
> luci-app-uhttpd: Add Spanish translation

- applications/luci-app-minidlna/po/es/minidlna.po
> luci-app-minidlna: Update Spanish translation

- applications/luci-app-samba/po/es/samba.po
> luci-app-samba: Update Spanish translation

- applications/luci-app-rp-pppoe-server/po/es/rp-pppoe-server.po
> luci-app-rp-pppoe-server: Add Spanish translation

- applications/luci-app-upnp/po/es/upnp.po
> luci-app-upnp: Update Spanish translation

- applications/luci-app-wol/po/es/wol.po
> luci-app-wol: Update Spanish translation

- applications/luci-app-shadowsocks-libev/po/es/shadowsocks-libev.po
> luci-app-shadowsocks-libev: Add Spanish translation

- modules/luci-mod-admin-mini/luasrc/model/cbi/mini/wifi.lua
- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
> wifi: add "macaddr" validator to bssid option

- applications/luci-app-wireguard/po/es/wireguard.po
> luci-app-wireguard: Add Spanish translation

- applications/luci-app-watchcat/po/es/watchcat.po
> luci-app-watchcat: Update Spanish translation

- applications/luci-app-travelmate/po/es/travelmate.po
> luci-app-travelmate: Add Spanish translation

- applications/luci-app-hd-idle/po/es/hd_idle.po
> luci-app-hd_idle: Update Spanish translation

- applications/luci-app-qos/po/es/qos.po
> luci-app-qos: Update Spanish translation

- applications/luci-app-transmission/po/es/transmission.po
> luci-app-transmission: Update Spanish translation

- applications/luci-app-advanced-reboot/po/es/advanced-reboot.po
> luci-app-advanced-reboot: Update Spanish translation

- applications/luci-app-olsr/po/es/olsr.po
> luci-app-olsr: Update Spanish translation

- applications/luci-app-wifischedule/po/es/wifischedule.po
> luci-app-wifischedule: Update Spanish translation

- applications/luci-app-wireguard/po/es/wireguard.po
> luci-app-wireguard: Update Spanish translation

- applications/luci-app-statistics/po/es/statistics.po
> luci-app-statistics: Update Spanish translation

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
* Reuse `request_dict` between requests.
* used vim Autoformat plugin to make the javascript code nice.
* add board_name as it eventually replaces board/model in requests
> luci-app-attendedsysupgrade: refactor and format

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
HTTP Error code is send by the upgrade server in case of package
conflicts, like when requesting to install both `odhcpd` and
`odhcpd-ipv6only`.
Also put a <p> around download links to make them look more appealing.
> luci-app-attendedsysupgrade: add 409 error code

- applications/luci-app-wifischedule/luasrc/model/cbi/wifischedule/wifi_schedule.lua
* minimal fix for #2631 (untested)
> luci-app-wifischedule: apply-bugfix

- applications/luci-app-simple-adblock/po/ja/simple-adblock.po
Updated Japanese translations.
> luci-app-simple-adblock: update Japanese translation

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
luci-theme-rosy: Fix the display bug in the mobile login interface
luci-theme-rosy: Modification of header style of Web pages.
Signed-off-by: YanlanShen <yanlan.Shen@rosinson.com>
> luci-theme-rosy: Fix bug in the login interface and header style 
