openwrt/luci

applications/luci-app-vpnbypass/po/es/vpnbypass.po
=> luci-app-vpnbypass: Add Spanish translation

applications/luci-app-dnscrypt-proxy/po/es/dnscrypt-proxy.po
=> luci-app-dnscrypt-proxy: Add Spanish translation

applications/luci-app-pagekitec/po/es/pagekitec.po
=> luci-app-pagekitec: Add Spanish translation

applications/luci-app-mwan3/po/es/mwan3.po
=> luci-app-mwan3: Add Spanish translation

applications/luci-app-noddos/po/es/noddos.po
=> luci-app-noddos: Add Spanish translation

applications/luci-app-vnstat/po/es/vnstat.po
=> luci-app-vnstat: Update Spanish translation

applications/luci-app-p910nd/po/es/p910nd.po
=> luci-app-p910nd: Update Spanish translation

applications/luci-app-nft-qos/po/es/nft-qos.po
=> luci-app-nft-qos: Add Spanish translation

applications/luci-app-unbound/po/es/unbound.po
=> luci-app-unbound: Add Spanish translation

themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css, themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js, themes/luci-theme-rosy/luasrc/view/themes/rosy/footer.htm
This PR includes below improvements:
1. Bugs fix for https://github.com/openwrt/luci/issues/2645
2. Padding improvement for network/wireless interfaces
https://github.com/rosywrt/luci-theme-rosy/issues/51
3. Fix compatibility for devices
@jow-  @hnyman
=> luci-theme-rosy: bugs fix

applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* see https://github.com/openwrt/packages/pull/8637 for reference
=> luci-app-travelmate: sync with update 1.4.5

modules/luci-mod-system/luasrc/view/admin_system/password.htm
=> luci-mod-system: add password strength info

applications/luci-app-ddns/po/es/ddns.po
=> luci-app-ddns: Udpate Spanish translation

applications/luci-app-adblock/po/es/adblock.po
=> luci-app-adblock: Update Spanish translation

applications/luci-app-nlbwmon/po/es/nlbwmon.po
=> luci-app-nlbwmon: Add Spanish translation

applications/luci-app-shadowsocks-libev/po/es/shadowsocks-libev.po
=> luci-app-shadowsocks-libev: Udpate Spanish translation

applications/luci-app-polipo/po/es/polipo.po
=> luci-app-polipo: Update Spanish translation

applications/luci-app-opkg/po/es/opkg.po
=> luci-app-opkg: Update Spanish translation

applications/luci-app-mjpg-streamer/po/es/mjpg-streamer.po
=> luci-app-mjpg-streamer: Add Spanish translation

applications/luci-app-aria2/po/es/aria2.po
=> luci-app-aria2: Update Spanish translation

applications/luci-app-hd-idle/po/es/hd_idle.po
=> luci-app-hd-idle: Update Spanish translation

applications/luci-app-uhttpd/po/de/uhttpd.po
German translation by Matthias Meißer
=> luci-app-uhttpd German translation

applications/luci-app-mjpg-streamer/luasrc/model/cbi/mjpg-streamer.lua
Signed-off-by: Jose Riha <jose1711@gmail.com>
=> luci-app-mjpg-streamer: add link option 

applications/luci-app-privoxy/po/hi/privoxy.po, luci.mk
Signed-off-by: Simmar Kalsi simmarkalsi@gmail.com
=> luci-app-privoxy: Added Hindi translation

applications/luci-app-tinyproxy/po/es/tinyproxy.po
=> luci-app-tinyproxy: Update Spanish translation

themes/luci-theme-material/htdocs/luci-static/material/cascade.css
Without the change:
With the change:
=> luci-theme-material: fix checkbox css StaticList view

applications/luci-app-lxc/Makefile
=> luci-app-lxc: add conffiles define

modules/luci-base/po/zh-tw/base.po
update Traditional Chinese translation.
Signed-off-by: Andy Yun <a962702@yahoo.com>
=> luci-base: update Traditional Chinese translation

applications/luci-app-aria2/luasrc/model/cbi/aria2.lua
just a spelling mistake.
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>
=> luci-app-aria2: fix: datatype

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js, applications/luci-app-opkg/po/ca/opkg.po, applications/luci-app-opkg/po/cs/opkg.po, applications/luci-app-opkg/po/de/opkg.po, applications/luci-app-opkg/po/el/opkg.po, applications/luci-app-opkg/po/en/opkg.po, applications/luci-app-opkg/po/es/opkg.po, applications/luci-app-opkg/po/fr/opkg.po, applications/luci-app-opkg/po/he/opkg.po, applications/luci-app-opkg/po/hu/opkg.po, applications/luci-app-opkg/po/it/opkg.po, applications/luci-app-opkg/po/ja/opkg.po, applications/luci-app-opkg/po/ko/opkg.po, applications/luci-app-opkg/po/ms/opkg.po, applications/luci-app-opkg/po/no/opkg.po, applications/luci-app-opkg/po/pl/opkg.po, applications/luci-app-opkg/po/pt-br/opkg.po, applications/luci-app-opkg/po/pt/opkg.po, applications/luci-app-opkg/po/ro/opkg.po, applications/luci-app-opkg/po/ru/opkg.po, applications/luci-app-opkg/po/sk/opkg.po, applications/luci-app-opkg/po/sv/opkg.po, applications/luci-app-opkg/po/templates/opkg.pot, applications/luci-app-opkg/po/tr/opkg.po, applications/luci-app-opkg/po/uk/opkg.po, applications/luci-app-opkg/po/vi/opkg.po, applications/luci-app-opkg/po/zh-cn/opkg.po, applications/luci-app-opkg/po/zh-tw/opkg.po
* add three dots to the first level 'Remove' button caption
(revert/fix da8668a)
=> luci-app-opkg: change remove button caption (first level)

themes/luci-theme-material/luasrc/view/themes/material/header.htm
=> luci-theme-material: make 'Loading...' text translatable

themes/luci-theme-material/luasrc/view/themes/material/header.htm
It's better to reuse the already available and well translated string
'Collecting data...'.
@jow- As discussed in #2793
=> luci-theme-material: change string 'Loading...' to 'Collecting data...'

applications/luci-app-firewall/po/de/firewall.po
=> luci-app-firewall: add some german translations

modules/luci-base/po/de/base.po
=> luci-base: add german translations for led trigger

applications/luci-app-mwan3/po/de/mwan3.po
=> luci-app-mwan3: add some german translations

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua, applications/luci-app-travelmate/po/pt-br/travelmate.po, applications/luci-app-travelmate/po/ru/travelmate.po, applications/luci-app-travelmate/po/templates/travelmate.pot, applications/luci-app-travelmate/po/zh-cn/travelmate.po, applications/luci-app-travelmate/po/zh-tw/travelmate.po, modules/luci-base/luasrc/sys.lua, modules/luci-mod-network/root/etc/uci-defaults/50_luci-mod-admin-full
=> Openwrt 19.07

modules/luci-base/po/de/base.po
=> luci-base: fix typo in german translation

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
=> luci-app-simple-adblock: sync with the latest version of simple-adblock

modules/luci-base/luasrc/view/cbi/cell_valueheader.htm, modules/luci-base/luasrc/view/cbi/full_valueheader.htm, modules/luci-base/luasrc/view/cbi/value.htm
=> luci-base: fix display of password input

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> [18.06] luci-app-advanced-reboot: kernel version length bugfix + add routers

applications/luci-app-advanced-reboot/Makefile
=> luci-app-advanced-reboot: fix README url in Makefile

applications/luci-app-advanced-reboot/Makefile
=> [19.07] luci-app-advanced-reboot: fix README url in Makefile

applications/luci-app-advanced-reboot/Makefile
=> [18.06] luci-app-advanced-reboot: fix README url in Makefile

applications/luci-app-lxc/po/templates/lxc.pot
=> luci-app-lxc: Add template

applications/luci-app-rosy-file-server/po/templates/rosy-file-server.pot
=> luci-app-rosy-file-server: Add template

applications/luci-app-firewall/po/uk/firewall.po, modules/luci-base/po/uk/base.po
=> luci-base & luci-app-firewall: update Ukrainian translation.

applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua, applications/luci-app-adblock/po/es/adblock.po, applications/luci-app-adblock/po/it/adblock.po, applications/luci-app-adblock/po/ja/adblock.po, applications/luci-app-adblock/po/pt-br/adblock.po, applications/luci-app-adblock/po/ru/adblock.po, applications/luci-app-adblock/po/sv/adblock.po, applications/luci-app-adblock/po/templates/adblock.pot, applications/luci-app-adblock/po/zh-cn/adblock.po, applications/luci-app-adblock/po/zh-tw/adblock.po
=> luci-app-adblock: English grammar fix

applications/luci-app-firewall/htdocs/luci-static/resources/tools/firewall.js, applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js, applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js
This should fix the issue #2878.
=> luci-app-firewall: format protocol family for forwards and rules

modules/luci-base/po/uk/base.po
=> luci-base: correct spelling mistake in Ukrainian translation

applications/luci-app-e2guardian/po/templates/e2guardian.pot
=> luci-app-e2guardian: Add template

applications/luci-app-bmx7/po/templates/bmx7.pot
=> luci-app-bmx7: Add template

applications/luci-app-banip/po/templates/banip.pot
=> luci-app-banip: Add template

applications/luci-app-attendedsysupgrade/po/templates/attendedsysupgrade.pot
=> luci-app-attendedsysupgrade: Add template

applications/luci-app-cshark/po/templates/cshark.pot
=> luci-app-cshark: Add template

applications/luci-app-dump1090/po/templates/dump1090.pot
=> luci-app-dump1090: Add template

applications/luci-app-ltqtapi/po/templates/ltqtapi.pot
=> luci-app-ltqtapi: Add template

applications/luci-app-mosquitto/po/templates/mosquitto.pot
=> luci-app-mosquitto: Add template

applications/luci-app-olsr-services/po/templates/olsr-services.pot
=> luci-app-olsr-services: Add template

applications/luci-app-olsr-viz/po/templates/olsr-viz.pot
=> luci-app-olsr-viz: Add template

applications/luci-app-squid/po/templates/squid.pot
=> luci-app-squid: Add template

applications/luci-app-lxc/po/es/lxc.po
=> luci-app-lxc: Add Spanish translation

themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
This commit fix https://github.com/openwrt/luci/issues/2887 on network/firewall/zones that the content is cut off on firefox browser.
=> luci-theme-rosy: fix #2887

applications/luci-app-https_dns_proxy/Makefile, applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
=> luci-app-https_dns_proxy: better handling of ports, update dhcp config

applications/luci-app-privoxy/po/es/privoxy.po
=> luci-app-privoxy: Add Spanish translation

applications/luci-app-ltqtapi/po/es/ltqtapi.po
=> luci-app-ltqtapi: Add Spanish translation

applications/luci-app-nut/po/es/nut.po
=> luci-app-nut: Add Spanish translation

applications/luci-app-banip/po/es/banip.po
=> luci-app-banip: Add Spanish translation

applications/luci-app-olsr-viz/po/es/olsr-viz.po
=> luci-app-olsr-viz: Add Spanish translation

applications/luci-app-openvpn/po/de/openvpn.po
=> luci-app-openvpn: add some german translations

applications/luci-app-attendedsysupgrade/po/es/attendedsysupgrade.po
=> luci-app-attendedsysupgrade: add Spanish translation

applications/luci-app-squid/po/es/squid.po
=> luci-app-squid: add Spanish translation

applications/luci-app-ocserv/po/es/ocserv.po
=> luci-app-ocserv: add Spanish translation

applications/luci-app-olsr-services/po/es/olsr-services.po
=> luci-app-olsr-services: add Spanish translation

applications/luci-app-bmx7/po/es/bmx7.po
=> luci-app-bmx7: add Spanish translation

applications/luci-app-cshark/po/es/cshark.po
=> luci-app-cshark: add Spanish translation

applications/luci-app-dump1090/po/es/dump1090.po
=> luci-app-dump1090: add Spanish translation

applications/luci-app-simple-adblock/po/es/simple-adblock.po
=> luci-app-simple-adblock: update Spanish translation

applications/luci-app-travelmate/po/es/travelmate.po
=> luci-app-travelmate: update Spanish translation

applications/luci-app-udpxy/po/templates/udpxy.pot
=> luci-app-udpxy: add template

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> luci-app-advanced-reboot: support for Linksys EA8300

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> [19.07] luci-app-advanced-reboot: support for Linksys EA8300

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> [18.06] luci-app-advanced-reboot: support for Linksys EA8300

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> luci-app-simple-adblock: support for varios DNS resolvers/options

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> [19.07] luci-app-simple-adblock: support for varios DNS resolvers/options

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> [18.06] luci-app-simple-adblock: support for varios DNS resolvers/options

modules/luci-base/po/de/base.po
=> luci-base: fix some german translations

modules/luci-base/po/uk/base.po
=> luci-base: fix some Ukrainian translations

applications/luci-app-adblock/luasrc/controller/adblock.lua, applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* fix a suspend/resume issue
* format overall domains with a thousands separator
=> luci-app-adblock: sync with adblock 3.8.3

applications/luci-app-firewall/po/de/firewall.po
=> luci-app-firewall: Use more appropriate terms in german translations

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> luci-app-simple-adblock: dns resolver value bugfix (#3000)

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> [19.07] luci-app-simple-adblock: dns resolver value bugfix (#3000)

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
=> [18.06] luci-app-simple-adblock: dns resolver value bugfix (#3000)

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> luci-app-vpnbypass: better start/stop controls, create entry in the VPN menu if it exists

applications/luci-app-banip/luasrc/controller/banip.lua, applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua, applications/luci-app-banip/luasrc/view/banip/runtime.htm
=> luci-app-banip: sync with banIP 0.2.0

themes/luci-theme-material/htdocs/luci-static/material/cascade.css, themes/luci-theme-material/luasrc/view/themes/material/header.htm
=> luci-theme-material: show logo also on login page

applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/cpu.lua, applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/memory.lua, applications/luci-app-statistics/luasrc/statistics/plugins/cpu.lua, applications/luci-app-statistics/luasrc/statistics/plugins/memory.lua, applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/cpu.lua, applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/memory.lua, applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
- Add new cpu plugin options
- Add new memory plugin option
- Add ping stddev definition
- Minify memory license header
closes #3013 
closes #3053
=> luci-app-statistics: Add new plugin options

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> [19.07] luci-app-vpnbypass: better start/stop controls, create entry in the VPN menu if it exists

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> [18.06] luci-app-vpnbypass: better start/stop controls, create entry in the VPN menu if it exists

applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
This resolves #3049
Signed-off-by: Eric Luehrsen <ericluehrsen@gmail.com>
=> luci-app-unbound: inform if odhcpd is not configured

applications/luci-app-udpxy/po/es/udpxy.po
=> luci-app-udpxy: add Spanish translation

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
Depends on: https://github.com/openwrt/packages/pull/10065
=> luci-app-simple-adblock: dnsmasq.ipset option support

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
Depends on: https://github.com/openwrt/packages/pull/10064
=> [19.07] luci-app-simple-adblock: dnsmasq.ipset option support

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
Depends on: https://github.com/openwrt/packages/pull/10063
=> [18.06] luci-app-simple-adblock: dnsmasq.ipset option support

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> luci-app-vpnbypass: fix dispatcher bug when VPN node is present

applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua, applications/luci-app-banip/luasrc/view/banip/runtime.htm
* see package PR for details (https://github.com/openwrt/packages/pull/10145)
=> luci-app-banip: sync with banIP 0.3.0

applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
* no longer filter out possible lan devices
=> luci-app-banip: sync with update 0.3.1

applications/luci-app-https_dns_proxy/Makefile, applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
This addresses the issue mentioned in #3148.
=> luci-app-https_dns_proxy: bugfix: subnet address datatype, add DNS.SB provider

applications/luci-app-https_dns_proxy/Makefile, applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
This addresses the issue mentioned in #3148.
=> [19.07] luci-app-https_dns_proxy: bugfix: subnet address datatype, add DNS.SB provider

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
This fixes https://github.com/openwrt/luci/issues/3162.
=> luci-app-simple-adblock: bugfix: fix invalid <br> entries

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
This fixes https://github.com/openwrt/luci/issues/3162.
=> [19.07] luci-app-simple-adblock: bugfix: fix invalid <br> entries

applications/luci-app-dcwapd/Makefile, applications/luci-app-dcwapd/luasrc/controller/dcwapd.lua, applications/luci-app-dcwapd/luasrc/model/cbi/dcwapd/dcwapd.lua, applications/luci-app-dcwapd/root/etc/uci-defaults/60_luci-dcwapd
Add web interface configuration pages for the Dual Channel Wi-Fi AP Daemon.
Signed-off-by: Carey Sonsino <careys@edgewaterwireless.com>
=> luci-app-dcwapd: Add Dual Channel Wi-Fi AP Daemon Management LuCI pages

applications/luci-app-dcwapd/po/es/dcwapd.po, applications/luci-app-dcwapd/po/templates/dcwapd.pot
Add template and Spanish translation
=> luci-app-dcwapd: add template and Spanish translation

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
This fixes https://github.com/openwrt/luci/issues/3162.
=> [18.06] luci-app-simple-adblock: bugfix: fix invalid <br> entries

protocols/luci-proto-modemmanager/Makefile, protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js, protocols/luci-proto-modemmanager/luasrc/model/network/proto_modemmanager.lua
Signed-off-by: Nicholas Smith <nicholas.smith@telcoantennas.com.au>
=> luci-proto-modemmanager: add luci-proto-modemmanager

applications/luci-app-firewall/po/zh-cn/firewall.po
update Simplified Chinese translation for luci-app-firewall
=> luci-app-firewall: update Simplified Chinese translation

applications/luci-app-simple-adblock/po/zh-cn/simple-adblock.po
update Simplefied Chinese translation for luci-app-simple-adblock
=> luci-app-simple-adblock: update Simplefied Chinese translation

applications/luci-app-advanced-reboot/po/zh-cn/advanced-reboot.po
update Simplified Chinese translation for luci-app-advance-reboot
=> luci-app-advanced-reboot: update Simplified Chinese translation

applications/luci-app-adblock/po/zh-cn/adblock.po
update Simplified Chinese translation for luci-app-adblock
=> luci-app-adblock: update Simplified Chinese translation

applications/luci-app-cifsd/po/es/cifsd.po, applications/luci-app-cifsd/po/templates/cifsd.pot
Add template and Spanish translation.
=> luci-app-cifsd: add template and Spanish translation

README.md
=> Add weblate to README.md

applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js, applications/luci-app-cifsd/po/templates/cifsd.pot, applications/luci-app-cifsd/po/zh-cn/cifsd.po
=> luci-app-cifsd: fix typo and add Simplified Chinese translation

applications/luci-app-ttyd/po/es/ttyd.po, applications/luci-app-ttyd/po/templates/ttyd.pot
Add template and Spanish translation.
=> luci-app-ttyd: add template and Spanish translation

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> luci-app-vpnbypass: bugfix: properly restart dnsmasq

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> [19.07] luci-app-vpnbypass: bugfix: properly restart dnsmasq

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
=> [18.06] luci-app-vpnbypass: bugfix: properly restart dnsmasq

applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua, applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm, applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
=> luci-app-travelmate: sync with update 1.5.0

applications/luci-app-dcwapd/Makefile, applications/luci-app-dcwapd/luasrc/controller/dcwapd.lua, applications/luci-app-dcwapd/luasrc/model/cbi/dcwapd/dcwapd.lua, applications/luci-app-dcwapd/po/es/dcwapd.po, applications/luci-app-dcwapd/po/templates/dcwapd.pot, applications/luci-app-dcwapd/root/etc/uci-defaults/60_luci-dcwapd
Add web interface configuration pages for the Dual Channel Wi-Fi AP Daemon.
Signed-off-by: Carey Sonsino <careys@edgewaterwireless.com>
Signed-off-by: Carey Sonsino <csonsino@gmail.com>
=> [19.07] luci-app-dcwapd: Add Dual Channel Wi-Fi AP Daemon Pages

applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua, applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* fix wireless and travelmate section naming
* fix other small visual issues
=> luci-app-travelmate: sync with update 1.5.1

applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
* fix some more WEP-related form issues
=> luci-app-travelmate: WEP-fixes

protocols/luci-proto-qmi/htdocs/luci-static/resources/protocol/qmi.js
Signed-off-by: Nicholas Smith <nicholas.smith@telcoantennas.com.au>
=> luci-proto-qmi: add PDP type option

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
=> [19.07] luci-app-vpnbypass: better service control buttons

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
=> [18.06] luci-app-vpnbypass: better service control buttons

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/css.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status.htm
=> luci-app-vpnbypass: better service control buttons

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
This fixes: https://github.com/openwrt/luci/issues/3243
=> luci-app-vpnbypass: bugfix: call to action has no parent node

modules/luci-base/htdocs/luci-static/resources/form.js
@jow- 
https://github.com/openwrt/luci/blob/6c7b1e156d8a3342864a5e5e03a8331f6819109f/modules/luci-base/htdocs/luci-static/resources/form.js#L1393-L1395
https://github.com/openwrt/luci/blob/6c7b1e156d8a3342864a5e5e03a8331f6819109f/modules/luci-base/htdocs/luci-static/resources/form.js#L874-L877
=> luci-base: form.js: fix GridSection not using user-input name when add

modules/luci-base/po/vi/base.po
Translate luci-base into vietnamese almost done.
=> luci-base: vi/base.po: translate to vietnamese almost done.

applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js, applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/servers.js
@yousong 
Related docs:
https://github.com/Jigsaw-Code/outline-shadowsocksconfig
https://shadowsocks.org/en/config/quick-guide.html
https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html
=> luci-app-shadowsocks-libev: add server links import feature

modules/luci-base/htdocs/luci-static/resources/ui.js, modules/luci-base/po/bg/base.po, modules/luci-base/po/ca/base.po, modules/luci-base/po/cs/base.po, modules/luci-base/po/de/base.po, modules/luci-base/po/el/base.po, modules/luci-base/po/en/base.po, modules/luci-base/po/es/base.po, modules/luci-base/po/fr/base.po, modules/luci-base/po/he/base.po, modules/luci-base/po/hi/base.po, modules/luci-base/po/hu/base.po, modules/luci-base/po/it/base.po, modules/luci-base/po/ja/base.po, modules/luci-base/po/ko/base.po, modules/luci-base/po/ms/base.po, modules/luci-base/po/no/base.po, modules/luci-base/po/pl/base.po, modules/luci-base/po/pt-br/base.po, modules/luci-base/po/pt/base.po, modules/luci-base/po/ro/base.po, modules/luci-base/po/ru/base.po, modules/luci-base/po/sk/base.po, modules/luci-base/po/sv/base.po, modules/luci-base/po/templates/base.pot, modules/luci-base/po/tr/base.po, modules/luci-base/po/uk/base.po, modules/luci-base/po/vi/base.po, modules/luci-base/po/zh-cn/base.po, modules/luci-base/po/zh-tw/base.po
I'll do the commits properly based on feedback.  The "changes to get applied" is the one that really feels uncomfortable to me... and the others are sort of fallout from the proposed change to that.
=> RFC - some language tweaks

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua, applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm, applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/alternative_reboot.htm, applications/luci-app-advanced-reboot/root/etc/uci-defaults/40_luci-advanced-reboot
=> luci-app-advanced-reboot: show OpenWrt info on compatible NAND routers

applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
also pls merge this https://github.com/openwrt/luci/pull/3314
=> luci-app-ddns: fix missing check for bindhost

applications/luci-app-nextdns/Makefile, applications/luci-app-nextdns/luasrc/controller/nextdns.lua, applications/luci-app-nextdns/luasrc/model/cbi/overview.lua, applications/luci-app-nextdns/luasrc/view/nextdns/logread.htm, applications/luci-app-nextdns/po/templates/nextdns.pot, applications/luci-app-nextdns/root/etc/uci-defaults/60_luci-nextdns
Signed-off-by: Olivier Poitrey <rs@nextdns.io>
Tested on 19.07.0-rc1
=> luci-app-nextdns: add luci integration for nextdns package

applications/luci-app-nextdns/po/es/nextdns.po
=> luci-app-nextdns: add Spanish translation

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
ip_network should be NetworkSelect
ip_interface/interface should be DeviceSelect
=> luci-app-ddns: use the correct widget Select

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm
=> luci-app-vpnbypass: use VPN node by default

applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> luci-app-advanced-reboot: add logger messages, README update

applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> [19.07] luci-app-advanced-reboot: add logger messages, README update

applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> [18.06] luci-app-advanced-reboot: add logger messages, README update

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> luci-app-advanced-reboot: better information for snapshots

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
unexpected token: punc ) caused by extra ,
=> luci-app-ddns: fix syntax error

applications/luci-app-yggdrasil/Makefile, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/keys.js, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/peers.js, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/session_firewall.js, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/settings.js, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/status.js, applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/tunnel_routing.js, applications/luci-app-yggdrasil/luasrc/controller/yggdrasil.lua, applications/luci-app-yggdrasil/root/usr/share/rpcd/acl.d/luci-app-yggdrasil.json
Signed-off-by: George Iv <57254463+zhoreeq@users.noreply.github.com>
Tested on: snapshot with yggdrasil v0.3.11-4
=> luci-app-yggdrasil: Add application for Yggdrasil

applications/luci-app-omcproxy/Makefile, applications/luci-app-omcproxy/htdocs/luci-static/resources/view/omcproxy.js, applications/luci-app-omcproxy/luasrc/controller/omcproxy.lua, applications/luci-app-omcproxy/po/templates/omcproxy.pot, applications/luci-app-omcproxy/po/zh-cn/omcproxy.po
Signed-off-by: Shun Li <riverscn@gmail.com>
=> add luci support for omcproxy

applications/luci-app-yggdrasil/po/templates/yggdrasil.pot
=> luci-app-yggdrasil: add template

applications/luci-app-ocserv/luasrc/model/cbi/ocserv/main.lua
New versions of certtool change its output format and thus break
the previous parsing. This update works with certtool 3.5.x or later.
It also restricts the output to valid values for openconnect 7.x or
later for simplification.
=> ocserv: fix the public key ID calculation

applications/luci-app-bmx7/po/bg/bmx7.po, applications/luci-app-bmx7/po/ca/bmx7.po, applications/luci-app-bmx7/po/cs/bmx7.po, applications/luci-app-bmx7/po/de/bmx7.po, applications/luci-app-bmx7/po/el/bmx7.po, applications/luci-app-bmx7/po/en/bmx7.po, applications/luci-app-bmx7/po/es/bmx7.po, applications/luci-app-bmx7/po/fr/bmx7.po, applications/luci-app-bmx7/po/he/bmx7.po, applications/luci-app-bmx7/po/hi/bmx7.po, applications/luci-app-bmx7/po/hu/bmx7.po, applications/luci-app-bmx7/po/it/bmx7.po, applications/luci-app-bmx7/po/ja/bmx7.po, applications/luci-app-bmx7/po/ko/bmx7.po, applications/luci-app-bmx7/po/mr/bmx7.po, applications/luci-app-bmx7/po/ms/bmx7.po, applications/luci-app-bmx7/po/nb_NO/bmx7.po, applications/luci-app-bmx7/po/pl/bmx7.po, applications/luci-app-bmx7/po/pt/bmx7.po, applications/luci-app-bmx7/po/ro/bmx7.po, applications/luci-app-bmx7/po/ru/bmx7.po, applications/luci-app-bmx7/po/sk/bmx7.po, applications/luci-app-bmx7/po/sv/bmx7.po, applications/luci-app-bmx7/po/tr/bmx7.po, applications/luci-app-bmx7/po/uk/bmx7.po, applications/luci-app-bmx7/po/vi/bmx7.po, applications/luci-app-bmx7/po/zh-cn/bmx7.po, applications/luci-app-bmx7/po/zh-tw/bmx7.po, applications/luci-app-bmx7/root/usr/lib/lua/luci/view/bmx7/status_j.htm, applications/luci-app-bmx7/root/usr/lib/lua/luci/view/bmx7/tunnels_j.htm
=> luci-app-bmx7: fix typos

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
=> luci-app-advanced-reboot: bugfix: compatible with new luci

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css, themes/luci-theme-material/htdocs/luci-static/material/cascade.css, themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css, themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
For some reason i missed the other ones heh.
=> luci-theme-*: remove modal max-height #3383 v2

modules/luci-compat/luasrc/model/network.lua
=> luci-compat: network.lua: fix typo

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/css.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/js.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-textarea.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot, applications/luci-app-vpn-policy-routing/root/etc/uci-defaults/40_luci-vpn-policy-routing
Companion Web UI package for https://github.com/openwrt/packages/pull/10902.
=> luci-app-vpn-policy-routing: initial release

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/css.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/js.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-textarea.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot, applications/luci-app-vpn-policy-routing/root/etc/uci-defaults/40_luci-vpn-policy-routing
Companion Web UI package for https://github.com/openwrt/packages/pull/10903.
=> [19.07] luci-app-vpn-policy-routing: initial release

applications/luci-app-vpn-policy-routing/po/es/vpn-policy-routing.po
=> luci-app-vpn-policy-routing: add Spanish translation

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm
=> luci-app-vpn-policy-routing: add note about default routing

applications/luci-app-yggdrasil/po/es/yggdrasil.po
=> luci-app-yggdrasil: add Spanish translation

applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua, applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
* see forum post https://forum.openwrt.org/t/travelmate-support-thread/5155/318
=> luci-app-travelmate: bugfix add/edit WPA3 uplinks

applications/luci-app-vnstat2/po/es/vnstat2.po
=> luci-app-vnstat2: add Spanish translation

applications/luci-app-ser2net/po/es/ser2net.po, applications/luci-app-ser2net/po/templates/ser2net.pot
=> luci-app-ser2net: add template + Spanish translation

applications/luci-app-frpc/Makefile, applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js, applications/luci-app-frpc/po/templates/frpc.pot, applications/luci-app-frpc/root/usr/share/luci/menu.d/luci-app-frpc.json, applications/luci-app-frpc/root/usr/share/rpcd/acl.d/luci-app-frpc.json, applications/luci-app-frps/Makefile, applications/luci-app-frps/htdocs/luci-static/resources/view/frps.js, applications/luci-app-frps/po/templates/frps.pot, applications/luci-app-frps/root/usr/share/luci/menu.d/luci-app-frps.json, applications/luci-app-frps/root/usr/share/rpcd/acl.d/luci-app-frps.json
[frp](https://github.com/fatedier/frp) is a reverse proxy which has a complicated config file. (Yes, like OpenVPN.)
Should I implement only a config file upload UI or all available options?
=> [RFC] luci-app-frp: add new packages

applications/luci-app-frpc/po/es/frpc.po, applications/luci-app-frps/po/es/frps.po
=> luci-app-frp: add Spanish translation

applications/luci-app-ttyd/po/zh_Hans/ttyd.po
Translate the title “ttyd” in service menu
=> Fix translation issue

modules/luci-base/src/jsmin.c
Signed-off-by: Howard Su <howard0su@gmail.com>
=> luci-base: import latest version of jsmin

applications/luci-app-ddns/Makefile, applications/luci-app-nextdns/Makefile, applications/luci-app-shadowsocks-libev/Makefile, applications/luci-app-upnp/Makefile
Remove it after converting to js implementaion.
Signed-off-by: Howard Su <howard0su@gmail.com>
=> luci-app: Remove luci-compat dependency

CONTRIBUTING.md
=> CONTRIBUTING.md: Fix sign_your_work link

applications/luci-app-openvpn/luasrc/view/openvpn/cbi-select-input-add.htm
* accept/replace common '.' seperator in instance names as well,
see comment in #2235
=> luci-app-openvpn: fix upload input validator

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/css.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/error.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/js.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
This is companion package for https://github.com/openwrt/packages/pull/11698.
=> luci-app-simple-adblock: better status/error display, better service control

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/css.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/error.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/js.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
This is companion package for https://github.com/openwrt/packages/pull/11699
=> [19.07] luci-app-simple-adblock: better status/error display, better service control

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/css.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/error.htm, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/js.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
This is companion package for https://github.com/openwrt/packages/pull/11700
=> [18.06] luci-app-simple-adblock: better status/error display, better service control

applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/dnsreport.js, applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/overview.js
=> luci-app-adblock: small visual tweaks for OpenWrt 2020

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> luci-app-simple-adblock: better service control & buttons styling

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> [19.07] luci-app-simple-adblock: better service control & buttons styling

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> [18..06] luci-app-simple-adblock: better service control & buttons styling

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot, applications/luci-app-vpn-policy-routing/root/etc/uci-defaults/40_luci-vpn-policy-routing
=> luci-app-vpn-policy-routing: better service control & buttons styling

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> [19.07] luci-app-vpn-policy-routing: better service control & buttons styling

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/etc/uci-defaults/40_luci-vpnbypass
=> luci-app-vpnbypass: better service control & buttons styling

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/etc/uci-defaults/40_luci-vpnbypass
=> [19.07] luci-app-vpnbypass: better service control & buttons styling

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm, applications/luci-app-vpnbypass/luasrc/view/vpnbypass/status-textarea.htm, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/etc/uci-defaults/40_luci-vpnbypass
=> [18.06] luci-app-vpnbypass: better service control & buttons styling

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot, applications/luci-app-https-dns-proxy/root/etc/uci-defaults/40_luci-https-dns-proxy
=> luci-app-https-dns-proxy: better service control & buttons styling

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [19.07] luci-app-https-dns-proxy: better service control & buttons styling

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [18.06] luci-app-https-dns-proxy: better service control & buttons styling

modules/luci-base/po/fr/base.po
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this …
=> luci-fr: typos fixes and translations proposal

applications/luci-app-dawn/Makefile, applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_config.lua
Fixes #3836.
Needs https://github.com/openwrt/packages/pull/11815.
=> luci-app-dawn: fix typos and dependencies

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: improve i18n

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [19.07] luci-app-https-dns-proxy: improve i18n

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua, applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot, applications/luci-app-advanced-reboot/root/etc/uci-defaults/40_luci-advanced-reboot
=> luci-app-advanced-reboot: improve localization by moving from translate to translatef

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua, applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
=> [19.07] luci-app-advanced-reboot: improve localization by moving from translate to translatef

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
This hopefully fixes translation strings to allow different word order due to other foreign grammar rules (e.g. German).
=> use translatef instead of translate

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
This is to complement https://github.com/openwrt/luci/pull/3875.
If https://github.com/openwrt/luci/pull/3875 was cherry-picked for 19.07/18.06 please close this without merging.
=> [19.07] luci-app-simple-adblock: improve i18n

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
This is to complement https://github.com/openwrt/luci/pull/3875.
If https://github.com/openwrt/luci/pull/3875 was cherry-picked for 19.07/18.06 please close this without merging.
=> [18.06] luci-app-simple-adblock: improve i18n

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> luci-app-vpn-policy-routing: improve i18n

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> [19.07] luci-app-vpn-policy-routing: improve i18n

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/df.js
Signed-off-by: Tobias Waldvogel <tobias.waldvogel@gmail.com>
=> luci_app_statistics: Add missing variable declaration for plugin df

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Tested on sunxi/H3, zeroPi, 19.07.1
=> luci-app-vpnbypass: better localizeable resources

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
=> [19.07] luci-app-vpnbypass: better localizeable resources

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
=> [18.06] luci-app-vpnbypass: better localizeable resources

applications/luci-app-ledtrig-rssi/htdocs/luci-static/resources/view/system/led-trigger/rssi.js, applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch0.js, applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch1.js, applications/luci-app-ledtrig-usbport/htdocs/luci-static/resources/view/system/led-trigger/usbport.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/default-on.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/heartbeat.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/netdev.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/none.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/timer.js
@hnyman Is this OK from you?
With this pullrequest I18N translation should be adapted, so it is clear what this trigger does.
=> luci-mod-system: update LED i18N trigger translation

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> luci-app-vpn-policy-routing: support phys-dev policies

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
=> [19.07] luci-app-vpn-policy-routing: support phys-dev policies

protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js
Add UI configuration option for openconnect user group.
See https://github.com/openwrt/packages/pull/11798#issuecomment-621511896
=> luci-proto-openconnect: add usergroup option

applications/luci-app-frpc/root/usr/share/rpcd/acl.d/luci-app-frpc.json
=>  luci-app-frpc: add uci file read permissions

modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
Signed-off-by: sunnyqeen <sunnyqeen@gmail.com>
=>  luci-mod-admin-full: fixed ipv6 address display in the overview page of luci 18.06

luci.mk
=> translation: add Arabic to luci.mk

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.family.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot, applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json
=> luci-app-https-dns-proxy: decrease reliance on shell commands; proper acl.d file; add cloudflare family/protect

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.family.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot, applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json
=> [19.07] luci-app-https-dns-proxy: decrease reliance on shell commands; proper acl.d file; add cloudflare family/protect

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.family.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot, applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json
=> [18.06] luci-app-https-dns-proxy: decrease reliance on shell commands; proper acl.d file; add cloudflare family/protect

protocols/luci-proto-vxlan/htdocs/luci-static/resources/protocol/vxlan.js
Add possibility to configure vxlan destination port.
=> luci-proto-vxlan: add destination port option

applications/luci-app-adblock/po/es/adblock.po
* updated Spanish (es) translation
Signed-off-by: Alberto Martínez Álvarez <amteza@gmail.com>
Maintainer: Dirk Brenken <dev@brenken.org> / @dibdot
=> luci-app-adblock: Spanish translation sync with 4.0.6

applications/luci-app-smartdns/po/templates/smartdns.pot
=> i18n: luci-app-smartdns: add template

applications/luci-app-smartdns/po/es/smartdns.po
=> i18n: luci-app-smartdns: add Spanish translation

applications/luci-app-wireguard/root/usr/share/luci/menu.d/luci-app-wireguard.json
=> luci-app-wireguard: fix acl issue

applications/luci-app-dockerman/luasrc/view/dockerman/cbi/inlinebutton.htm, applications/luci-app-dockerman/luasrc/view/dockerman/cbi/inlinevalue.htm, applications/luci-app-dockerman/luasrc/view/dockerman/container_file.htm, applications/luci-app-dockerman/luasrc/view/dockerman/images_import.htm, applications/luci-app-dockerman/luasrc/view/dockerman/images_load.htm, applications/luci-app-dockerman/luasrc/view/dockerman/newcontainer_resolve.htm, applications/luci-app-dockerman/root/etc/init.d/dockerman
1. Move uci config calls into the start function
2. Add btn css class to all button inputs. Fix button view.
@lisaac  Please have a look so we could also move this changes to https://github.com/lisaac/luci-app-dockerman
=> luci-app-dockerman: improvements

applications/luci-app-mwan3/luasrc/view/mwan/status_diagnostics.htm, applications/luci-app-mwan3/root/etc/uci-defaults/60_luci-mwan3
This pull request adds two changes into stable branch:
1. Since merge of pull request https://github.com/openwrt/packages/pull/12732 mwan3 is now reloaded with procd. So we do not need ucitrack anymore.
2. Enhance diagnostic status output
=> luci-app-mwan3: sync changes with mwan3

applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/df.js, applications/luci-app-statistics/root/etc/config/luci_statistics, applications/luci-app-statistics/root/usr/share/luci/statistics/plugins/df.json
=> luci-app-statistics: add missing ValuesPercentage option

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.doh.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.familyshield.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: add OpenDNS servers

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.doh.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.familyshield.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [19.07] luci-app-https-dns-proxy: add OpenDNS servers

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.doh.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.opendns.familyshield.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [18.06] luci-app-https-dns-proxy: add OpenDNS servers

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2.lua, applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea4500.lua, applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm, applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/alternative_reboot.htm, applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/power_off.htm
=> luci-app-advanced-reboot: bugifx: btn style; board names for some Linksys devices

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.alidns.dns.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/pub.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: add DNSPod.cn DoH

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.alidns.dns.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/pub.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [19.07] luci-app-https-dns-proxy: add DNSPod.cn DoH

applications/luci-app-https-dns-proxy/Makefile, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.alidns.dns.lua, applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/pub.doh.lua, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [18.06] luci-app-https-dns-proxy: add DNSPod.cn DoH

applications/luci-app-nft-qos/luasrc/model/cbi/nft-qos/nft-qos.lua
fix style issue
Signed-off-by: Tong Zhang <ztong0001@gmail.com>
=> luci-app-nft-qos: code reindent

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
* Update config view, so that the individual sections (info, global) are divided into different tabs. 
* Cleaned up source
@Ansuel could you please have a look if this breaks anything?
You did the intial checkin of this package in javascript.
=> luci-app-ddns: add improvments

applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-mr8300.lua
Signed-off-by: Hans Geiblinger <cybrnook2002@yahoo.com>
Tested and confirmed working against master branch and mr8300
=> luci-app-advanced-reboot: add linksys-mr8300 support

applications/luci-app-uhttpd/po/zh-cn/uhttpd.po
Just a letter.
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>
=> luci-app-uhttpd: i18n - fix zh-cn translation

applications/luci-app-hd-idle/po/es/hd_idle.po
=> luci-app-hd-idle: i18n: update Spanish translation

applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/stations.js
- add notifications in case of errors during save
=> luci-app-travelmate: add notifications

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
Also small tweaks for controller and ACL. Dependent on https://github.com/openwrt/packages/pull/13433.
=> luci-app-simple-adblock: support for config auto-update

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot, applications/luci-app-vpn-policy-routing/root/usr/share/rpcd/acl.d/luci-app-vpn-policy-routing.json
=> luci-app-vpn-policy-routing: ACL-related update

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot, applications/luci-app-vpn-policy-routing/root/usr/share/rpcd/acl.d/luci-app-vpn-policy-routing.json
=> [19.07] luci-app-vpn-policy-routing: ACL-related update

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/usr/share/rpcd/acl.d/luci-app-vpnbypass.json
=> luci-app-vpnbypass: ACL-related update

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/usr/share/rpcd/acl.d/luci-app-vpnbypass.json
=> [19.07] luci-app-vpnbypass: ACL-related update

applications/luci-app-vpnbypass/Makefile, applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua, applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua, applications/luci-app-vpnbypass/po/templates/vpnbypass.pot, applications/luci-app-vpnbypass/root/usr/share/rpcd/acl.d/luci-app-vpnbypass.json
=> [18.06] luci-app-vpnbypass: ACL-related update

applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/stations.js, applications/luci-app-travelmate/root/usr/share/rpcd/acl.d/luci-app-travelmate.json
* just change the location of one state file
=> luci-app-travelmate: sync with travelmate 2.0.1

applications/luci-app-xinetd/Makefile, applications/luci-app-xinetd/htdocs/luci-static/resources/view/xinetd/xinetd.js
This change rearranges some parameters in the Basic and Advanced settings for a better user experience.
=> luci-app-xinetd: rearrange params in tabs

modules/luci-base/htdocs/luci-static/resources/network.js
Iterate through VLANs to get the clients connected on configured wifi
VLANs (as configured by `wifi-vlan` sections in `wireless` configuration).
This is a minimum support for VLANs on wireless network. The VLAN name is
nowhere displayed, but at least clients using VLANs are visible.
=> luci-base: network.js: Show clients also from wifi VLANs.

modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
=> luci-mod-system: fix uci led option remove callback

modules/luci-base/root/usr/libexec/rpcd/luci
Signed-off-by: Martin Böh <mart.b@outlook.de>
=>  luci-base: fix syntax error in hostapd features

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
Extensive description the commits log. I think i wrote too much there... ahahah
@jow- 
Fixes #4524
=> Fix one display bug for ap join and #4524

applications/luci-app-upnp/htdocs/luci-static/resources/view/upnp/upnp.js
This was introduce in b01a394bded4dc2dd838ef579a80e12c4e23407b
(Fix: "luci-app-upnp: add stun support")
Fixes: #4604
=> luci-app-upnp: remove extra space

protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js
see https://github.com/openwrt/packages/pull/13763
Signed-off-by: Mengyang Li <mayli.he@gmail.com>
=> luci-proto-openconnect: add vpn_procotol support

applications/luci-app-dockerman/Makefile
Maintainer: @feckert 
Compile tested: x86_x64, OpenWrt Master
Run tested: x86_x64, OpenWrt Master
Following @feckert's request, to complete [#13874](https://github.com/openwrt/packages/pull/13874)
=> luci-app-dockerman: Updated `docker-ce` -> `docker`

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> luci-app-simple-adblock: README URL update

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> [19.07] luci-app-simple-adblock: README URL update

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> [18.06] luci-app-simple-adblock: README URL update

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/snmp6.js, applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/snmp6.js, applications/luci-app-statistics/root/etc/config/luci_statistics, applications/luci-app-statistics/root/usr/share/luci/statistics/plugins/snmp6.json
Add IPv6 statistics.
Depends on:
https://github.com/openwrt/packages/pull/14205
=> luci-app-statistics: add snmp6 collector

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
- Add check for missing ht_operation data
- Add support for radio that both support 5 and 2.4 band
- Hide wireless station that doesn't belong to the graph band
=> luci-mod-status: fix bugs in channel analysis

applications/luci-app-eoip/Makefile, applications/luci-app-eoip/htdocs/luci-static/resources/view/eoip/eoip.js, applications/luci-app-eoip/po/en/eoip.po, applications/luci-app-eoip/po/ru/eoip.po, applications/luci-app-eoip/po/templates/eoip.pot, applications/luci-app-eoip/root/usr/share/luci/menu.d/luci-app-eoip.json, applications/luci-app-eoip/root/usr/share/rpcd/acl.d/luci-app-eoip.json
For https://github.com/openwrt/openwrt/pull/3721
=> Add Luci for Eoip package

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
Default values were not quoted before, resulting in them not working.
=> [18.06] luci-app-simple-adblock: bugfix: default values for ListValue

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.idnet.doh.lua, applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: add Force DNS, IDNet support, add missing class to buttons

applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: add IDNet to template pot

applications/luci-app-banip/htdocs/luci-static/resources/view/banip/ipsetreport.js, applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js
* fix translation warning
* cosmetics
=> luci-app-banip: cosmetics

applications/luci-app-vpn-policy-routing/Makefile, applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-service.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> [19.07] luci-app-vpn-policy-routing: sync with principal app

applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> [19.07] luci-app-vpn-policy-routing: bugfix: template layout on theme-openwrt-2020

applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm, applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm, applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
=> luci-app-vpn-policy-routing: bugfix: template layout on theme-openwrt-2020

applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/status.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> [19.07] luci-app-https-dns-proxy: bugfix: layout issues on theme-openwrt-2020

applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm, applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/status.htm, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: bugfix: layout issues on theme-openwrt-2020

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/etc/uci-defaults/40_luci-advanced-reboot, applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot
=> luci-app-advanced-reboot: explicit package version

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/etc/uci-defaults/40_luci-advanced-reboot, applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot
=> [21.02] luci-app-advanced-reboot: explicit package version

applications/luci-app-simple-adblock/Makefile
=> luci-app-simple-adblock: explicit package version

applications/luci-app-simple-adblock/Makefile
=> [21.02] luci-app-simple-adblock: explicit package version

applications/luci-app-simple-adblock/Makefile
=> [19.07] luci-app-simple-adblock: explicit package version

applications/luci-app-vpn-policy-routing/Makefile
=> luci-app-vpn-policy-routing: explicit package version

applications/luci-app-vpn-policy-routing/Makefile
=> [21.02] luci-app-vpn-policy-routing: explicit package version

applications/luci-app-vpn-policy-routing/Makefile
=> [19.07] luci-app-vpn-policy-routing: explicit package version

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
The running branch determines which upgrades are suggested. A jump to a
newer branch (e.g. 19.07.8 to 21.02.1) is only suggested if the advanced
mode is enable, since it may break the router.
OpenWrt versions end in either `-SNAPSHOT`, `.X-rcY` or `.x`. All these
suffixes are removed, resulting in the branch name.
Previously the `-SNAPSHOT` suffix wasn't removed resulting in wrong
branch names.
Also clean up some log spam.
=> luci-app-attendedsysupgrade: fix branch detection

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
Fix for the "Domain" tooltip in the ddns form
Fixes #5056
=> [luci-app-ddns] Fix Domain Tooltip in ddns form

applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
/etc/init.d/samba4 already support that
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>
=> luci-app-samba4: support listen on multiple interfaces

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
OpenWrt switched from "option hwmode" to "option band" in order to select
the frequency band to use for the radio phy.
Extend the channel selector to recognize and use an existing "option band"
to select the appropriate channel list. When operating upon a wireless
configuration still using "option hwmode", then translate it to a band
value internally and translate it back to "option hwmode" on save.
This should provide forward- and backwards compatibility with both current
OpenWrt master and older versions still using hwmode.
Fixes: #5106
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
=> luci-mod-network: support newer wireless.wifi-device.band option

applications/luci-app-fwknopd/htdocs/luci-static/resources/view/fwknopd.js
=> luci-app-fwknopd: trivial typo fix

applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js
* support the new 'ban_fetchinsecure' option
* improve the chain help text to make clear that you can assign
multiple FW chains
=> luci-app-banip: sync with banip 0.7.9

applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js, applications/luci-app-frpc/root/usr/share/rpcd/acl.d/luci-app-frpc.json, applications/luci-app-frps/htdocs/luci-static/resources/view/frps.js, applications/luci-app-frps/root/usr/share/rpcd/acl.d/luci-app-frps.json
reference from luci-app-smartdns
Special thanks to Nick Peng <pymumu@gmail.com>
Signed-off-by: SiYao Mo <msylgj@vip.qq.com>
=> luci-app-frpc/frps:add service status display

applications/luci-app-openvpn/luasrc/controller/openvpn.lua
* trivial fix for never ending ticket #3454
=> luci-app-openvpn: create base directory if not available

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/configuration.js
Does this require some build/i18n-sync.pl run?
Suggested-by: Jo-Philipp Wich <jo@mein.io>
=> luci-app-attendedsysupgrade: fix typo

applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
* Fix the error that next_update sometimes display Verify
=> luci-app-ddns: fix next_update error

applications/luci-app-attendedsysupgrade/Makefile, applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js, applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/luci-app-attendedsysupgrade.json
Better ACL and no more forced uhttpd dependency.
=> luci-app-attendedsysupgrade: sync with master

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/custom.js
10 lines are very few and there is much unused space
=> firewall: more text lines for custom script

modules/luci-mod-system/htdocs/luci-static/resources/view/system/crontab.js
10 lines are very few and there is much unused space
=> system: more text lines for crontab

applications/luci-app-ksmbd/htdocs/luci-static/resources/view/ksmbd.js
without this, only 50% of screen where used
also show version only 1 time if Ksmbd/Kmod
versions match
=> ksmbd: fix the layout of textbox

applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
without this, only 50% of screen where used
=> samba4: fix the layout of textbox

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
The server provides a queue_position argument, show it.
=> luci-app-attendedsysupgrade: show position in queue

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Sync with server changes now that a *stable* v1 is out.
=> [21.02] luci-app-attendedsysupgrade: backport API changes

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/css/custom.css, themes/luci-theme-material/htdocs/luci-static/material/cascade.css
Introduce some small fix for material theme to better support the dashboard module.
If you have more hint or notice some problem with the changes, pls report them here.
=> Minor fix for material theme

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
One bugfix and one cosmetic improvement for the luci-mod-status wifi index table.
@jow- i fixed the broken feature
=> luci-mod-status: some improvement to wifi status

applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_network.lua
=> add missing quotation mark

protocols/luci-proto-wireguard/root/usr/libexec/rpcd/luci.wireguard
=> luci-app-wireguard: fix allowed_ip parsing

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js, applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-e4200v2.json
* bugfix for Linksys E4200v2
* minor code changes
=> luci-app-advanced-reboot: bugfix for Linksys E4200v2

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js, applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-e4200v2.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea7500v1.json
* bugfix for Linksys E4200v2
* backport updates from master
=> [19.07] luci-app-advanced-reboot: bugfix for Linksys E4200v2

.github/workflows/ci_helpers.sh, .github/workflows/formal.yml
Migrate the same formal tests used in packages.git
=> CI: add formal tests

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.he.ordns.lua
Ref https://github.com/stangri/source.openwrt.melmac.net/pull/142
=> luci-app-https-dns-proxy: Add HE.net DNS

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/olsrd.js
Signed-off-by: Martin Schitter <ms+git@mur.at>
=> luci-app-statistics: protect nested formating litteral

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.he.ordns.lua
(cherry picked from commit a25d56c28d7437f4755b465983678fca0b76c0cc)
=> [21.02] luci-app-https-dns-proxy: Add HE.net DNS

.github/issue_template
@jow-  I like the issue templates of #5565 and #5564.
I would nice if we had something like that.
=> [RFC] github: add issue templates file

applications/luci-app-nft-qos/luasrc/model/cbi/nft-qos/nft-qos.lua
Signed-off-by: Lopot li <gxfclql@gmail.com>
=> luci-app-nft-qos: fix lua trace by moving limit_mac_enabled option.

modules/luci-mod-status/htdocs/luci-static/resources/view/status/nftables.js, modules/luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json, modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json
The PR introduces an nftables status page similar to the existing one for iptables.
=> luci-mod-status: add nftables status page

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js, applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/luci-app-attendedsysupgrade.json
Better JavaScript code with new features like being more verbose between build steps.
=> [21.02] luci-app-attendedsysupgrade: backport LuCIfication

modules/luci-mod-network/htdocs/luci-static/resources/view/network/switch.js
This fix issue https://github.com/openwrt/luci/issues/5714
=> luci-mod-network: switch: Fix multi instances handling

applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea4500.json
Signed-off-by: Andy Bartolo <andrew.bartolo@gmail.com>
=> luci-app-advanced-reboot: Fix Linksys EA4500 descriptor file

applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea4500.json
Signed-off-by: Andy Bartolo <andrew.bartolo@gmail.com>
(cherry picked from commit 5d7446e1be05baef6463c29dc00587e5952db9fc)
=> [21.02] luci-app-advanced-reboot: Fix Linksys EA4500 descriptor file

applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea4500.json
Signed-off-by: Andy Bartolo <andrew.bartolo@gmail.com>
(cherry picked from commit 5d7446e1be05baef6463c29dc00587e5952db9fc)
=> [22.03] luci-app-advanced-reboot: Fix Linksys EA4500 descriptor file

modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/heartbeat.js
Depends on https://github.com/openwrt/openwrt/pull/10358
Fixes #5911
=> luci-mod-system: add config option to invert heartbeat trigger

applications/luci-app-travelmate/Makefile, applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/overview.js, applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/stations.js
* expose new options to LuCI
* cosmetics
Signed-off-by: Dirk Brenken dev@brenken.org
=> luci-app-travelmate: sync with travelmate 2.1.0

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock
* Support for (upcoming) dnsmasq nftset
Depends on https://github.com/openwrt/packages/pull/19212
=> luci-app-simple-adblock: update to 1.9.0-1

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
=> luci-mod-network: Expose multicast_to_unicast setting

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
```
It makes it much easier to find selected service provider.
```
=> luci-app-ddns: sort list of services

applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js, applications/luci-app-frpc/po/templates/frpc.pot, applications/luci-app-frpc/po/zh_Hans/frpc.po
1. fix local_ip data type
2. add plugin options
3. show remote port on overview page
4. some translations fix
=> luci-app-frpc: some improvement

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
=> [22.03] luci-app-ddns: fix creation of custom service (fix #4926)

protocols/luci-proto-vti/Makefile, protocols/luci-proto-vti/htdocs/luci-static/resources/protocol/vti.js
Signed-off-by: Jaymin Patel <jem.patel@gmail.com>
=> luci-proto-vti: add vti protocol support

applications/luci-app-xfrpc/htdocs/luci-static/resources/view/xfrpc.js
Signed-off-by: Dengfeng Liu <liudf0716@gmail.com>
=> luci-app-xfrpc: add subdomain option

protocols/luci-proto-nebula/Makefile, protocols/luci-proto-nebula/htdocs/luci-static/resources/protocol/nebula.js
Depends on https://github.com/openwrt/packages/pull/19586
=> luci-proto-nebula: add nebula protocol support

protocols/luci-proto-nebula/Makefile, protocols/luci-proto-nebula/htdocs/luci-static/resources/protocol/nebula.js
Depends on https://github.com/openwrt/packages/pull/19604
(cherry picked from commit d55913cfa44c81280111d093807c6830b3584d8d)
=> [22.03] luci-proto-nebula: add nebula protocol support

applications/luci-app-dockerman/luasrc/model/cbi/dockerman/newcontainer.lua
Signed-off-by: Jonathon Walker <jonathon.l.walker@gmail.com>
=> luci-app-dockerman: change default to nil if data.blkio_weight is not defined

modules/luci-base/root/usr/libexec/rpcd/luci, modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/50_dsl.js
This is just a cleanup on something I stumbled upon.
=> remove 'dsl' feature flag 

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
=> luci-app-simple-adblock: bugfix: identify nft set support

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
(cherry picked from commit 4dc98fefcac468917227bd9037bf6a71cbed9b67)
=> [22.03] luci-app-simple-adblock: bugfix: identify nft set support

applications/luci-app-keepalived/Makefile, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/globals.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/ipaddress.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/overview.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/peers.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/route.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/script.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/servers.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/track_interface.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/url.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/vrrp_instance.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/vrrp_sync_group.js, applications/luci-app-keepalived/htdocs/luci-static/resources/view/status/include/35_keepalived.js, applications/luci-app-keepalived/root/usr/share/luci/menu.d/luci-app-keepalived.json, applications/luci-app-keepalived/root/usr/share/rpcd/acl.d/luci-app-keepalived.json
LuCI Support for Keepalived
**We also need https://github.com/openwrt/packages/pull/19329**
**We also need https://github.com/openwrt/packages/pull/19374**
Screenshots from the new Luci App Keepalived:
Overview (Master):
Overview (Backup):
Globals:
IP Address:
IP Address (Add/Edit):
Static IP Address (Add/Edit):
Route:
Route (Add/Edit):
Static Route (Add/Edit):
URLs:
URLs (Add/Edit):
Scripts:
Scripts (Add/Edit):
Track Scripts (Add/Edit):
Interfaces:
Interfaces (Add/Edit):
Instance:
Instance (General):
Instance (Peer):
Instance (Tracking):
Instance (GARP):
Instance (Advanced):
Servers:
Real Servers (Add/Edit):
Virtual Servers (General):
Virtual Servers (Advanced):
Sync Group:
Sync Group (Add/Edit):
=> luci-app-keepalived: Add LuCI for keepalived

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock
Depends on: https://github.com/openwrt/packages/pull/19900
=> luci-app-simple-adblock: update to 1.9.3-1

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock
Depends on: https://github.com/openwrt/packages/pull/19993
=> luci-app-simple-adblock: localizable error/warning messages

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock
Depends on: https://github.com/openwrt/packages/pull/19994
(cherry picked from commit 6a4251ff9ad5832e861f9582a88cfd053dcbc436)
=> [22.03] luci-app-simple-adblock: localizable error/warning messages

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
=> luci-mod-network: Expose 802.11k settings.

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
=> luci-mod-network: Expose 802.11v settings.

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
=> luci-app-pbr: Detect missing iptables & error-proofing WebUI

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
(cherry picked from commit f8cbfa11c6583f298f505b103c73781f6349eba8)
=> [22.03] luci-app-pbr: Detect missing iptables & error-proofing WebUI

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot
* add more error/warning messages
* better error/ubus error handling
=> luci-app-pbr: update to 1.0.1-1

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot
* add more error/warning messages
* better error/ubus error handling
(cherry picked from commit 54c3ba32f9a2327ca4fdb9c419fb842108b17894)
=> [22.03] luci-app-pbr: update to 1.0.1-1

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
2 minor fixup for channel_analysis status page.
- Handle HE channel width
- Fix undefined diff in ap sort function
Fixes: #6167
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>
=> luci-mod-status: minor fix to channel_analysis

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
=> luci-mod-network: Expose WPA Enterprise RADIUS VLAN settings.

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
=> luci-app-pbr: additional error messages

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
(cherry picked from commit a748f86fec61d7c390ff0f9ee4a007fadfa936f7)
=> [22.03] luci-app-pbr: additional error messages

themes/luci-theme-bootstrap/Makefile, themes/luci-theme-material/Makefile, themes/luci-theme-openwrt-2020/Makefile, themes/luci-theme-openwrt/Makefile
Remove theme configuration uci section on theme uninstall.
=> luci-theme-: add postrm script

modules/luci-base/htdocs/luci-static/resources/form.js
=> luci-base: help-text spell fix

libs/rpcd-mod-luci/Makefile, libs/rpcd-mod-luci/src/luci.c, modules/luci-base/htdocs/luci-static/resources/network.js, modules/luci-base/root/usr/share/rpcd/ucode/luci, modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
That seems too easy? But it works for me (tm)
Depends on https://github.com/openwrt/openwrt/pull/11280
=> luci-mod-network: enable configuring wifi ax networks on the 6G band

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot
* do not remove non-empty custom user files fields
* add provides for vpnbypass and vpn-policy-routing luci apps 
addresses  https://github.com/openwrt/luci/pull/6127#pullrequestreview-1311512052
=> luci-app-pbr: bugfixes

applications/luci-app-xfrpc/Makefile, applications/luci-app-xfrpc/htdocs/luci-static/resources/view/xfrpc.js, applications/luci-app-xfrpc/po/templates/xfrpc.pot, applications/luci-app-xfrpc/root/usr/share/luci/menu.d/luci-app-xfrpc.json, applications/luci-app-xfrpc/root/usr/share/rpcd/acl.d/luci-app-xfrpc.json
=> [22.03] xfrpc : add xfrpc to 22.03 branch

.github/workflows/formal.yml, .github/workflows/jsdoc.yml
Ref: 63a5e3dcfc5e ("CI: update dependencies")
Sorry I overlooked these changes in my last PR...
=> CI: update remaining outdated dependencies

applications/luci-app-simple-adblock/Makefile, applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js, applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js, applications/luci-app-simple-adblock/po/templates/simple-adblock.pot, applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock
* update to support corresponding principal package
Depends on https://github.com/openwrt/packages/pull/20768
=> luci-app-simple-adblock: update to 1.9.5

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
* update to support 1.1.1-1 principal package
Depends on PR: https://github.com/openwrt/packages/pull/20912
=> luci-app-pbr: update to 1.1.1-1

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
* update to support 1.1.1-1 principal package
Depends on PR: https://github.com/openwrt/packages/pull/20913
(cherry picked from commit dfa792148a71f88f26ac66abd1a2d2d57c924b5e)
=> [22.03] luci-app-pbr: update to 1.1.1-1

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
(cherry picked from commit f45a91013c85e8e0b21f9ba0f2f507b034152aab)
=> [22.03] luci-app-pbr: opkg_get_version bugfix

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
This should be merged together with
https://github.com/openwrt/odhcpd/pull/186
=> luci-mod-network: add PREF64 support

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/dsl.js
- Fix ATTNDR title
- Make labels translatable
=> Statistics: DSL: fix titles

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
Add small fixes to improve channel graph view and make it more user friendly.
The new view for 5GHz graph is this
---
@jow- ok with this?
=> luci-mod-status: improve channel graph view

applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/overview.js, applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js, applications/luci-app-p910nd/luasrc/model/cbi/p910nd.lua, applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/overview.js, applications/luci-app-travelmate/htdocs/luci-static/resources/view/travelmate/stations.js, applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/config.js, modules/luci-mod-system/htdocs/luci-static/resources/view/system/dropbear.js
In many places when widgets.ZoneSelect and widgets.NetworkSelect used it often used the unspecified option.
But it's not really used anywhere in codebase.
This seems like leftover from old times.
=> Devices unspecified

applications/luci-app-dockerman/luasrc/model/cbi/dockerman/container.lua
=> luci-app-dockerman: fix typos

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
Signed-off-by: Kristian Skramstad <kristian+github@83.no>.
=> luci-theme-bootstrap: better readability in System Log/Kernel Log.

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
(cherry picked from commit 8d502df1b0951c415b236ccfd7a3b8ae104b765f)
=> [23.05] luci-app-adblock-fast: update to 1.0.0-3

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
* bugfix: add missing dl command to RPCD script
* improve output of error messages/link to README
=> luci-app-adblock-fast: bugfix: working re-download

protocols/luci-proto-cni/htdocs/luci-static/resources/protocol/cni.js
Updated luci support for updated netifd cni support openwrt/packages#22341
maintainer: me
build/test platform: x86_64, latest git
=> luci-proto-cni: protocol update

applications/luci-app-olsr/htdocs/luci-static/resources/view/olsr/status-olsr/neighbors.js, applications/luci-app-olsr/root/usr/share/luci/menu.d/luci-app-olsr-frontend.json
Reordering the OLSR menu entry and enhancing the ETX display for the neighbours status view by displaying it with three decimal points of precision
=> [23.05] luci-app-olsr: change menu order and improve etx display for neighbours status view

applications/luci-app-olsr/htdocs/luci-static/resources/view/olsr/status-olsr/neighbors.js, applications/luci-app-olsr/root/usr/share/luci/menu.d/luci-app-olsr-frontend.json
Reordering the OLSR menu entry and enhancing the ETX display for the neighbours status view by displaying it with three decimal points of precision.
=> luci-app-olsr: change menu order and improve etx display for neighbours status view

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
=> luci-mod-network: Evidently hostid was not max 32 bits but 64 bits 🤷

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
Allow creating redirects using IP family `any`.
This helps redirect both IPv4 and IPv6 traffic.
It is used to intercept traffic on the router.
=> luci-app-firewall: allow redirects using ip family any

modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/stats.js, modules/luci-mod-dsl/po/cs/dsl.po, modules/luci-mod-dsl/po/da/dsl.po, modules/luci-mod-dsl/po/de/dsl.po, modules/luci-mod-dsl/po/es/dsl.po, modules/luci-mod-dsl/po/fr/dsl.po, modules/luci-mod-dsl/po/it/dsl.po, modules/luci-mod-dsl/po/lt/dsl.po, modules/luci-mod-dsl/po/nb_NO/dsl.po, modules/luci-mod-dsl/po/pl/dsl.po, modules/luci-mod-dsl/po/pt/dsl.po, modules/luci-mod-dsl/po/pt_BR/dsl.po, modules/luci-mod-dsl/po/ro/dsl.po, modules/luci-mod-dsl/po/ru/dsl.po, modules/luci-mod-dsl/po/sv/dsl.po, modules/luci-mod-dsl/po/templates/dsl.pot, modules/luci-mod-dsl/po/tr/dsl.po, modules/luci-mod-dsl/po/uk/dsl.po, modules/luci-mod-dsl/po/vi/dsl.po, modules/luci-mod-dsl/po/zh_Hans/dsl.po, modules/luci-mod-dsl/po/zh_Hant/dsl.po
HEC stands for Header Error Control in the context of ATM, AFAIK
=> Fix ATM HEC label on stats.js

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast, applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json
Depends on https://github.com/openwrt/packages/pull/22821
(cherry picked from commit 8db9af146acc0e4d5a0aa026636943d3f28468f2)
=> [23.05] luci-app-adblock-fast: update to 1.1.0-1

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js, applications/luci-app-usteer/po/template/usteer.pot
Removed the save/apply buttons on status pages and added friendly error message is usteer is not running.
=> luci-app-usteer: Cosmetic update, added error checking, refresh of status page and translate template

applications/luci-app-strongswan-ipsec/Makefile, applications/luci-app-strongswan-ipsec/htdocs/luci-static/resources/view/ipsec.js, applications/luci-app-strongswan-ipsec/root/etc/config/ipsec, applications/luci-app-strongswan-ipsec/root/usr/share/luci/menu.d/luci-app-strongswan-ipsec.json, applications/luci-app-strongswan-ipsec/root/usr/share/rpcd/acl.d/luci-app-strongswan-ipsec.json
I'm not an IPSec pro, so if there's anything missing or wrong please point it out and I'll be sure to address it. Should we include the example config in the LuCI package? I'm thinking no, it should be a part of the strongswan package. Thoughts?
=> luci-app-strongswan-ipsec: add package

applications/luci-app-olsr/htdocs/luci-static/resources/view/olsr/status-olsr/neighbors.js
please cherry pick that to 23.05, too
Thank you!
=> luci-app-olsr: fix null pointer exception

applications/luci-app-sshtunnel/Makefile, applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_servers.js
=> luci-app-sshtunnel: servers: ProxyCommand option

applications/luci-app-alist/Makefile, applications/luci-app-alist/htdocs/luci-static/resources/view/alist/config.js, applications/luci-app-alist/htdocs/luci-static/resources/view/alist/log.js, applications/luci-app-alist/po/templates/alist.pot, applications/luci-app-alist/po/zh_Hans/alist.po, applications/luci-app-alist/root/usr/share/luci/menu.d/luci-app-alist.json, applications/luci-app-alist/root/usr/share/rpcd/acl.d/luci-app-alist.json
Add LuCI interface for the AList package.
Ref: https://github.com/openwrt/packages/pull/22902
=> luci-app-alist: add new package

applications/luci-app-example/BUILDING.md, applications/luci-app-example/README.md, applications/luci-app-example/YAML.md, applications/luci-app-example/structure.md, modules/luci-base/htdocs/luci-static/resources/form.js, modules/luci-base/htdocs/luci-static/resources/fs.js
Spitted from #6846
@systemcrash
=> [minor] chore JsDoc and luci-app-example 

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
=> luci-app-adblock-fast: remove unnecessary translation calls

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
Thank you @hnyman!
(cherry picked from commit 126443aad5c29a393b48505372a11a1fc51a4722)
=> [23.05] luci-app-adblock-fast: remove unnecessary translation calls

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
=> luci-app-https-dns-proxy: remove unnecessary translation call

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
=> luci-mod-network: wireless: RADIUS Access/Accounting-Request attrs

themes/luci-theme-bootstrap/Makefile, themes/luci-theme-bootstrap/ucode/template/themes/bootstrap/footer.ut, themes/luci-theme-material/Makefile, themes/luci-theme-material/ucode/template/themes/material/footer.ut, themes/luci-theme-openwrt-2020/Makefile, themes/luci-theme-openwrt/Makefile
Add `luci-base` as depends for luci themes.
Open footer links in new tab instead of replacing OpenWrt WebUI.
=> luci-themes: depends on `luci-base` and small front change

applications/luci-app-fwknopd/htdocs/luci-static/resources/view/fwknopd.js
=> luci-app-fwknopd: remove unused vars

luci.mk
APK expects hashes to be prefixed with a ~
@jow- please have a look
=> luci.mk: make APK version compliant

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
=> luci-app-pbr: prepare migration to APK

protocols/luci-proto-nebula/Makefile
(cherry picked from commit 82105922ebf36743cd11d140d90f7bf4a5660455)
=> [23.05] luci-proto-nebula: prepare migration to APK

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/dlink-fgs1210-28.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea8100v1.json
(cherry picked from commit 120710420a7f653e1cf695b52e667783d5cc5dc8)
=> [23.05] luci-app-advanced-reboot: prepare migration to APK

themes/luci-theme-material/htdocs/luci-static/material/cascade.css, themes/luci-theme-material/htdocs/luci-static/material/custom.css
Spawned from https://github.com/openwrt/luci/pull/6936#issuecomment-2011632254. Everything should look as before.
Partially reverts 2bdabf14c30320ef0433828b1a080f6b8fe9c430 by adding back the deleted color variables as the custom.css was used by users to override the theme with their own colors. To maintain backwards compatibility with users we should not remove/rename these as it will result in colors being applied incorrectly.
Ping @feckert
=> luci-theme-material: add back removed color variables

applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/config.js, applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/term.js
=> luci-app-ttyd: add option for UNIX socket and URL override

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
Event Network value source should be NetworkSelect instead of DeviceSelect
=> luci-app-ddns: fix Event Network value source

protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js
Event Network value source should be NetworkSelect instead of DeviceSelect
=> luci-proto-bonding: Modify ipaddr as optional

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
Depends on https://github.com/openwrt/packages/pull/23880
=> luci-app-pbr: sync with principal package

applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js, applications/luci-app-banip/htdocs/luci-static/resources/view/banip/setreport.js, applications/luci-app-banip/po/templates/banip.pot
=> luci-app-banip: sync with 0.9.5-1

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js
Added 2 missing parameters, updated 2 defaults, updated help texts
=> luci-app-usteer: Added 2 missing parameters, updated 2 defaults, updated help texts

applications/luci-app-banip/htdocs/luci-static/resources/view/banip/firewall_log.js, applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js, applications/luci-app-banip/htdocs/luci-static/resources/view/banip/setreport.js, applications/luci-app-banip/po/templates/banip.pot
* add various translation improvements based on the work of "stokito"
* use the new logreadbox component for the firewall log as well
* removed obsolete standard Save/Save & Apply buttons in the footer, use only the improved/customized "Reload" and "Restart" buttons
* improved the error handling in the try/catch blocks
Signed-off-by: Dirk Brenken dev@brenken.org
=> luci-app-banip: various optimizations

modules/luci-mod-system/root/usr/share/rpcd/acl.d/luci-mod-system.json
=>  luci-mod-system: Fix broken JSON in ACL

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Ping @aparcar 
This reverts commit 8860ca069c04e3dbd3f107f1526f2901f1085902.
=> luci-app-attendedsysupgrade: revert version code request

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/README.md, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/status/include/70_adblock-fast.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Depends on https://github.com/openwrt/packages/pull/24745
(cherry picked from commit bd7bee7731a45ee72960562546cc713a03fbfc92)
=> [23.05] luci-app-adblock-fast: sync with 1.1.2-3 principal package

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/README.md, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/status/include/72_pbr.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
This PR syncs the luci app with the principal package PR: https://github.com/openwrt/packages/pull/24738
=> luci-app-pbr: sync with 1.1.6-20 principal package

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/README.md, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/htdocs/luci-static/resources/view/status/include/72_pbr.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr, applications/luci-app-pbr/root/usr/share/rpcd/acl.d/luci-app-pbr.json
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Run tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Description:
* refer to cherry-picked commits for details.
=> [23.05] luci-app-pbr: cherry-pick commits from snapshots to update to 1.1.6-20 

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
related PR https://github.com/openwrt/packages/pull/23988
=> luci-mod-network: sourcefilter option available for modemmanager

modules/luci-mod-status/htdocs/luci-static/resources/view/status/processes.js
I just wrapped all process commands in a span and set `word-break: break-word` as an attribute style for all of them.
=> luci-mod-status: break-word for large commands in processes

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Run tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Description:
* fix spelling in error message
* sync version with principal package
=> luci-app-pbr: update to 1.1.7-10

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/README.md, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4200v1.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4200v2.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4300.json
* update copyright
* update license
* split version string into PKG_VERSION and PKG_RELEASE for APK compatibility
* update upstream URL link
* add menuconfig title/version info
* update README
* add support for:
* Linksys MX4200v1 (Thanks @innovara)
* Linksys MX4200v2 (Thanks @innovara)
* Linksys MX4300 (Thanks @PIPIPIG233666)
=> luci-app-advanced-reboot: update to 1.0.1-13

applications/luci-app-pbr/Makefile
* fixes the build issue reported by @krant in comments to https://github.com/openwrt/luci/pull/7267
=> luci-app-pbr: bugfix: update luci.mk link in Makefile

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js, applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
* better description/link for force_dns in WebUI
=> luci-app-https-dns-proxy: better description/link for force_dns

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Run tested: x86_64, Dell EMC Edge620, OpenWrt 23.05.4
Description:
* sync error messages with principal package
=> luci-app-pbr: update to 1.1.7-15

docs/LMO.md
=> docs: update the reference implementation source

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Maintainer: me
Depends on https://github.com/openwrt/packages/pull/25237
=> luci-app-adblock-fast: update to sync with principal package

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
=> luci-app-adblock-fast: sync with principal

applications/luci-app-upnp/po/ca/upnp.po, applications/luci-app-upnp/po/cs/upnp.po, applications/luci-app-upnp/po/da/upnp.po, applications/luci-app-upnp/po/de/upnp.po, applications/luci-app-upnp/po/es/upnp.po, applications/luci-app-upnp/po/fr/upnp.po, applications/luci-app-upnp/po/ga/upnp.po, applications/luci-app-upnp/po/hu/upnp.po, applications/luci-app-upnp/po/it/upnp.po, applications/luci-app-upnp/po/ja/upnp.po, applications/luci-app-upnp/po/lt/upnp.po, applications/luci-app-upnp/po/nb_NO/upnp.po, applications/luci-app-upnp/po/pl/upnp.po, applications/luci-app-upnp/po/pt/upnp.po, applications/luci-app-upnp/po/pt_BR/upnp.po, applications/luci-app-upnp/po/ro/upnp.po, applications/luci-app-upnp/po/ru/upnp.po, applications/luci-app-upnp/po/sk/upnp.po, applications/luci-app-upnp/po/sv/upnp.po, applications/luci-app-upnp/po/tr/upnp.po, applications/luci-app-upnp/po/uk/upnp.po, applications/luci-app-upnp/po/vi/upnp.po, applications/luci-app-upnp/po/zh_Hans/upnp.po, applications/luci-app-upnp/po/zh_Hant/upnp.po
Fixes for the #7407
@systemcrash please merge before conflicts
=> luci-app-upnp: restore translations: ACL, intro

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Maintainer: me
Description:
* catch up to snapshots version
=> [23.05] luci-app-adblock-fast: catch up to snapshots version

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
Maintainer: me
Description:
* catch up to snapshots version
=> [24.10] luci-app-adblock-fast: catch up to snapshots version

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
Maintainer: me
Description:
* sync version with principal package
=> luci-app-adblock-fast: catch up to snapshots version

applications/luci-app-filemanager/htdocs/luci-static/resources/view/system/filemanager.js
=> luci-app-filemanager: fixed negative time zone parsing

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx5300.json
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc2
Run tested: Linksys MX5300, OpenWrt 24.10.0-rc2
=> luci-app-advanced-reboot: Linksys MX5300 support

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Fix bug in applyPackageChanges, it was using the installed version as the target, resulting in no changes being applied.
(cherry picked from commit 2e9ffc6628d91065326cc1e16ea15f9f8f4f00a0)
=> [24.10] luci-app-attendedsysupgrade: supply proper version to package changes

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-e7350.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx2000.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx5500.json
* Linksys E7350 (thanks forum/OothecaPickle)
* Linksys MX2000 (thanks @georgemoussalem)
* Linksys MX550 (thanks @georgemoussalem)
=> luci-app-advanced-reboot: add support for more Linksys devices

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-e7350.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx2000.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx5500.json
* Linksys E7350 (thanks forum/OothecaPickle)
* Linksys MX2000 (thanks @georgemoussalem)
* Linksys MX550 (thanks @georgemoussalem)
=> [24.10] luci-app-advanced-reboot: add support for more Linksys devices

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/README.md, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Description:
* fix documentation URL in README
* improve supported_interface description
* improve ignored_interface description
=> luci-app-pbr: update to 1.1.8-10

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/README.md, applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js, applications/luci-app-pbr/po/templates/pbr.pot
Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Description:
* fix documentation URL in README
* improve supported_interface description
* improve ignored_interface description
=> [24.10] luci-app-pbr: update to 1.1.8-10

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mr5500.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-spnmx56.json
- Linksys MX5500 (thanks @georgemoussalem)
- Linksys SPNMX56 (thanks @georgemoussalem)
=> luci-app-advanced-reboot: add MR5500 and SPNMX56

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mr5500.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-spnmx56.json
- Linksys MX5500 (thanks @georgemoussalem)
- Linksys SPNMX56 (thanks @georgemoussalem)
=> [24.10] luci-app-advanced-reboot: add MR5500 and SPNMX56

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Fix bug in applyPackageChanges, it was using the installed version as the target, resulting in no changes being applied.
Also include many previous bug fixes that didn't have a backport, const errors and so on.
(cherry picked from commit 2e9ffc6628d91065326cc1e16ea15f9f8f4f00a0)
=> [23.05] luci-app-attendedsysupgrade: backport several bugfixes

protocols/luci-proto-vxlan/htdocs/luci-static/resources/protocol/vxlan.js
=> luci-proto-vxlan: fix option name: vxlan_peers to vxlan_peer

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js, applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js, applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
=> luci-app-firewall: add log option

protocols/luci-proto-yggdrasil/htdocs/luci-static/resources/protocol/yggdrasil.js
Tested on 24.10.0 MT7621 Newifi-D2 ✅
=> luci-proto-yggdrasil: update parameter name for 0.5.7+ version

applications/luci-app-squid/htdocs/luci-static/resources/view/squid.js
The `ssl_db` option should be `ssldb`.
@dannil
=> luci-app-squid: Fix wrong `ssldb` option

applications/luci-app-filemanager/htdocs/luci-static/resources/view/system/filemanager.js
=> luci-app-filemanager: fixed time parsing

applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/net.ffmuc.doh.json
Update ffmuc doh bootstrap_dns to ffmuc dns servers
See Servers: https://ffmuc.net/wiki/doku.php?id=knb:dohdot
Edit:
Ups i linked only the DOH/DOT Wiki Page
Here is our wiki Page about "normal" DNS: https://ffmuc.net/wiki/doku.php?id=knb:dns
=> luci-app-https-dns-proxy: Update: ffmuc bootstrap_dns servers

applications/luci-app-advanced-reboot/Makefile, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mr7500.json, applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx8500.json
* add support for Linksys MR7500 (thanks @PIPIPIG233666)
* add support for Linksys MX8500 (thanks @PIPIPIG233666)
(cherry picked from commit 476b64626d3d9bda66826cd164b3083c7fc65f66)
=> [24.10] luci-app-advanced-reboot: update to 1.0.1-21

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Check various aspects of the overview and revision downloads from the sysupgrade site, giving the user better error messages when things go wrong.
Partially addresses issue #7687 with respect to diagnosis, but not root cause.
=> luci-app-attendedsysupgrade: add more robust handling of downloads

applications/luci-app-antiblock/htdocs/luci-static/resources/view/antiblock/routes.js
1) Changed from "widgets.NetworkSelect" to "widgets.DeviceSelect"
=> luci-app-antiblock: Gateway selection bug fixed

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css, themes/luci-theme-material/htdocs/luci-static/material/cascade.css, themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css, themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css
=> luci-theme-*: fix zone-forwards wrap

modules/luci-base/src/Makefile, modules/luci-lua-runtime/src/Makefile
build was failing b/c gcc15 defaults to c23, which lemon is not written for (and errors with).
=> specify c17 standard for lemon.c compilation

applications/luci-app-banip/htdocs/luci-static/resources/view/banip/overview.js
Unable to open a banip Overview tab.
Update overview.js for the Trim() error fix.
=> luci-app-banip: Trim() error fix.

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
Direct error reports to a LuCI-ASU-app-specific thread on the forum, where they'll get more attention and reduce clutter on the ASU server's github issues.
(cherry picked from commit 9fd692ab4402260bbbe5512cfeff6427c18d39b4)
=> [23.05] luci-app-attendedsysupgrade: change error reporting url

.github/workflows/eslint.yml, .gitignore, applications/luci-app-crowdsec-firewall-bouncer/root/usr/share/luci/menu.d/luci-app-crowdsec-firewall-bouncer.json, eslint.config.mjs
Add CI which lints JSON files using official ESLint json plugin.
This PR also contains fixes for JSON problem found by ESLint.
=> ci: lint JSON files using ESLint

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/README.md, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast, applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json
Maintainer: me
Description:
Depends on https://github.com/openwrt/packages/pull/27135
=> luci-app-adblock-fast: sync with principal package

applications/luci-app-pbr/Makefile, applications/luci-app-pbr/README.md, applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js, applications/luci-app-pbr/po/templates/pbr.pot, applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr, applications/luci-app-pbr/root/usr/share/rpcd/acl.d/luci-app-pbr.json
Maintainer: me
Description:
Depends on https://github.com/openwrt/packages/pull/27141
(cherry picked from commit 6b4d69723c311c3bfbfbc54c408e6fd71e5800d2)
=> [24.10] luci-app-pbr: sync with principal package

applications/luci-app-adblock-fast/Makefile, applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js, applications/luci-app-adblock-fast/po/templates/adblock-fast.pot, applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
Maintainer: me
Description:
* add Donate section/URL to status
* improve visibility with the RPCD return variable names (thanks @systemcrash)
* improve LEDs detection in RPCD script
=> luci-app-adblock-fast: update to 1.1.4-6

applications/luci-app-attendedsysupgrade/README.md
I think the link is outdated and should point to OpenWrt org repo.
=> luci-app-attendedsysupgrade: correct asu link

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
odhcpd has had support for Discovery of Network-designated Resolvers (DNR, RFC9463), which allows allows devices on the network to discover encrypted DNS resolvers, since December 2024 [1].
This patch adds a basic luci interface to configure DNR records. odhcp actually supports DNR records via DHCPv4, DHCPv6 and RA, but since it's typically only used for the latter two, stashing the option next to IPv6 DNS server options seems reasonable.
[1] https://github.com/openwrt/odhcpd/commit/6d342cc03bf72f27d0838942d009bf1c5df4f954
=> luci-mod-network: add DNR (RFC9463) support

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js
`acme.sh` uses 60 days as its default if nothing is specified, which is the case if the field is left empty. This renewal time is also in line with Let's Encrypt's recommendation[^1].
[^1]: <https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid>
=> luci-app-acme: Fix incorrect "Days until renewal" placeholder
