openwrt/luci

- applications/luci-freifunk-diagnostics/luasrc/view/freifunk/diagnostics.htm
the openwrt.org host has no ipv6. 
so the ping6 / traceroute6 test wasnt possible for people who are using this for testing. i changed it to an openwrt-host which already has ipv6..
> luci-freifunk-diagnostics: change adress to an ipv6-enabled host

- contrib/package/luci/Makefile
- protocols/hso/Makefile
- protocols/hso/luasrc/model/cbi/admin_network/proto_hso.lua
- protocols/hso/luasrc/model/network/proto_hso.lua
LuCI interface for HSO protocol to support Option 3G cards.
To use along with comgt + patch https://dev.openwrt.org/attachment/ticket/6995/comgt-hso_141012.patch
> Add LuCI support for HSO protocol (Option 3G card)

- collections/luci/Makefile
- modules/luci-base/Makefile
- modules/luci-mod-admin-full/Makefile
* Module luci-base
libubus-lua not needed
* Module luci-mod-admin
libubus-lua needed
* Collection luci
luci-lib-nixio not needed, already in luci-base
Signed-off-by: Christian Schoenebeck <christian.schoenebeck@gmail.com>
> Modified dependencies

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- protocols/luci-proto-3g/luasrc/model/cbi/admin_network/proto_3g.lua
UCI network already permit dialnumber option for 3g interfaces.
This adds dialnumber to luci protocol 3g. Also it introduces a
new translation string "Dial number", added to template and updated
on each language (all empty but pt-br).
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
I don't know if I should or not update translation files.
> luci-proto-3g: add dialnumber option

- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/main.lua
> luci-app-ocserv: express PKID in a way that is acceptable by openconnect

- libs/luci-lib-httpclient/luasrc/httpclient.lua
commit c30cf9abd4e1e46731e36552ae2f459a27c5cf46
Fix response body only have partial content when under a slow network
commit b6d4f32dcc4bba2645d3758c3dc027fe0e2b4d14
Send cookies in a single header line, which follow browsers' behavior. If not, cookies may not be recognized by some webserver.
commit 3dbdff70960ec8c7de7d5a54721a560941627e0b
add params support in options, it is convenient to user.
Signed-off-by: Yuzo <hyzgog@gmail.com>
> libs/luci-lib-httpclient: fix not straightforward behavior of httpclient

- protocols/luci-proto-ipv6/Makefile
- protocols/luci-proto-ipv6/luasrc/model/cbi/admin_network/proto_aiccu.lua
- protocols/luci-proto-ipv6/luasrc/model/network/proto_aiccu.lua
Initial commit.
TODO:
- hide option tunnelid when username:match("^[^/]+/(T[0-9]+)$") ~= nil
see issue openwrt/luci/issues/313
- more testing (works for me)
> luci-proto-ipv6: add aiccu

- themes/luci-theme-bootstrap/root/etc/uci-defaults/luci-theme-bootstrap
- themes/luci-theme-freifunk-bno/root/etc/uci-defaults/luci-theme-freifunk-bno
- themes/luci-theme-freifunk-generic/root/etc/uci-defaults/luci-theme-freifunk-generic
- themes/luci-theme-openwrt/root/etc/uci-defaults/luci-theme-openwrt
Currently by default theme Bootstrap is installed but
luci.main.mediaurlbase (it holds the current active theme) still has
openwrt.org set.
I did not find the mechanism how LuCI starts Bootstrap theme but the
installation should set luci.main.mediaurlbase correctly.
> luci-themes: luci.main.mediaurlbase not set correctly

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
NOTE: three <br /> in some luci-app's cbi-tab-descr section which help
to workaround must be removed. Check issue #298 
And may I know about some LuCI idea (freifunk proposed) of GSoC this year?
I've also post at the end of #333
> theme/bootstrap: add a mssing class style in form section (#298)

- contrib/package/community-profiles/files/etc/config/profile_potsdam
Without this the router remains dyfunctional when selecting community Potsdam.
> Fixed default DNS settings for community Potsdam

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
Fix log spam that uhttpd logging change has brought to surface.
```
Sun Mar  1 11:10:42 2015 daemon.err uhttpd[2293]: /usr/lib/lua/luci/dispatcher.lua:433: Failed to execute call dispatcher target for entry '/admin/statistics/graph/conntrack'.
Sun Mar  1 11:10:42 2015 daemon.err uhttpd[2293]: The called action terminated with an exception:
Sun Mar  1 11:10:42 2015 daemon.err uhttpd[2293]: .../luci/controller/luci_statistics/luci_statistics.lua:153: attempt to use a closed file
```
Closing the png file explicitly on line 153 is unnecessary, as ltn12's source.file method already closes the file after use.
https://github.com/openwrt/luci/blob/master/modules/luci-base/luasrc/ltn12.lua#L119
More info at https://dev.openwrt.org/ticket/19083#comment:2
Signed-off-by: Hannu Nyman …
> luci-statistics: fix uhttpd log spam from extra png close

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua
modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua:138
generating /etc/config/dhcp section:
>config dhcp
>	option interface 'lan2'
Fix:
>config dhcp 'lan2'
>	option interface 'lan2'
> ifaces.lua:fix generating /etc/config/dhcp section

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/mobile.css
This is a workaround to prevent the navigation bar from covering the title of the section below on mobile browsers.
Let's just have a look. 
**Before:**
The title of STATUS was gone.
**After:** 
The title of STATUS appeared.
I have tested some other languages like Simplified Chinese, etc, and they just work fine. But this is just an workaround.
Dear all,
I've heard that this year freifunk provide an idea of [LuCI Bootstrap3 Theme](http://wiki.freifunk.net/Ideas#LuCI_Bootstrap3_Theme) for [GSoC 2015](https://www.google-melange.com/gsoc/homepage/google/gsoc2015).
Could someone tell me who would be mentors of LuCI or someone reponsible for that? I really want to participate in this idea?
Thank you and kind regards,
Wensheng Tang
> themes/bootstrap: add media queries to bootstrap-theme for better responsive UI on mobile devices

- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/users.lua
> luci-app-ocserv: uclibc's crypt() doesn't support sha2crypt

- modules/luci-base/luasrc/http/protocol.lua
urldecode(urlencode(s)) == s
if s contains '+'
> luci-base: fix wrong pattern of urlencode() (encode '+' properly) #182

- modules/luci-mod-admin-full/luasrc/view/admin_network/diagnostics.htm
change hostname to dev.openwrt.org.. that is available via ipv4 AND ipv6
p.s. this is similiar to https://github.com/openwrt/luci/pull/273 
so that code seems to be twice within luci?
> luci-mod-admin-full: change adress to an ipv6-enabled host

- applications/luci-app-qos/luasrc/model/cbi/qos/qos.lua
Cleanup luci-app-qos, as it still contains references to l7 functionality that has been removed both from kernel and from qos-scripts.
Qos config page has a non-functional "Service" option and every visit to qos config page generates currently an error as no l7 files can be found.
daemon.err uhttpd[2285]: find: /etc/l7-protocols/: No such file or directory
Patch removes "Service" option and the l7 file search.
Signed-off-by: Hannu Nyman <hannu.nyman@iki.fi>
@jow- 
Should I create a separate PR for for-15.05 branch ?
> luci-app-qos: remove l7 options

- libs/luci-lib-json/luasrc/json.lua
There is currently no way to encode an empty object {}, as empty tables are
encoded as empty lists [].
With this patch, encode() will ignore table fields with the key json.null (which
doesn't make sense anyways). This allows adding a field with key json.null to
force encoding it as an object.
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
> luci-lib-json: ignore null keys to allow encoding empty objects

- applications/luci-app-upnp/root/etc/uci-defaults/luci-upnp
Stop sys upgrade disabling miniupnpd service on first boot after upgrade.
I spent a lot of time tracking this behaviour down which only occurs if you have luci-app-upnp installed.
> luci-app-upnp: Stop sys upgrade disabling miniupnpd service on first boot after upgrade

- applications/luci-app-vnstat/luasrc/view/vnstat.htm
The regex used to process the iface query string argument in
vnstat.htm was stripping underscores, which caused the graph not to
display for interfaces with names containing underscores.  This
patch adds the underscore to that regex so that the interface name
will be correct and the graph will be displayed.
Signed-off-by: Michael Marley <michael@michaelmarley.com>
> luci-app-vnstat: Fix blank graphs for iface names with underscores

- modules/luci-base/luasrc/cbi.lua
Add setting "self.section.changed" on changes like other values do.
Signed-off-by: Christian Schoenebeck <<hristian.schoenebeck@gmail.com>>
> cbi.lua: Fix Flag.parse() to set "self.section.changed"

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/conntrack.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
Collectd 5.5.0  (https://github.com/openwrt/packages/pull/1575)  introduced new data to conntrack plugin (https://github.com/collectd/collectd/commit/c66eedcd0cae3019928e03c9c38538fca10d59c8): 
In addition to the number of the tracked connections there is also the static max conntrack limit value and the calculated use percentage.
Luci statistics's conntrack plugin interpretes "conntrack-max" as a new data instance and includes it in the graph in addition to the real "conntrack" number.
Eliminate "max" from graph by specifying empty "" instance as data source.
Ps. The plugin might later be expanded to show also the percentage graph, but as the max value is usually static, it would not provide much additional value.
> statistics: fix conntrack and ping regression caused by collectd changes

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
Backport of the relevant part of #444 
Update to collectd 5.4.1 changed the field from "ping" to "value",
which was changed in the graph definition here, but the label definition
was forgotten. Field's label now reads "ping_IPaddr_value".
Correct the label definition to show only IPaddr like the other two graphs.
@jow-
> statistics: fix ping graph label regression

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
This is useful in client mode as well, since it allows one to use --route-noexec and --up <cmd> or --route-up <cmd> to create routes manually instead of relying on whatever routes vpn server pushes down to the client.
mode=server dependency in luci was introduced together with script_security by mmunz back in 2011, with no explanation in the commit why mode=server was there.
> Enable setting --script-security in client mode.

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/memory.lua
* Implement support in Luci statistics for alternative scaling of the y-axis. By default, rrdtool will autoscale to 1,2,5,10,20,50,100,200,... etc., which is not always suitable (e.g. memory charts for a device with 128 MB). Rrdtool 1.0.50 already supports alternative autoscaling that creates a tighter y-axis (info at http://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html ). Implement graph-level options in Luci statistics to support those boolean options as "alt_autoscale" and "alt_autoscale_max". 
* Memory plugin: utilise alt_autoscale_max to make the memory chart y-axis to scale better for devices with e.g. 128 MB RAM. Also fix the axis min value to 0 to better show the "Used" memory.
Original scaling (axis 20-200):
Modified scaling (axis 0-140):
> statistics: support better autoscaling in rrdtool, improve memory graph's y-axis

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/cpu.lua
CPU plugin in the Luci statistics was missing the label definitions,
so the field labels are like "cpu_system" instead of "System".
Add proper label definitions to CPU (like the other plugins already have).
The statistics graph was also missing softirq and interrupt stats, although colors
for them were defined. Softirq consumes massive amount of CPU especially with
any qos in use, so it is important for the user to see also that data. Add both
softirq and interrupt stats to the graph.
> statistics: cpu graph - add label definitions, add softirq and interrupt stats

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/entropy.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/entropy.lua
- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
Add statistics on the available entropy into Luci statistics.
This PR utilises collectd-mod-entropy, which was created by https://github.com/openwrt/packages/pull/1717
The amount of entropy is typically rather limited in embedded systems. Monitoring the available entropy might be useful in some debugging situations.
Example graph:
> statistics: Add support for entropy stats

- applications/luci-app-firewall/luasrc/model/cbi/firewall/zone-details.lua
fw3 sets the maximum length of the zone name to 14 and ignores zone definitions with too long names.
http://nbd.name/gitweb.cgi?p=firewall3.git;a=blob;f=zones.h;hb=HEAD#l25
http://nbd.name/gitweb.cgi?p=firewall3.git;a=blob;f=zones.c;hb=HEAD#l195
Add a simple validation to ensure that the new zone name is short enough.
This should fix issue #345
> luci-app-firewall: validate zone name to enforce fw3 max. length

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/cpu.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/memory.lua
- applications/luci-app-statistics/luasrc/view/admin_statistics/index.htm
Backport the small improvements/tweaks in luci-app-statistics from trunk to for-15.05.
* Clarify statistics section introduction
* support rrdtool's alt_autoscale and alt_autoscale_max options in graph definitions
* memory graph: improve y-axis scaling
* cpu graph: add proper titles to legend, remove idle and add softirq & interrupt data items
> for-15.05: statistics: Backport recent improvements

- applications/luci-app-ocserv/luasrc/controller/ocserv.lua
- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/users.lua
This was marked as "(none)" which was not caught by the regex.
> luci-app-ocserv: list users with no group

- modules/luci-base/luasrc/model/ipkg.lua
Many packages currently include a git commit hash in version string.
That makes version strings very long and the version column takes much space
when listing available/installed packages in Luci.
Longest version string is 58 characters (micropython).
85 packages have at least 50 chars and 150 packages at least 40 chars.
Adjust Luci to display max. 26 characters (= luci's own version string).
Longer version strings are cut to: "first 21c" + ".." + "last 3c"
The last 3 chars are used to preserve the possible PKG_REVISION string.
E.g. 'opkg' has only hash+PKG_REVISION, so using only start of the string
might not be optimal.
Examples:
1.3.10-20150302-f2a889564b3a215902622b040a1247af38cb8203-1
1.3.10-20150302-f2a88..3-1
0.1-20150302-654c7d288603f7dae09eb09b57fb67b38c7ac6c3-1 …
> Luci opkg/packages: Limit version string display to 26 chars

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/ipkg.lua
opkg config was recently changed by https://dev.openwrt.org/changeset/46491/
Existing /etc/opkg.conf was split to three:
/etc/opkg.conf -> base opkg configuration
/etc/opkg/distfeeds.conf -> default Openwrt package feeds
/etc/opkg/customfeeds.conf -> custom package feeds
Since then, the actual feed definitions have not been visible/configurable, as only /etc/opkg.conf has been visible in Luci.
This patch restores the capability to see and edit package feed definitions.
@jow- 
Could you please check this up, and possible polish it a bit. The form works ok, each of the three files can be edited/saved individually, but it looks a bit crude.
> luci-mod-admin-full: restore opkg feed config capability

- modules/luci-mod-rpc/luasrc/controller/rpc.lua
Calling auth  method returns:
```
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
Cache-Control: no-cache
Expires: 0
{"id":1,"error":{"message":"Invalid params.","data":"/usr/lib/lua/luci/controller/rpc.lua:53: attempt to index global 'luci' (a nil value)","code":-32602},"jsonrpc":"2.0"}
```
with fff7c6c
````
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
Set-Cookie: sysauth=e37acdcb0f23ea40bb0d98fce88e0309; path=/
Cache-Control: no-cache
Expires: 0
{"id":1,"jsonrpc":"2.0","result":"e37acdcb0f23ea40bb0d98fce88e0309"}
```
Ref: https://dev.openwrt.org/ticket/20361#no2
> modules/luci-mod-rpc: fix #466 #427 attempt to index global 'luci' (a nil value) 

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/nut.lua
At some point since I last checked, the nut plugin for collectd changed the
names of the timeleft and percent datasets. Update the luci module to match
so that those graphs are generated correctly again.
Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>
> luci/statistics: Fix nut UPS graphs

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
no-hosts does not disable addn-hosts.
> luci-mod-admin-full: fix dnsmasq no-hosts/addn-hosts options

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
Reorganise the menu items of the Luci statistics module:
* Re-label "Collectd" to "Setup" and place it after the "Graphs" items.
- "Graphs" is used much more frequently so it should be first.
- Change "Collectd" menu item to "Setup" to clarify things.
* Re-label "System plugins" to "General plugins" to change sorting.
"Network / Output / System" changes to "General / Network / Output"
that is more logical order for the items.
> luci-app-statistics: reorganise menu items

- applications/luci-app-asterisk/Makefile
ahcpd dependency appears to have come from a cut-n-paste from
luci-app-ahcpd.
> applications/asterisk: Remove incorrect dependency

- modules/luci-base/root/www/index.html
I propose that the black Luci entrance page (visible for a second) with the black background is changed to have a white background to be more like the other parts of Luci.
The current page dates at least from luci-0.8 in 2008 (https://github.com/openwrt/luci/blob/luci-0.8/libs/sgi-cgi/htdocs/index.html), and the themes at that time may have been darker, but currently the shortly flashing black background seems strange.
The font is left unspecified, so the browser defaults are used. In Windows systems both IE and Firefox use Times New Roman, creating a visible difference to other parts of Luci.
Change index.html that is visible for a second when entering Luci:
* Black text on white background (instead of white on black)
* Specify font as Arial / Helvetica
> luci-base: change index.html to be more like current themes

- modules/luci-base/luasrc/cbi.lua
cbi.lua
- Implement Flag.validate function to be overwritable
- rewritten "if" clause for easier reading ;-)
> cbi.lua: Implement Flag.validate function

- modules/luci-base/luasrc/cbi.lua
- modules/luci-base/luasrc/view/cbi/value.htm
Either use "DummyValue"
or (optical better) use "Value" with property "readonly" set "true".
modified cbi.lua and template cbi/value.htm
> cbi: Implement "readonly" property for "Value"

- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/main.lua
The removed option was not used by the VPN server, and the proxy arp is used by ocserv in master branch.
> ocserv: removed unnecessary option and add proxy arp option

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/fstab/mount.lua
Signed-off-by: Ran Bao <worksev@gmail.com>
> Fix a typo mistake in UI string (mount/fstab extroot advice)

- applications/luci-app-privoxy/Makefile
- applications/luci-app-privoxy/luasrc/model/cbi/privoxy.lua
remove map.title hack; no longer needed
> luci-app-privoxy: remove map.title hack

- modules/luci-base/luasrc/http.lua
* Prevents an empty Location header
* Useful in environments where build_url() could return an empty string (such as http server rewrites requests to /cgi-bin/luci)
Signed-off-by: Joel Pedraza <github@saik0.net>
Replaces openwrt/luci#525
> Redirect to root on empty path (signed off)

- applications/luci-app-qos/luasrc/model/cbi/qos/qos.lua
Adding these lines will list custom created QOS classes in "target" dropdown list.
> luci-app-qos: Add custom QOS classes to luci dropdown list

- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/detail_logview.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
- applications/luci-app-ddns/po/de/ddns.po
- applications/luci-app-ddns/po/templates/ddns.pot
- support for new options "lookup_host", "param_enc" and "param_opt"
- rewritten ddns provider handling to only show/check needed options "domain", "username", etc.
- modified version check/handling incl. using new ipkg.compare_versions function
- modified map.title and map.description generation
- changed XHR.poll interval to 15 seconds on system status page
- using new value_parse function for testing and later implementation into cbi.lua
- some optimizations
> luci-app-ddns: rollup to 2.3.0 to reflect changes on ddns-scripts

- modules/luci-base/luasrc/util.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/fstab.lua
This pull request contains a series of commits that do the following:
1) Add the ability to unmount non-system mounts from the UI.
2) Hides jail bind mounts from the UI mounts list.
3) Adds the 'global' settings for fstab (e.g. anonymous mounts).
4) Adds a button to do block detect and write the output to /etc/config/fstab (in order for mounts points config to find new block devices).
> Pull request fstab improvements

- modules/luci-base/luasrc/view/cbi/value.htm
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_l2tp.lua
This PR also contains a fix for escaping lua string to js repr.
> Allow host:port value for l2tp `server` option

- modules/luci-mod-admin-full/luasrc/view/admin_network/iface_overview.htm
For better view of 'Interface Overview' IPv4/IPv6 addresses for
interfaces should be displayed as lists, but not as comma separated
strings.
> luci-mod-admin-full: update IPv4/IPv6 list views

- applications/luci-app-pbx-voicemail/luasrc/model/cbi/pbx-voicemail.lua
- applications/luci-app-pbx/luasrc/model/cbi/pbx-advanced.lua
- applications/luci-app-pbx/luasrc/model/cbi/pbx-voip.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/olsrd.lua
- applications/luci-app-tinyproxy/luasrc/model/cbi/tinyproxy.lua
- applications/luci-app-watchcat/luasrc/model/cbi/watchcat/watchcat.lua
- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/luasrc/cbi/datatypes.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/system.lua
- protocols/luci-proto-ipv6/luasrc/model/cbi/admin_network/proto_aiccu.lua
- protocols/luci-proto-openconnect/luasrc/model/cbi/admin_network/proto_openconnect.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_l2tp.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppossh.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pptp.lua
Make ipaddrport supprt ipv4 and ipv6, add ipv4addrport and add option ipv4only for hostport which allows hostport to accept only ipv4 IP addresses when an IP address rather than host name is specified (for apps and protocols that don't support ipv6).
Also update affected consumers of host and hostport datatype.
> Pull request validator rework

- modules/luci-base/luasrc/cbi.lua
- modules/luci-base/luasrc/view/cbi/upload.htm
Some files and pointers to files are not safe to remove without a replacement
file and config pointing to the file.  For instance for uhttpd application in
the works, removing the certificate or key config or files without having the
replacements in places renders the WeUI inaccessible.
The only other place where FileUpload is currently used is for wifi certificates
for which the 'safe' handling is also preferred.  Therefore make the default for
the FileUpload widget the safe handling and add a property self.unsafeupload that
allows for the old unsafe handling should it prove useful in some case.
Also allow to specify a file already on router instead of uploading a file.
Signed-off By: Daniel Dickinson <openwrt@daniel.thecshore.com>
> luci-base: Make default for FileUpload 'safe'

- applications/luci-app-ddns/Makefile
- applications/luci-app-privoxy/Makefile
- applications/luci-app-radicale/Makefile
If absolute path to `luci.mk` (i.e. `$(TOPDIR)/feeds/luci/luci.mk`) is specified and LuCI feed has a different name than "luci", errors like this one are raised:
```
Makefile:36: /openwrt/feeds/feedname/luci.mk: No such file or directory
```
This pull request contains fixes for three applications that use absolute paths in their Makefiles and replaces them with relative ones.
> Use relative paths to luci.mk

- applications/luci-app-ddns/Makefile
- applications/luci-app-privoxy/Makefile
- applications/luci-app-radicale/Makefile
backport of PR #608 / #614 to "for-15.05"-branch
Signed-off-by: Sven Roederer devel-sven@geroedel.de
> [Makefile] make include of luci.mk relative

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- remove unneeded assert() in tools/ddns.lua fix #611
- set PKG_VERSION to the correct value from controller/ddns.lua
> luci-app-ddns: removing unneeded assert

- themes/luci-theme-material/htdocs/luci-static/material/css/style.css
No default font size is set by this theme, so it will be the browser default (16px), this is too large for most people.
There are also the same feature requests from this thread's comments: https://forum.openwrt.org/viewtopic.php?id=59696
> luci-theme-material: set default font-size to 13px

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
* add more WPA-EAP phase2 authentication methods.
* client cert, client key and key password are only relevant for
WPA EAP-TLS, change dependency accordingly.
* add support for certificates and key for EAP-TLS phase2 auth.
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
> luci-admin-full: improve WPA(2)-Enterprise client support

- modules/luci-base/luasrc/sys.lua
- modules/luci-base/luasrc/tools/status.lua
status.lua - change default directory of dhcp.leases file
sys.lua - read location of dhcp.leases file from uci
> sys.lua _nethints(): read location of dhcp.lease file from uci

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
This patch enables editing the Identity field in station/station WDS mode EAP-TLS so that EAP-TLS client configuration via LuCI works.
Signed-off-by: Matthew Reeve <matthewreeve@xmission.com>
> luci-mod-admin-full: Identity field is required for EAP-TLS, too.

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
Remove the usually empty standard deviation graph from the ping page.
The graph is empty for most users as collectd measures standard deviation of individual pings inside the general interval of statistics collection. Default setting for both ping interval and general collection interval is 30s in Luci statistics, meaning just 1 ping per interval, which leads to empty graph.
(To provide relevant data, the ping interval should be 1/4-1/5 of the general collection interval. Even then the graph does not look very informative due to different scaling than the latency graph.)
Note that this commit does not change collectd itself, which continues to collect and calculate also the std.dev. data, which can be fetched with 'rrdtool' if needed.
Note:
Instead of directly committing, I make this …
> luci-app-statistics: Remove usually empty std.dev. graph from ping page

- themes/luci-theme-material/luasrc/view/themes/material/header.htm
before:
http://192.168.1.1/cgi-bin/luci//admin/status/overview
after:
http://192.168.1.1/cgi-bin/luci/admin/status/overview
similar issue: #625
> luci-theme-material: remove the double slash (//) from menu url

- modules/luci-base/luasrc/dispatcher.lua
Fall back to default language if "auto" is configured, but none provided by
the browser matches.
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
> modules/base: dispatcher: use default language if automatic choice fails

- luci.mk
- modules/luci-base/src/Makefile
- modules/luci-base/src/mkversion.sh
Adjust luci.mk and luci-base to find out correctly if Luci is built from master or from a branch. (Assume that Luci is permanently in git, forget about Luci svn revisions.) Display that branch name in the footer and the overview page.
Now that the Openwrt main repo is only git based, private CC15.05 builds display the Luci version strangely. The Luci branch name contains actually the main Openwrt git repo's branch and hash:
```
LuCI 15.05-261-gc75367d Release (git-16.043.44305-e2f9172)
```
The "15.05-261-gc75367d Release" is actually the description of the 15.05 since the release tag in the main Openwrt repo, not the Luci git revision. The reason for that is the following:
* when Luci is built, the make for the luci-base modules runs the src/mkversion.sh script that is used to generate …
> LuCI: Display the proper LuCI git branch in GUI

- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
- Under some conditions the system will shutdown
uhttpd before the page will be delivered to
the client. Waiting one second should eleminate
this behaviour.
> luci-mod-admin-full: add sleep before sysupgrade

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/crontab.lua
Write an empty crontab file to remove all content
from file /etc/crontabs/root
- refs #609
> luci-mod-admin-full: allow writing empty crontab config

- modules/luci-base/luasrc/sys/iptparser.lua
- modules/luci-mod-admin-full/luasrc/view/admin_status/iptables.htm
Show also the NAT table in Status->Firewall->IPv6 if table is present.
When kmod-nf-nat6 and kmod-ipt-nat6 are installed, the firewall has also
the 'nat' table for ipv6, and packages like 'adblock' utilize that table.
Currently that table is not shown on the Luci firewall status page,
although it is visible by 'ip6tables -L -v -t nat' from console.
This patch adds support for showing that table in Luci.
> Add support for showing ipv6 NAT table in Luci

- modules/luci-base/luasrc/util.lua
Some packages have different variants that have different
capabilities depending on which libraries against which
they are linked.  Add a function to check which library a
binary links against in order to determine available
functionality.
This is used by various pull requests coming up.
> luci-base: Add option to check linked libraries

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
With mac80211 you can set the wireless interface;
expose this capability.
> luci-mod-admin-full: Add option to set wireless interface name

- modules/luci-base/luasrc/util.lua
Using tristate is counter-intuitive and probably doesn't provide a lot
of benefit so we use a boolean and treat "don't know" as false (because
it is safer than showing options that are not actually available).
This pull request is per Hynam's request so he can test before I have a chance to.  I haven't tested to case of library not present (e.g. to omit show options for dnssec for dnsmasq without crypto compiled in (required for dnssec support).
> [RFC] luci-base: utils: Make checklib return a boolean

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
DSL has one more transmission technologies this is VDSL.
Spelling xDSL reflect this
> luci-mod-admin-full: change spelling ADSL to xDSL

- applications/luci-app-olsr/Makefile
backport of https://github.com/openwrt/luci/commit/ba897c6a209eec3a4ea447a66407a385170ccb80
Signed-off-by: Sven Roederer <devel-sven@geroedel.de>
> luci-app-olsr: depend on luci-lib-json

- modules/luci-mod-freifunk/luasrc/model/cbi/freifunk/basics.lua
restore the lookup of the freifunk community-name stored in
uci "freifunk.community.name".
In https://github.com/openwrt/luci/commit/9780ee382e72f8a5fb69e337a3fcc51fc0914883
the value changed to the complete path of the community-profile, e.g.
"/etc/config/profile_berlin". This causes lookup problems on other
pages, like "mod-freifunk -> overview -> index" (view/freifunk/index.htm line37, line 54).
And as the option suggests it's the community-name not the community-profile path.
Signed-off-by: Sven Roederer devel-sven@geroedel.de
> luci-mod-freifunk: fix lookup of community-name

- contrib/package/community-profiles/files/etc/config/profile_cottbus
- add the current community-file for freifunk Cottbus to for-15.05 branch
- this is a copy of the file with all commits up to "Jan 4, 2016"
Signed-off-by: Sven Roederer <devel-sven@geroedel.de>
> freifunk-profiles: add profile Cottbus

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
With rrdsingle the average values are used for graphing. As the
timescale increases (say over a day or month) the average values
progressively reduce.  Using the maximum value over the longer periods
is arguably no less deceptive but it does produce more informative
graphs.
> Graph the max value rather than avg if rrdsingle disabled

- modules/luci-base/src/mkversion.sh
Otherwize the distrevision may be displayed twice if it contains some special matching patterns.(For example I am using "git-$hash" in my own OpenWrt branch.)
Signed-off-by: Chuanhong Guo <gch981213@gmail.com>
> luci-base:Turn off pattern matching when generating distversion

- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
This pull request adds a condition, which checks whether the file "/etc/config/fstab" exists before it allows access to "mount points".
Signed-off-by: Guido Lipke <lipkegu@gmail.com>
> luci-mod-admin-full: Look also if the file /etc/config/fstab exists.

- luci.mk
- modules/luci-base/Makefile
An lua interpreter is required on the building host to run the
luasrcdiet lua script.  Due to a build change, the interpreter was not
being installed to the correct location.
> luci-base: fix lua interpreter location

- modules/luci-mod-freifunk/luasrc/view/freifunk/public_status.htm
This PR fixes an Internal Server Error when requesting the Wireless Informations in luci-mod-freifunk. 
It checks an unindexed value "net.iwdata".
```
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute template dispatcher target for entry '/freifunk/status'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'freifunk/public_status'. 
A runtime error occured: [string "/usr/lib/lua/luci/view/freifunk/public_stat..."]:116: attempt to index field 'iwdata' (a nil value) stack traceback: [C]: in function 'assert' /usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:141: in function...
```
signed-off.by: Guido Lipke <lipkegu@gmail.com>
> luci-mod-freifunk: Fix "Undefined reference to net.iwdata"

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
Otherwise the log is spammed with:
```uhttpd[2037]: sh: 1: unknown operand ```
Signed-off-by: Mathias Kresin <dev@kresin.me>
> luci-app-ddns: pass the is_glue option value to the helper

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/po/de/ddns.po
- fix handling of parameter "is_glue" and "dns_seerver"
- depends on https://github.com/openwrt/packages/pull/2875
> luci-app-ddns: fix handling of parameter "is_glue" and "dns_seerver"

- modules/luci-mod-admin-full/luasrc/view/admin_network/wifi_overview.htm
When a wireless network is disabled it can't be removed. From
wifi_overview.htm the delete call is generated as wlan0, wlan1 or
whatever. This wlan is not working because it is disabled, then LuCI
deletes the virtual radio which really is named as wlan0.
> Closes #741: Can't delete disabled wireless networks

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/df.lua
It used data source instance name instead of plugin instance name which resulted in missing phrase in graph title, e.g.:
`hostname: Disk space usage on`
vs
`hostname: Disk space usage on overlay-boot`
> luci-app-statistics: Fix missing title in df graphs

- luci.mk
- modules/luci-base/Makefile
Also, don't make any assumptions about the staging dir lua and LuaSrcDiet
were installed to.
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
> luci-base: use default install paths for host utils

- collections/luci-ssl-openssl/Makefile
- collections/luci-ssl/Makefile
@jow- 
Your opinion, please. 
The discussion with build000 got me into looking things and this might be the sensible first step on the LuCI side. I thought about creating a menu for selecting the SSL provider for luci-ssl, but then I thought that it is more-straightforward to keep the old luci-ssl intact and to create a new collection next to it.
* Add a new OpenSSL-based collection ```luci-ssl-openssl``` that uses libustream-openssl instead of the default libustream-polarssl. (Note: px5g is included and still needs libpolarssl, so both underlying SSL libs will be included. Mention that in the package description.)
* Mention PolarSSL in the title of luci-ssl.
------------
Additional thoughts:
The next step in the path towards "openssl-only" would be to look for openssl-based alternatives …
> luci-ssl-openssl: Provide OpenSSL-based LuCI collection

- modules/luci-base/Makefile
I just noticed that my previous commit broke the build on OpenWrt,
sorry about that.
OpenWrt doesn't provide an argument to Host/Install like LEDE does; use
HOST_BUILD_PREFIX instead, which is available on both.
> luci-base: fix luci-base host tool install on OpenWrt

- luci.mk
- modules/luci-base/Makefile
This reverts commit d4c33720208346ee7983213fe764df3102b8a771.
PATH inconsistencies and Host/Install arguments have been fixed in both
LEDE and OpenWrt, so we can revert the revert.
Build-tested with both LEDE and OpenWrt.
> luci-base: use default install paths for host utils (again)

- applications/luci-app-rp-pppoe-server/Makefile
- applications/luci-app-rp-pppoe-server/luasrc/controller/rp-pppoe-server.lua
- applications/luci-app-rp-pppoe-server/luasrc/model/cbi/rp-pppoe-server.lua
Adds support for rp-pppoe-server configuration once pending
pull request for packages feed gets applied.
> luci-app-pppoe-server: Add PPPoE server configuration

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/nut.lua
Different UPSes report differents stats; here we add graphing
of some additional statistics supports by some models.
> luci-app-statistics: nut: Add additional stats some UPSes report

- protocols/luci-proto-wireguard/Makefile
> luci-proto-wireguard: do not depend on meta-package

- applications/luci-app-wifischedule/Makefile
- applications/luci-app-wifischedule/README.md
- applications/luci-app-wifischedule/luasrc/controller/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/model/cbi/wifischedule/wifi_schedule.lua
- applications/luci-app-wifischedule/luasrc/view/wifischedule/file_viewer.htm
Turns WiFi on and off according to a schedule.
Splitted frontend and backend in different packages. This feature has now a dependency to the package
wifischeduler
in openwrt/packages which needs to be merged as well.
Signed-off-by: Nils Koenig <<mailUNDERSCOREopenwrt@newkDOTit>
> Added luci-app-wifischeduler 

- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
Description was misleading, as the routes are not created automatically. We have
a flag to create routes. Added a hint what to fill into the AlledIPs field as
users repeatedly have struggled to use it correctly. Thanks to Stefan Agner for
providing feedback on this.
> luci-proto-wireguard: Fix misleading description

- protocols/luci-proto-ipip/Makefile
- protocols/luci-proto-ipip/luasrc/model/cbi/admin_network/proto_ipip.lua
- protocols/luci-proto-ipip/luasrc/model/network/proto_ipip.lua
This package adds LuCI support for IPIP tunnels (IPv4-in-IPv4 RFC2003)
Signed-off-by: Roger Pueyo Centelles roger.pueyo@guifi.net
> luci-proto-ipip: Add package

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/global_value.htm
- applications/luci-app-ddns/root/etc/uci-defaults/40_luci-ddns
needed changes to support ddns-scripts 2.7.6
- new command line options of dynamic_ddns_lucihelper.sh
- renamed global config options
- new location of services files
> luci-app-ddns: update to support ddns-scripts 2.7.6

- applications/luci-app-unbound/Makefile
- applications/luci-app-unbound/luasrc/controller/unbound.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound.lua
Compile tested: ar71xx OpenWrt 15.05.1
Run tested: TL-WDR3600
Description: Basic LuCI to go with recent Unbound UCI enhancements
cc: @hansmi @Borromini
> Unbound: Basic LuCI to go with recent Unbound UCI enhancements

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
The linear-gradient function syntax uses 'to bottom' instead of 'top' for a gradient from top to bottom.
Signed-off-by: Arjen de Korte \<build+openwrt@de-korte.org\>
> theme-bootstrap: fix invalid use of 'linear-gradient'

- applications/luci-app-ddns/luasrc/view/ddns/detail_lvalue.htm
- applications/luci-app-ddns/luasrc/view/ddns/overview_enabled.htm
- modules/luci-base/luasrc/view/cbi/firewall_zonelist.htm
- modules/luci-base/luasrc/view/cbi/fvalue.htm
- modules/luci-base/luasrc/view/cbi/lvalue.htm
- modules/luci-base/luasrc/view/cbi/mvalue.htm
- modules/luci-base/luasrc/view/cbi/network_ifacelist.htm
- modules/luci-base/luasrc/view/cbi/network_netlist.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk/remote_update.htm
Add an empty, normally invisible label after checkboxes and radio buttons
with cbi-input-{checkbox,radio} classes to allow CSS styling them as
suggested on http://www.paulund.co.uk/style-checkboxes-with-css
This is another patch we've been carrying in Gluon for some time, allow us to get the nice styled checkboxes in our config mode theme ( https://kbu.freifunk.net/wiki/images/thumb/a/ad/Gluon-config-welcome.png/800px-Gluon-config-welcome.png ).
I've extended our patch to add such an label for all instances of cbi-input-{checkbox,radio} (I hope I didn't miss any...) I also moved two "id" attributes from enclosing <label>s to an <input> element to allow referencing the <input> from the added labels, but I didn't understand why those <label>s had ids in the first place, so I hope my changes …
> luci-base: view: make checkboxes and radio buttons styleable

- contrib/package/freifunk-common/files/usr/bin/neigh.sh
Starting with version 0.9.5 the new olsr-deamon behaves
more standard-compliant and outputs correct HTTP-headers.
This would confuse the script and abort parsing.
Fix that by only trying to parse the JSON-value and
just ignore the other stuff. After this, we can see neighbours again.
Thanks to FreifunkUFO <ufo@rund.freifunk.net> for spotting this.
> freifunk-common: neigh.sh: fix for new olsrd 0.9.5

- contrib/package/freifunk-common/files/usr/bin/neigh.sh
Older OLSRd-version outputs JSON humanreadable over multiple lines.
The introduced change in 524439cd1647e5d6d7b48f9c75ec5800a5444109 broke
the output for those users. Fix that be a finer filter regex.
Thanks to Thomas Huehn <thomas@net.t-labs.tu-berlin.de> for spotting that.
> freifunk-common: neigh.sh: work also with unprettyfied JSON output

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
Add missing comma, 'none' is not a valid value for background-color (changed to 'transparent') and 'dpx' is not a valid unit for height (removed)
Signed-off-by: Arjen de Korte \<build+luci@de-korte.org\>
> luci-theme-bootstrap: fix minor CSS errors

- protocols/luci-proto-qmi/Makefile
- protocols/luci-proto-qmi/luasrc/model/cbi/admin_network/proto_qmi.lua
- protocols/luci-proto-qmi/luasrc/model/network/proto_qmi.lua
Derived mostly from (ppp) 3g implementation. Currently exposing the following configuration through cbi (apn/pincode/username/password/auth/ipv6).
Signed-off-by: David Thornley <david.thornley@touchstargroup.com>
> luci-proto-qmi: Added support for QMI Cellular

- applications/luci-app-fwknopd/luasrc/model/cbi/fwknopd.lua
- applications/luci-app-fwknopd/luasrc/view/fwknopd-qr.htm
- applications/luci-app-fwknopd/root/etc/uci-defaults/40_luci-fwknopd
- applications/luci-app-fwknopd/root/usr/sbin/gen-qr.sh
Also adds NAT-DNS as a default setting, and enables a QR-code per access.conf entry
Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>
> [luci-app-fwknopd] Remove usage of dynamic tag.

- applications/luci-app-olsr/luasrc/controller/olsr.lua
- applications/luci-app-olsr/luasrc/view/status-olsr/neighbors.htm
controller/olsr.lua:
drop HTTP-headers which are now emitted, we do not need them
status-olsr/neighbors.htm:
olsr ETX value now without muliplication 1024x
Signed-off-by: Bastian Bittorf <bb@npl.de>
Signed-off-by: Freifunk UFO <ufo@rund.freifunk.net>
> luci-app-olsr: adapt to changed behavior of new OLSRd v0.9.5

- modules/luci-base/luasrc/tools/webadmin.lua
When converting interface names to UCI network names
webadmin fails if there is no UCI network name because
webadmin failed to ensure uciname has a value before
attempting to take a substring.
> base: webadmin: Don't take substring of nil variable

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/df.lua
The df plugin wasn't displaying useful lables for the space
used vs free vs reserved due to title override.  This patch
fixes that issues by removing the per-instance setting.
> app-statistics: df: Don't separate disk usage types

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/global.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
- applications/luci-app-ddns/luasrc/view/ddns/overview_status.htm
- applications/luci-app-ddns/luasrc/view/ddns/system_status.htm
depends on pull: https://github.com/openwrt/packages/pull/3829
compiled ipk-packages available at
https://github.com/chris5560/OpenWrt-Backports/tree/master/for-CC15.05.01/luci-app-ddns
> [for-15.05] luci-app-ddns: support for backported ddns-scripts 2.7.6

- contrib/package/freifunk-common/Makefile
the updates for olsr-0.9.5 compatibility should have changed the release-number
> freifunk-common: bump version as of recent changes

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi_add.lua
Fixed an issue where the target network name is displayed as "%q" on wlan
connection destination network settings page.
> luci-mod-admin-full: Fix display problem of wifi_add

- modules/luci-mod-admin-full/luasrc/controller/admin/status.lua
> luci-mod-admin-full: show realtime wlan graph only if iw command is installed

- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
We're currently just setting system time, but we don't set battery
backed RTC. Time in the RTC is only set on the graceful shutdown, which
is quite hard to achieve on embedded devices.
In other words, on systems with battery backed RTC we currently don't
handle following use case properly:
1. Set system time from web UI (sets only system time, but not RTC)
2. Unplug the device from power
Then after the reboot, we've wrong system time again, because time set
in [1] is not saved to battery backed RTC.
Signed-off-by: Petr Štetiar <ynezz@true.cz>
> luci-mod-admin-full: Store system time into RTC also

- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
Enable static addresses on WireGuard tunnel interfaces without requiring
an static address interface.
This removes the requirement to use a static address interface on top of a
WireGuard tunnel interface in the majority of cases. In the past, users have
been confused by the current approach and asked for a simpler way to configure
WireGuard interfaces.
**PS: If possible, please merge before Mon Jan 16 2017 so this change will be part of the upcoming freeze.**
> luci-proto-wireguard: enable addressing for tunnel interfaces

- applications/luci-app-commands/luasrc/controller/commands.lua
- applications/luci-app-commands/luasrc/view/commands.htm
- applications/luci-app-commands/luasrc/view/commands_public.htm
- applications/luci-app-commands/po/en/commands.po
- applications/luci-app-commands/po/zh-cn/commands.po
Now we can get public links that shows execution result rather than downloading it.
We append an `s` behind the command name to show that we intend to show the result.
This is useful: we can just bookmark the link to do something, without having to download the result.
Signed-off-by: t123yh t123yh@outlook.com
> luci-app-commands: allow executing without downloading on public links

- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/controller/admin/network.lua
- modules/luci-mod-admin-full/luasrc/view/admin_network/iface_overview.htm
- modules/luci-mod-admin-full/luasrc/view/admin_network/iface_status.htm
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
The Overview page and Network>Interfaces page currently do not give much information about IPv6, particularly with Prefix Delegated setups. In these setups, ISP will delegate a prefix to the router. Currently LuCI doesn't display this Prefix Delegation from the ISP anywhere. A number of changes was added to this commit:
1) self:_ubus("ipv6-prefix") was extracted and put into protocol.ip6prefix.
2) Network>Interfaces page, if a .ip6prefix is present, show it under Status. (IPv6-PD).
3) On the Overview page, "Type" and "Prefix Delegated" has been added to the IPv6 Network Overview Status:
- Type will display the .proto, similar to the IPv4 case. If a .ip6prefix is present, it'll display a "-pd" at the end of the Type: i.e. dhcpv6-pd vs. dhcpv6.
- If no .ip6prefix is present, it'll do what …
> mod-admin-full: Add IPv6 Prefix Delegation information to Status Pages

- applications/luci-app-adblock/luasrc/model/cbi/adblock.lua
this PR reflect the changes made in adblock 2.3.0
> luci-app-adblock: put backup options to global section

- libs/luci-lib-nixio/src/fs.c
Hi,
using the `nixio.fs` module I noticed the `nixio.fs.lstat()` function behaves the same way `nixio.fs.stat()` does. Looking at the source code I saw the `nixio_lstat()` C function calls `stat()` but not `lstat()`. This does not seem right.
Thank you in advance,
thoto
> luci-lib-nixio: nixio_lstat calls stat instead of lstat

- modules/luci-base/luasrc/tools/status.lua
This should result in the MAC address display being the same
using odhcpd for v4 DHCP as when using DNSMasq for v4 DHCP.
> base: status: For odhpcd leases display MAC formatted with colons

- modules/luci-mod-admin-full/luasrc/view/admin_status/connections.htm
- modules/luci-mod-admin-full/src/luci-bwc.c
luci ignores only 127.0.0.1 in real time connections.
The dnsmasq.init script sets up resolv.conf(s) as such.
With alternate DNS servers configured 'localhost' will
resolve to '127.0.0.1' or '::1'. The connections graph
will spam itself. openwrt/luci#996
It works and it was *too easy*. @hnyman please
check this, but it might be the answer.
> luci: ignore '::1' in realtime connections

- applications/luci-app-minidlna/root/etc/uci-defaults/40_luci-minidlna
Do not disable minidlna after sysupgrade, rather trust the config
enabled status in /etc/config/minidlna.
> luci-app-minidlna: permit minidlna after sysupgrade

- applications/luci-app-unbound/root/etc/uci-defaults/60_luci-unbound
Tested: TL-Archer-C7 LEDE Trunk
Description: 
Also if unbound-control is installed, then configure so
luci-app-commands can quickly show the "local zones" and
"local data" (aka hosts). This helps diagnose DHCP-DNS
zone data and adblock zone data.
> unbound: add uci-default script

- applications/luci-app-upnp/root/etc/uci-defaults/40_luci-miniupnp
Restore luci indexcache handling incorrect removed in
https://github.com/openwrt/luci/commit/387a06bb73462312c075e53ce9e6002d4af09e92
> luci-app-miniupnpd: restore missing luci install file

- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Updated luci-app to directly edit dnsmasq ipsets and link to README on github.
> luci-app-vpnbypass: include dnsmasq settings, link to README

- modules/luci-base/luasrc/cbi/datatypes.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
This PR contains three commits that backport the recent additions of 802.11r and 802.11w config options into the lede-17.01 branch.
Three commits:
* hexstring data type validation
* 802.11r support, roll-up of four commits
* 802.11w support, roll-up of two commits
Run-tested in LEDE 17.01 with ipq806x/R7800 and ar71xx/WDNR3700.
> Backport 802.11r and 802.11w LuCI support to lede-17.01

- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Hannu, as per your feedback I've removed the link to README from translatable section. I've also noticed I've accidentally left an unneeded section in the cbi file before.
There's no earth-shattering change, but I'm not going to touch this for a while, so I wanted to submit this now.
Thank you!
> luci-app-vpnbypass: cbi file fix for README link and an unneeded section

- applications/luci-app-squid/Makefile
- applications/luci-app-squid/luasrc/controller/squid.lua
- applications/luci-app-squid/luasrc/model/cbi/squid.lua
This application was moved from the packages repository to luci.
This  PR depends on: https://github.com/openwrt/packages/pull/4013
> luci-app-squid: added squid application

- applications/luci-app-bcp38/Makefile
- applications/luci-app-bcp38/luasrc/controller/bcp38.lua
- applications/luci-app-bcp38/luasrc/model/cbi/bcp38.lua
- applications/luci-app-bcp38/root/etc/uci-defaults/60_luci-bcp38
This application was moved from the packages repository to luci.
What I do not know how to implement best is this part:
````
define Package/luci-app-bcp38/postrm
#!/bin/sh
uci delete ucitrack.@bcp38[0]
uci commit
endef
````
What is the correct trigger in the LuCI build system for that?
This  PR depends on: https://github.com/openwrt/packages/pull/4013
> luci-app-bcp38: added bcp38 application

- protocols/luci-proto-wireguard/Makefile
Marks package luci-proto-wireguard as architecture independent.
> luci-proto-wireguard: mark package as arch indep.

- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
I've added datatypes and placeholders for both local and remote ports/addresses fields.
I've also made minor modifications to translatable labels and rebuilt the pot-file.
> luci-app-vpnbypass: add datatypes and placeholders to fields

- applications/luci-app-upnp/luasrc/model/cbi/upnp/upnp.lua
Add a 'master' miniupnpd service enable flag rather than just relying on
rcS.d script existence.  This allows the service to be disabled
across sysupgrade, similar to minidlna.
> luci-minuupnpd: use enable flag

- modules/luci-base/luasrc/cbi/datatypes.lua
- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
Adds support for the fwmark option.
FwMark is a 32-bit fwmark for outgoing packets.
If set to 0 or "off", this option is disabled.
> luci-proto-wireguard: add support for fwmark option

- applications/luci-app-wireguard/po/ja/wireguard.po
- applications/luci-app-wireguard/po/templates/wireguard.pot
Added po templates file and Japanese translations.
> luci-app-wireguard: Add Japanese translation

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
@jow- 
Could you please check this one out:
Use the new hostapd functionality (in LEDE) to detect 802.11r and 802.11w more properly. Leave the old logic in place for Openwrt.
* I wonder if it would be more efficient performance-wise to use just one variable and just "or" the two os.execute statements (to avoid two os.executes in case the first one already provides a positive answer)
----
This goes outside the core scope of the PR but is related: 
Regarding 80211w:
There have been a few forum discussions from persons who have got ieee80211w=0 option in their hostapd config, and it prevents radio from getting up if there is no 80211w support. 
* Hostapd startup uci script places also the unnecessary ieee80211w=0 value to the final hostapd config file, although that value value means that …
> luci-mod-admin-full: new hostapd functionality for 80211w/r detection

- applications/luci-app-meshwizard/luasrc/model/cbi/freifunk/meshwizard.lua
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
- contrib/package/freifunk-common/Makefile
- contrib/package/freifunk-common/files/etc/config/freifunk
- contrib/package/meshwizard/Makefile
- contrib/package/meshwizard/files/usr/bin/meshwizard/helpers/rename-wifi.sh
- contrib/package/meshwizard/files/usr/bin/meshwizard/helpers/setup_wifi.sh
- contrib/package/meshwizard/files/usr/bin/meshwizard/helpers/supports_vap.sh
- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
- modules/luci-mod-admin-full/luasrc/view/admin_network/wifi_overview.htm
- modules/luci-mod-admin-mini/luasrc/model/cbi/mini/wifi.lua
Remove from LuCI the code related to the deprecated madwifi driver. The last references to the driver were removed from Openwrt main code two years ago with https://github.com/openwrt/openwrt/commit/0be32368ad57192f5b92c96f61021b6d8752469e
Run-tested with
* ipq806x / R7800
* ar71xx / WNDR3700
I will also disable the madwifi plugin in collectd (in the packages repo).
@jow-
> treewide: cleanup references to madwifi

- applications/luci-app-unbound/luasrc/model/cbi/unbound.lua
- applications/luci-app-unbound/root/etc/uci-defaults/60_luci-unbound
LEDE 17.01.0 pulled in Unbound "acts like dnsmasq" UCI behaviors, but the matching LuCI update was not carried in. Specifically, `add_local_fqdn` and `add_wan_fqdn` are supported by Unbound UCI but not LuCI. No failures but some configuration is not accessible to the novice user. Should be timed with PR https://github.com/openwrt/packages/pull/4072
> [lede-17.01] luci-app-unbound: service updates coordinated with application package

- contrib/package/community-profiles/files/etc/config/profile_potsdam
Sorry, I totaly messed up PR #1044 so here is a new clean one.
- fixed ssid
- disable IPv6
- added more interface settings
- added settings for 5GHz wifi
- added ssidscheme
- added dhcp leasetime setting
- added LinkQualityAlgorithm for olsrd
Signed-off-by: Hannes Fuchs <hannes.fuchs@gmx.org>
> community-profiles: update Potsdam

- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
Allows to enable/start and stop/disable service from Web UI.
Minor fix: show all fields.
Minor fix: readme URL is in variable allowing more compact lua code.
> luci-app-vpnbypass: directly enable service from Web UI.

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/po/templates/vpnbypass.pot
Following up on the previous PR, this implementation respects the config's enable option, yet enables/starts or stops system service depending on UI switch.
> luci-app-vpnbypass: updated service start/enable logic.

- protocols/luci-proto-ncm/Makefile
- protocols/luci-proto-ncm/luasrc/model/cbi/admin_network/proto_ncm.lua
- protocols/luci-proto-ncm/luasrc/model/network/proto_ncm.lua
NCM is used by some 3G/LTE dongles.
First introduced in https://github.com/lede-project/source/commit/51a5ff094703c4db984284913d605e83e819d99c
light modified file taken from OpenWRT/Gargoyle github
https://github.com/obsy/packages/tree/master/luci-proto-wwan
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>
> Add luci-proto-ncm for comgt-ncm

- applications/luci-app-simple-adblock/po/ja/simple-adblock.po
> luci-app-simple-adblock: Add Japanese translation

- applications/luci-app-adblock/Makefile
Cannot load this package in buildroot, so I fixed package call from
buildroot in the Makefile.
> luci-app-adblock: Fix package call from buildroot

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* fix XHTML parsing errors in openwrt theme
* tested with openwrt, bootstrap & material theme
> luci-app-adblock: fix XHTML/HTML5 markup

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
Add new/missing mwan3 parameter to the tracking interface configuration
- ping (new) -> ICMP ping size for mwan3track
- family (missing) -> IP-Family for the mwan3 interface config IPv6/IPv4
- conntrack (new) -> Flush global conn-track table one interface events (ifup/ifdown/always/never)
> Mwan3 add params

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
* made buttons translatable
* accept empty values for interface trigger input field
* replace 'url' with 'luci.dispatcher.build_url'
> luci-app-adblock: sync with adblock 2.5.1

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua
If `proto` option is `static` then `force_link` will be enabled by default and the hotplug-scripts will `not` be invoked. The behaviour for the proto `static` should be configurable in luci. The config option `force_link` manage this.
> luci-mod-admin-full: Add force link option in interfaces advanced settings section

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/memberconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policy.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/policyconfig.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/rule.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua
Fixed strings in Lua sources where the LuCI i18n tools cannot be
detected. And also fixed some other problems.
> luci-app-mwan3: Fix luci tools cannot detect translate()

- applications/luci-app-adblock/Makefile
- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* add new trigger timeout input field
* the download utility plus SSL Library will be listed in runtime
information and the blocklist source table contains an additional 
"SSL req." column
* various small fixes
* changed copyright notice
> luci-app-adblock: sync with adblock 2.6.0

- applications/luci-app-adblock/Makefile
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* made default trigger delay more conservative to fix possible start up issues
* add luci-lib-jsonc dependency
> luci-app-adblock: sync with 2.6.0-2

- applications/luci-app-samba/luasrc/model/cbi/samba.lua
There are two valid values: 0 and 1. The page looks much better with a check box for "Share home-directories".
> luci-app-samba: "Share home-directories" check box

- applications/luci-app-samba/luasrc/model/cbi/samba.lua
The current "Network Shares" page is missing a frequently used option: "browseable yes/no". When setting up a number of shares with different access levels this one was the only missing option on the page that I had to add manually. 
The default value for it is "yes" if it is missing for backwards compatibility, because that is the initial value in /etc/samba/smb.conf.template on a new samba install.
With this new checkbox, the page is still readable.
> luci-app-samba: add "Browsable" checkbox to each share

- applications/luci-app-hd-idle/luasrc/controller/hd_idle.lua
- applications/luci-app-hd-idle/luasrc/model/cbi/hd_idle.lua
- applications/luci-app-hd-idle/po/ca/hd_idle.po
- applications/luci-app-hd-idle/po/cs/hd_idle.po
- applications/luci-app-hd-idle/po/de/hd_idle.po
- applications/luci-app-hd-idle/po/el/hd_idle.po
- applications/luci-app-hd-idle/po/en/hd_idle.po
- applications/luci-app-hd-idle/po/es/hd_idle.po
- applications/luci-app-hd-idle/po/fr/hd_idle.po
- applications/luci-app-hd-idle/po/he/hd_idle.po
- applications/luci-app-hd-idle/po/hu/hd_idle.po
- applications/luci-app-hd-idle/po/it/hd_idle.po
- applications/luci-app-hd-idle/po/ja/hd_idle.po
- applications/luci-app-hd-idle/po/ms/hd_idle.po
- applications/luci-app-hd-idle/po/no/hd_idle.po
- applications/luci-app-hd-idle/po/pl/hd_idle.po
- applications/luci-app-hd-idle/po/pt-br/hd_idle.po
- applications/luci-app-hd-idle/po/pt/hd_idle.po
- applications/luci-app-hd-idle/po/ro/hd_idle.po
- applications/luci-app-hd-idle/po/ru/hd_idle.po
- applications/luci-app-hd-idle/po/sk/hd_idle.po
- applications/luci-app-hd-idle/po/sv/hd_idle.po
- applications/luci-app-hd-idle/po/templates/hd_idle.pot
- applications/luci-app-hd-idle/po/tr/hd_idle.po
- applications/luci-app-hd-idle/po/uk/hd_idle.po
- applications/luci-app-hd-idle/po/vi/hd_idle.po
- applications/luci-app-hd-idle/po/zh-cn/hd_idle.po
- applications/luci-app-hd-idle/po/zh-tw/hd_idle.po
The menu item and some text on the configuration page itself do not match the other pages. Now words in the menu are upper-cased and the dashes removed in the labels.
Fixes #1138
> luci-app-hd-idle: removed dashes in menu items and text labels

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
Not sure why, but the "isolate" option is only available for broadcom, but it works for mac80211 (tested in Netgear R7800). This commit makes it available in LUCI.
I suspect it is available for other chip sets as well, because this should be standard functionality...
> luci-mod-admin-full: "isolate" option is missing for mac80211

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
Modified `proto` Parameter values to match extended `config` view.
Accepted values for proto are udp, tcp-server and tcp-client as written in openvpn 2.4 manual
https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
Bug description:
If you select in advanced view tcp-server/tcp-client and switch to basic-view then the param is set to `--delete` because the values tcp-server/tcp-client are unknown
> luci-app-openvpn: fix proto param selection in basic

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* Limit Blacklist/Whitelist Online editing to max. 512 KB, approx.
20.000 domains per list
* Automatically refresh the overview page after button onclick event,
e.g. 'Suspend/Resume' or 'Save & Apply'
* cosmetics
> luci-app-adblock: sync with adblock 2.6.3

- luci.mk
Rectification of non-standard name for language Chinese.
Signed-off-by: Angus Ding angus.ding@gmail.com
> luci.mk: Update language name for Chinese

- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
Fixed some issues.
- Fix duplicated text in Lua source.
- Fix syntax error in sv/adblock.po
And synchronized translations.
> luci-app-adblock: Fix duplicated text

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* Automatically refresh the overview page after button onclick event,
e.g. 'Save & Apply'
> luci-app-travelmate: sync with travelmate 0.7.3

- modules/luci-base/root/etc/config/ucitrack
If hostname get changed in "/etc/config/system" dnsmasq should reloaded
his config to be reached again under the new URL [HOSTNAME].lan
> luci-base: add dhcp to system ucitrack

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
Fixed an issue that mwan3 fails to detect connection because "ip"
command was relocated.
This issue has been reported in #1166 .
> luci-app-mwan3: Fix "ip" command path

- applications/luci-app-wireguard/luasrc/view/wireguard.htm
- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
Maintainer: @danrl 
This should only be merged when openwrt/packages#4341 is also merged.
> wireguard: preshared-key is now an attribute of the peer

- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
Updated Japanese translations, and cleaned up old translations.
Most of old translations in Japanese po file were replaced with different strings or removed, and I decided that all of them were unnecessary and deleted.
> luci-app-adblock: Update Japanese translation

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* "Save & Reply" now distinguish between normal and manual/backup mode
and triggers an appropriate reload or a start action
> luci-app-adblock: sync with adblock 2.7.1

- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
"hostname" and "address" in interfaceconfig.lua are mismatched with
the strings in po/pot files, and their translations are not applied.
> luci-app-mwan3: Fix mismatched texts

- protocols/luci-proto-openconnect/luasrc/model/cbi/admin_network/proto_openconnect.lua
This depends on https://github.com/openwrt/packages/pull/4315
I plan to backport this also to lede-17.01 branch.
> luci-proto-openconnect: allow setting no_cert_check, password2, mtu

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
Currently there are only 2 encryption options visible for adhoc
mode. But in netifd, others are also supported and working as
expected. So adding WPA-PSK, WPA2-PSK and WPA-PSK/WPA2-PSK Mixed
mode as encryption options.
Signed-off-by: Kishan Gondaliya <kishanpgondaliya@gmail.com>
> luci-mod-admin-full: Enable adhoc mode encryption options

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/apcups.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/apcups.lua
- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
OpenWRT/LEDE support for APC UPSes is only partial: although the collectd apcups plugin is included, related lua/luci code is missing. These changes add the lua side and have been used for ~2 years, both on OpenWRT and LEDE.
Reworked from patches submitted by James Klaas to the luci development listin 2015.
EDIT: clarified text as requested.
> luci-app-statistics: add support for apcups plugin

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/alternative_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/power_off.htm
- applications/luci-app-advanced-reboot/po/templates/luci-app-advanced-reboot.pot
This luci-app allows owners of supported dual-partition routers to reboot to alternative partition. Owners of other supported devices can initiate power off from Web UI.
Compiled with SDK_ipq806x_17.01.2, tested on Linksys EA8500.
PS. Hannu, I've tried converting app tabs to spaces, as the other way around resulted in too much indentation. I hope this is satisfactory.
> luci-app-advanced-reboot: initial commit

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/apcups.lua
#1227 [luci-app-statistics: add support for apcups plugin](https://github.com/openwrt/luci/pull/1227)
The Voltage graph combines Battery, Input Voltage and Output Voltage.
The Y-Axis scale masks changes in Input/Output voltages over time.
This patch splits the graphs into 2 graphs.
This makes it possible to see variations in AC Input/Output voltages.
Signed-off-by: bobmseagithub <bobmseagithub@squakmt.com>
> luci-app-statistics: Voltage graphs - AC and DC

- applications/luci-app-mwan3/luasrc/view/mwan/advanced_diagnostics.htm
- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
Translation function is not used in "start", "stop", and "restart", and I modified them because the LuCI i18n-tools cannot be detected.
The parameter "task" is used for building the URL in update_status(), so I added a new parameter "task_name".
> luci-app-mwan3: Add translate strings in update_status()

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* fix interface default value on overview page
* fix re-ordering of wireless stations
> luci-app-travelmate: bugfixes

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_order.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* rework wireless station re-ordering code, now complete uci index
based, therefore no longer tied to a definite order of wifi-iface
sections
> luci-app-travelmate: rework wireless station re-ordering

- modules/luci-base/htdocs/luci-static/resources/xhr.js
Content-length and Connection should not be set in a JS request. Security issue when they are set. My browser throws two errors when they are set.
https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection
https://stackoverflow.com/questions/2623963/webkit-refused-to-set-unsafe-header-content-length
> luci-base: Remove request headers that are set automatically by browser

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
the slash leads to // redirecting to /. The redirecting causes problems
with CORS [1].
[1]: http://enable-cors.org/
> luci-app-attendedsysupgrade: remove leading slash

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/network.lua
This change is needed to support the new default 'auto' xfer_mode
setting.
> luci-mod-admin-full: add 'auto' xfer_mode to dsl configuration

- applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
This is mainly for ss_server section
> luci-app-shadowsocks-libev: hide key, password value in instance overview

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
Made 802.11r selection availible in AP-WDS mode
Signed-off-by: Anton Engelhardt anton@neednow.de
> [PATCH] luci-mod-admin-full: 802.11r AP-WDS mode enable

- applications/luci-app-attendedsysupgrade/Makefile
uhttpd-mod-ubus is missing on some devices where rpcd is installed.
the luci app fundamentally depends on /ubus
> luci-app-attendedsysupgrade: add missing dep

- modules/luci-base/Makefile
When the `/etc/config/ucitrack` is modified, it should not be overwritten when luci-base is upgraded.
> luci-base: add missing conffiles

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
add a keep-settings checkbox to the webview
this PR depends on [this][1] PR in openwrt/packages
[1]: https://github.com/openwrt/packages/pull/4689
> luci-app-attendedsysupgrade: add keep-settings opt

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
as reported [here][1] the board_name is not everywhere unified yet. to
solve this problem, the model name is transported as well and used as a
fallback identifier
[1]: https://github.com/aparcar/gsoc17-attended-sysupgrade/issues/26
> luci-app-attendedsysupgrade: send model info

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
now uses JSON.stringify instead of creating pseudo JSON data via
`'{' + variable + '}'`
also simplify uci naming
> luci-app-attendedsysupgrade: use JSON.stringify

- applications/luci-app-dnscrypt-proxy/Makefile
- applications/luci-app-dnscrypt-proxy/luasrc/controller/dnscrypt-proxy.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/cfg_dnsmasq_tab.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/configuration_tab.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
- applications/luci-app-dnscrypt-proxy/luasrc/view/dnscrypt-proxy/config_css.htm
- applications/luci-app-dnscrypt-proxy/luasrc/view/dnscrypt-proxy/logread.htm
- applications/luci-app-dnscrypt-proxy/luasrc/view/dnscrypt-proxy/res_options.htm
- applications/luci-app-dnscrypt-proxy/luasrc/view/dnscrypt-proxy/view_reslist.htm
- applications/luci-app-dnscrypt-proxy/root/etc/uci-defaults/60_luci-dnscrypt-proxy
to ease the dnscrypt-proxy configuration I've build this package, main features:
* full resolver list handling, incl. list refresh and  simple resolver selection per instance
* trigger support
* support the following (conditional) options:
- resolvers_list
- ephemeral_keys
- blacklist
- block_ipv6
- local_cache
- query_log_file
* complete dnscrypt & dnsmasq configuration in Advanced section
> luci-app-dnscrypt-proxy: new package

- applications/luci-app-dnscrypt-proxy/Makefile
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
* remove libustream-mbedtls dependency in makefile and check for
'libustream-ssl.so' in the app. (fix for #1310)
* add missing uclient-fetch dependency in makefile.
> luci-app-dnscrypt-proxy: fix ssl dependency

- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
- applications/luci-app-dnscrypt-proxy/po/ja/dnscrypt-proxy.po
- applications/luci-app-dnscrypt-proxy/po/templates/dnscrypt-proxy.pot
- Added translate() functions for some UI texts.
- Added po templates and po for Japanese translations.
> luci-app-dnscrypt-proxy: Add Japanese translation

- applications/luci-app-dnscrypt-proxy/po/ja/dnscrypt-proxy.po
- applications/luci-app-dnscrypt-proxy/po/templates/dnscrypt-proxy.pot
Updated Japanese translations.
> luci-app-dnscrypt-proxy: Update Japanese translation

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* supports a Connection Limit of '0',
to disable this feature (unlimited retries)
> luci-app-travelmate: sync with 0.9.3

- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/rules.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
- modules/luci-base/htdocs/luci-static/resources/cbi.js
- modules/luci-base/luasrc/cbi/datatypes.lua
Apart from changes related to luci-app-shadowsocks-libev, this pull request first tries to divide datatype `ipmask` into three sub types: `cidr`, `ipnet`, `ipaddr` and use `cidr` in `luci-app-shadowsocks-libev`
Other commits are mainly tweaks, bug fixes while adding `dst_forward_recentrst` option support.
> luci-app-shadowsocks-libev: support for option dst_forward_recentrst

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
re add lua code to handle content of acl.d/. This should enable users to
use the luci-app without having the full snapshot luci installed, e.g.
trying the app from 17.01.2
> luci-app-attendedsysupgrade: lua code for acl.d

- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/zh-cn/adblock.po
Fixed translations that commented out due to difference of letter-case
in msgid.
Related: #1361 
> luci-app-adblock: Fix commented out translations

- applications/luci-app-dnscrypt-proxy/luasrc/controller/dnscrypt-proxy.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/cfg_resolvcrypt_tab.lua
- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
* automatically transfer dnscrypt specific settings to dnsmasq as well,
This may change the values for 'noresolv', 'resolvfile',
'allservers' and the list 'server' settings (enabled by default)
* parse/show the resolver, Location, DNSSEC- and NOLOG-Flag
in the resolver select box
* make buttons for resolver list download & file creation
(resolv-crypt.conf) more descriptive & responsive
* ease the startup trigger handling
* add an edit tab for 'resolv-crypt.conf' in the 'Advanced' section
> luci-app-dnscrypt-proxy: major update

- applications/luci-app-dnscrypt-proxy/luasrc/model/cbi/dnscrypt-proxy/overview_tab.lua
* fix regex for resolver selection, bring back 'cs-*' and 'securedns' entries
> luci-app-dnscrypt-proxy: fix resolver selection

- applications/luci-app-fwknopd/root/usr/sbin/gen-qr.sh
In some cases, the missing quotation marks can cause error messages.  Although harmless, adding the quotation marks for correctness.
Signed-off-by: Jonathan Bennett <JBennett@Incomsystems.biz>
> Luci-app-fwknopd: add quotation marks to squash error

- applications/luci-app-fwknopd/root/usr/sbin/gen-qr.sh
The qrencode update in the packages repo includes a patch that
adds the --inline option.  We use that option to generate a
proper inline SVG image.
Signed-off-by: Jonathan Bennett <JBennett@Incomsystems.biz>
This PR depends on the qrencode update to 4.0.0.
> luci-app-fwknop: add inline option to qrencode usage

- applications/luci-app-minidlna/luasrc/model/cbi/minidlna.lua
- applications/luci-app-minidlna/po/ca/minidlna.po
- applications/luci-app-minidlna/po/cs/minidlna.po
- applications/luci-app-minidlna/po/de/minidlna.po
- applications/luci-app-minidlna/po/el/minidlna.po
- applications/luci-app-minidlna/po/en/minidlna.po
- applications/luci-app-minidlna/po/es/minidlna.po
- applications/luci-app-minidlna/po/fr/minidlna.po
- applications/luci-app-minidlna/po/he/minidlna.po
- applications/luci-app-minidlna/po/hu/minidlna.po
- applications/luci-app-minidlna/po/it/minidlna.po
- applications/luci-app-minidlna/po/ja/minidlna.po
- applications/luci-app-minidlna/po/ms/minidlna.po
- applications/luci-app-minidlna/po/no/minidlna.po
- applications/luci-app-minidlna/po/pl/minidlna.po
- applications/luci-app-minidlna/po/pt-br/minidlna.po
- applications/luci-app-minidlna/po/pt/minidlna.po
- applications/luci-app-minidlna/po/ro/minidlna.po
- applications/luci-app-minidlna/po/ru/minidlna.po
- applications/luci-app-minidlna/po/sk/minidlna.po
- applications/luci-app-minidlna/po/sv/minidlna.po
- applications/luci-app-minidlna/po/templates/minidlna.pot
- applications/luci-app-minidlna/po/tr/minidlna.po
- applications/luci-app-minidlna/po/uk/minidlna.po
- applications/luci-app-minidlna/po/vi/minidlna.po
- applications/luci-app-minidlna/po/zh-cn/minidlna.po
- applications/luci-app-minidlna/po/zh-tw/minidlna.po
This option was added to minidlna in version 1.2.0
and is set to no by default.
Signed-off-by: James Christopher Adduono <jc@adduono.com>
> luci-app-minidlna: add allow wide links option

- luci.mk
If you make a fresh build env the languages config tags `CONFIG_LUCI_LANG_*` are sometimes resorted in an undefined order.
I track my configuration with git this will mess my change tracking.
There are changes where no changes are!
This change will fix this
> luci.mk: sort languages in lexical order

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
Add local generation of PMK when using a PSK.
So 802.11r is easier to configure and no inter AP communication is needed any more.
Allow user to chose if use FT over DS protocol or FT over the Air protocol for Fast BSS Transition.
> luci-mod-admin-full: wifi.lua: ft_psk_generate_local and ft_over_ds

- applications/luci-app-upnp/luasrc/controller/upnp.lua
- applications/luci-app-upnp/luasrc/view/upnp_status.htm
Getting the Description data from upnp_lease_file. This data often displays the Application Name which made the upnp call. If the upnp_lease_file doesn't exist, it'll just return a blank entry under "Description".
upnp_lease_file order example: TCP:33333:192.168.0.100:33333:1485578298:NAT-PMP 33333 tcp
As an optimisation, since the upnp_lease_file has only active leases and is ordered by epoch timestamp (5th column above), and since "iptables --line-numbers -t nat -xnvL MINIUPNPD" has active leases and is also displayed in order of rule applied (time). This means the order of these two sources will be the same. This prevents us from "searching" the upnp_lease_file for every rule, and instead for the n'th rule, look at the n'th upnp_lease_file line. As a result we only need to read in one …
> luci-app-upnp: Adding and displaying "Description" to upnp data

- protocols/luci-proto-ipv6/luasrc/model/network/proto_4x6.lua
The dash '-' needs to be escaped by a '%', otherwise it will
be interpreted as minus, which means '0 or more repetitions'.
This fixes LEDE FS#1157.
> luci-proto-ipv6: fix patterns in proto_4x6.lua

- applications/luci-app-attendedsysupgrade/luasrc/view/attendedsysupgrade.htm
- applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/attendedsysupgrade.json
* now uses the new introduced rpcd call `ubus call rpc-sys packagelist`
https://git.lede-project.org/?p=project/rpcd.git;a=commit;h=4e483312b0216905cad11131270aaec76d7f5be4
* refactored the code and removed doubled server statuscode hadling (of "upgrade check" and "upgrade request")
* check for sufficient free memory before downloading image and verify correct checksum before flashing.
Once https://github.com/openwrt/packages/pull/5118 passes the sha256 could be checked as an alternative. 
Tested with x86/64 vm
> luci-app-attendedsysupgrade: v3

- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
Fixes [FS#1118](https://bugs.lede-project.org/index.php?do=details&task_id=1118)
Luci chokes on devices that do not have _iptables_ installed with:
```
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute firstchild dispatcher target for entry '/admin'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute function dispatcher target for entry '/admin/status'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute template dispatcher target for entry '/admin/status/overview'.
The called action terminated with an exception: …
```
> Fix bad argument #1 to 'tonumber'

- modules/luci-mod-admin-full/luasrc/view/admin_network/lease_status.htm
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
LuCI tries to match the DUID send via DHCPv6 to an existing mac adress to displays already available informations next to the DHCPv6 supplied hostname. It was initial intended to make it easy to spot misconfigured DHCPv6 clients.
Unfortunately the display logic doesn't work as I would expect in case the DUID can be matches to an already known MAC-Address:
- if the DHCPv6 hostname matches an already known hostname, the IPv4 address is show after the DHCPv4 hostname for no reason
- the already known hostname is displayed instead of the one send via DHCPv6
It makes it hard/impossible to spot issues like DHCPv4/DHCPv6 hostname mismatch or missing DHCPv6 hostname. Furthermore, it will claim that a specific hostname has an IPv6 Address where it doesn't (due to different send hostname).
Find …
> fix DHCPv6 hostname display

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/memberconfig.lua
- applications/luci-app-mwan3/po/ja/mwan3.po
- applications/luci-app-mwan3/po/templates/mwan3.pot
- applications/luci-app-mwan3/po/zh-cn/mwan3.po
- applications/luci-app-mwan3/po/zh-tw/mwan3.po
mwan3 accepts only 1-256 metric of member, if it is more, member is ignored.
This patch fix translations and allowed values of member metric input.
This is second part of issue https://github.com/openwrt/packages/issues/4428
> luci-app-mwan3: fix member metric allowed values

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
Added support for: Linksys EA3500 and ZyXEL NBG6817.
Added error reporting to both system log and WebUI on errors.
Tested on Linksys EA8500 by @stangri; on ZyXEL NBG6817 by @pkgadd.
Please back-port to current release tree.
> luci-app-advanced-reboot: 2 new routers + error reporting

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* add new extra options (disabled by default):
- Flush DNS Cache
- Email Notification
- Email Notification Count
> luci-app-adblock: sync with adblock 3.4.0

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/logread.htm
* LuCI: BSSID will be ignored by default in 'wireless add' dialog
* LuCI: Textarea 'autoscroll down' in logfile view
* LuCI: refine logfile search term
> luci-app-travelmate: sync with 1.0.1

- luci-app-wireguard/Makefile
- luci-app-wireguard/luasrc/controller/wireguard.lua
- luci-app-wireguard/luasrc/view/wireguard.htm
- luci-app-wireguard/po/ja/wireguard.po
- luci-app-wireguard/po/pt-br/wireguard.po
- luci-app-wireguard/po/sv/wireguard.po
- luci-app-wireguard/po/templates/wireguard.pot
- luci-app-wireguard/po/zh-cn/wireguard.po
This pulls the Wireguard status code for LuCI into 17.01 as well.
@danrl I hope this is OK for you? Since the other Wireguard bits made it into 17.01 as well I suppose there's no showstoppers for adding this to 17.01.
Signed-off-by: Stijn Segers <foss@volatilesystems.org>
> luci-app-wireguard: add LuCI Wireguard status to 17.01 as well

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
* refine status view
* add two missing eap auth variants
* small visual fixes
> luci-app-travelmate: sync with travelmate 1.0.2

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/network.lua
If no DSL SNR offset is set for the dsl line the first entry from the
dropdown list is pre-selected by default, which would apply a -10 db
offset by default.
Pre-select the 0 db option if nothing else is specified in the uci config
files.
Signed-off-by: Mathias Kresin <dev@kresin.me>
> luci-mod-admin-full: set 0 db DSL SNR offset by default

- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
* added support for new board names for ea8500 and nbg6817
* updated README
Tested on nbg6817 by @pkgadd, on ea8500 by @stangri.
PS. Please back-port to 17.01.x, as far as I understood @pkgadd, the new board names will be a part of the 17.01.5 release.
> luci-app-advanced-reboot: support for new board names for ea8500 and nbg6817

- applications/luci-app-dynapoint/luasrc/model/cbi/dynapoint.lua
- applications/luci-app-dynapoint/po/de/dynapoint.po
- applications/luci-app-dynapoint/po/ja/dynapoint.po
- applications/luci-app-dynapoint/po/pt-br/dynapoint.po
- applications/luci-app-dynapoint/po/ru/dynapoint.po
- applications/luci-app-dynapoint/po/templates/dynapoint.pot
Signed-off-by: Vladimir <picfun@ya.ru>
Corrected script: applications/luci-app-dynapoint/luasrc/model/cbi/dynapoint.lua
There was no translation - "Please install the package in the"
I put screenshots it was so:
now:
> fixed dynapoint.lua, there was no translation

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
Read registered IP from file, updated by ddns-scripts.
Only read from DNS if file does not exist or outdated (check_interval).
Require ddns-scripts v 2.7.7
> luci.app-ddns: Update to 2.4.9-1

- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/po/ru/travelmate.po
Signed-off-by: Vladimir <picfun@ya.ru>
There was no space:
Corrected, clarified the Russian text:
> luci-app-travelmate fixed

- applications/luci-app-mwan3/luasrc/view/admin_status/index/mwan.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_detail.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_diagnostics.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_interface.htm
- applications/luci-app-mwan3/luasrc/view/mwan/status_troubleshooting.htm
- applications/luci-app-mwan3/root/etc/uci-defaults/60_luci-mwan3
Service changes
- update uci track to call "/etc/init.d/mwan3 reload"
- Do not show interface status on Overview page if mwan3 is not global enabled
- Add hint if service is not enabled globally
Look and feel changes
- change look and fell interface status page
> luci-app-mwan3: add service hint

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
* add an option for the captive portal detection
* support the new signal quality treshold (default 30)
* small fixes
> luci-app-travelmate: sync with release 1.1.0

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
* refine timings & valid input ranges
> luci-app-travelmate: sync with release 1.1.2

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/po/it/adblock.po
- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/ru/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
- applications/luci-app-adblock/po/zh-tw/adblock.po
fix trivial 'msmtp' typo & changed .po files as well
> luci-app-adblock: fix frontend typo

- contrib/package/community-profiles/files/etc/config/profile_potsdam
I know there was a recently PR #1634 on this profile, but there was an ongoing discussion about "fixed" SSID's. Finaly we came to a conclusion, so here is a new PR withe only a ssid change.
Commit message:
```
community-profiles: potsdam - changed SSID
After some discussion in our meetings and on the maling list we decided to
change the SSID to a fixed one.
Signed-off-by: Hannes Fuchs <hannes.fuchs@gmx.org>
```
> community-profiles: potsdam - changed SSID

- applications/luci-app-adblock/po/it/adblock.po
- applications/luci-app-adblock/po/ja/adblock.po
- applications/luci-app-adblock/po/pt-br/adblock.po
- applications/luci-app-adblock/po/ru/adblock.po
- applications/luci-app-adblock/po/sv/adblock.po
- applications/luci-app-adblock/po/templates/adblock.pot
- applications/luci-app-adblock/po/zh-cn/adblock.po
- applications/luci-app-adblock/po/zh-tw/adblock.po
XHTML markup of "&" in the description about "download queue" was fixed
in 71230d2. Since UI text of it no longer matches msgid, I fixed it.
> luci-app-adblock: fix the msgid to keep the translations

- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
* remove unofficial 'WPA2' enc. token for better compatibility with
certain QR code reader, still 'WPA', 'WEP' and 'nopass' are supported
* add WEP key slot support (not really needed, but it's still
supported by LuCI wireless)
* correct escape single quotes and other special chars
in SSID & passwords
* code cleanup
> luci-app-travelmate: fixes for new QR code template

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/apcups.lua
Some graph definitions rely on data not supported across all APC UPSes.
Due to recent upstream changes in collectd, the daemon no longer creates
a NaN-filled .rrd file corresponding to any missing UPS data. Depending
on the connected UPS, this may result in some "broken" graphs on the Luci
Statistics page since rrdtool cannot find the expected .rrd file.
These changes determine the UPS data available at runtime and update any
definitions of graphs to include only supported data. For example, the
chart stack of AC input and output voltages will normally be broken if
the UPS only measures AC input voltage. With these changes, the output
voltage graph definition is stripped out, allowing the chart to render.
This also includes some cleanup of code and graph definitions.
Signed-off-by: Tony …
> [RFC] luci-app-statistics: only graph data supported by APC UPS

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
Reads the header X-Unknown-Package offered by the sysupgrade server and
shows it in the error message.
Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>
> luci-app-attendedsysupgrade: show unknown package

- applications/luci-app-attendedsysupgrade/root/etc/uci-defaults/40_luci-attendedsysupgrade
- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
when installing the luci app and opening it for the first time the
webinterface shows an error as some freshly installed rpcd calls are not
yet available. The reload fixes the problem.
luci-app-attendedsysupgrade: downloadable image
the creted sysupgrade image can now easily be downloaded via web
interface.
also fixed some </br> to <br />
Signed-off-by: Paul Spooren <spooren@informatik.uni-leipzig.de>
> luci-app-attendedsysupgrade: reload rpcd fix #1668

- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
* forthcoming qrencode version will remove the short option "-I"
for inline, to get prepared switch to normal qrencode
command line parameters.
> luci-app-travelmate: remove qrencode short options

- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/main.lua
Modify the default setting of compression to match the default
value of the package ocserv.
Signed-off-by: Raymond Tau <raymondtau@gmail.com>
> luci-app-ocserv: match default value of compression

- applications/luci-app-firewall/luasrc/view/firewall/cbi_addrule.htm
- applications/luci-app-firewall/luasrc/view/firewall/cbi_addsnat.htm
- modules/luci-base/luasrc/view/cbi/browser.htm
- modules/luci-mod-admin-full/luasrc/view/admin_system/flashops.htm
luci-app-firewall: only show SNAT template if there are more then one zone
luci-app-firewall: on forward rule change pre-selection to wan
luci-app-firewall: only show portforward template if there are more then one zone
luci-mod-admin-full: add hint on backup restore that there will not be a factory reset before
luci-base: fix browser.htm template icon view if "cbi_init()" is not called no icon will be found
> luci-app-firewall/luci-base/luci-mod-admin-full: some fixes and improvements

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
* fix function calls that have an implicit extra parameter self,
pre-requisite for PR #1681
> luci-app-adblock: fix function calls

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
* fix function calls that have an implicit extra parameter self,
pre-requisite for PR #1681
> luci-app-travelmate: fix function calls

- applications/luci-app-wifischedule/luasrc/model/cbi/wifischedule/wifi_schedule.lua
* fix function calls that have an implicit extra parameter self,
pre-requisite for PR #1681
> luci-app-wifischedule: fix function calls

- applications/luci-app-travelmate/Makefile
- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
* made qrencode support optional (remove hardcoded dependency)
* add a conditional QR Code button on overview page,
remove separate "QR Codes" tab
* move trigger timeout setting to extra section
> luci-app-travelmate: final frontend changes for 18.x

- modules/luci-base/luasrc/util.lua
* enhance the checklib function in util.lua to check the 'fullpathexe'
as well, e.g. this fixes runtime errors on the dhcp/dns template in
environments without dnsmasq
> luci-base/util.lua: enhance checklib function 

- applications/luci-app-wireguard/Makefile
Installing luci-app-wireguard should also install luci-proto-wireguard, to have it as an protocol for interface setup.
Signed-off-by: Sven Roederer <devel-sven@geroedel.de>
> wireguard: add dependency to luci-proto-wireguard

- modules/luci-base/luasrc/view/cbi/tblsection.htm
If the table is empty the colspan is wrong!
Add an additional element will fix this.
> luci-base: add missing colspan in tblsection if table is empty

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
* made the "ignore bssid" flag conditional to ease connection to hidden networks:
* default for hidden networks "disabled"
* default for all others "enabled"
> luci-app-travelmate: made "ignore bssid" flag conditional

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/apcups.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/apcups.lua
- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
OpenWRT/LEDE support for APC UPSes has been partial, including only the collectd
apcups plugin. The related lua code has been developed on `lede-17.01` and added
to `master` over several months, and this change backports those improvements.
Signed-off-by: Tony Ambardar <itugrok@yahoo.com>
Tested-on: LEDE-17.01.4 / ar71xx / UPS: Back-UPS ES_650
@hnyman I've taken the liberty of following up on this [conversation](https://github.com/openwrt/luci/pull/1653#issuecomment-373888724) from #1653 and proposing the backport PR. The commits are all straight cherry-picks, and the resulting affected code is identical between `master` and `lede-17.01` branches.
For reference, pinging @bobmseagithub and @stephengeorgewest as interested parties, and noting this change addresses #1412 on LEDE stable.
Kind …
> luci-app-statistics: backport completed support for apcups plugin

- applications/luci-app-fwknopd/Makefile
- applications/luci-app-fwknopd/root/etc/uci-defaults/40_luci-fwknopd
Maintainer: @jp-bennett 
Since its initial inclusion in `lede-17.01`, package `luci-app-fwknopd` suffers from a bug which wipes existing credentials (key/hmac) on upgrade, and may result in loss of remote access for users.  This change backports the simple fix from `master`. Thanks for reviewing!
Tested on: LEDE 17.01.4 / ar71xx
> luci-app-fwknop:  backport a check to not overwrite user configured keys

- modules/luci-base/luasrc/model/network.lua
* fix wrong private function call to handle
section id as parameter (fix for #1687)
> luci-base/network.lua: fix get_interface function

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
* b00b676 fixed the cbi initialization for SimpleForm, therefore bring
back "Ignore BSSID" flag with dependent input field
> luci-app-travelmate: bring back cbi element to wifi_add.lua

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/dhcp.lua
The value of cachesize is hardcoded to 10000 in
dnsmasq-2.79/src/option.c to 10000 max
case 'c':  /* --cache-size */
{
int size;
if (!atoi_check(arg, &size))
ret_err(gen_err);
else
{
/* zero is OK, and means no caching. */
if (size < 0)
size = 0;
else if (size > 10000)
size = 10000;
daemon->cachesize = size;
}
break;
}
Tested on Netgear R7800
Signed-off-by: Marc Benoit <marcb62185@gmail.com>
> luci-mod-admin-full: limit dns cachesize to 10000

- contrib/package/community-profiles/files/etc/config/profile_berlin
- contrib/package/community-profiles/files/etc/config/profile_cottbus
- contrib/package/community-profiles/files/etc/config/profile_potsdam
- contrib/package/community-profiles/files/etc/config/profile_tulumlibre
See issue openwrt/luci#1757
Signed-off-by: Perry Melange <isprotejesvalkata@gmail.com>
> Removed retired nameserver 213.73.91.35 from the Freifunk profiles

- applications/luci-app-pagekitec/Makefile
- applications/luci-app-pagekitec/luasrc/controller/pagekitec.lua
- applications/luci-app-pagekitec/luasrc/model/cbi/pagekitec.lua
- applications/luci-app-pagekitec/po/templates/pagekitec.pot
- applications/luci-app-pagekitec/root/etc/uci-defaults/40_luci-pagekitec
Adds a simple interface to the basic functionality of pagekite services.
Signed-off-by: Karl Palsson <karlp@tweak.net.au>
Note: I'm not sure I've setup the i18n correctly.  I used i18n-scan to generate po/template/pagekite.pot, is there anything else that should happen?
> luci-app-pagekitec: new package

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua
Adds the option to configure IGMP snooping on a bridge. An useful addition for people with IPTV, since IGMP snooping is disabled by default in OpenWrt/Lede.
> luci-mod-admin-full: add igmp snooping option

- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_l2tp.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_ppp.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoa.lua
- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoe.lua
If there is no translation set, then on the material theme the dropdown
selection is displaced. To fix this add an translation to this dropdown.
The commit also changes source code whitespace shifting.
> luci-proto-ppp: add translation to ipv6 handling

- modules/luci-base/root/etc/config/ucitrack
If log configuration get changed in uci system no new values are applied
until reboot. Add /etc/init.d/log reload to exec option will solve this
issue.
> luci-base: reload log on uci system change

- applications/luci-app-upnp/luasrc/model/cbi/upnp/upnp.lua
Change default leasefile hint from /var/log/upnp.leases to
/var/run/miniupnpd.leases
> luci-app-upnp: change leasefile location hint

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
* archive sub-categories (shalla & ut_capitole) are now configurable
via LuCI CBI template
* small bugfixes & enhancements
> luci-app-adblock: sync with adblock 3.5.2

- modules/luci-base/luasrc/model/network.lua
@jow-   Need you opinion on this. I am not sure how expensive the extra call to iwinfo is here.
Show the correct wifi chip identification in case iwinfo recognises the chip.
So far the wifidev.get_i18n function has practically always returned just "Generic", but use iwinfo.hardware_name to fetch the name.
In case the default "Generic MAC80211" is returned from iwinfo, use just "Generic" to avoid double 80211 in the final string.
----
Until now, the network/wireless page has shown the correct ID, but the frontpage overview has shown just "Generic mac80211...".
References:
* iwinfo returns "Generic MAC80211" by default, leading into a need of polishing the output a bit. https://git.openwrt.org/?p=project/iwinfo.git;a=blob;f=iwinfo_nl80211.c;h=de5d2b4baabb3772d2a0ea70915a33ec667dabb1;hb=HEAD# …
> luci-base: show wifi chip identification on overview

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
@dibdot Following our discussion in #1659, I'd like to propose backporting this nearly year-old change from `master`. It helps improve consistency across HW for the GUI, and exposes a widely used security feature for easier use. 
Based on my own non-Luci usage and the [comments](https://github.com/openwrt/luci/pull/1140#issuecomment-298299068) from PR #1140, the capability has been available in mac80211 for a few years now.
Tested on: LEDE-17.01.4 / ar71xx
> luci-mod-admin-full: backport add missing "isolate" option for mac80211

- modules/luci-base/luasrc/dispatcher.lua
http.getenv("SCRIPT_NAME") fail if it's not provided. This can happen in the login screen when we don't have any script to load.
@jow- still a security flaw? 
> luci-base: fix dispacher fail

- applications/luci-app-lxc/Makefile
- applications/luci-app-lxc/luasrc/controller/lxc.lua
- applications/luci-app-lxc/luasrc/model/cbi/lxc.lua
- applications/luci-app-lxc/luasrc/view/lxc.htm
I've tried to get the lxc app in a more usable state. Tested with mips
and amd64 targets.
* fix missing tar/xz dependency,
only if LXC_BUSYBOX_OPTIONS is not selected
* mute needless gpg validation warning
* tidy up controller a little bit
* fix multiple possible dispatcher errors
* fix compatibility with XHTML standard theme (looks still horrible ;-)
* inform the user about custom kernel prerequisites
* inform the user about the template download
* inform the user if no template was found
Should fix #1762 and other complains in forum / package repo.
> luci-app-lxc: fix "plain-vanilla" integration

- applications/luci-app-firewall/luasrc/model/cbi/firewall/zones.lua
@nbd168 @jow- 
comments, please.
Is it sensible to expose the offloading options in LuCI?
I noticed on forum discussion that some people have even tried to make over-complex special LuCI apps for controlling the offloading, but now that the feature is in the normal firewall uci config in /etc/config/firewall, I see no need for a special LuCI app just for that.
Please give feedback if there should be more explanations or the proposed ones should be changed.
I did not try to craft kernel version (or offloading support) detection logic, but simply exposed the two options while mentioning that kernel 4.14 is required.
> luci-app-firewall: expose flow offloading options

- applications/luci-app-lxc/luasrc/controller/lxc.lua
- applications/luci-app-lxc/luasrc/model/cbi/lxc.lua
- applications/luci-app-lxc/luasrc/view/lxc.htm
I've tried to get the lxc app in a more usable state. Tested with mips
and amd64 targets.
* check /etc/config/lxc in controller, not in cbi
* more controller cleanups
* remove unused 'fork_exec' function
* check path before container creation
* check space requirements before container creation
* support new uci options 'min_space' and 'min_temp',
default for both is 100000 KB
* both options are configurable via LuCI CBI template
* write messages to log in case of an error
* validate the container name during creation,
automatically remove invalid chars
* inform the user that only a stopped container can be destroyed
* add experimental ssl support (untested, disabled by default)
> luci-app-lxc: fix "plain-vanilla" integration, part 2

- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
Referring to this, #1698 , we add architecture info and we show Unknown instead of ?. This is usefull if someone needs to install opkg packages manually.
> luci-admin-full: add architecture info

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Tested: TL-Archer-C7v2 OpenWrt 18.06(head)
Description: LuCI updates to support openwrt/packages#6147
> [openwrt-18.06] luci-app-unbound: provide transparent defaults with documentation

- applications/luci-app-lxc/luasrc/controller/lxc.lua
- applications/luci-app-lxc/luasrc/view/lxc.htm
* migrate JS generated HTML tables to divs
* remove (most of) the inline styles
* various markup cleanups
That's the final part ... hopefully it's now in a  more usable &
maintainable state.
> luci-app-lxc: fix "plain-vanilla" integration, part 3

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/controller/ddns.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/hints.lua
- applications/luci-app-ddns/luasrc/model/cbi/ddns/overview.lua
- applications/luci-app-ddns/luasrc/tools/ddns.lua
Every request directed to the ddns app call ddns tools module.
Ddns tools module have lots of global variable that call slow os.execute function. This adds 10 second to every ddns request even if the function that is requested doesn't need that global variable. This commit introduce env_info function that execute os.execute command by executing what is actually requested and not process all the variables. Also remove 2 unecessary module that are not used. More researh find that major slowdown was caused by the calling of ddns script for the version check. Now we check if opkg is present and use it to check ddns-scripts version.
> luci-app-ddns: improve performance

- applications/luci-app-ddns/Makefile
- applications/luci-app-ddns/luasrc/model/cbi/ddns/detail.lua
Currently this param that should be optional but is required for any configuration. We add an "optional" value to validate function so that we can make this pram optional as it should be.
> luci-app-ddns: make param opt, optional

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
* use now CSS for non breaking spaces in div table header
> luci-app-adblock: partly revert last commit

- applications/luci-app-ddns/luasrc/controller/ddns.lua
DDns script call another sh script to check ddns-scripts version. We can use the quicker IPKG.info function instead of execute another slow command.
@hnyman 
> luci-app-ddns: use standard pkg info function

- collections/luci-nginx/Makefile
- collections/luci-ssl-nginx/Makefile
- collections/luci-ssl-openssl-nginx/Makefile
Permit to remove uhttpd dep if nginx package is selected
@jow-  any idea why i have this? By testing it the dep works correctly
(by unselecting nginx, uhttpd gets selected and viceversa)
```
Collecting package info: done
tmp/.config-package.in:40035:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:40035:   symbol PACKAGE_luci is selected by PACKAGE_luci-ssl
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:40072:   symbol PACKAGE_luci-ssl depends on PACKAGE_uhttpd
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive …
```
> luci-nginx: add nginx metapackages

- applications/luci-app-firewall/po/uk/firewall.po
- modules/luci-base/po/uk/base.po
"Content-Type: text/plain; charset=UTF-8" was wrote twice in each
of base.po and firewall.po, and one was an incorrect place which
was the cause of the errors.
And, The escape in abbr HTML tag was incorrect, so I fixed it.
> i18n: fix syntax errors in Ukrainian po

- collections/luci-nginx/Makefile
- collections/luci-ssl-nginx/Makefile
- collections/luci-ssl-openssl-nginx/Makefile
This adds nginx-mod-luci as a dependency of this package.
@hnyman 
> luci-nginx: add nginx support file

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_system/admin.lua
If you delete all ssh keys in the textarea then LuCI will rais an error.
So if you added one ssh-key to the textarea and then you want to delete them
again that is not possbile in LuCI.
To fix this remove "rmempty" attribute and add a remove function which will
called if the textarea is empty.
This should fix https://github.com/openwrt/luci/issues/668
> luci-mod-admin-full: fix empty SSH-Keys textarea issue

- modules/luci-mod-admin-full/luasrc/controller/admin/network.lua
With e5ba594d77eed77d31d4b9b8c0e86026eb5a5fac the list of the connected device broke up. This fix this problem by creating a proper request link.
@jow- bug.
> luci-mod-admin-full: fix missing wifi_assoclist

- applications/luci-app-lxc/luasrc/controller/lxc.lua
- applications/luci-app-lxc/luasrc/model/cbi/lxc.lua
- applications/luci-app-lxc/luasrc/view/lxc.htm
* backingstore support via ubus does not work, remove it for now
* fix target mapping for linuximages.org
* cosmetics
> luci-app-lxc: small fixes & cosmetics

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
Attempting to do a diagnostic ping in mwan3 fails for interfaces that are aliased, such as @wan6 is to @wan.
Code is courtesy of @jow- (thank you) and tested & slightly fixed by myself. Issue #1918
@feckert
> luci-app-mwan3: fix aliased interfaces (@wan6)

- protocols/luci-proto-wireguard/luasrc/model/cbi/admin_network/proto_wireguard.lua
For wireguard it would be handy to have a description field, especially when you have many peers.
Signed-off-by: Robert Walli <rwalli@gmx.net>
> luci-proto-wireguard: description field

- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoe.lua
The host_uniq tag setting is supported by uci since CC15. It is actually the only setting that is not available within LuCi to support full internet service setup for some ISP to be completed by webui only.
The PPPoE RFC provide no upper bound to tag length, so its field datatype is unlimited length hex-encoded bytes string.
Signed-off-by: Luca Piccirillo <luca.piccirillo@gmail.com>
> luci-proto-ppp: expose pppoe host_uniq tag setting

- modules/luci-base/root/etc/config/ucitrack
Default behaviour of changes to fstab (Mount Points) was
to use /etc/init.d/fstab restart, however this unmounts
filesystems via block umount which can cause the device
to fail, so replace the initscript call with an exec
of 'block mount'.
> luci-base: Avoid block umount on fstab apply

- modules/luci-base/po/ru/base.po
Add missing translations and update existing not quite correct translations.
Replaced hyphens on em dashes where it is required by the Russian rules.
> luci-base: update and improve Russian translation

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/view/simple-adblock/status.htm
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Built with mvebu 18.06.0-rc1 SDK, tested on mvebu 18.06.0-rc2.
Can this be backported to 18.08.0 please?
> luci-app-simple-adblock: new start/stop button, better integration with simple-adblock

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/alternative_reboot.htm
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/power_off.htm
Added ```important``` styling to buttons to be consistent with the new styling/reboot page.
Backport to 18.06 please.
> luci-app-advanced-reboot: change style of buttons to important

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
Added ```important``` styling to buttons to be consistent with the new styling.
Backport to 18.06 please.
> luci-app-simple-adblock: change style of button to important

- protocols/luci-proto-ncm/luasrc/model/cbi/admin_network/proto_ncm.lua
The default seting should be none.
Most modems have persistent mode setting that is stored in internal flash.
If option mode is unset the default modem setting is used.
If we choose some mode, then on every connection we write to modem flash.
In the current state we can't disable that from LuCI.
Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>
> luci-proto-ncm: remove mode 'auto' as default

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simpleadblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Uhm, dunno what to say, my bad, extra controller file wasn't deleted when I sent the previous PR. Still learning.
And still, please back-port to 18.06.
Again, sorry to be creating extra burden so close to release.
> luci-app-simple-adblock: remove extra controller file

- protocols/luci-proto-ncm/luasrc/model/cbi/admin_network/proto_ncm.lua
This removes all options 100% unrelated to NCM protocol.
Some options like 'dns' are not currently used by connection scripts,
but may be used in the future.
Signed-off-by: Dmitry Tunin <hanipouspilot@gmail.com>
> luci-proto-ncm: remove unrelated options

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/blacklist_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/configuration_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/whitelist_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/blocklist.htm
- applications/luci-app-adblock/luasrc/view/adblock/logread.htm
- applications/luci-app-adblock/luasrc/view/adblock/query.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
backend:
* add low priority mode (nice level 10), disabled by default
* enhance 'Force DNS' to redirect ports 53, 853 and 5353
frontend:
* switch to dynamic XHR polling for runtime information and logfile
viewing
* add new 'Refresh' button to reload blocklists
* various cleanups & small fixes
> luci-app-adblock: sync with adblock 3.5.4

- modules/luci-base/po/pl/base.po
Updated Polish translations.
@jow- @musashino205 
I have a question to you. In commit https://github.com/openwrt/luci/commit/86660f92d12b963a05118a8f9471513a18773be4 and https://github.com/openwrt/luci/commit/524ce90c4e22dcb64ac8e6c2e012eb54cd5f098e, you have added "Alias interface" and "Alias Interface". Should there be almost identical expressions here?
Signed-off-by: Krystian Kozak <krystian.kozak20@gmail.com>
> luci-base: update Polish translation

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Change "master" to "openwrt-18.06" in help link.
> [openwrt-18.06] luci-app-unbound: point documentation to 18.06 branch

- contrib/package/freifunk-common/files/usr/sbin/ff_olsr_watchdog
When OLSRd crashes, the old tunnels still exist.  This can lead to unexpected behaviour.
The tunnels to be removed start with "tnl_"
See freifunk-berlin/firmware#522
> ff_olsr_watchdog: delete stale tunnels

- applications/luci-app-samba4/Makefile
- applications/luci-app-samba4/luasrc/controller/samba4.lua
- applications/luci-app-samba4/luasrc/model/cbi/samba4.lua
- applications/luci-app-samba4/po/ca/samba4.po
- applications/luci-app-samba4/po/cs/samba4.po
- applications/luci-app-samba4/po/de/samba4.po
- applications/luci-app-samba4/po/el/samba4.po
- applications/luci-app-samba4/po/en/samba4.po
- applications/luci-app-samba4/po/es/samba4.po
- applications/luci-app-samba4/po/fr/samba4.po
- applications/luci-app-samba4/po/he/samba4.po
- applications/luci-app-samba4/po/hu/samba4.po
- applications/luci-app-samba4/po/it/samba4.po
- applications/luci-app-samba4/po/ja/samba4.po
- applications/luci-app-samba4/po/ms/samba4.po
- applications/luci-app-samba4/po/no/samba4.po
- applications/luci-app-samba4/po/pl/samba4.po
- applications/luci-app-samba4/po/pt-br/samba4.po
- applications/luci-app-samba4/po/pt/samba4.po
- applications/luci-app-samba4/po/ro/samba4.po
- applications/luci-app-samba4/po/ru/samba4.po
- applications/luci-app-samba4/po/sk/samba4.po
- applications/luci-app-samba4/po/sv/samba4.po
- applications/luci-app-samba4/po/templates/samba4.pot
- applications/luci-app-samba4/po/tr/samba4.po
- applications/luci-app-samba4/po/uk/samba4.po
- applications/luci-app-samba4/po/vi/samba4.po
- applications/luci-app-samba4/po/zh-cn/samba4.po
- applications/luci-app-samba4/po/zh-tw/samba4.po
Maintainer: me
Compile tested: arm/mips (master)
Run tested: arm/mvebu (master)
Description:
Its the updated luci-ui for this PR openwrt/packages#5563.
Basically just a copy from the latest `luci-app-samba`, with some added extra options for samba 4 and changed deps/names.
> luci-app-samba4: add new application

- applications/luci-app-transmission/luasrc/model/cbi/transmission.lua
There are exists several custom web ui for transmission. Such as:
https://github.com/ronggang/transmission-web-control
https://github.com/Secretmapper/combustion
https://github.com/fcsonline/react-transmission
But for now there are no way to use custom ui without editing `init.d` script.
> luci-app-transmission: Allow user to define custom web interface

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_firewall_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_network_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/cfg_wireless_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/configuration_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/ap_qr.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/logread.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/stations_backup.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* Runtime Information, Logview and Station Overview are now dynamically
updated via XHR poll
* New runtime information for "Faulty Stations" (Travelmate backend will
no longer rename faulty uplinks)
* Add a new "Restart" button to reset "Faulty Stations" information and
trigger a Travelmate restart
* In Stations overview the currently used uplink is emphasized in blue,
faulty uplinks in red
* Numerous cleanups (e.g. space=>tab indentation) and other small fixes
example screenshots:
> luci-app-travelmate: sync with travelmate 1.2.1

- modules/luci-base/Makefile
fix compilation failure when luasrcdiet is being copied to non existing directory
> fix compilation failure when luasrcdiet is being copied to non existing directory

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/runtime.htm
during intense testing with different browsers (Chrome/Firefox/partly IE
in a VM) I found & fixed some more minor things:
* re-add accidently removed "apply_on_parse" attribute in overview cbi
* fixed a corner case where the "Restart" button not works correctly
* Removed leftovers from last commit
> luci-app-travelmate: "final" fixes

- modules/luci-base/luasrc/view/cbi/apply_widget.htm
- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
This patch corrects "to get" to "to be" in apply_widget.htm
This shell command was used to find and make the change in
all impacted files:
find . -type f -exec sed -i 's/Waiting for configuration to get applied/Waiting for configuration to be applied/g' {} +
Signed-off-by: Gregory L. Dietsche <gregory.dietsche@cuw.edu>
> Correct grammar in apply_widget.htm

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
This rename style.css to casade.css (like the other themes) and fix the css to display the header even in the applyreboot page
> luci-theme-material: fix theme for applyreboot page changes

- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
- modules/luci-mod-admin-full/luasrc/view/admin_system/flashops.htm
- modules/luci-mod-admin-full/luasrc/view/admin_system/upgrade.htm
* allow 'forced' firmware upgrades, even if the image format check fails. Useful where flashing back to the OEM versions or switching between ar71xx and ath79 builds
* option is only visible after first/failed image check
* added warning info (see screenshots below)
> luci-mod-admin-full: allow forced upgrade (revised)

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
Most OpenWrt applications do not have a colon in input headers.
This has been explained in #1566 as well.
This commit removes the said colons.
> luci-app-unbound: Colons removed from input headers

- applications/luci-app-nut/Makefile
- applications/luci-app-nut/luasrc/controller/nut.lua
- applications/luci-app-nut/luasrc/model/cbi/nut_cgi.lua
- applications/luci-app-nut/luasrc/model/cbi/nut_monitor.lua
- applications/luci-app-nut/luasrc/model/cbi/nut_server.lua
- applications/luci-app-nut/root/etc/uci-defaults/40_luci-nut
Adds app to configure NUT (Network UPS Tools), including
nut-server, nut-monitor, and nut-cgi.
All good and ready to go; works with current package in 18.06 as well as the updates I've done.
> luci-app-nut: Add support for NUT configuration

- applications/luci-app-samba4/luasrc/model/cbi/samba4.lua
- applications/luci-app-samba4/po/ca/samba4.po
- applications/luci-app-samba4/po/cs/samba4.po
- applications/luci-app-samba4/po/de/samba4.po
- applications/luci-app-samba4/po/el/samba4.po
- applications/luci-app-samba4/po/en/samba4.po
- applications/luci-app-samba4/po/es/samba4.po
- applications/luci-app-samba4/po/fr/samba4.po
- applications/luci-app-samba4/po/he/samba4.po
- applications/luci-app-samba4/po/hu/samba4.po
- applications/luci-app-samba4/po/it/samba4.po
- applications/luci-app-samba4/po/ja/samba4.po
- applications/luci-app-samba4/po/ms/samba4.po
- applications/luci-app-samba4/po/no/samba4.po
- applications/luci-app-samba4/po/pl/samba4.po
- applications/luci-app-samba4/po/pt-br/samba4.po
- applications/luci-app-samba4/po/pt/samba4.po
- applications/luci-app-samba4/po/ro/samba4.po
- applications/luci-app-samba4/po/ru/samba4.po
- applications/luci-app-samba4/po/sk/samba4.po
- applications/luci-app-samba4/po/sv/samba4.po
- applications/luci-app-samba4/po/templates/samba4.pot
- applications/luci-app-samba4/po/tr/samba4.po
- applications/luci-app-samba4/po/uk/samba4.po
- applications/luci-app-samba4/po/vi/samba4.po
- applications/luci-app-samba4/po/zh-cn/samba4.po
- applications/luci-app-samba4/po/zh-tw/samba4.po
* add macOS compatibility option
* adds Apple Timemachine support
* dynamically disable invalid options
depends on openwrt/packages#6772
> luci-app-samba4: add macOS and Apple Timemachine support

- modules/luci-base/luasrc/sys.lua
- modules/luci-mod-admin-full/luasrc/controller/admin/system.lua
- modules/luci-mod-admin-full/luasrc/view/admin_system/flashops.htm
This commit add the feature that allow user to backup the image of the flash.
> Backup: add firmware backup for mtdblock devices

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
* minimal fix to bring back openvpn config creation based on
openvpn_recipes template, fix for #2146
> luci-app-openvpn: fix template based config creation

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
This fixes LuttyYang/luci-theme-material#48
> luci-theme-material: Monospace font for textarea elements

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/custom.css
The var() css function can be used to insert the value of a custom property.
A custom.css file is added to change the colors. This file will get included
in the cascade.css file.
The following colors could be costomized in the file costom.css.
--header-bg
--header-color
--menu-bg-color
--menu-color
--submenu-bg-hover
--submenu-bg-hover-active
> luci-theme-material: make colors configurable

- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/ifaces.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/vlan.lua
*	uci:get replaced with direct access of value (functions has 3x better performance in that way)
Signed-off-by: Darius Joksas <jok.darius@gmail.com>
> luci-mod-admin-full: performance fix

- applications/luci-app-unbound/luasrc/controller/unbound.lua
This adds in the State tab a new option to dump cache from unbound-control application
> luci-app-unbound: add cache_dump tab

- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
Several devices have multiple upstream interfaces, for example a fixed
and a mobile broadband connection. Currently, only one upstream
interface is shown per address family in Luci. So in my example, one of
the interfaces would not appear on the Status-page.
This PR introduces support for showing multiple upstream interfaces on
the Status-page. The code is not very complicated. get_status_by_route()
has been extended to return a list of all routes, and
get_wannet()/get_wan6net() now returns all upstream interfaces.
I could not find any other (active) users of these three functions than
calls triggered from the Status-page, so changing the default behavior
should be fine. get_wandev()/get_wan6dev() called get_status_by_route(),
but I could not find any place where those functions were …
> luci-base: Show multiple upstream interface

- applications/luci-app-snmpd/Makefile
- applications/luci-app-snmpd/luasrc/controller/snmpd.lua
- applications/luci-app-snmpd/luasrc/model/cbi/snmpd.lua
Imported from https://github.com/remakeelectric/owrt_pub_feeds/tree/master/luci-app-snmpd
Only provides configuration of basic authentication and system level
options, not even close to the entire slew of options that net-snmp
supports, but the basics are still helpful, and a base for future work.
> luci-app-snmpd: Basic net-snmpd config options

- modules/luci-mod-network/luasrc/controller/admin/network.lua
If we add a new wifi-iface to the config then the iface will start at once.
But normaly we would configure the wireless security in the next step.
So do not start wifi iface on add.
> luci-mod-network: disable wifi config on new wifi-iface add

- applications/luci-app-wireguard/luasrc/controller/wireguard.lua
- applications/luci-app-wireguard/luasrc/view/wireguard.htm
* add optional QR Code support to status page (per wg Interface),
submitted information via QR code are:
- [Interface] (list of) Address / PrivateKey
- [Peer] Endpoint / PublicKey / (list of) AllowedIPs
- support multiple interfaces and peers
* fix XHTML rendering errors with OpenWrt standard theme
* fix logical glitch with empty descriptions, remove needless variables
* left align the output for better viewing esp. with material theme
* freshen up design a little bit
* switch space indentation to tabs
> luci-app-wireguard: add QR Code support plus fixes

- applications/luci-app-snmpd/luasrc/model/cbi/snmpd.lua
AgentX support doesn't actually require TCP, it also works over unix
domain sockets, and UDS is the only method that's compiled in by
default.  Remove that misleading text, and make the section
add/removable so that you can remove it to disable agentx support.
Behaviour with multiple sections is undefined. (don't do that!)
This matches the current behaviour of the snmpd init script, which will
enable agentx with the compile time default settings if the agentx
socket config is blank/missing.
> luci-app-snmpd: Allow turning off agentx

- contrib/package/community-profiles/files/etc/config/profile_berlin
- contrib/package/community-profiles/files/etc/config/profile_cottbus
- contrib/package/community-profiles/files/etc/config/profile_potsdam
- contrib/package/community-profiles/files/etc/config/profile_tulumlibre
The new nameserver has been choosen from www.fdn.fr/actions/dns
> freifunk profiles: add nameserver 80.67.169.40

- modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
It's completely OK to select a bridge as the underlying interface of
other interfaces, say a tunnel or PPPoE. The only case which should be
forbidden is bridge over bridge.
> luci-mod-network: show bridges in ifacelist when the interface itself is not a bridge

- applications/luci-app-wireguard/luasrc/view/wireguard.htm
* no longer baffle QR code import with "(none)" values from wg dump
> luci-app-wireguard: clean up QR Code generation

- applications/luci-app-mwan3/luasrc/controller/mwan3.lua
This has worked before because the interface variable is global. But
this is not nice. So this commit will fix this.
This was already mentioned in https://github.com/openwrt/luci/pull/2197#issuecomment-426211483
> luci-app-mwan3: fix typo

- applications/luci-app-dump1090/luasrc/model/cbi/dump1090.lua
Option `aggressive` is supported by dump1090 binary, but oddly missing in
dump1090.init. Nevertheless, neither of them support the wrong
`agressive`.
> luci-app-dump1090: Fix typo of a dumb option

- applications/luci-app-statistics/luasrc/controller/luci_statistics/luci_statistics.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/curl.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/curl.lua
- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
Add collectd-mod-curl plugin support. Which can do some complex track,
such as grab stock, but by now, only response time are supported.
#2138
> luci-app-statistics: add support for cUrl

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/custom.css
This PR introduces a main color variable and sets it wherever #0099CC is chosen in the original theme. Using it should help with consistency and ease of use whentheming using the custom.css file.
Signed-off-by: Simon Tretter <simon@mediaarchitectu.re>
> luci-theme-material: Add main color variable

- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* fix possible crash during wireless scan
when no valid WPA label was found
> luci-app-travelmate: fix wireless scan

- modules/luci-mod-system/luasrc/view/admin_system/packages.htm
Add **id** attribute for **software/freespace** div so that developers can control the css style in their theme.
@hnyman @jow- 
> luci-mod-system: add id for software/freespace div

- modules/luci-mod-system/luasrc/model/cbi/admin_system/leds.lua
Give the user the possibility to define and interface for the netdev
trigger which is not available at the moment. This is usefull if a
interface is not presented on configuration time.
> luci-mod-system: add user defined interface to netdev trigger

- modules/luci-mod-network/luasrc/model/cbi/admin_network/dhcp.lua
'non-wildcard' interfaces enables dnsmasq's '--bind-dynamic' mode.
This binds dynamically to interfaces rather than wildcard addresses
*and* keeps track of interface comings/goings via a unique Linux api.
Quoting dnsmasq's author "bind-dynamic (bind individual addresses,
keep up with changes in interface config) ... On linux, there's actually
no sane reason not to use --bind-dynamic, and it's only not the default
for historical reasons."
listen/exclude interfaces may be used independently of bind dynamic mode
so removed the bogus dependency of 'nonwildcard' enabling access to
'listen/exclude' interfaces - they may be used in any mode..  In fact
the dnsmasq init script takes notice of include/exclude interfaces
irrespective of the 'nonwildcard' parameter.
Signed-off-by: Kevin …
> luci-mod-admin-full: dnsmasq clarify non-wildcard mode

- modules/luci-mod-system/luasrc/model/cbi/admin_system/fstab/mount.lua
The filesystem option doesn't include additional filesystem included with /etc/filesystems, this is usefull if someone have ntfs-3g installed and wants to force use the external utility to mount partition instead of the default present in the kernel (if it's supported)
@jow- 
> luci-mod-system: add support for additional filesystem

- applications/luci-app-firewall/po/zh-cn/firewall.po
- applications/luci-app-uhttpd/po/zh-cn/uhttpd.po
- modules/luci-base/po/zh-cn/base.po
This PR contains three commits below:
i18n: luci-app-firewall: update Simplified Chinese translation 
i18n: luci-base: update Simplified Chinese translation
i18n: luci-app-uhttpd: add initial Simplified Chinese translation
> i18n: update Simplified Chinese translation for openwrt-18.06

- applications/luci-app-olsr/luasrc/controller/olsr.lua
- applications/luci-app-olsr/luasrc/model/cbi/olsr/olsrdplugins.lua
- applications/luci-app-olsr/luasrc/model/cbi/olsr/olsrdplugins6.lua
- applications/luci-app-olsr/luasrc/view/status-olsr/interfaces.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/mid.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/overview.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/smartgw.htm
- modules/luci-base/luasrc/model/network.lua
* On the configuration page for the plugins, the library version number is now dropped.  This conforms to the change in openwrt-routing/packages@f4bc87d
* The network.lua function get_status_by_address now checks to see if the ip address is listed by ubus as ipv6-prefix-assignment in addition to ipv6-address and ipv4-address.  The interface is now properly shown in the olsr neighbor status page for ipv6 interfaces (previouls it was "undefined").
* The olsr status pages now function with the latest version of the jsoninfo plugin.
19b640b53 luci-app-olsr: cbi remove library version numbers in library search results
4fc3ab473 luci-base: network.lua add ipv6-prefix-assignment support to get_status_by_address
6ef3a00f6 luci-app-olsr: convert olsr.lua and overview.htm to new json plugin …
> update luci-app-olsr to the new jsoninfo library

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
: is used to delimit fields in DEF: rrd instructions, so when it appears in a filename it [must be escaped using `\`](https://oss.oetiker.ch/rrdtool/doc/rrdgraph_data.en.html#IDEF).  This commit adds the escaping.
I discovered the issue after configuring collectd-mod-ping to monitor an IPv6 host (2001:19f0:5:727:5b56:205d:ff55:2208).  Accessing https://192.168.0.1/cgi-bin/luci/admin/statistics/graph/ping would cause the following messages to be logged:
Wed Nov 14 23:04:33 2018 daemon.err uhttpd[30261]: ERROR: can't parse DEF '2ping_avg_raw=/tmp/rrd/openwrthost/ping/ping-2001:19f0:5:727:5b56:205d:ff55:2208.rrd:value:AVERAGE' -2
Wed Nov 14 23:04:33 2018 daemon.err uhttpd[30261]: ERROR: can't parse DEF '2ping_droprate_avg_raw=/tmp/rrd/openwrthost/ping/ping_droprate-2001:19f0:5:727:5b56:205d:f …
> luci-app-statistics: quote : in filenames for DEF

- applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
* add a manual interface selection to support
multiple WAN interfaces in iptables rules
> luci-app-banip: sync with update 0.0.6

- applications/luci-app-lxc/luasrc/controller/lxc.lua
Add i686 to target map so i386 container templates are usable.
> luci-app-lxc: add i686 to target map

- applications/luci-app-aria2/luasrc/controller/aria2.lua
- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
- applications/luci-app-aria2/po/pt-br/aria2.po
- applications/luci-app-aria2/po/ru/aria2.po
- applications/luci-app-aria2/po/sv/aria2.po
- applications/luci-app-aria2/po/templates/aria2.pot
- applications/luci-app-aria2/po/zh-cn/aria2.po
- applications/luci-app-aria2/po/zh-tw/aria2.po
As AriaNg is another web UI for aria2, I add a button to open AriaNg if installed package ariang or ariang-nginx
> luci-app-aria2: add button for to AriaNg

- applications/luci-app-openvpn/luasrc/controller/openvpn.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
* fix possible exception in template based ovpn creation
* remove needless shellquote function in controller,
the filename will be checked on client side with JS
* enhance FileUpload behaviour in basic/advanced mode:
- change "auth_user_pass" to FileUpload
- cfg entries (even with default values) will be shown
- existing entries are now removable (incl. file unlink),
simply clear the appropriate textbox
* change "key_direction" option to boolean ListValue
* add "config" option to basic/advanced edit, to make it possible to change the upload path in LuCI
> luci-app-openvpn: more changes & fixes

- modules/luci-mod-network/luasrc/view/admin_network/iface_overview.htm
We must pass to the translate() a string without substituted zone name.
> luci-mod-network: fix invalid translate() argument pass

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-file.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
- applications/luci-app-openvpn/luasrc/view/openvpn/cbi-select-input-add.htm
- applications/luci-app-openvpn/luasrc/view/openvpn/ovpn_css.htm
- applications/luci-app-openvpn/luasrc/view/openvpn/pageswitch.htm
* add 'auth-user-pass' edit section in file mode (see screenshot)
* add port & protocol detection in file mode (see screenshot)
* don't mix file & normal edit modes any longer
* add CC compatibility fix (for turris devices)
* fix/refine JS instance name filter
* remove needless CSS rules
* unlink ovpn/auth files on section removal
* commit changes instantly (Add/Upload/Delete)
> luci-app-openvpn: "final" changeset

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
Add the missing error css class definitions.
Highlights the wrong inputs detected by the cbi validation function.
> luci-theme-material: add missing css cbi-section-error definitions

- applications/luci-app-olsr-services/luasrc/view/freifunk-services/services.htm
- applications/luci-app-olsr/luasrc/controller/olsr.lua
- applications/luci-app-olsr/luasrc/view/status-olsr/hna.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/interfaces.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/mid.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/neighbors.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/routes.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/smartgw.htm
- applications/luci-app-olsr/luasrc/view/status-olsr/topology.htm
- applications/luci-app-olsr/po/de/olsr.po
- applications/luci-app-olsr/po/en/olsr.po
- applications/luci-app-olsr/po/templates/olsr.pot
modify the status tables so that then headers and columns align, values
left justified.
Additionally, add the openwrt style interface name to the interfaces table,
change huge  ETX numbers to 'infinate', and add the german translation for
'Selected'.
> luci-app-olsr: make cosmetic changes.

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/custom.css
- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
- themes/luci-theme-material/luasrc/view/themes/material/header.htm
The material theme is a mess in its current state. This attempts to solve a lot of the problems. A total rewrite would be the proper solution, but I think this is a good compromise.
It also reverts the removal of color fill to the buttons since the theme originally seemed to rely on color vibrancy to emphasize button actions. It already barely follows "material design" spec as it is and I don't think heavy use of empty buttons is a good idea without fancy animation that requires heavier js (dynamic ripple) and other significant changes to the button scheme.
Issues #1231, #1795, and #2258 can be closed.
> luci-theme-material: partial style overhaul

- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
In the openWebUI function, the url is assumed as http protocol,
this will cause problem when we login luci-admin with https.
The variable localhostPath has already contained http/https
protocol, so we can use it directly and add the path of aria2
webUI.
Signed-off-by: Zheng Qian <sotux82@gmail.com>
> luci-app-aria2: fix http/https protocol when opening aria2 webUI

- modules/luci-mod-status/luasrc/view/admin_status/index.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/10-system.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/20-memory.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/30-network.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/40-dhcp-leases.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/50-dsl.htm
- modules/luci-mod-status/luasrc/view/admin_status/index/60-wifi.htm
Split status page into a series of partials as discussed in PR #2359.
> luci-mod-status: split status page into a series of partials

- collections/luci-ssl-nginx/Makefile
Remove libustream-openssl because Nginx doesn't depend on it.
> luci-ssl-nginx: fix dependencies

- applications/luci-app-aria2/Makefile
- applications/luci-app-aria2/luasrc/view/aria2/overview_status.htm
if login luci-admin with https, RPC protocol should be https or wss.
Signed-off-by: Zheng Qian <sotux82@gmail.com>
> luci-app-aria2: fix showRPCURL when using https

- applications/luci-app-aria2/Makefile
- applications/luci-app-aria2/luasrc/model/cbi/aria2.lua
- applications/luci-app-aria2/po/pt-br/aria2.po
- applications/luci-app-aria2/po/ru/aria2.po
- applications/luci-app-aria2/po/sv/aria2.po
- applications/luci-app-aria2/po/templates/aria2.pot
- applications/luci-app-aria2/po/zh-cn/aria2.po
- applications/luci-app-aria2/po/zh-tw/aria2.po
According to the package aria2, the log option
is enable_logging, so fix this option name.
As luci-app-aria2 can't set custom log file dir,
the default log file is /var/log/aria2.log but not
in the config file dir.
Some discussion is here. [packages PR 7665](https://github.com/openwrt/packages/pull/7665)
> luci-app-aria2: fix the log option

- modules/luci-mod-system/luasrc/model/cbi/admin_system/leds.lua
Not every user knows which trigger does what. To make this clear, the
triggers are now translated with a short help text.
> luci-mod-system: add translation for led trigger names

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/adblock_css.htm
- applications/luci-app-adblock/luasrc/view/adblock/report.htm
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* add adblock dns query reporting via tcpdump (see readme for details)
* fix tld compression on low memory systems (< 64 MB)
* fix various small issues
> luci-app-adblock: sync with release 3.6.0

- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
If you change the color of the submenues then the colors of the toplevel
should also be changed into the same color.
> luci-theme-material: make top level menu fontcolor configurable

- applications/luci-app-uhttpd/luasrc/model/cbi/uhttpd/uhttpd.lua
Had 'at list' instead 'at least' for the help text on listing
HTTP/HTTPS listening addresses.
> luci-app-uhttpd: Correct spelling in two places

- applications/luci-app-nut/luasrc/model/cbi/nut_server.lua
There are a lot of options for the drivers (used by nut-server.init), so alphabetize them (by uci name).
Also, update server/drivers options to include what is in packages master.
> luci-app-nut: Update nut-server settings to match packages master

- applications/luci-app-nft-qos/luasrc/controller/nft-qos.lua
This commit fix the issue that the realtime monitor doesn't work when there no ipv6 support.
> luci-app-nft-qos: fix monitor doesn't work when there no ipv6 support.

- applications/luci-app-shadowsocks-libev/luasrc/model/cbi/shadowsocks-libev/rules.lua
- applications/luci-app-shadowsocks-libev/luasrc/model/shadowsocks-libev.lua
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/network.js
- modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
By replacing url "admin/system/packages" with "admin/system/opkg"
While at it, also remove query arguments as they have been invalid for quite a while.
> treewide: fix redirecting to System->Software

- applications/luci-app-ddns/luasrc/tools/ddns.lua
This saves a DNS request whenever the nslookup check is performed.  For systems with nameservers configured in `/etc/resolv.conf`, nslookup will send a request to those servers (eg bypassing /etc/hosts), thus taking a lot more time than necessary.  For nameservers that are remote, this will take a *lot* longer than just checking if the nslookup util exists.
This change follows in the same vein as all the other checks that currently exist in the file which just use `which` without actually invoking each util's functionality.
Signed-off-by: David Beitey <david@davidjb.com>
> luci-app-ddns: check existence of nslookup util rather than making DNS request

- applications/luci-app-rp-pppoe-server/luasrc/model/cbi/rp-pppoe-server.lua
- applications/luci-app-rp-pppoe-server/po/templates/rp-pppoe-server.pot
Currently if no non-commented uci sections exist in the config then
it's impossible to create a config from LuCI. Fix that, which also
allows what the initscript does, which is multiple instances. While
we're at it create the translation template.
Closes: #2431
Run tested on Raspberry Pi B+
> luci-app-rp-pppoe-server: Add ability to create uci sections

- applications/luci-app-nut/po/en/nut.po
- applications/luci-app-rp-pppoe-server/po/en/rp-pppoe-server.po
- applications/luci-app-uhttpd/po/en/uhttpd.po
This adds the 'en' 'translation' for various luci-apps I've created in the past.
> Add PO for en 'translation' for apps I've created in the past

- modules/luci-base/htdocs/luci-static/resources/cbi.js
In cbi.js there is an error which causes ipaddrport validation to always fail.
JS match() return the entire match as ret[0] and individual matches (for multiple ()) as the
subsequent list members.  So we fix it by just fixing the index in the calls that want the
individual parts.
> luci-base: Fix addr:port validate always fails

- modules/luci-mod-freifunk/luasrc/view/freifunk/adminindex.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk/contact.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk/index.htm
The get_all() function has changed and how it was used before no
longer works properly.  These changes not only change to individual
get() calls, but actually adds to the readability of the code and reduces
file size.
> luci-mod-freifunk: replace calls to get_all() with separate get() calls

- modules/luci-mod-freifunk/luasrc/model/cbi/freifunk/basics.lua
Using uci:get_first with a /PATH/FILENAME as the first argument no longer works.  Now the name of the config file (profile_X) is passed to get_first instead
> luci-mod-freifunk: fix the list of community profiles

- modules/luci-mod-freifunk/luasrc/view/freifunk/adminindex.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk/contact.htm
- modules/luci-mod-freifunk/luasrc/view/freifunk/index.htm
This is a backport commit from PR #2448.
The get_all() function has changed and how it was used before no
longer works properly.  These changes not only change to individual
get() calls, but actually adds to the readability of the code and reduces
file size.
> Backport 18.06: luci-mod-freifunk: replace calls to get_all() with separate get() calls

- applications/luci-app-radicale2/Makefile
- applications/luci-app-radicale2/luasrc/controller/radicale2.lua
- applications/luci-app-radicale2/luasrc/model/cbi/radicale2/auth.lua
- applications/luci-app-radicale2/luasrc/model/cbi/radicale2/logging.lua
- applications/luci-app-radicale2/luasrc/model/cbi/radicale2/server.lua
- applications/luci-app-radicale2/luasrc/model/cbi/radicale2/storage.lua
- applications/luci-app-radicale2/luasrc/view/cbi/raduigo.htm
- applications/luci-app-radicale2/po/en/radicale2.po
- applications/luci-app-radicale2/po/templates/radicale2.pot
- libs/rpcd-mod-rad2-enc/Makefile
- libs/rpcd-mod-rad2-enc/files/rad2-enc
Radicale 2.x has been out for some time, and has better support for a
number of clients as well as new features, so radicale2 package has
been added to packages, and this is the corresponding UI.
This is the companion to https://github.com/openwrt/packages/pull/7871 that I'm working on.
> luci-app-radicale2: Add CalDAV/CardDAV server Radicale 2.x

- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/collectd.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/conntrack.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/dns.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/interface.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/iptables.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/memory.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/netlink.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/openvpn.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/sensors.lua
- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/uptime.lua
- applications/luci-app-statistics/luasrc/statistics/i18n.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/colors.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/apcups.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/conntrack.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/curl.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/disk.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/netlink.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/olsrd.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/processes.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/sensors.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/splash_leases.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/tcpconns.lua
- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/uptime.lua
- fix whitespaces in rrdtool definitions
- reduce copyright headers
- only include lua modules into local scope
- remove unused luci.sys include
- only include lua modules in rrd statistics into local scope
> luci-app-statistics: some code cleanup

- protocols/luci-proto-ppp/luasrc/model/cbi/admin_network/proto_pppoe.lua
My previous addition of host_uniq tag setting for pppoe protocol (#1937 ) uses a wrong `hex` datatype for filed validation, `hexstring` is the correct one instead. This fixes bad validation error for that field.
Signed-off-by: Luca Piccirillo <luca.piccirillo@gmail.com>
> luci-proto-ppp: fix wrong pppoe host_uniq datatype

- applications/luci-app-radicale2/luasrc/model/cbi/radicale2/auth.lua
- applications/luci-app-radicale2/luasrc/view/cbi/raduigo.htm
* In some case the password hash for existing users could be lost when updating other users
* The link the Radicale 2.x web UI sometimes was written has https:// when SSL not enabled.
> luci-app-radicale2: A couple of fixes for radicale2 UI

- applications/luci-app-lxc/luasrc/controller/lxc.lua
Turris MOX uses aarch64 architecture and according to [stackoverflow.com](https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64), it is also called arm64.
With this commit, It was able to show me templates from images.linuxcontainers.org, create them, start them and so on. 
I think it would be great to ask review from @dibdot as he seems to be most active about luci-app-lxc even it's one row, however, I don't know anything about Lua so he may have a better solution.
> luci-app-lxc: add aarch64 to target map

- applications/luci-app-adblock/luasrc/controller/adblock.lua
- show 'DNS Query Report' tab only when tcpdump was found
- remove needless Turris Omnia logread workaround, due to changes in latest syslog-ng package
> luci-app-adblock: small controller changes

- applications/luci-app-travelmate/luasrc/controller/travelmate.lua
- remove needless Turris Omnia logread workaround, due to changes in
latest syslog-ng package
> luci-app-travelmate: small controller changes

- applications/luci-app-banip/luasrc/controller/banip.lua
- remove needless Turris Omnia logread workaround, due to changes in
latest syslog-ng package
> luci-app-banIP: small controller changes

- applications/luci-app-dnscrypt-proxy/luasrc/controller/dnscrypt-proxy.lua
- remove needless Turris Omnia logread workaround, due to changes in
latest syslog-ng package
> luci-app-DNSCrypt-Proxy: small controller changes

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
Tested and confirmed working properly with ```mtd12``` by [imi2003](https://forum.openwrt.org/u/imi2003).
> luci-app-advanced-reboot: secondary partition fix for Linksys EA6350v3

- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
This checks if the installed hostapd supports SAE and allows to select
WPA3 Personal SAE in that case.
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>
> luci-mod-network: Add WPA3 SAE support

- applications/luci-app-rosy-file-server/Makefile
- applications/luci-app-rosy-file-server/luasrc/controller/rosy-file-server/rosy-file-server.lua
- applications/luci-app-rosy-file-server/luasrc/model/cbi/rosy-file-server/rosy-file-server.lua
- applications/luci-app-rosy-file-server/luasrc/model/cbi/rosy-file-server/rosyfs.lua
This application allows users to deploy a download server over http on their openwrt machine without installing external packages like samba, ftp, tftp. And this application takes up almost no memory unless users download files.
I wanted to add a http file server application so that we can deploy a download server on an openwrt machine and people can get the files without login to my machine. Unfortunately, the download action failed with below issue (can not access without authentication):
Is there any solution for this ?? thanks @jow- @hnyman 
So it turned to be a internal application. like this.
> luci-app-rosy-file-server: add new application

- themes/luci-theme-material/htdocs/luci-static/material/js/script.js
After opening an external hyperlink in a new browser tab, LuCI hangs in the
load screen. This commit will fix this issue.
> luci-theme-material: fix loading view on href

- modules/luci-base/luasrc/view/cbi/tsection.htm
In some situation it is usefull to inform the use that this section
could not get delete, because this config is referenced or is in use.
Example pseudo code:
```
function s.remove(self, sid)
<check if secation could get deleted>
if output == nil then
self.error_msg = translatef("Unable to remove this section")
return nil
end
end
```
> luci-base: add cbi tsection error msg option

- modules/luci-mod-system/luasrc/model/cbi/admin_system/system.lua
Also changed original "kiB" to "KiB" in accordance with IEEE 1541-2002.
> luci-mod-system: add "KiB" to translatable strings

- modules/luci-base/luasrc/cbi/datatypes.lua
* fix unknown cidr datatype (#2671)
> luci-app-shadowsocks-libev: fix cidr datatype

- modules/luci-mod-system/luasrc/controller/admin/system.lua
- modules/luci-mod-system/luasrc/view/admin_system/clock_status.htm
Especially for systems without RTC this change has two advantages
* manual time sync with time server during configuration
* test possibility of the time sync over the configured servers
> luci-mod-system: add button to sync with ntp server

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
Fixes situations where RRD file name contains ":" (eg. _ping/ipv6_) in `rrdtool` it's unescaped - thus not able to render image. Adding simple escaping of `:` to `\\:` fixes the situation.
Might be a solution for https://github.com/openwrt/luci/issues/985
> luci-app-statistics - allow rrd files to contain :

- themes/luci-theme-rosy/htdocs/luci-static/rosy/js/script.js
Fix https://github.com/openwrt/luci/issues/2645
@yglb @fantom-x  @hnyman 
Signed-off-by: Yan Lan Shen <yanlan.shen@rosinson.com>
> luci-theme-rosy: fix table overflow on network/switch

- modules/luci-base/luasrc/view/cbi/wireless_modefreq.htm
- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
Do not show 'auto' channel option if hostapd is not compiled with CONFIG_ACS
Signed-off-by: Enrique Giraldo <hgiraldos@gmail.com>
> luci-mod-admin-full: add dependency for channel auto

- applications/luci-app-statistics/root/etc/config/luci_statistics
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
collectd can support multiple UPSs .. 
- altered the config builder to take a list
- altered the template to use list
> luci-app-statistics: adding ability for luci_stats config to have multiple UPS's

- applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
* change maxqueue default to '4' to reduce the overall system load
> luci-app-banip: change maxqueue default / sync with banIP 0.1.1

- modules/luci-base/po/de/base.po
The following changes are included:
* properly handle "Präfix" as neuter
* add missing hyphens to many appearances of "Präfix"
* fix spelling
* add few missing translations
> Various improvements of the German translation

- modules/luci-base/luasrc/view/lease_status.htm
If the system does not have ipv6 support, just drop the relevant module, so that the page seems more concise. :-)
> luci-base: drop ipv6 lease status when IPV6 is not support

- applications/luci-app-unbound/Makefile
Maintainer: me
Compile tested: Linksys-WRT3200ACM (master)
Run tested: Linksys-WRT3200ACM
Supports changes in openwrt/packages#9029 to depend on unbound-daemon for clearer menu selections. This also relates to openwrt/packages#8956.
> luci-app-unbound: match dependencies with unbound package

- modules/luci-mod-network/luasrc/model/cbi/admin_network/ifaces.lua
Since openwrt-18.06 the auto option is set/unset if we press
connect/disconnect on the interface page. So I think we should move this
to the general tab so that we see at once if this is started on boot or
not.
This revers also to #2119
> luci-mod-network: move auto option to general tab

- modules/luci-base/luasrc/sys.lua
- modules/luci-base/luasrc/tools/status.lua
Currently only the dnsmasq lease file is read for hostname hint. If someone use only odhcpd as dhcp daemon the hostname resolution on wifi_assoc list is broken.
Also i notice that very similar code is used in 2 different source.
dhcp_leases_common(family) in luci tools status.lua is very similar to what _nethints does... 
Some cleanup should be done as this error was already fixed in status.lua but was still present in sys.lua.
Wifi_assoc list use sys.lua 
lease_status use status.lua and include the odchpd lease file.
@jow- 
> luci-base: handle dhcp lease from odhcpd

- modules/luci-base/luasrc/tools/status.lua
* fix for openwrt/packages#9148
> luci-base: fix duid_to_mac reference in status.lua

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
This is related to the change in https://github.com/openwrt/packages/pull/9128
> luci-app-mwan3: change flush_conntrack option to list option

- contrib/package/community-profiles/Makefile
- contrib/package/community-profiles/files/etc/config/profile_berlin
- contrib/package/community-profiles/files/etc/config/profile_cottbus
- contrib/package/community-profiles/files/etc/config/profile_fuerstenwalde
- contrib/package/community-profiles/files/etc/config/profile_potsdam
The old digitalcourage nameservers 85.214.20.141 and 2a01:238:42f6:ac00:2a29:4f7f:b6d:ef46
will be retired in 2020.  The new nameservers are 46.182.19.48 and 2a02:2970:1002::18.
The change is announced https://digitalcourage.de/support/zensurfreier-dns-server
This fixes https://github.com/freifunk/openwrt-packages/issues/11
This is cherry-picked from https://github.com/freifunk/openwrt-packages/pull/16/commits/2c4a93e646607b0e2a2faa272c985beff52606e1
> 18.06.x freifunk community-profiles: update profiles to use the new digitalcourage nameservers

- applications/luci-app-statistics/luasrc/model/cbi/luci_statistics/ping.lua
- applications/luci-app-statistics/root/usr/bin/stat-genconfig
It allows to force ipv4 or ipv6 when the DNS returns both addresses, but
only one works (for example if there is no ipv6 connectivity).
Signed-off-by: Loïc Yhuel <loic.yhuel@gmail.com>
> luci-app-statistics: add address family configuration for ping

- protocols/luci-proto-ncm/luasrc/model/cbi/admin_network/proto_ncm.lua
This option is useful for setting the dial number used for data service connection
Signed-off-by: geekinaboxx <aleem@tectonic.it>
> luci-proto-ncm: add dialnum option

- modules/luci-mod-network/root/etc/uci-defaults/50_luci-mod-admin-full
This is a followup to commit 8a34a54b6aa6 ("base-files: use OPENWRT prefix for os-release variables") in the base repo.  It changes the prefix of the os-release variables from LEDE_ to OPENWRT_.  
luci-mod-network was the only place I found where any of these variables were in use
Signed-off-by: Bjørn Mork <bjorn@mork.no>
> luci-mod-network: os-release variables have been renamed to OPENWRT_

- protocols/luci-proto-qmi/luasrc/model/cbi/admin_network/proto_qmi.lua
- Add the missing delay option
-  Only show username and password if we use PAP/CHAP, PAP or CHAP
authentication.
> luci-proto-qmi: improvements

- modules/luci-mod-status/luasrc/view/admin_status/connections.htm
Currently the lookup loop is very inefficient. This improve the lookup loop by moving the entities to a separate array and adds them only one time. Every entities is checked 3 times, after that it will be moved to dns cache as a raw addres (not resolved). This also introduce the Type column to identify common packet using the source port.
> luci-mod-admin-full: improve connection page lookup loop

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-system/luasrc/model/cbi/admin_system/leds.lua
@feckert This fixes 2 typos introduced by commit a56935c241f84f5870057555b9d029a7732ef049
> luci-mod-system: fix some led trigger name translations

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/po/pt-br/travelmate.po
- applications/luci-app-travelmate/po/ru/travelmate.po
- applications/luci-app-travelmate/po/templates/travelmate.pot
- applications/luci-app-travelmate/po/zh-cn/travelmate.po
- applications/luci-app-travelmate/po/zh-tw/travelmate.po
* add optional 'trm_scanbuffer' parm
* fix wrong lua escape character in wifi edit
* sync translations
> luci-app-travelmate: sync with update 1.4.8

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-system/luasrc/model/cbi/admin_system/leds.lua
The former name "Flashmemory write access" is wrong. The triggers also
indicate read/erase access to the flash memories.
> luci-mod-system: fix flash activity trigger name

- protocols/luci-proto-qmi/luasrc/model/cbi/admin_network/proto_qmi.lua
Add missing mtu option.
This dependence on https://github.com/openwrt/openwrt/pull/2176
> luci-proto-qmi: add missing mtu option

- protocols/luci-proto-3g/luasrc/model/cbi/admin_network/proto_3g.lua
The option maxwait is not support by the 3g netifd proto.
To standardize that rename the maxwait option to delay as in the other
proto handlers luci-proto-qmi and luci-proto-ncm.
> luci-proto-3g: rename maxwait to delay option

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
- themes/luci-theme-material/htdocs/luci-static/material/cascade.css
- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
This PR should fix a style issue with interface boxes, which is described in PR #2758.
Tested with browsers:
- Google Chrome 75.0.3770.100
- Mozilla Firefox 67.0.4
- Opera 60.0.3255.170
- Internet Explorer 11.0.9600.18817
> Fix a overview page style issue for various themes

- applications/luci-app-ocserv/luasrc/model/cbi/ocserv/users.lua
- modules/luci-base/luasrc/cbi/datatypes.lua
- modules/luci-base/luasrc/util.lua
* fix escaping of magic lua chars (#2800)
* fix redundant second gsub line in shellstartsqescape function
* fix return value of shellstartsqescape function
> system-wide: fix escaping of magic chars

- .circleci/Dockerfile
- .circleci/README
- .circleci/config.yml
This automatically performs formal checks and also checks and compiles
the packages. The resulting packages are then stored as artifacts and
easily testable on running machines.
> build: add circleci

- applications/luci-app-statistics/root/usr/bin/stat-genconfig
Fix config generation for the following sections:
* curl
* exec
* network
* iptables
This was added with the following commit.
https://github.com/openwrt/luci/commit/c1380ab36797dc4a9cba5a6aa738019452178d79
> luci-app-statistics: fix collectd config generation

- applications/luci-app-wireguard/luasrc/view/wireguard.htm
* explain the QR-Code 'use case' and the transfered information
* limit the QR-Code information to bare minimum (per interface):
* [Interface] A random, on the fly generated 'PrivateKey',
the key will not be saved on the router
* [Peer] The 'PublicKey' of that wg interface and the
'AllowedIPs' with the default of '0.0.0.0/0, ::/0'
to allow sending traffic to any IPv4 and IPv6 address
* the QR-Code logic will be processed only once per page load,
and not every 5 seconds with the regular XHR refresh
See corresponding forum thread:
https://forum.openwrt.org/t/luci-app-wireguard-qr-code-shows-private-key/38133
> luci-app-wireguard: QR-Code enhancements

- libs/luci-lib-nixio/src/address.c
ualarm has been deprecated and may not be available in the libc.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> address: Replace ualarm with setitimer

- modules/luci-base/luasrc/view/cbi/dropdown.htm
- modules/luci-base/luasrc/view/cbi/mvalue.htm
In the dc0211803e commit, the parameter "multi" in ui.js is replaced with "multiple" everywhere. Thus, it must also be changed in the cbi templates.
> luci-base: fix multiple parameter in cbi templates

- modules/luci-mod-network/luasrc/model/cbi/admin_network/wifi.lua
@hauke LIttle bugfix as I've been using two routers in WPA3-SAE mode for a few months.
802.11w has to be enabled in station mode to be effective. If the AP is using WPA3-SAE or requires 11w, station will not connect unless 11w is enabled via this option.
> luci-mod-network: 802.11w config in station mode

- applications/luci-app-watchcat/root/etc/uci-defaults/40_luci-watchcat
I do not use this application but I think the ucitrack configuration generation file is wrong.
The related issue is https://github.com/openwrt/packages/issues/9506
> luci-app-watchat: fix ucitrack file

- themes/luci-theme-rosy/htdocs/luci-static/rosy/cascade.css
The software page is out of the parent box, and the same is true in chrome and firefox.
> Fix a software page style issue for rosy, Fix #2965.

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
- applications/luci-app-travelmate/luasrc/view/travelmate/stations.htm
- applications/luci-app-travelmate/luasrc/view/travelmate/wifi_scan.htm
* wifi add/edit: add a select box to reference an external script
for automated captive portal logins
* fix a visual issue with material theme
> luci-app-travelmate: sync with 1.4.10

- applications/luci-app-banip/luasrc/model/cbi/banip/overview_tab.lua
* add new extra options to control auto-addons to
blacklist & whitelist ('ban_autoblacklist' & 'ban_autowhitelist')
> luci-app-banip: sync with 0.1.5

- applications/luci-app-ocserv/luasrc/controller/ocserv.lua
- applications/luci-app-ocserv/luasrc/view/ocserv_status.htm
- applications/luci-app-openvpn/luasrc/controller/openvpn.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
- applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
- applications/luci-app-openvpn/luasrc/view/openvpn/cbi-select-input-add.htm
- applications/luci-app-openvpn/luasrc/view/openvpn/pageswitch.htm
- modules/luci-base/luasrc/controller/admin/index.lua
There is always more and more vpn services. To make the LuCI menu look cleaner, a new top level menu "VPN" will be added with this pullrequest. All luci-app-* that have something to do with VPN should move to this new menu entry.
* Add new vpn menu section
* Move luci-app-openvpn to the new vpn section
* Move luci-app-ocserv to the new vpn section
The luci-app-vpnbypass should also go to this section.
> luci-base: add new VPN toplevel menu entry

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ping.lua
In original collectd, values of this metric are in range 0-1.  OpenWrt
previously have a custom patch scaling them up to range 0-100.  That
patch has been removed to align with possibly other deployments.
Ref: https://github.com/openwrt/packages/pull/9677
/hold
> luci-app-statistics: scale up ping_droprate to range 0-100

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
- applications/luci-app-adblock/luasrc/view/adblock/runtime.htm
* add support for the 'null' blocking variant in dnsmasq
(via addn-hosts), see new select box 'DNS Variant'
* add support for 'DNS File Reset', where the final DNS blockfile
will be purged after DNS backend loading (save storage space)
* Provide additional Runtime information:
'DNS Variant' and 'Backup Directory'
* add E-Mail notification options to LuCI
> luci-app-adblock: sync with adblock 3.8.0

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
> [18.06] luci-app-advanced-reboot: bugfix for when network.lan.ipaddr is a table

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
> [19.07] luci-app-advanced-reboot/: bugfix for when network.lan.ipaddr is a table

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/overview_tab.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
* option to add open uplinks to your wireless config,
e.g. hotel captive portals (disabled by default)
> luci-app-travelmate: sync with 1.4.12

- applications/luci-app-adblock/luasrc/model/cbi/adblock/overview_tab.lua
* support the new extra options 'TLD Compression Threshold',
'Local FW/DNS Ports' and 'DNS Inotify', see packages PR for details.
> luci-app-adblock: sync with adblock 3.8.5

- applications/luci-app-firewall/po/uk/firewall.po
Removed unnecessary double quotation at the end of the line. It was
reported as an error by i18n-sync.sh script.
> luci-app-firewall: remove unnecessary quotation in Ukrainian translation

- applications/luci-app-adblock/po/es/adblock.po
- applications/luci-app-advanced-reboot/po/es/advanced-reboot.po
- applications/luci-app-aria2/po/es/aria2.po
- applications/luci-app-banip/po/es/banip.po
- applications/luci-app-ddns/po/es/ddns.po
- applications/luci-app-firewall/po/es/firewall.po
- applications/luci-app-mjpg-streamer/po/es/mjpg-streamer.po
- applications/luci-app-mwan3/po/es/mwan3.po
- applications/luci-app-ntpc/po/es/ntpc.po
- applications/luci-app-simple-adblock/po/es/simple-adblock.po
- applications/luci-app-travelmate/po/es/travelmate.po
- applications/luci-app-vpnbypass/po/es/vpnbypass.po
- applications/luci-app-wifischedule/po/es/wifischedule.po
- applications/luci-app-wireguard/po/es/wireguard.po
- modules/luci-base/po/es/base.po
Update of the Spanish translation of luci-base and some LuCI applications.
* luci-base
* adblock
* advanced-reboot
* aria2
* banip
* ddns
* firewall
* mjpg-streamer
* mwan3
* ntpc
* simple-adblock
* travelmate
* vpnbypass
* wifischedule
* wireguard
> luci-base and apps: update Spanish translation

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- sync translations (luci-base)
- use old translation for "Gateway Ports"
- original text is replaced from "Gateway ports"
- update Japanese translation
> luci-base: update Japanese translation

- applications/luci-app-olsr/luasrc/controller/olsr.lua
The response of the jsoninfo request may be non-empty (e.g. a linebreak
or just whitespace), but still yield "nil" after "json.decode".
This situation was handled before for the "status" request, but it lead
to a dictionary access against a "nil" value for all other tables.
> luci-app-olsr: handle empty result for non-status tables

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_add.lua
- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
This can be helpful for example in hotels where you need to
enter a new user/password combination every week.
Maintainer @dibdot
> luci-app-travelmate: add support for optional args in auto-login script

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
This option is usefull if someone needs to route ipv6 dhcp from wan to lan.
@jow- 
> luci-mod-network: add master option

- modules/luci-base/po/ca/base.po
- modules/luci-base/po/cs/base.po
- modules/luci-base/po/de/base.po
- modules/luci-base/po/el/base.po
- modules/luci-base/po/en/base.po
- modules/luci-base/po/es/base.po
- modules/luci-base/po/fr/base.po
- modules/luci-base/po/he/base.po
- modules/luci-base/po/hu/base.po
- modules/luci-base/po/it/base.po
- modules/luci-base/po/ja/base.po
- modules/luci-base/po/ko/base.po
- modules/luci-base/po/ms/base.po
- modules/luci-base/po/no/base.po
- modules/luci-base/po/pl/base.po
- modules/luci-base/po/pt-br/base.po
- modules/luci-base/po/pt/base.po
- modules/luci-base/po/ro/base.po
- modules/luci-base/po/ru/base.po
- modules/luci-base/po/sk/base.po
- modules/luci-base/po/sv/base.po
- modules/luci-base/po/templates/base.pot
- modules/luci-base/po/tr/base.po
- modules/luci-base/po/uk/base.po
- modules/luci-base/po/vi/base.po
- modules/luci-base/po/zh-cn/base.po
- modules/luci-base/po/zh-tw/base.po
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
Currently WPS push-button is dropped when SAE or SAE-Mixed is selected. WPS is still supported in WPA3.
@jow- 
> luci-mod-network: permit WPS push-button on WPA3

- applications/luci-app-commands/luasrc/controller/commands.lua
Do not escape pipe on cmd line
closes #1622
> luci-app-commands: fix escaping of additional shell chars

- applications/luci-app-https_dns_proxy/Makefile
- applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
> luci-app-https_dns_proxy: bugfix: proper formatting of dhcp server entries

- applications/luci-app-https_dns_proxy/Makefile
- applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
> [19.07] luci-app-https_dns_proxy: bugfix: proper formatting of dhcp server entries

- modules/luci-base/po/de/base.po
> luci-base: fix typo in german translation

- applications/luci-app-statistics/po/de/statistics.po
... of the msgid "Wireless".
The luci-base also use the same msgid "Wireless", where it is translated
with "WLAN".
The translation in luci-app-statistics overlays the translation in
luci-base, so use the same translation here.
> luci-app-statistics: fix german translation

- applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua
This was dropped in mosquitto 1.6.0.
> luci-app-mosquitto: drop tls1.0, add tls1.3

- applications/luci-app-banip/po/es/banip.po
- applications/luci-app-openvpn/po/es/openvpn.po
- applications/luci-app-simple-adblock/po/es/simple-adblock.po
- applications/luci-app-statistics/po/es/statistics.po
- applications/luci-app-transmission/po/es/transmission.po
- applications/luci-app-travelmate/po/es/travelmate.po
- applications/luci-app-uhttpd/po/es/uhttpd.po
- applications/luci-app-unbound/po/es/unbound.po
Updated translations:
* banip
* openvpn
* simple-adblock
* statistics
* transmission
* travelmate
* uhttpd
* unbound
> i18n: update spanish translations

- modules/luci-base/htdocs/luci-static/resources/tools/widgets.js
- modules/luci-base/root/usr/share/rpcd/acl.d/luci-base.json
There's few applications provide user selection.
https://github.com/openwrt/luci/blob/07dbee37f858b93c10fe5114fbe55e36ddb0d654/applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua#L65 https://github.com/openwrt/luci/blob/9a489da90f1edeb01e88959c3092602bccf50a79/applications/luci-app-transmission/luasrc/model/cbi/transmission.lua#L28
However, after moving to client-siew view, we can't execute command directly from client-side. So I think we need corresponding widgets.
<del>I also removed the `-- Deprecated` comment of execl in util.lua, because rpcd/luci uses this function.</del>
> luci-base: widgets.js: add user and group select

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-basic.lua
> luci-app-openvpn: add missing proto param for ipv6

- modules/luci-base/root/usr/share/rpcd/acl.d/luci-base.json
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
We determine flash reset capability by checking overlayfs in /proc/mounts
Traversing the ubi partitions is a little bad, it could not cover all the case
for some case if `rootfs_data` locates at `ubi_vol > 4`
and Traversing is not fast.
> luci-mod-system: refine flash reset

- applications/luci-app-cifsd/Makefile
- applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js
- applications/luci-app-cifsd/luasrc/controller/cifsd.lua
- applications/luci-app-cifsd/root/usr/share/rpcd/acl.d/luci-app-cifsd.json
As openwrt/openwrt#2368 said, I'm going to add luci-app-cifsd.
But I noticed that luci is moving to client-side view implemention. Should I implement it in client-side?
> [RFC] luci-app-cifsd: add new package

- applications/luci-app-ttyd/Makefile
- applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/config.js
- applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/term.js
- applications/luci-app-ttyd/luasrc/controller/ttyd.lua
[ttyd](https://github.com/tsl0922/ttyd) is an easy-to-use web-based terminal, which exists in packages for some time.
However, a app for it is absent in this repo. There's only a [luci-app-terminal](https://github.com/tsl0922/ttyd/tree/master/openwrt/luci-app-terminal), which is written using server-side rendering.
This package reimplement it using client-side rendering. And add a config page.
This package requires the corresponding init script https://github.com/openwrt/packages/pull/10267.
@tsl0922 @jow-
> [RFC] luci-app-ttyd: add new package

- applications/luci-app-travelmate/luasrc/model/cbi/travelmate/wifi_edit.lua
* fix logical glitch in last commit for WEP/EAP stations
> luci-app-travelmate: fix logical glitch

- modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
https://github.com/openwrt/openwrt/blob/a8a934060957212eb7b9eb6bd14fc80a3857d9d8/package/base-files/files/etc/init.d/led#L113-L115
> luci-mod-system: add missing speed_mask option in leds.js

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
This fixes: https://github.com/openwrt/luci/issues/3243
> [19.07] luci-app-vpnbypass: bugfix: call to action has no parent node

- applications/luci-app-vpnbypass/Makefile
- applications/luci-app-vpnbypass/luasrc/controller/vpnbypass.lua
- applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
- applications/luci-app-vpnbypass/luasrc/view/vpnbypass/js.htm
This fixes: https://github.com/openwrt/luci/issues/3243
Only merge if the luci-app-openvpn which creates its entries under the VPN (and not Services) node will ever be merged to 18.06.
> [18.06] luci-app-vpnbypass: bugfix: call to action has no parent node

- modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/20_memory.js
Ref: https://github.com/openwrt/luci/issues/1148
Uses available and cached memory from /proc/meminfo via procd, and carefully
handles the cases where they are nil or zero, so as to not require specific
linux or procd versions to function
MemAvailable is a better estimate than free + buffered/cached, see:
git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0
Also adds a new progressbar that shows cached memory if not nil
Related procd [patch](http://lists.infradead.org/pipermail/openwrt-devel/2019-February/015762.html)
> luci-mod-status: use available and cached memory for progress bars

- README.md
The weblate badge show the overall translation status, however before
only for the luci base package, now for all components at once.
Also add a overview to the bottom which languages need more attention,
hopefully motivating some more people to contribute.
> README: use correct weblate badge and add status

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/load.lua
Fixes: #3301
During my tests and developing with the collectd and so
luci-app-statistics I noticed that the values displayed in the Y-axis
are misleading, because probably the individual values are added
together in each case. So the view is not corrected.
> luci-app-statistics: update misleading load view

- applications/luci-app-nextdns/Makefile
- applications/luci-app-nextdns/luasrc/controller/nextdns.lua
- applications/luci-app-nextdns/luasrc/model/cbi/overview.lua
- applications/luci-app-nextdns/luasrc/view/nextdns/logread.htm
- applications/luci-app-nextdns/po/templates/nextdns.pot
- applications/luci-app-nextdns/root/etc/uci-defaults/60_luci-nextdns
Signed-off-by: Olivier Poitrey <rs@nextdns.io>
Description:
Adding support for [NextDNS](https://nextdns.io), a DNS over HTTPS service that provides customized block-lists (ad-block, malware protection, kid safety) as well advanced analytics amongst other things.
Depends on: https://github.com/openwrt/packages/pull/10535
> luci-app-nextdns: add luci integration for nextdns package

- applications/luci-app-https_dns_proxy/Makefile
- applications/luci-app-https_dns_proxy/luasrc/controller/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/com.adguard.dns-family.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/com.adguard.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/cz.nic.odvr.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns10.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns11.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns9.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/com.cloudflare-dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/com.google.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/sb.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/buttons.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/css.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/js.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/status-textarea.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/status.htm
As dnsmasq integration is moved to the principal service in https://github.com/openwrt/packages/pull/10413, luci app no longer needs that functionality.
> luci-app-https_dns_proxy: luci-app-https_dns_proxy: remove dnsmasq integration, better service controls, providers as plugins, misc fixes

- applications/luci-app-https_dns_proxy/Makefile
- applications/luci-app-https_dns_proxy/luasrc/controller/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/com.adguard.dns-family.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/com.adguard.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/cz.nic.odvr.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns10.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns11.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/net.quad9.dns9.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers.disabled/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/com.cloudflare-dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/com.google.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/https_dns_proxy/providers/sb.dns.lua
- applications/luci-app-https_dns_proxy/luasrc/model/cbi/https_dns_proxy.lua
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/buttons.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/css.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/js.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/status-textarea.htm
- applications/luci-app-https_dns_proxy/luasrc/view/https_dns_proxy/status.htm
As dnsmasq integration is moved to the principal service in https://github.com/openwrt/packages/pull/10414, luci app no longer needs that functionality.
> [19.07] luci-app-https_dns_proxy: remove dnsmasq integration, better service controls, providers as plugins, misc fixes

- applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
> luci-app-ddns: fix typo err in luci.ddns

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
Add the new possibilty to ping https targets with httping.
This depends on https://github.com/openwrt/packages/pull/10538
> luci-app-mwan3: add new httping_ssl option

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/applyreboot.htm
This fixes:
1. Luci error on reboot on 19.07.x and master
2. logger errors for compatible NAND devices (when trying to mount alternative partition in order to obtain OpenWrt version information)
> luci-app-advanced-reboot: bugfix: luci error on reboot, logger errors

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/applyreboot.htm
This fixes:
1. Luci error on reboot on 19.07.x and master
2. logger errors for compatible NAND devices (when trying to mount alternative partition in order to obtain OpenWrt version information)
> [19.07] luci-app-advanced-reboot: bugfix: luci error on reboot, logger errors

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/applyreboot.htm
This fixes:
1. Luci error on reboot on 19.07.x and master
2. logger errors for compatible NAND devices (when trying to mount alternative partition in order to obtain OpenWrt version information)
> [18.06] luci-app-advanced-reboot: bugfix: luci error on reboot, logger errors

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
dnsmasq v2.80 made 'dnssec-check-unsigned' the default, reflect this in
the gui.
> luci-mod-network: dnsmasq: correct sense & usage of dnsseccheckunsigned

- applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
* align defaults with upstream
* mark our default UCI changes and enforce updates to config
> luci-app-samba4: fix defaults (none writeable default shares) [19.07]

- applications/luci-app-samba4/htdocs/luci-static/resources/view/samba4.js
* align defaults with upstream
* mark our default UCI changes and enforce updates to config
> luci-app-samba4: fix defaults (none writeable default shares)

- applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js
* align defaults with upstream
* mark our default UCI changes and enforce updates to config
> luci-app-cifsd: fix defaults (none writeable default shares)

- applications/luci-app-cifsd/htdocs/luci-static/resources/view/cifsd.js
* align defaults with upstream
* mark our default UCI changes and enforce updates to config
> luci-app-cifsd: fix defaults (none writeable default shares) [19.07]

- themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
> luci-theme-bootstrap: fix background of large modal overlays.

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/cn.rubyfish.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/sb.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cz.nic.odvr.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/google.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm
- applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/css.htm
- applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/js.htm
- applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/status-textarea.htm
- applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/status.htm
- applications/luci-app-https-dns-proxy/po/https-dns-proxy.pot
- applications/luci-app-https-dns-proxy/root/etc/uci-defaults/40_luci-https-dns-proxy
@hnyman @feckert sorry, was easier for me to start from scratch to fix the issue with existing translations. Please merge asap, as the principal package has already been merged.
> [18.06] luci-app-https-dns-proxy: package name change, support for RFC8484 binary

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
* Always write **httping_ssl** configuration parameter into the config.    
* If **rmempty** and **optional** not removed for the size configuration option, then httping cannot be selected as the tracking method. The field size is a must field for ping but it is not displayed because httping does not need it.
> luci-app-mwan3: minor fixes for httping selection

- modules/luci-mod-admin-mini/luasrc/model/cbi/mini/dhcp.lua
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
- modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js
There are both *Leasetime remaining* and *Lease time remaining* entries in the language files, so no need to modify the PO files.
> luci-base: fix typos

- applications/luci-app-mjpg-streamer/luasrc/model/cbi/mjpg-streamer.lua
- applications/luci-app-mjpg-streamer/po/bg/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ca/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/cs/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/de/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/el/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/en/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/es/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/fr/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/he/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/hi/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/hu/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/it/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ja/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ko/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/mr/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ms/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/nb_NO/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/pl/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/pt-br/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/pt/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ro/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/ru/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/sk/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/sv/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/tr/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/uk/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/vi/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/zh-cn/mjpg-streamer.po
- applications/luci-app-mjpg-streamer/po/zh-tw/mjpg-streamer.po
Fixed typos:
- smaller then -> smaller than
- Mjpg-streamer parse the filename -> Mjpg-streamer parses the filename
> luci-app-mjpg-streamer: fix typos

- luci.mk
- modules/luci-base/Makefile
luasrcdiet is being moved to the packages feed as a separate package.
Adjust luci feed accordingly.
See https://github.com/openwrt/packages/pull/10626 for the other half of the move.
> luci-base: use luasrcdiet from separate package

- modules/luci-compat/luasrc/model/network.lua
Fixes these bugs:
1. Functions interface.bridge_id() and interface.bridge_stp() uses self.br field
that is not exists at all
2. Function interface.is_bridgeport() return true only for bridge interface, not for
bridge port interfaces.
3. Function interface.ports() is not return anything
> luci-base: network.lua: bridge information request functions fixes

- luci.mk
Almost every uci-defaults script for ucitrack execute after the uci
commands the following line '/tmp/luci-indexcache'.
So that we don't always write the same thing, we now do this in
postinst. This was the result from discussion in #3388 .
We still need to remove this line from every uci-defualts script.
> luci.mk: move indexcache delete into postinst

- applications/luci-app-noddos/luasrc/view/noddos/clients.htm
Changed PascalCase value to human readable words. Can you please cherry-pick this change into branch ``openwrt-19.07``? I did not change this in *.po files now, because this is not just a cosmetic change. Can you please run ``./build/i18n-sync.sh`` after merging?
There is a number (1) after the key name in this line of the file:
```html
<div class="td cbi-value-field"><%=v.DhcpVendor1%></div>
```
Is this OK, or just a typo? The file `applications/luci-app-noddos/htdocs/cgi-bin/clientdetails:77` lists different key (without number):
```lua
for i, key in ipairs{"MacAddress", "Ipv4Address", "Ipv6Address", "DeviceProfileUuid", "DhcpHostname", "DhcpVendor", "SsdpFriendlyName", "SsdpLocation", "SsdpManufacturer", "SsdpModelName", "SsdpModelUrl", "SsdpSerialNumber", "SsdpServer","SsdpUserAgent", …
```
> luci-app-noddos: improve table header

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/switch.js
Having a description attached to a VLAN makes identification a lot easier when
dealing with many VLANs
Signed-off-by: Tobias Schramm <tobleminer@gmail.com>
> luci-mod-network: Add description field to VLANs (trivial)

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices.disabled/linksys-ea9500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
Switching to a model where device specifics are in pluggable files.
Highlight current (instead of first) partition in the list.
> luci-app-advanced-reboot: pluggable device files, highlight current partition

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices.disabled/linksys-ea9500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
Switching to a model where device specifics are in pluggable files.
Highlight current (instead of first) partition in the list.
> [19.07] luci-app-advanced-reboot: pluggable device files, highlight current partition

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
This PR is tied to changes being made via openwrt/openwrt#2654, and it
allows users to provide a certificate constraint when connecting as a
STA to an AP using Enterprise modes. The constraints can either be
provided via the certificate's X509 subject using a substring (e.g.
/CN=wifi.mycompany.com) or subject alternate name values (e.g.
DNS:wifi.mycompany.com), although both can be combined for a stricter
validation criteria.
Signed-off-by: David Lam <david@thedavid.net>
> luci-mod-network: add certificate subj validation

- applications/luci-app-vpn-policy-routing/Makefile
- applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm
- applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
Fix for the orphaned text in the view-file.
> luci-app-vpn-policy-routing: styling bugfix

- modules/luci-base/root/usr/libexec/rpcd/luci
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
luci-mod-network: add system cert bundle validation
This commit adds the ability for users to validate against the system's 
built-in CA bundle if it is installed. The process is made much easier because 
the user does not have to first extract the CA certificate from the EAPOL 
handshake and upload it via LuCI uploads. Dependent on commit 
openwrt/openwrt#2696.
luci-base: add system cert bundle detection
Add detection mechanism for system cert CA bundle installed by the 
ca-bundle package. Used by LuCI to detect whether the "Use system 
certificates" certificate validation option should be enabled.
Signed-off-by: David Lam <david@thedavid.net>
> luci-base/mod-network: add system cert bundle validation

- applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua
- applications/luci-app-mosquitto/po/templates/mosquitto.pot
Marks all the strings as translateable, which had been completely skipped in the past
Also includes a fix to the list of tls versions.
further details are in each commit
> luci-app-mosquitto: translations + option list fixes

- modules/luci-base/htdocs/luci-static/resources/luci.js
- modules/luci-base/luasrc/view/header.htm
- modules/luci-base/root/etc/config/luci
Currently the ubus path that provide the webserver is hardcoded to be /ubus.
Change this to make it configurable from the luci config file.
> luci-base: make rpc webserver path configurable

- modules/luci-base/htdocs/luci-static/resources/fs.js
- modules/luci-base/htdocs/luci-static/resources/luci.js
- modules/luci-base/htdocs/luci-static/resources/ui.js
- modules/luci-base/root/www/index.html
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js
Currently LuCI can be loaded only when placed in the root of the server as the cgi-bin paths are hardcoded. Change the index.html to load the cgi-bin path from the current level.
Also add a new entry in the env Object to make the cgi_base path easily accessible.
This variable will be based on the position of /cgi-bin/luci.
@jow- Was easier than I tought. No extra config needed. 
Should I also change the comments? 
> luci-base: remove hardcoded cgi-bin path

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
- applications/luci-app-openvpn/po/templates/openvpn.pot
The POT and PO files already contain the changed string. I changed only the POT file, Weblate will merge it to PO files and remove the unnecessary entry.
> luci-app-openvpn: fix typo

- applications/luci-app-vnstat2/Makefile
- applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js
- applications/luci-app-vnstat2/luasrc/controller/vnstat2.lua
- applications/luci-app-vnstat2/luasrc/view/vnstat2/graphs.htm
- applications/luci-app-vnstat2/po/templates/vnstat2.pot
- applications/luci-app-vnstat2/root/usr/share/rpcd/acl.d/luci-app-vnstat2.json
This adds a LuCI application for vnStat 2.x.
Depends-on: https://github.com/openwrt/packages/pull/10935
> luci-app-vnstat2: add application

- applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua
- applications/luci-app-openvpn/luasrc/view/openvpn/pageswitch.htm
Translation of page titles in the advanced configuration mode is done
in such a way that the strings to be translated are not visible for
'i18n-scan.pl' script. This commit fixes this and makes page titles
visible for the 'i18n-scan.pl'.
> luci-app-openvpn: fix advanced mode page switcher translation

- applications/luci-app-ser2net/Makefile
- applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/leds.js
- applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/proxies.js
- applications/luci-app-ser2net/htdocs/luci-static/resources/view/ser2net/settings.js
- applications/luci-app-ser2net/luasrc/controller/ser2net.lua
- applications/luci-app-ser2net/root/usr/share/rpcd/acl.d/luci-app-ser2net.json
This implements full support to the new uci config format for ser2net in luci.
Requires openwrt/packages#11086 for full functionality.
Signed-off-by: Michele Primavera <primavera@elmod.it>
> luci-app-ser2net: add app supporting ser2net

- protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js
This change allows to configure `nohostroute` option for wireguard to explicitely prevent creation
of host routes to endpoints.
By default without `option nohostroute '1'`, an explicite route to the peer's endpoint will be created in the main routing table with the next hop to the gateway. However, it causes issues with some setup. Enabling this option will inhibit this behavior. See discussions at http://lists.openwrt.org/pipermail/openwrt-devel/2019-March/016329.html.
> wireguard: add checkbox for `nohostroute` option

- applications/luci-app-wol/htdocs/luci-static/resources/view/wol.js
Use uci config 'etherwake.setup.interface' to default WOL interface
selection.
On some devices the lan interface is not the first item in the drop down
interface selection list.  Configuring this parameter allows the user to
set a preferred interface to be used/selected.
> luci-app-wol: use uci etherwake default interface

- applications/luci-app-snmpd/Makefile
luci-app-snmpd allows to configure snmpd via LuCI. Without making sure that
the snmpd package is installed, the daemon that is about to be configured via
luci-app-snmpd might be missing (unless explicitly installed otherwise).
This is not only counter-intuitive, but also inconsistent with other LuCI based
applications, as they always include the underlying package(s) in order to make
sure that the software being configured is being available in the first place.
> luci-app-snmpd: Add snmpd as dependency

- modules/luci-base/luasrc/dispatcher.lua
The cbi() function has a second argument 'config' in which various
configuration parameters can be passed. When converting the lua menu
to JSON, we must also convert this parameter.
> luci-base: Add missed config parameter for cbi when converting to JSON

- applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
Value "hours" is used twice instead of "hours" and "days".
> luci-app-ddns: fix update interval unit values in combobox

- applications/luci-app-yggdrasil/htdocs/luci-static/resources/view/yggdrasil/settings.js
Tested against yggdrasil v3.12-develop (v3.13) / APU2 x86_64 (next release expected tomorrow)
uri is required, using address was omitting listen address for: `ygguci get`   
tap interface support is removed in v3.13
do we need to update translation maps file now?
> luci-app-yggdrasil: fix listen uri type and remove tap for v3.13

- applications/luci-app-aria2/luasrc/model/cbi/aria2/config.lua
- applications/luci-app-aria2/root/etc/uci-defaults/40_luci-aria2
The "Extra Settings" section `extra_setting` option name does not match what the `net/aria2` package expects: `extra_settings`. 
See:
- https://github.com/openwrt/packages/blob/openwrt-19.07/net/aria2/files/aria2.init#L311
- https://github.com/openwrt/packages/blob/openwrt-19.07/net/aria2/files/aria2.conf#L31
Causing the luci UI "Extra Settings" option to have **no effect**. This fix renames `extra_setting` => `extra_settings`
> luci-app-aria2: fix incorrect "Extra Settings" section option name

- applications/luci-app-ledtrig-rssi/Makefile
- applications/luci-app-ledtrig-rssi/htdocs/luci-static/resources/view/system/led-trigger/rssi.js
- applications/luci-app-ledtrig-switch/Makefile
- applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch0.js
- applications/luci-app-ledtrig-switch/htdocs/luci-static/resources/view/system/led-trigger/switch1.js
- applications/luci-app-ledtrig-usbport/Makefile
- applications/luci-app-ledtrig-usbport/htdocs/luci-static/resources/view/system/led-trigger/usbport.js
- modules/luci-mod-system/Makefile
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/default-on.js
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/heartbeat.js
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/netdev.js
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/none.js
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/timer.js
- modules/luci-mod-system/htdocs/luci-static/resources/view/system/leds.js
This pullrequest is intended to create the possibility that not only kernel-led-triggers can be selected but also application-led-triggers from user space. This is done via a plugin mechanism.
Application-led-triggers are scripts that set LEDs on system events or services (for example the package rssileds service). Until now this has not been possible
The following new packages are added:
- luci-app-ledtrig-rssi (application-led-trigger) 
- luci-app-ledtrig-switch (kernel-led-trigger) not needed on every most devices
- luci-app-ledtrig-usport (kernel-led-trigger) optional trigger
Since we have now a plugin mechanism I have added the following triggers as a dependency. So this triggers are now installed per default on LuCI installation.
- kmod-ledtrig-default-on
- kmod-ledtrig-heartbeat
- …
> luci-mod-system: add led plugin infrastructure

- modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/20_memory.js
This makes sure solid/blue bar shows the used memory. Fix #3682 
Signed-off-by: Howard Su <howard0su@gmail.com>
> luci-base: Show used memory instead of Free

- applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/conntrack.js
The existing graph shows a conntrack entry usage value but doesn't show
a conntrack table size figure so you don't know if you're close to
filling the table.  Add a percent usage graph to show conntrack table
percent used.
> luci-app-statistics: conntrack: add percent usage graph

- applications/luci-app-adblock/luasrc/view/adblock/query.htm
Right now you can hit the enter key while the input field is focused, and it submits the form, but no result is displayed. Even though a POST request is made, it doesn't seem to actually be querying the domain.
It might be nice to fix that too, so it would work for users that have JavaScript disabled. But I am not sure how to make that work, so if someone can provide help with that, that would be great.
Thanks!
> luci-app-adblock query form: Fix enter key submitting form but not showing any results

- modules/luci-base/htdocs/luci-static/resources/network.js
In some cases it could be needful to check whether a new interface can be created.
This extension allows proto handlers to implement such a functionality.
The result of this check can be evaluated in interfaces.js for example and the creation can be aborted with an error message.
The implementation in interfaces.js can be found at https://github.com/openwrt/luci/pull/3713
> luci-base: extended network.js for check if new interface is createable

- applications/luci-app-attendedsysupgrade/root/www/luci-static/resources/attendedsysupgrade.js
The API of ASU changed as it now uses a static `versions` JSON file.
This moves the upgrade validation to the client site and simplifyies the
server code.
Build requests now use the unique `profile` withouth the need of sending
the devices target.
Also some XMLHttpRequests were replaced by the newer `fetch` function.
> luci-app-attendedsysupgrade: use new ASU API

- applications/luci-app-mwan3/Makefile
There is no need to depend on luci-app-firewall, so remove the dependency.
I have examined the code and cannot see any reason for the dependency
and I have built a router with luci-app-mwan3, and without firewall,
luci-app-firewall and it all functions just fine.
Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>
> luci-app-mwan3: Remove unnecessary dependency

- applications/luci-app-radicale2/Makefile
- libs/rpcd-mod-rad2-enc/Makefile
Life changes, I'm no longer avaiable to be an sufficiently active
OpenWrt developer.  Therefore removing myself from maintainer from
all packages I maintained in OpenWrt.
All the best for those who keep up the good work!
> treewide: Remove myself as maintainer

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
Previously an undocumented _default_ps_ option without a corresponding luci entry. Hotplug script was [updated](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=d3868f15f876507db54afacdef22a7059011a54e) in openwrt master to use _packet_steering_ as the option and now defaults to off since on routers it can be detrimental.
Descriptive text needs to indicate that this may help or hinder network speed without be overly verbose on, say, IRQ balancing versus packet steering. Set as optional so config entry will be removed if disabled/0.
> luci-mod-network: interfaces.js: add global packet steering option

- applications/luci-app-statistics/luasrc/statistics/rrdtool/definitions/ip6tables.lua
Permits one to obtain real-time graphs of any ip6tables chains being monitored by collectd.
Fixes issue #3760.
> add ipv6 firewall view

- applications/luci-app-dawn/Makefile
- applications/luci-app-dawn/luasrc/controller/dawn.lua
- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_config.lua
- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_hearing_map.lua
- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_network.lua
- applications/luci-app-dawn/luasrc/tools/ieee80211.lua
Dawn is a decentralized WiFi controller.
Just install dawn and the APs will find each other via umdns. They periodically exchange information about connected clients, wireless statistics and other needed information. With that, the daemon load balances clients between different APs through association control.
Luci-app-dawn is the graphical user interface.
It allows to:
- Configure dawn
- View Wireless Network Overview
- View Hearing Map
The hearing map is the list of all probe requests seen from a client from all APs that are running the controller.
https://github.com/openwrt/packages/pull/11648
> luci-app-dawn: add luci app for dawn

- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/blacklist.js
- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/whitelist.js
* disable spellcheck for black- and whitelist textareas
> luci-app-adblock: disable textarea spellcheck

- applications/luci-app-samba/luasrc/model/cbi/samba.lua
Change the link on luci samba page to point to the correct path
> luci-app-samba: Fix path url link to mounts

- applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/term.js
Fixes #3831
Since ttyd failed to build ([faillogs](https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/ttyd/)) and rpcd crashed on x86_64 snapshot, I have not tested.
> luci-app-ttyd: use correct http protocol

- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/en/https-dns-proxy.po
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
LibreDNS (libredns.gr) is a Doh service provided by LibreOps(libreops.cc), a group
of hackers around the world that are (re-)decentralizing the net.
Trying offering distributed, free (as in freedom) services to the world.
Always based on Free Open Source Software.
Signed-off-by: Konstantinos Stamou (Dinos) <github@f3rr3t.net>
> luci-app-https-dns-proxy: Add LibreDNS as a DoH provider

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
The help links (used when a certain DoH provider offers various filters on their servers) were hard-coded in the model/cbi file, they have now been moved to the providers pluggable files.
PS. As per Contributions Guidelines I'm requesting a merge access.
> luci-app-https-dns-proxy: Move help links to providers files

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
The help links (used when a certain DoH provider offers various filters on their servers) were hard-coded in the model/cbi file, they have now been moved to the providers pluggable files.
Also add LibreDNS provider which was only merged to master previously.
> [19.07] luci-app-https-dns-proxy: Move help links to providers files, Add LibreDNS

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
The help links (used when a certain DoH provider offers various filters on their servers) were hard-coded in the model/cbi file, they have now been moved to the providers pluggable files.
Also add LibreDNS provider which was only merged to master previously.
> [18.06] luci-app-https-dns-proxy: Move help links to providers files, Add LibreDNS

- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/blacklist.js
- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/dnsreport.js
- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/logread.js
- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/overview.js
- applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/whitelist.js
* this partly reverts 3c4bc22 to ensure 19.07.2 compatibility,
this is only a temporary "fix" as long as we don't have
adblock 4 backported to 19.07 branch
> luci-app-adblock: revert poll/view class changes

- modules/luci-base/root/etc/init.d/ucitrack
In file `/etc/config/ucitrack`
```
config fstab
option exec '/sbin/block mount'
```
`/sbin/block mount` never be called after fstab changed.
Signed-off-by: Liangbin Lian <1129525450@qq.com>
> ucitrack: fix bug for exec with params

- themes/luci-theme-bootstrap/root/etc/uci-defaults/30_luci-theme-bootstrap
- themes/luci-theme-material/root/etc/uci-defaults/30_luci-theme-material
- themes/luci-theme-openwrt-2020/root/etc/uci-defaults/30_luci-theme-openwrt-2020
- themes/luci-theme-openwrt/root/etc/uci-defaults/30_luci-theme-openwrt
- themes/luci-theme-rosy/root/etc/uci-defaults/30_luci-theme-rosy
If we build multi-themes into firmware, each of them set itself
to be the default theme, what theme should it be?
To make it clear, we only set mediaurlbase if the theme is the
first time to be installed/built-in.
This resolve the issue that theme always change to somewhat default
after upgrading the firmware even with a config-keep-upgrade
> set mediaurlbase only when it is the first time to be installed

- modules/luci-base/htdocs/luci-static/resources/network.js
- modules/luci-base/root/usr/libexec/rpcd/luci
Currently relay.js is included in any case even if
the router doesn't have the needed package to use it.
Fix this by checking if the system has this feature.
> luci-base: fix error 404 on missing relay protocol

- modules/luci-base/root/usr/share/rpcd/acl.d/luci-base.json
- modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js
* minimal change to accept the usual logread location
plus the alternative location (/usr/sbin/logread)
used by syslog-ng (see openwrt/packages/issues/11535 for reference)
> luci-base: accept alternative logread location

- luci.mk
zh_Hans: 简体中文 (Chinese Simplified)
zh_Hant: 繁體中文 (Chinese Traditional)
> luci.mk: correct titles of zh_Hans and zh_Hant

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices.disabled/linksys-ea9500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/luasrc/view/advanced_reboot/advanced_reboot.htm
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
This brach has severly outdated version of the package.
Changes include:
1. Pluggable device files (separate device definitions from core code)
2. Improve localization by moving from translate to translatef where needed
> [18.06] luci-app-advanced-reboot: bring up-to-date with master

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
This is to complement https://github.com/openwrt/luci/pull/3875 and bring master version number in-sync with 19.07/18.06.
If https://github.com/openwrt/luci/pull/3875 was cherry-picked for 19.07/18.06 please close this without merging.
> luci-app-simple-adblock: improve i18n

- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_hearing_map.lua
Doing a rewrite of the luci dawn hearing map in fancy table form.
Thanks to @PolynomialDivision for the work
> luci-app-dawn: Rewrite of Dawn Hearing Map in Table Form

- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_hearing_map.lua
- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_network.lua
Fixes https://github.com/berlin-open-wireless-lab/DAWN/issues/64.
The app adds config files under /etc/config/ for the Hearing Map and the Network Overview. Change to SimpleForm fixes the issue.
> luci-app-dawn: stop adding not used config files

- modules/luci-base/htdocs/luci-static/resources/form.js
Add 'nodescriptions' property to the TableSection class that allows to disable displaying table header row with descriptions.
Also fixed descriptions row rendering at actions column for some cases.
> Allow to disable descriptions row in TableSection + descriptions render fix

- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_network.lua
Based on the work of @PolynomialDivision I did a rewrite of the dawn network overview similar to https://github.com/openwrt/luci/pull/3927
> luci-app-dawn: Network Overview Rewrite with div tables

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
This patch properly sets version and status info for the first launch on fresh install, without these values, some Web UI items are not displayed.
> luci-app-simple-adblock: bugfix: get package version from opkg

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
This patch properly sets version and status info for the first launch on fresh install, without these values, some Web UI items are not displayed.
> [19.07] luci-app-simple-adblock: bugfix: get package version from opkg

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.private.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.protected.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
This patch adds support for CIRA Canadian Shield DoH servers and drops "Over" from "DNS Over HTTPS Proxy" in controller/and CBI for more compact title.
> luci-app-https-dns-proxy: add CIRA Canadian Shiled

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.private.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.protected.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
This patch adds support for CIRA Canadian Shield DoH servers and drops "Over" from "DNS Over HTTPS Proxy" in controller/and CBI for more compact title.
> [19.07] luci-app-https-dns-proxy: add CIRA Canadian Shiled

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.family.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.private.lua
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ca.cira.canadianshield.protected.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
This patch adds support for CIRA Canadian Shield DoH servers and drops "Over" from "DNS Over HTTPS Proxy" in controller/and CBI for more compact title.
> [18.06] luci-app-https-dns-proxy: add CIRA Canadian Shiled

- applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js
- applications/luci-app-vnstat2/root/usr/share/rpcd/acl.d/luci-app-vnstat2.json
This fixes the missing uci read ACL rule, and disables the delete button when the granted permissions are read-only.
Signed-off-by: Jan Hoffmann <jan@3e8.eu>
> luci-app-vnstat2: fix ACL rules, disable button on insufficient ACLs

- luci.mk
This includes `bn_BD` and `bn` via an alias.
Weblate currently does not support `bn_IN` (Indian Bangla), so I think
the alias is reasonable.
> translation: add Bengali to luci.mk

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Tested on mvebu, WRT3200ACM, 19.07.2.
> luci-app-https-dns-proxy: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
> [19.07] luci-app-https-dns-proxy: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
> [18.06] luci-app-https-dns-proxy: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-vpn-policy-routing/Makefile
- applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
- applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm
- applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
Tested on mvebu, WRT3200ACM, 18.06.8.
> luci-app-vpn-policy-routing: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-vpn-policy-routing/Makefile
- applications/luci-app-vpn-policy-routing/luasrc/controller/vpn-policy-routing.lua
- applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
- applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm
- applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot
> [19.07] luci-app-vpn-policy-routing: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Tested on mvebu, WRT3200ACM, 18.06.8.
> luci-app-simple-adblock: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
> [19.07] luci-app-simple-adblock: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
> [18.06] luci-app-simple-adblock: bugfix: remove escaped double-quotes from translateable resources

- applications/luci-app-acme/Makefile
- applications/luci-app-acme/luasrc/model/cbi/acme.lua
- applications/luci-app-acme/root/usr/share/luci/menu.d/luci-app-acme.json
- applications/luci-app-acme/root/usr/share/rpcd/acl.d/luci-app-acme.json
Move the ACME luci app from the integrated Makefile in the packages feed,
to be able to take advantage of tree-wide improvements to luci
applications, and translation.
Creating this pull request for review. Please don't merge it yet; need to sync
it with removal of the luci application from the acme package in the packages
feed.
> luci-app-acme: move from packages feed

- protocols/luci-proto-bonding/Makefile
- protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js
This is a luci implementation to configure Link Aggregation (Channel Bonding) through the netifd proto handler.
The netifd proto handler is already integrated in the OpenWrt packages.
This PR is related with #3712, #3713. 
@jow-  This is a follow-up to https://github.com/openwrt/luci/pull/3720
> luci-proto-bonding: add protohandler configuration for channel bonding

- applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/sqm.js
- applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/sqmcake.js
- applications/luci-app-statistics/root/etc/config/luci_statistics
Add graphs for sqm data collected by 'sqm_collect.sh'
An overall sqm graph displays bandwidth (kb/s), Backlog (Bytes) and
drops for each supported qdisc.
Sqm-cake supports cake's tin structure and displays many(!) graphs per
tin:
Bandwidth: Bandwidth (kb/s), bandwidth threshold (kb/s).
Latency: Target latency, Peak, Average, Sparse flow latency
Backlog v Drops: Backlog (Bytes), Drops, ECN marks, Ack-filter drops
Flow counts: Sparse flows, Bulk flows, Unresponsive flows
Fun for all the family :-)
> luci-app-statistics: add graphs for sqm-collect

- applications/luci-app-acme/luasrc/model/cbi/acme.lua
Signed-off-by: Will O'Neill <0100wrxb@gmail.com>
Maintainer: @tohojo 
Compile tested: Snapshot, default target (for makefile download of new URL)
Run tested: ramips_mt7621_DEVICE_ubnt_edgerouter-x (for shell scritp run)
Description:
1) The acme.sh project has moved on github to [acmesh-official](https://github.com/acmesh-official/acme.sh)
2) I have added some simple logic in the script to support challenge and domain aliases. These related functions allow using CNAME records from the main domain to point to a different domain where the script can modify text records.
I am preparing an associated packages commit with the script file changes.
> luci-app-acme: Update acme.sh URL, add support for challenge & domain alises.

- applications/luci-app-wireguard/luasrc/view/wireguard.htm
If nothing is configured yet for wireguard, you only see an empty box, not knowing whether there happened an error not displaying anything, machine still busy, ...
This patch adds the standard message "This section contains no values yet" for better user guidance.
> luci-app-wireguard: show hint in status page if no entry defined yet

- applications/luci-app-commands/luasrc/view/commands.htm
If no commands are defined yet, you only see an empty box, not knowing whether there happened an error not displaying anything, machine still busy, ...
This patch adds the standard message "This section contains no values yet" for better user guidance.
> luci-app-commands: show hint in status page if no entry defined yet

- modules/luci-base/po/de/base.po
... instead of a mixture of "WLAN", "W-LAN", "Drahtlos" etc.
> luci-base: German translation: Use the uniform term "WLAN"

- protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js
* add warning that `allowed_ips` must not be empty
* verify last base64 string symbol is an `=` sig
If this is not the case I get the following error during connection
```
Thu Apr 30 11:37:42 2020 daemon.notice netifd: wg1 (23647): Key is not the correct length or format: `3UW+WgCasdu1SEOngdwYZm2jc5ogAQx9GQAjCt520g01'
Thu Apr 30 11:37:42 2020 daemon.notice netifd: wg1 (23647): Configuration parsing error
```
> luci-proto-wireguard: fix value validation

- build/i18n-merge-master.pl
Refine the code to ignore apps that have been deleted from master but still exist in release branches. E.g. luci-app-samba
Previously the unhandled git error from non-existing master mangled the .po files in the release branch: the 18n header was removed and all non-ASCII chars were deleted from translation.
Fix this by processing only those files where 'git show' succeeds.
I author this in 19.07, as it can be tested there. (I will later cherry-pick it to master)
----------------
Background:
@jow- 
I have been using the merge-master script that you adapted from the idea from @urbalazs in the weblate discussion 
Generally it works ok, but has some quirks.
Two issues:
1 )
mostly information for you & others:
The working workflow requires running i18n-sync both before and after …
> build/i18n-merge-master: ignore apps deleted in master

- modules/luci-base/htdocs/luci-static/resources/validation.js
Allow only ipv4 or ipv6 addresses without IP mask.
A host IP with mask does not make sense in this context.
Without changing the validation, we could set the IPv4 11.11.11.11/24, which generate the following error on interface start.
```
Wed May 13 09:19:57 2020 daemon.notice netifd: wg1 (10779): Name does not resolve: `11.11.11.11/24:51825'
Wed May 13 09:19:57 2020 daemon.notice netifd: wg1 (10779): Configuration parsing error
```
> luci-base: fix host validation function

- modules/luci-base/htdocs/luci-static/resources/ui.js
Fix "SyntaxError: Strict mode does not allow function declarations
in a lexically nested statement" error that may occur in some old
browsers (detected on QtWebKit 5.212).
> luci-base: ui.js: fix function declaration in nested statement

- applications/luci-app-ddns/luasrc/tools/ddns.lua
`bind-host` is installed, but I got the following hint. Now fix it!
```
当前编译版本中 BusyBox 的 nslookup 在处理给定的 DNS 服务器不正确！
- 如果您需要指定 DNS 服务器来检测您注册的 IP，您应该安装“bind-host”或“knot-host”或“drill”或“hostip”软件包。
```
> [18.06] luci-app-ddns: fix huge typo in luasrc/tools/ddns.lua

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
This update contains the following:
1. Better processing of failed downloads (should be merged in sync with the principal package PR https://github.com/openwrt/packages/pull/12333)
2. Decrease reliance on shell commands (grep, awk, wc) and use Lua instead
3. The acl.d file now lists everything used by the application
> luci-app-simple-adblock: bugfix: proper processing of failed downloads; decrease reliance on shell commands; proper acl.d file

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
This update contains the following:
1. Better processing of failed downloads (should be merged in sync with the principal package PR https://github.com/openwrt/packages/pull/12334)
2. Decrease reliance on shell commands (grep, awk, wc) and use Lua instead
3. The acl.d file now lists everything used by the application
> [19.07] luci-app-simple-adblock: bugfix: proper processing of failed downloads; decrease reliance on shell commands; proper acl.d file

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
This update contains the following:
1. Better processing of failed downloads (should be merged in sync with the principal package PR https://github.com/openwrt/packages/pull/12335)
2. Decrease reliance on shell commands (grep, awk, wc) and use Lua instead
3. The acl.d file now lists everything used by the application
> [18.06] luci-app-simple-adblock: bugfix: proper processing of failed downloads; decrease reliance on shell commands; proper acl.d file

- applications/luci-app-opkg/root/usr/libexec/opkg-call
The default opkg lists dir is /usr/lib/opkg/lists rather than /tmp/opkg-lists.
https://git.openwrt.org/?p=project/opkg-lede.git;a=blob;f=libopkg/opkg_conf.h;h=37f95a1a9935d673cbba5f786d58c150a74e2fa7;hb=HEAD#l34
> luci-app-opkg: update default opkg list dir

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
- applications/luci-app-advanced-reboot/root/usr/share/rpcd/acl.d/luci-app-advanced-reboot.json
This update fixes https://github.com/openwrt/luci/issues/4135. While technically not required on stable branches, I'd prefer the stable branch PRs be merged as well to ease the supported device maintenance.
As this is a bugfix, I suggest this is merged as is and I will implement the dd_helper script in a future revision.
> luci-app-advanced-reboot: bugfix: new board names for Linksys WRT-devices

- applications/luci-app-advanced-reboot/Makefile
- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-e4200v2-ea4500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea3500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea6350v3.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8300.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea8500.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1200ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900ac.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acs.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt1900acv2.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt3200acm.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-wrt32x.lua
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/zyxel-nbg6817.lua
- applications/luci-app-advanced-reboot/luasrc/controller/advanced_reboot.lua
- applications/luci-app-advanced-reboot/po/templates/advanced-reboot.pot
- applications/luci-app-advanced-reboot/root/usr/share/rpcd/acl.d/luci-app-advanced-reboot.json
This update fixes https://github.com/openwrt/luci/issues/4135. While technically not required on stable branches, I'd prefer the stable branch PRs be merged as well to ease the supported device maintenance.
As this is a bugfix, I suggest this is merged as is and I will implement the dd_helper script in a future revision.
> [19.07] luci-app-advanced-reboot: bugfix: new board names for Linksys WRT-devices

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/diagnostics.js
discovered when iputils-ping is installed diag cant ping the v4 of domains with both A and AAAA records.
tested on snapshots with ping utils:
- iputils-ping_20190709
- BusyBox v1.31.1 (busybox ping)
> luci-mod-network: diagnostics.js: pass IP version flag to ping/ping6

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Sync with https://github.com/openwrt/packages/pull/12506.
> luci-app-simple-adblock: racially-neutral names

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Sync with https://github.com/openwrt/packages/pull/12507.
> [19.07] luci-app-simple-adblock: racially-neutral names

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
Sync with https://github.com/openwrt/packages/pull/12508.
> [18.06] luci-app-simple-adblock: racially-neutral names

- modules/luci-base/root/usr/libexec/rpcd/luci
- modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
This commit removes WEP from the list of supported encryption methods in case hostapd or wpa_supplicant were compiled without WEP support.
Currently WEP is always offered for STA as well as AP modes regardless of the support from the supplicant / hostapd.
> luci-mod-network: query WEP support

- applications/luci-app-ddns/luasrc/view/ddns/global_value.htm
class `cbi-value-description` already contains help.gif
it's not necessary to add one manually
Signed-off-by: Chuck <fanck0605@qq.com>
> [18.06] luci-app-ddns: remove duplicate help.gif

- libs/luci-lib-nixio/src/address.c
- libs/luci-lib-nixio/src/binary.c
- libs/luci-lib-nixio/src/bind.c
- libs/luci-lib-nixio/src/bit.c
- libs/luci-lib-nixio/src/file.c
- libs/luci-lib-nixio/src/fs.c
- libs/luci-lib-nixio/src/io.c
- libs/luci-lib-nixio/src/nixio.c
- libs/luci-lib-nixio/src/nixio.h
- libs/luci-lib-nixio/src/poll.c
- libs/luci-lib-nixio/src/process.c
- libs/luci-lib-nixio/src/protoent.c
- libs/luci-lib-nixio/src/socket.c
- libs/luci-lib-nixio/src/sockopt.c
- libs/luci-lib-nixio/src/splice.c
- libs/luci-lib-nixio/src/syslog.c
- libs/luci-lib-nixio/src/tls-context.c
- libs/luci-lib-nixio/src/tls-crypto.c
- libs/luci-lib-nixio/src/tls-socket.c
- libs/luci-lib-nixio/src/user.c
Lua 5.1 defines a "luaL_Reg" alias for deprecated
"luaL_reg", but Lua >= 5.2 and LuaJIT do not.
Replace by "luaL_Reg", and define a "luaL_reg"
alias in case we build with old Lua 5.0.
Signed-off-by: Manuel BACHMANN <tarnyko@tarnyko.net>
> luci-lib-nixio: allow building with Lua5.2/LuaJIT

- applications/luci-app-mwan3/root/etc/uci-defaults/60_luci-mwan3
Remove uci track handling. This is now done with procd in mwan3.
https://github.com/openwrt/packages/pull/12533
> luci-app-mwan3: use ucitrack is now done with mwan3 procd

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Remove eDNS support per https://github.com/openwrt/luci/issues/4195.
> luci-app-https-dns-proxy: bugfix: remove eDNS support

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Remove eDNS support per https://github.com/openwrt/luci/issues/4195.
> [19.07] luci-app-https-dns-proxy: bugfix: remove eDNS support

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
- applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
Remove eDNS support per https://github.com/openwrt/luci/issues/4195.
> [18.06] luci-app-https-dns-proxy: bugfix: remove eDNS support

- protocols/luci-proto-sstp/Makefile
- protocols/luci-proto-sstp/htdocs/luci-static/resources/protocol/sstp.js
This is the "luci-proto-sstp" implementation to support SSTP via the sstp-client package from LUCI.
This is a follow up to this PR: https://github.com/openwrt/luci/pull/3071
This work is inspired by the work of @harveyhu2012 and has been ported to the new Javascript based LUCI API.
One thing to note is that this requires sstp-client with at least version 1.0.12.3. I noticed that the version included in the latest OpenWRT version 19.07.3 is still at the previous 1.0.12.2 version of sstp-client which is not compatible.
Signed-off-by: Robert Koszewski <rkkoszewski@gmail.com>
> Add luci-proto-sstp implementation

- applications/luci-app-smartdns/Makefile
- applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
- applications/luci-app-smartdns/po/zh-cn/smartdns.po
- applications/luci-app-smartdns/root/usr/share/luci/menu.d/luci-app-smartdns.json
- applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json
This luci app supports smartdns.
Depends on openwrt/packages#10797.
Signed-off-by: Nick Peng <pymumu@gmail.com>
> luci-app-smartdns: add new package

- libs/luci-lib-nixio/src/address.c
- libs/luci-lib-nixio/src/binary.c
- libs/luci-lib-nixio/src/nixio.h
This fixes compilation under GCC10.
There's no reason for this to be in a C file anyway.
Also fixed a -Wmissing-prototypes warning with nixio__addr_prefix.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> move nixio__bin2hex to header and make static

- protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
Add ModemManager specific error messages to indicate the status of the modem during operation.
Requires https://github.com/openwrt/packages/pull/12775
Signed-off-by: Nicholas Smith <nicholas.smith@telcoantennas.com.au>
> luci-proto-modemmanager: add modem specific error messages

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/zone-details.lua
maintainer: me
tested: Linksys WRT3200ACM
description:
resolves #4174 and picks up options from https://github.com/openwrt/packages/pull/12798
> luci-app-unbound: add rate_limit and dns_assist option support

- modules/luci-compat/luasrc/view/cbi/button.htm
- modules/luci-compat/luasrc/view/cbi/delegator.htm
- modules/luci-compat/luasrc/view/cbi/error.htm
- modules/luci-compat/luasrc/view/cbi/ipaddr.htm
- modules/luci-compat/luasrc/view/cbi/nsection.htm
- modules/luci-compat/luasrc/view/cbi/simpleform.htm
- modules/luci-compat/luasrc/view/cbi/tblsection.htm
- modules/luci-compat/luasrc/view/cbi/tsection.htm
- modules/luci-compat/luasrc/view/cbi/ucisection.htm
This fixes the view of the buttons, that are still written in lua and therefore use luci-compat.
The buttons do not look nice when using the new luci-theme-openwrt-2020 theme.
Therefore I have added the btn css class to every button input in this pullrequest
Before the change:
After the change:
> luci-compat: add btn class to all button inputs

- applications/luci-app-uhttpd/luasrc/model/cbi/uhttpd/uhttpd.lua
Clarify DER support as having DER and PEM support.
Issue #4248's request.
maintainer: @cshoredaniel
Signed-off-by: Aaron Tiensivu <atiensivu@users.noreply.github.com>
> luci-app-uhttpd: fix translation for key option

- modules/luci-base/htdocs/luci-static/resources/tools/widgets.js
By using `widgets.UserSelect` the user list is appended to the dropdown again each time the page is loaded.
Although I'm not sure whether this PR is the correct solution to the problem I experienced it is working.
I came across this problem during the implementation of the LuCI xinetd module (https://github.com/openwrt/luci/pull/4178)
when @jow- gave me the hint to use the `widgets.UserSelect` instead of the local realization.
> luci-base: fix widgets CBIUserSelect appending list on load

- applications/luci-app-xinetd/Makefile
- applications/luci-app-xinetd/htdocs/luci-static/resources/view/xinetd/xinetd.js
- applications/luci-app-xinetd/po/de/xinetd.po
- applications/luci-app-xinetd/po/en/xinetd.po
- applications/luci-app-xinetd/po/templates/xinetd.pot
- applications/luci-app-xinetd/root/usr/share/luci/menu.d/luci-app-xinetd.json
- applications/luci-app-xinetd/root/usr/share/rpcd/acl.d/luci-app-xinetd.json
This is a luci application to configure xinetd services.
Only the (probably) most used parameters are implemented for now.
This package depends on PR in another repo (https://github.com/openwrt/packages/pull/12389)
> luci-app-xinetd: add new package

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua
> luci-app-https-dns-proxy: fix bootstrap_dns for cloudflare security

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua
> [19.07] luci-app-https-dns-proxy: fix bootstrap_dns for cloudflare security

- applications/luci-app-https-dns-proxy/Makefile
- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.security.lua
> [18.06] luci-app-https-dns-proxy: fix bootstrap_dns for cloudflare security

- applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js
- applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/instances.js
Following changes are related and included in the same commit
- Deprecate bind_address by not displaying and handling it in the UI
- Allow ipv6 address for the old local_address option
Depends on openwrt/packages#12945
> luci-app-shadowsocks-libev: local_{ipv4,ipv6}_address for ss_server

- modules/luci-base/root/usr/libexec/rpcd/luci
This PR fixes a bug, visible on LuCI Switch Settings on a Netgear R7800:
When navigating to Network -> Switch everything but the Port Status loads immediately.
This is caused by `getSwconfigPortState` returning more port states than exist, which is caused by a too lax [RegEx](https://github.com/openwrt/luci/blob/6d59a6400ed055d71e0b335679d291c22bbdbd40/modules/luci-base/root/usr/libexec/rpcd/luci#L370).
On a R7800 `swconfig dev switch0 show` (called by `getSwconfigPortState`) returns additional port information (ARP table) as global attributes:
```
root@OpenWrt:~# swconfig dev switch0 show
Global attributes:
enable_vlan: 1
[…]	
arl_table: address resolution table
Port 0: MAC b0:7f:b9:xx:xx:xx
Port 3: MAC b8:27:xx:xx:xx:xx
Port 4: MAC 64:4b:xx:xx:xx:xx
Port 5: MAC 5c:e2:xx:xx:xx:xx
Port 5: …
```
> luci-base: Fixed delayed portstatus loading on R7800

- applications/luci-app-ttyd/htdocs/luci-static/resources/view/ttyd/config.js
@ysc3839 Can you see if the combinations match.
Add only allowed debug value as a drop down.
This depends on [pullrequest](https://github.com/openwrt/packages/pull/13011).
> luci-app-ttyd: add debug value list

- applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.alidns.dns.lua
It's difficult to use Cloudflare or the DNS provided by Google in China, which means that users with https-dns-proxy enabled will have trouble accessing the site properly.
Alibaba Group now offers DoH services to regular users, so I added AliDNS servers to give users located in China the option to use them.
Signed-off-by: Yuan Tao ty@wevs.org
> luci-app-https-dns-proxy: add AliDNS DoH servers

- applications/luci-app-statistics/luasrc/statistics/rrdtool.lua
Fixes rendering errors when RRD file names contain IPv6 addresses and the colon (":") characters are double-escaped under OpenWrt 19.07.3.
Before this change, adding an IPv6 address to the `collectd-mod-ping` configuration results in broken "Ping" graph images in Luci when viewing `/cgi-bin/luci/admin/statistics/graph/ping`.
The following messages are written to the system log and can be viewed via `logread | grep "can't parse"`:
```shell
Thu Aug  6 00:35:56 2020 daemon.err uhttpd[1656]: ERROR: can't parse DEF '2ping_avg_raw=/tmp/rrd/OpenWrt/ping/ping-\\:\\:1.rrd:value:AVERAGE' -2
Thu Aug  6 00:35:56 2020 daemon.err uhttpd[1656]: ERROR: can't parse DEF '2ping_droprate_avg_raw=/tmp/rrd/OpenWrt/ping/ping_droprate-\\:\\:1.rrd:value:AVERAGE' -2
Thu Aug  6 00:35:56 2020 daemon.err …
```
> luci-app-statistics: remove rrd path double escape

- applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm
Interface grid can become misaligned due to varying number of
lines. Use non-breaking spaces to ensure all interface boxes are three
lines long.
Fixes #4352
> luci-app-mwan3: fix interface grid

- applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
- applications/luci-app-dockerman/luasrc/model/cbi/dockerman/container.lua
- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
- build/i18n-init.sh
- libs/luci-lib-nixio/src/Makefile
Fix shellcheck SC2230
> which is non-standard. Use builtin 'command -v' instead.
Once applied to everything concerning OpenWrt we can disable the busybox
feature `which` and save 3.8kB.
> treewide: replace `which` with `command -v`

- applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua
- applications/luci-app-unbound/luasrc/model/cbi/unbound/zone-details.lua
Cherry-pick master 11f72bbca
Relates to merged PR openwrt/packages#13046
> [19.07] luci-app-unbound: add rate_limit and dns_assist option support

- collections/luci-ssl/Makefile
OpenWrt installs WolfSSL per default to offer WPA3. To save some space
switch to a WolfSSL based px5g implementation for self-signed
certificate generation instead of a MbedTLS version.
> luci-ssl: switch to WolfSSL

- modules/luci-base/luasrc/dispatcher.lua
- modules/luci-base/luasrc/view/error404.htm
message was only being shown in the plain text case when the render
failed.
> luci-base: dispatcher: error404: flow message into template

- protocols/luci-proto-openfortivpn/Makefile
- protocols/luci-proto-openfortivpn/htdocs/luci-static/resources/protocol/openfortivpn.js
Create a luci interface for the openfortivpn netifd protocol.
@jow- Is there anyway to exclude the current interface name in the `widgets.NetworkSelect` selector? I'd like to make it impossible for the user to accidentally try to use their new vpn interface as the bound interface.
cc: @lucize 
Signed-off-by: Aaron Goodman <aaronjg@stanford.edu>
> luci-proto-openfortivpn: add luci interface for openfortivpn

- applications/luci-app-nft-qos/luasrc/model/cbi/nft-qos/nft-qos.lua
This patch adds MAC address based speed limit to luci.
This patch is used together with nft-qos-mac.
See https://github.com/openwrt/packages/pull/13097
Signed-off-by: Tong Zhang <ztong0001@gmail.com>
Screenshot below
> luci-app-nft-qos: support mac address based speed limit

- protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/map.js
legacymap causes map to use the legacy IPv6 Interface Identifier format
that was described in draft-ietf-softwire-map-00, but was eventually
changed in RFC7597. It is however still used by some major ISPs,
including in Japan.
Signed-off-by: Remi NGUYEN VAN <remi.nguyenvan+openwrt@gmail.com>
> protocols: add legacymap option for map

- protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/map.js
"type" is already used as a common option for all protocols. This makes
the configuration ambiguous, and Luci sees JS errors when trying to save
a MAP configuration.
Switch to "maptype" instead to avoid the conflict. MAP currently uses
"maptype" and falls back to "type" when not specified.
Signed-off-by: Remi NGUYEN VAN <remi.nguyenvan+openwrt@gmail.com>
> protocols: rename type to maptype for map

- applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
This is a partial backport of dc57e4bc6c83d6c869c318256057e3636bfc5d66
Fixes: #4077
Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>
> [19.07] luci-app-opkg: flush menu cache after opkg actions

- applications/luci-app-ttyd/root/usr/share/luci/menu.d/luci-app-ttyd.json
Nobody can do anything with the title ttyd.
To make it more meaningful the menu entry is renamed to Terminal.
> luci-app-ttyd: rename menu entry to terminal

- libs/luci-lib-ip/src/ip.c
The bug can be reproduced with the following script at least in qemu and mips.
```
local ip = require("luci.ip")
for i = 1,10,1 do
print(ip.MAC('a8:40:41:1c:aa:aa'):tolinklocal())
end
```
```
root@node:~# lua linklocak.lua 
fe80:736f:2f:6970:aa40:41ff:fe1c:aaaa
fe80:2f6c:7561:2f6c:aa40:41ff:fe1c:aaaa
fe80:bc90::aa40:41ff:fe1c:aaaa
fe80:272e:2f6c:7563:aa40:41ff:fe1c:aaaa
fe80:4::aa40:41ff:fe1c:aaaa
fe80:4::aa40:41ff:fe1c:aaaa
fe80:31::111:aa40:41ff:fe1c:aaaa
fe80:a09:6e6f:2066:aa40:41ff:fe1c:aaaa
fe80::aa40:41ff:fe1c:aaaa
fe80::aa40:41ff:fe1c:aaaa
```
> luci-lib-ip: fix tolinklocal invalid ipv6 result

- applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool.js
It is sometimes useful not to display avg values int the graph.
This option is used to prevent this from appearing in the graph.
In a graph definition this option must be set to *true*,
if the avg values should not be displayed.
```
options = {
gauge = {
title = "Status",
color = "0000ff",
noarea = true,
noavg = true
}
```
> luci-app-statistics: add noavg option

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
Address is very useful in dnsmasq. I don't see a reason why we should not have it in the form
> luci-mod-network: add address parameter in DHCP for dnsmasq

- modules/luci-base/htdocs/luci-static/resources/protocol/dhcp.js
We must be able to translate these values.
Fixes: fd75c2b7c ("luci-base: add default value options dhcp hostname")
> luci-base: make translatable default values for dhcp hostname

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
Also small tweaks for controller and ACL. Dependent on https://github.com/openwrt/packages/pull/13434.
> [19.07] luci-app-simple-adblock: support for config auto-update

- applications/luci-app-simple-adblock/Makefile
- applications/luci-app-simple-adblock/luasrc/controller/simple-adblock.lua
- applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
- applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
- applications/luci-app-simple-adblock/root/usr/share/rpcd/acl.d/luci-app-simple-adblock.json
Also small tweaks for controller and ACL. Dependent on https://github.com/openwrt/packages/pull/13435.
> [18.06] luci-app-simple-adblock: support for config auto-update

- applications/luci-app-mwan3/luasrc/model/cbi/mwan/interfaceconfig.lua
@feckert LuCI currently sets the following defaults if they are not directly set on interface configurations.
Option | LuCI default  | mwan3track default  |
| :------------- |-------------| -----|
| `up`  | `3` | `5` |
| `down`  | `3` |  `5` |
| `interval` | `5` | `10` |
| `timeout` | `2` | `4` |
These are different to the defaults specified by mwan3track, so this updates them to match.
> luci-app-mwan3: Update default values for down, up, timeout and interval on interfaces

- applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js
- applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns
- applications/luci-app-ddns/root/usr/share/rpcd/acl.d/luci-app-ddns.json
This commit rework the app with the new ddns changes. DDns services are now stored in a dedicated list and the service specific data is stored in a dedicated json. This json can both preinstalled with a companion package or be downloaded on demand. The new app now check if the script is present and give a button to install it if not present in the system.
The app now reset the ddns rule settings on service change.
Also rework the app to drop any global function and rework the function to use more default way to get data.
@feckert this should be the changes needed. Can you check and give some suggestion about variable naming (it's a mess) and if i miss something of the new feature?
(in short, I added
- the global ca_cert and url option
- in status a way to get last modified services list
- …
> luci-app-ddns: rework with new ddns changes

- applications/luci-app-advanced-reboot/README.md
- applications/luci-app-advanced-reboot/luasrc/advanced-reboot/devices/linksys-ea7300.lua
Add support for new (recently supported) hardware. Image with this change in place,
Thanks!
> luci-app-advanced-reboot: Advanced Reboot support for Linksys EA7300 v2

- modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
The mac section for the static lease doesn't correctly handle when multiple mac are set for a rule.
Fixes: #4291
@jow- 
> luci-mod-network: handle multiple mac for static lease
