openwrt/luci

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

This allows the configuration of `acme_server` from the LuCI application.
Signed-off-by: Jannis Pinter <jannis+openwrt@pinterjann.is>

luci-app-acme: Add option for custom ACME server

---

applications/luci-app-dockerman/luasrc/view/dockerman/apply_widget.htm
modules/luci-base/luasrc/model/uci.lua
modules/luci-base/luasrc/view/header.htm

cc @jow- @feckert 
luci-base & luci-app-dockerman: set the fallback default of rollback timeout to 90s
Set the fallback value of the config change rollback timeout to 90 seconds to match the change in /etc/config/luci by commit 81cf99a50.
That commit changed the default value in the config file, but did not change the underlying fallback values that do get applied when there is no proper config item in etc/config/luci.
Users sysupgrading from old systems may have carried an ancient /etc/config/luci (without rollback config) with them, so this change should help them to see the intended user experience of 90 seconds instead of 30 seconds that may be too short e.g. for wifi changes.
Related to forum discussion at https://forum.openwrt.org/t/luci-changing-wifi-config-results-in-timeout/77104/ …

Set the fallback default of rollback timeout to 90s

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

This changes the layout of the certificate section. The configuration is now **organized in tabs** and mutually exclusive options are hidden, which makes it **more accessible for the end user**.
For a standard configuration (fetch a certificate from Let's Encrypt using standalone mode), only the `General Settings` tab needs to be configured/adapted. Anything else can be found in either the `Services`, `Challenge Validation` or the `Advanced Settings` tab.
This change also adds the `Days until renewal` option, which can be used later on by the `acme` package to set the `--days` option in `acme.sh`.
**Note:** @tohojo and others: This is a proposal, please give me some feedback on what you like/dislike with this new tabbed UI. You can find a demo of the new UI below.
Signed-off-by: Jannis …

luci-app-acme: Use tabs for certificate section

---

applications/luci-app-sqm/htdocs/luci-static/resources/view/network/sqm.js

Show device instead of interface in interface selection.
Fixes: #4539

luci-app-sqm: fix missing interface in selection

---

applications/luci-app-transmission/Makefile

In recent changes in packages feed
(https://github.com/openwrt/packages/commit/56e4edad82211c14528122566f56168f1bee0fd8),
there were removed variants, so if you will install
luci-app-transmission now, it will pull also transmission-daemon
and users do not need to install it separately.
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>

luci-app-transmission: add dependency for transmission-daemon

---

applications/luci-app-bmx7/root/usr/lib/lua/luci/view/admin_status/index/bmx7_nodes.htm
applications/luci-app-bmx7/root/usr/lib/lua/luci/view/bmx7/nodes_j.htm
applications/luci-app-bmx7/root/usr/lib/lua/luci/view/bmx7/status_j.htm
applications/luci-app-bmx7/root/usr/lib/lua/luci/view/bmx7/tunnels_j.htm
applications/luci-app-bmx7/root/www/cgi-bin/bmx7-info

nice to see luci-app-bmx7, but nothing goes except the topology sub-page.
here is a fix for all other status pages. modern webbrowsers do convert the $ to %24.
info-page is reloaded too much atm, so i delayed it.
p.s. do i have to pull-request this for openwrt-1907 repo too? would be a nice small test for opkg upgrade
Signed-off-by: FreifunkUFO ufo@rund.freifunk.net
see also: https://github.com/openwrt/luci/pull/4144 as first try to fix this bug some months ago

luci-app-bmx7: fix displaying values

---

modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-compat/luasrc/view/cbi/nsection.htm
modules/luci-compat/luasrc/view/cbi/nullsection.htm
modules/luci-compat/luasrc/view/cbi/tsection.htm
themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The `legend` HTML element is allowed only as first element in `fieldset`, so use `h3` instead, which is rendered the same within themes.
Fixes #3149.

luci-base/luci-compat: Replace legend element with h3.

---

protocols/luci-proto-gre/htdocs/luci-static/resources/protocol/gre.js
protocols/luci-proto-gre/htdocs/luci-static/resources/protocol/gretap.js
protocols/luci-proto-gre/htdocs/luci-static/resources/protocol/grev6.js
protocols/luci-proto-gre/htdocs/luci-static/resources/protocol/grev6tap.js

Code has been modified to better handling of the protocol settings (especially handling of ToS and TC values).
When creating a new interface, the optional value specifying the local endpoint address is pre-filled in the form, based on the current address of wan interface.

luci-proto-gre: improvements of interface

---

modules/luci-base/root/usr/libexec/rpcd/luci
modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Add a way to trigger and get the WPS Push Button status from the webui if supported.
Not in UTOPIA but I think it should. If the system supports this feature any type of check or trigger is absent in the webui. This feature can only be manage with the hardware button. Since the button call the exact same command, we can easily simulate this.
If this gets approved, I would ask some improvement for this... 
Is the button in the badge acceptable? How can I change this to make things better?
Also I would make the check for hostapd_cli as and env variable like we do with dnsmasq...
To clean things a bit, is it necessary to have global function instead of adding them in the view struct?
Fixes: #1072

luci-mod-status: add WPS control for wifi info

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js

Introduce a button in the status lease table to quickly add an host as static.
This would address #3681 . I notice it would be not that hard to implement and I'm here to propose a version of it. (the quickest)
Another version would be show a modal with the text autocompleted.
For ipv4 this creates a host rule named with the mac address (without the : ) and with ip mac and hostname (or '-') or the lease.
For ipv6 the rule is named with the mac address and with only the duid and the mac address.
@jow- sorry for the tag but this would remove an issue from UTOPIA :D

luci-mod-status: add support for one-click static lease

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js

The "Match ICMP type" drop-down menu was missing this ICMPv6 type. According to RFC 4890 section 4.3.1 it is essential for communications and must not be dropped. This patch allows for doing this through LuCI.

luci-app-firewall: rules: add ICMPv6 Packet Too Big (Type 2)

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js

The "Match ICMP type" drop-down menu was missing this ICMPv6 type. According to RFC 4890 section 4.3.1 it is essential for communications and must not be dropped. This patch allows for doing this through LuCI.

[19.07] luci-app-firewall: rules: add ICMPv6 Packet Too Big (Type 2)

---

applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua

Supported since mosquitto 1.5 released in May 2018, and has long
been supported in the init scripts.

master: mosquitto: support notifications_local_only flag

---

applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua

Supported since mosquitto 1.5 released in May 2018, and has long
been supported in the init scripts.

19.07: mosquitto: support notifications_local_only flag

---

libs/luci-lib-base/luasrc/util.lua

It might happen (e.g. when downloading a large file with low speed connection) that the ubus connection will time out.
The ubus_connect function allows to specify ubus socket path and ubus connection timeout so it should allowed to set these arguments from luci.

luci-base: Add possiblity to set path and timeout of ubus connection

---

modules/luci-base/htdocs/luci-static/resources/form.js

The `onchange` notification handler is called too early to be able to evaluate other widget's `isActive()` status. Solve this by changing order of event handling - first register/execute `map.checkDepends` and then `onchange`.
Fixes: openwrt/luci#4516.

luci-base: Fix using isActive in widget-change notification.

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
themes/luci-theme-material/htdocs/luci-static/material/cascade.css

Add support for one-click add device to wifi black/whitelist in the status page. If the black/whitelist feature is enabled a combobox is displayed with the disconnect option.
Device already added will display only the disconnect button.
Fixes: #3675
@jow-  Another easy UTOPIA task ahahha
The first commit is needed since  theme-material have a display bug that show all the combo box bigger than expected....
(is problematic with the new introduced combobox in the wifi row)
Also is there a way to make the disconnect button display first?

luci-mod-status: add support for add device to wifi black/whitelist

---

applications/luci-app-upnp/htdocs/luci-static/resources/view/upnp/upnp.js

STUN support has been added to upnp init but luci lacks support of it.
Fixes: #4544

luci-app-upnp: add stun support

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

WiFi join won't work if is tried to connect to a Hidden Wifi without specifying the WiFi SSID.
Fixes: #2085

luci-mod-network: require ssid when join hidden wifi

---

protocols/luci-proto-gre/htdocs/luci-static/resources/protocol/grev6.js

fix the following error:
SyntaxError
Unexpected token ')'
in http://192.168.122.131/luci-static/resources/protocol/grev6.js:?
at http://192.168.122.131/luci-static/resources/luci.js:22
at async Promise.all (index 4)
at async Promise.all (index 5)
Fixes: 2b7fd1292 ("luci-proto-gre: improvement of LuCI interface")
Signed-off-by: Chuanhong Guo <gch981213@gmail.com>
Not quite sure how the developments here works so I decided to create a PR.

luci-proto-gre: remove extra parenthesis

---

applications/luci-app-mwan3/luasrc/model/cbi/mwan/globalsconfig.lua
applications/luci-app-mwan3/luasrc/model/cbi/mwan/interface.lua
applications/luci-app-mwan3/luasrc/model/cbi/mwan/ruleconfig.lua

- Use standard LuCI variable name for map, section and option as m, s and o
- Add missing family selection on rulconfig (any | IPv4 | IPv6) if any is selected the rule is applied to IPv4 and IPv6
- Add dependency to port option. This is only valid if proto is tcp or udp

luci-app-mwan3: rulconfig variable name refactoring and dependency fixes

---

protocols/luci-proto-qmi/htdocs/luci-static/resources/protocol/qmi.js

This change add the following missing default options.
- defaulroute
- peerdns
- metric
This should fixes #4577 
@Nowaker **Since I do not use the qmi I cannot test it**.
Can you please check if it meets your requirements and give a feedback?

luci-proto-qmi: add missing proto default options

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/routes.js

Add protocol column to the active routes tables. The route protocol is
for example helpful when using a dynamic routing daemon, such as bird or
babel.

luci-mod-status: routes.js: add route protocol

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

Add support for the cell_density option added to OpenWRT via commit:
81ff23fc91dbbedc374e58afdb4b0b13146c0f15
This configures data rates based on the coverage cell density.
Normal configures basic rates to 6, 12, 24 Mbps if legacy 802.11b rates
are not used else to 5.5, 11 Mbps.
High configures basic rates to 12, 24 Mbps if legacy 802.11b rates are
not used else to the 11 Mbps rate.
Very High configures 24 Mbps as the basic rate. Supported rates lower
than the minimum basic rate are not offered.
Signed-off-by: Nick Lowe <nick.lowe@gmail.com>

luci-mod-network: wireless.js cell_density support

---

modules/luci-base/luasrc/sys.lua

The special characters '!' and '*' in /etc/shadow are
used to disable password login for a specific account.
The character 'x' has no special meaning, but should not
be interpreted as an empty password.
However, Luci treats the special characters '!' and 'x' like no password is
set and displays the "No password set!" notification.
As this might be misleading, the extra check for these special
characters is removed, so the invalid hash is returned in that case.
This aligns the behavior of this notification with a change in rpcd,
which also removed these extra checks, so no login is possible, if
password login is disabled [1].
[1] https://git.openwrt.org/?p=project/rpcd.git;a=commit;h=3df62bcebd2caff47506ccffb42df8d2d2123c06
Signed-off-by: Fabian Bläse <fabian@blaese.de>

luci-base: hide "No password set!" notification if password login is disabled

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js

Reset the WPS_button variable to correctly add the button to the enabled interface.
@jow- 
Fixes: #4625

luci-mod-status: fix WPS button to wrong interface

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

The time has long come where 802.11b DSSS/CCK data rates should be disabled
by default in OpenWRT. Users in need of 802.11b client support can reasonably
enable these where they are needed.
The balance of equities has significantly, and for a long time, tipped
such that dropping backwards compatibility by default with 802.11b
devices is appropriate, proportionate and justified. By doing so,
management and control traffic is moved by default to a 20
MHz wide 6 Mb/s OFDM data rate instead of a 22 MHz wide 1 Mb/s data rate.
This is significantly more airtime efficient.
Signed-off-by: Nick Lowe nick.lowe@gmail.com

luci-mod-network: wireless.js Disable 802.11b by default

---

libs/rpcd-mod-luci/Makefile
libs/rpcd-mod-rad2-enc/Makefile
libs/rpcd-mod-rrdns/Makefile

Usage of killall is replaced with init script. This is cleaner solution
as it does not consider some implementation detail but rather passes
that on to init script implementation.
IPKG_INSTROOT was added to prevent execution when not running in current
root. It is invalid to request reload if install-root is not current
root. In this case it can be considered harmless but it is invalid
nonetheless.
Last change is removal of `exit 0`. This caused skip of default
postinst. Execution of default postinst does no harm and is more
standard considering possible future expansion of it.

rpcd-mod-*: improve postinst script

---

applications/luci-app-firewall/htdocs/luci-static/resources/tools/firewall.js

Before the change, the options '*' and 'any' in the drop down were not
recognized as valid options, when loaded from the uci. With this change,
the options '*' and 'any' are mapped to 'all' and saved as such. This
change is especially important if the proto option is changed manually
to '*' or 'any' in shell and then further configured via LuCI.

luci-app-firewall: map proto '*' and 'any' to all on rule config

---

applications/luci-app-advanced-reboot/Makefile

This package has converted to client side and doesn't need `luci-compat` any more.

luci-app-advanced-reboot: drop luci-compat dependency

---

applications/luci-app-babeld/Makefile
applications/luci-app-babeld/luasrc/model/cbi/babeld.lua
applications/luci-app-babeld/root/usr/share/luci/menu.d/luci-app-babeld.json
applications/luci-app-babeld/root/usr/share/rpcd/acl.d/luci-app-babeld.json

Add overview of babeld status, xroutes and routes.

luci-app-babeld: add babeld overview

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

luci-mod-network Describe issues: Hidden SSID, WMM
The performance and reliability implications of hiding SSIDs or disabling
WMM are not commonly known and these settings often end up being
misconfigured to harmful effect.
To seek to mitigate this, add descriptions explaining that:
Where the ESSID is hidden, clients may fail to roam and airtime efficiency
may be significantly reduced.
Where Wi-Fi Multimedia (WMM) Mode QoS is disabled, clients may be limited
to 802.11a/802.11g rates.
Signed-off-by: Nick Lowe <nick.lowe@gmail.com>

luci-mod-network Add description: Hidden SSID, WMM

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json

compiled/tested for rampis/er-x/19.07.5

luci-app-https-dns-proxy: WebUI for dnsmasq config update, quad9 bootstrap IPv6

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json

compiled/tested for rampis/er-x/19.07.5

[19.07] luci-app-https-dns-proxy: WebUI for dnsmasq config update, quad9 bootstrap IPv6

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/controller/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns10.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns11.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.quad9.dns9.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/rpcd/acl.d/luci-app-https-dns-proxy.json

compiled/tested for rampis/er-x/19.07.5

[18.06] luci-app-https-dns-proxy: WebUI for dnsmasq config update, quad9 bootstrap IPv6

---

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js

```sh
commit 05328b2746602a7dd35e3b9e89448986438e7492
Author: Peter Somogyvari <peter.metz@unarin.com>
Date:   Mon Dec 21 11:39:31 2020 -0800
luci-app-ddns: whitespace fixes in overview.js
No change in logic, just the whitespace fixes
as picked up by VSCode's auto-formatter.
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
```

luci-app-ddns: whitespace fixes in overview.js

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

luci-theme-bootstrap: fix text wrapping in buttons

---

applications/luci-app-sqm/htdocs/luci-static/resources/view/network/sqm.js

The sqm-scripts package depends on kmod-sched-cake, meaning CAKE is always
available in normal installs. So we might as well just make CAKE the
default config in SQM configs.

luci-app-sqm: Use CAKE as default qdisc

---

modules/luci-base/root/usr/libexec/rpcd/luci
modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

OpenWrt commit 1a9b896d ("treewide: nuke DRIVER_11W_SUPPORT") enables
802.11w feature for all wpad/hostapd configurations. The feature flag
was removed at all but for the compatibility reasons 11w is still
advertised (but there's a plan to nuke it also) [1].
Remove conditional 802.11w LuCI support to match current behavior.
[1]: https://github.com/openwrt/openwrt/pull/3347
Signed-off-by: Dobroslaw Kijowski <dobo90@gmail.com>

luci-mod-network: skip check for 802.11w feature

---

modules/luci-base/htdocs/luci-static/resources/firewall.js
modules/luci-base/htdocs/luci-static/resources/tools/prng.js
modules/luci-base/htdocs/luci-static/resources/ui.js
modules/luci-mod-status/htdocs/luci-static/resources/svg/channel_analysis.svg
modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
modules/luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Add channel analysis support. This can be very useful as a user can directly use the webui to check wifi channel utilization without using external tool. This use data already provided by iwinfo.
@jow- This is the """final""" implementation. If you are fine with this (and after some feedback with some testing), we still need to decide where to put this.  @hnyman advised to put this in a separate status menu. Currently this is added to the join wifi modal.
(some details about how the page works, a tab with all the radios is created. The pool function is unique and use the custom event 'tab-change' to detect the tab displayed and based on the tab name, updates the related graph and table. Multiple pool function were not acceptable since this would overload the wifi driver and also slowdown …

luci-mod-status: add new channel analysis page

---

modules/luci-mod-system/Makefile

~The kmod packages were dropped from OpenWrt,~
~and the led triggers are now kernel built-in.~
...Not yet, but it will be.
This is the counterpart of openwrt/openwrt#3754.

[RFC] luci-mod-system: drop kmod-ledtrig-* dependency

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

Signed-off-by: Nicholas Smith <nicholas@nbembedded.com>
LuCI support for signal refresh rate support added in PR https://github.com/openwrt/packages/pull/13009

luci-proto-modemmanager: add support for specifying signal refresh rate

---

applications/luci-app-softether/Makefile
applications/luci-app-softether/htdocs/luci-static/resources/view/softether-status.js
applications/luci-app-softether/root/usr/libexec/vpncmd-call
applications/luci-app-softether/root/usr/share/luci/menu.d/luci-app-softether.json
applications/luci-app-softether/root/usr/share/rpcd/acl.d/luci-app-softether.json

This adds a basic SoftEther VPN client status page.
I have tested/using it on 19.07.4 mir3g.

luci-app-softether: add basic softether status page

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns1.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns2.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

This implements support for editing DSCP codepoints/tagging in WebUI.

luci-app-https-dns-proxy: DSCP tagging support

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns1.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns2.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

This implements support for editing DSCP codepoints/tagging in WebUI.

[19.07] luci-app-https-dns-proxy: DSCP tagging support

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns1.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ca.dnscrypt.dns2.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

This implements support for editing DSCP codepoints/tagging in WebUI.

[18.06] luci-app-https-dns-proxy: DSCP tagging support

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js
applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/zones.js
modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js

@jow- I just have a use case where I need a generic tooltip handling.
Please have a look at this [commit](https://github.com/openwrt/luci/commit/c2f4e917cd099e0516bd7b80fa63482d6e17482c)
I want to output a hint in the LuCI that only restricted masquerading is enabled.
This has led to problems several times.
To map this correctly I have integrated into the Luci framwork.

luci-base: add generic tooltip handling

---

modules/luci-base/htdocs/luci-static/resources/luci.js

The try/catch is meant for the `res.json()` call and should only apply to that. As it was before, an exception inside the poll callback would cause the callback to be reinvoked without the JSON parameter, which is an odd behaviour. Moreover, it makes it hard to debug because it is completely hidden from the browser console. We now differentiate between exceptions thrown due to bad JSON in `responseText` from exceptions generated inside the callback itself, which are let through for browser console logging.

luci-base: luci.js: fix `LuCI.request.poll.add()` exception handling

---

modules/luci-base/luasrc/ccache.lua
modules/luci-base/luasrc/sgi/cgi.lua
modules/luci-base/luasrc/template.lua
modules/luci-compat/luasrc/model/network/proto_vpnc.lua
modules/luci-compat/luasrc/tools/webadmin.lua
modules/luci-mod-admin-mini/luasrc/controller/mini/index.lua
modules/luci-mod-admin-mini/luasrc/controller/mini/system.lua
modules/luci-mod-admin-mini/luasrc/model/cbi/mini/dhcp.lua
modules/luci-mod-admin-mini/luasrc/model/cbi/mini/passwd.lua
modules/luci-mod-admin-mini/luasrc/model/cbi/mini/wifi.lua
modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
modules/luci-mod-rpc/luasrc/jsonrpc.lua
modules/luci-mod-rpc/luasrc/jsonrpcbind/uci.lua
modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/routes.js

Whitespace and indent cleanup of 'modules' folder.
- Remove trailing whitespace
- Ensure one and only one final newline at the end of file
- Fix indentation

Clean up trailing whitespace in 'modules'

---

applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns

Description: Fix path of wget-ssl due to https://github.com/openwrt/packages/pull/14257
See also https://github.com/openwrt/packages/pull/14510

luci-app-ddns: fix wget-ssl path

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/io.nextdns.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/tw.twnic.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

NextDNS.io is tested by me, the Quad 101 contribution and testing is by the forum member: https://forum.openwrt.org/t/dns-https-proxy-and-quad-101-recommend/87761.

luci-app-https-dns-proxy: add nextdns.io and quad 101 providers

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/io.nextdns.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/tw.twnic.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

NextDNS.io is tested by me, the Quad 101 contribution and testing is by the forum member: https://forum.openwrt.org/t/dns-https-proxy-and-quad-101-recommend/87761.

[19.07] luci-app-https-dns-proxy: add nextdns.io and quad 101 providers

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/io.nextdns.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/tw.twnic.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

NextDNS.io is tested by me, the Quad 101 contribution and testing is by the forum member: https://forum.openwrt.org/t/dns-https-proxy-and-quad-101-recommend/87761.

[18.06] luci-app-https-dns-proxy: add nextdns.io and quad 101 providers

---

applications/luci-app-https-dns-proxy/po/zh_Hans/https-dns-proxy.po
applications/luci-app-https-dns-proxy/po/zh_Hant/https-dns-proxy.po

In Chinese translation po files for luci-app-https-dns-proxy, some "%s" was translated as "％s" in full-width character,  witch made the luci ui not displayed rightly.

fix %s in Chinese translation for luci-app-https-dns-proxy

---

applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm

This fixes the button rendering on luci-theme-openwrt-2020 as per https://github.com/openwrt/luci/issues/3909.

luci-app-https-dns-proxy: add missing btn class to buttons

---

applications/luci-app-vpnbypass/Makefile
applications/luci-app-vpnbypass/luasrc/model/cbi/vpnbypass.lua
applications/luci-app-vpnbypass/luasrc/view/vpnbypass/buttons.htm

This fixes the button rendering on luci-theme-openwrt-2020 as per https://github.com/openwrt/luci/issues/3909.

luci-app-vpnbypass: add missing btn class to buttons

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices.disabled/netgear-wac510.json

This fixes the button rendering on luci-theme-openwrt-2020 as per https://github.com/openwrt/luci/issues/3909.

luci-app-advanced-reboot: add missing btn class to buttons

---

libs/rpcd-mod-luci/src/luci.c
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/50_dsl.js
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

This is significantly faster.
This is the luci feed part of: http://patchwork.ozlabs.org/project/openwrt/list/?series=220557
That needs to be merged first before this can go in

luci-mod-status: use the new ubus dsl metrics

---

themes/luci-theme-openwrt-2020/luasrc/view/themes/openwrt2020/header.htm

Without a doctype, the browser is put into quirks mode. In quirks mode, Webkit (Safari on macOS and iOS) ignores `display: block;` for `<td>` elements which causes the firewall page (among others) to display improperly.
**Without doctype:**
**With doctype:**

luci-theme-openwrt-2000: Add doctype to header

---

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua

Default values were not quoted before, resulting in them not working.

luci-app-simple-adblock: bugfix: default values for ListValue

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

Default values were not quoted before, resulting in them not working.

[19.07] luci-app-simple-adblock: bugfix: default values for ListValue

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.idnet.doh.lua

Adds the UK provider's [IDNet](https://www.idnet.com/) DoH. It allows for circumventing Google tracking.

luci-app-https-dns-proxy: add idnet.net provider

---

applications/luci-app-vpn-policy-routing/Makefile
applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/buttons.htm
applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-gateways.htm
applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status-service.htm
applications/luci-app-vpn-policy-routing/luasrc/view/vpn-policy-routing/status.htm
applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot

Depends on: https://github.com/openwrt/packages/pull/14693.
Sync with vpn-policy-routing version 0.3 (depends on https://github.com/openwrt/packages/pull/14693)
This also fixes the button rendering on luci-theme-openwrt-2020 as per https://github.com/openwrt/luci/issues/3909.

luci-app-vpn-policy-routing: sync with package version 0.3; add missing btn class to buttons;

---

applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

Depends on https://github.com/openwrt/packages/pull/14709.

luci-app-https-dns-proxy: support for Force DNS option

---

applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

Depends on https://github.com/openwrt/packages/pull/14866.

[21.02] luci-app-https-dns-proxy: add Force DNS option support

---

libs/rpcd-mod-luci/src/luci.c

Fix parsing of DUID-LLT's in duid2ea.  Unlike DUID-LL's, DUID-LLT's have a 32-bit time field between the hardware type and link-layer address fields, see RFC 3315 Sections 9.2 and 9.4:
https://tools.ietf.org/html/rfc3315#section-9.2
https://tools.ietf.org/html/rfc3315#section-9.4
therefore, the link-layer address starts at offset 16 instead of 8.
Signed-off-by: Niels Widger <niels@qacafe.com>

rpcd-mod-luci: Fix parsing of DUID-LLT's in duid2ea

---

applications/luci-app-wireguard/Makefile
protocols/luci-proto-wireguard/Makefile

Prepares for 5.10 migration. wireguard-tools will bring in the correct
wireguard kernel module dependency - either kmod-wireguard or
kmod-wireguard-oot.
Depends on openwrt/openwrt#3885

luci-{app,proto}-wireguard: remove kmod-wireguard

---

applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua

maintainer: me
tested: Linksys WRT3200ACM
description: iface_lan, iface_wan, and iface_trig were not supported in LuCI since they were added to UCI.

luci-app-unbound: fix interface selections to match UCI

---

applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua

maintainer: me
tested: Linksys WRT3200ACM
description: iface_lan, iface_wan, and iface_trig were not supported in LuCI since they were added to UCI.

[openwrt-21.02] luci-app-unbound: fix interface selections to match UCI

---

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/status.htm
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

[19.07] luci-app-simple-adblock: bugfix: template layout on theme-openwrt-2020

---

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/status.htm
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

[21.02] luci-app-simple-adblock: bugfix: template layout on theme-openwrt-2020

---

applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/status.htm
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

luci-app-simple-adblock: bugfix: template layout on theme-openwrt-2020

---

applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/buttons.htm
applications/luci-app-https-dns-proxy/luasrc/view/https-dns-proxy/status.htm
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

[21.02] luci-app-https-dns-proxy: bugfix: layout issues on theme-openwrt-2020

---

themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css

This fixes #4734
I would also cherry-pick this to openwrt-21.02 if this works for @ajayramaswamy you.

luci-theme-openwrt-2020: add missing css success color

---

applications/luci-app-https-dns-proxy/Makefile

luci-app-https-dns-proxy: explicit package version

---

applications/luci-app-https-dns-proxy/Makefile

[21.02] luci-app-https-dns-proxy: explicit package version

---

applications/luci-app-https-dns-proxy/Makefile

[19.07] luci-app-https-dns-proxy: explicit package version

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

Update luci-mod-system/zram to reflect the lastest zram-swap changes.
**NOTE**: This is **completely untested**. My motivation to test LuCI is zero, as I personally don't use it at all.

luci-mod-system: zram fixes

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js
applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js
modules/luci-base/htdocs/luci-static/resources/protocol/dhcp.js
modules/luci-base/htdocs/luci-static/resources/protocol/static.js
modules/luci-mod-network/htdocs/luci-static/resources/tools/network.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
modules/luci-mod-network/root/usr/share/rpcd/acl.d/luci-mod-network.json
protocols/luci-proto-3g/htdocs/luci-static/resources/protocol/3g.js
protocols/luci-proto-hnet/htdocs/luci-static/resources/protocol/hnet.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/464xlat.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/6in4.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/6rd.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/6to4.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/dhcpv6.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/dslite.js
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/map.js
protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
protocols/luci-proto-ncm/htdocs/luci-static/resources/protocol/ncm.js
protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/l2tp.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/ppp.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoa.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoe.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pptp.js
protocols/luci-proto-pppossh/htdocs/luci-static/resources/protocol/pppossh.js
protocols/luci-proto-sstp/htdocs/luci-static/resources/protocol/sstp.js
protocols/luci-proto-vpnc/htdocs/luci-static/resources/protocol/vpnc.js
protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

This PR adds initial support for managing `config device` sections which allows for fine grained control over low level device details in uci. It requires the latest netifd Git HEAD to function.
Additionally, it implements support for bridge VLAN filtering as defined in http://lists.openwrt.org/pipermail/openwrt-devel/2020-July/030151.html

Introduce support for managing `config device` and `config bridge-vlan` sections

---

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool.js

Fixes rendering errors when RRD file names contain IPv6 addresses and the colon (":") characters are triple escaped.
Adapts the Lua-specific fix in #4340 to Javascript as suggested by @hnyman.
This is the change was tested using a VirtualBox image created from the [`r14184-eadb1a9437` snapshot x86/64 squashfs combined image](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz):
* Install required packages
```shell
opkg update
opkg install luci-app-statistics collectd-mod-ping uhttpd luci-theme-bootstrap
```
* Configure Collectd Ping plugin
```shell
uci set luci_statistics.collectd_ping.enable='1'
uci set luci_statistics.collectd_ping.AddressFamily='any'
uci set luci_statistics.collectd_ping.Hosts='127.0.0.1 ::1'
uci commit …
```

luci-app-statistics: remove rrd path triple escape

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

Implement two new text "options" for UCI system config, intended to
help humans describe the device.
"system.description" is a short, single-line description suitable for
selector UIs in remote administration applications, or remote UCI (over
ubus RPC), etc.  It would also be suitable as a default for LLDP/SNMP
"system description".
"system.notes" is a multi-line, free-form text field that can be used in
any way the user wishes, e.g. to hold installation notes, or unit serial
number and inventory number, location, etc.
Signed-off-by: Henrique de Moraes Holschuh <henrique@nic.br>

[snapshot] luci-mod-system: implement system.description, system.notes

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

Implement two new text "options" for UCI system config, intended to
help humans describe the device.
"system.description" is a short, single-line description suitable for
selector UIs in remote administration applications, or remote UCI (over
ubus RPC), etc.  It would also be suitable as a default for LLDP/SNMP
"system description".
"system.notes" is a multi-line, free-form text field that can be used in
any way the user wishes, e.g. to hold installation notes, or unit serial
number and inventory number, location, etc.
Signed-off-by: Henrique de Moraes Holschuh <henrique@nic.br>

[21.02] luci-mod-system: implement system.description, system.notes

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

Implement two new text "options" for UCI system config, intended to
help humans describe the device.
"system.description" is a short, single-line description suitable for
selector UIs in remote administration applications, or remote UCI (over
ubus RPC), etc.  It would also be suitable as a default for LLDP/SNMP
"system description".
"system.notes" is a multi-line, free-form text field that can be used in
any way the user wishes, e.g. to hold installation notes, or unit serial
number and inventory number, location, etc.
Signed-off-by: Henrique de Moraes Holschuh <henrique@nic.br>

[19.07] luci-mod-system: implement system.description, system.notes

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js
applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot

As discovered by @Ansuel and @pkgadd, with the 5.10 kernel the partition name which used to be `0:DUAL_FLAG` is now in lowercase (`0:dual_flag`). This patch is based on the code originally developed by @pkgadd to address this and also includes an additional error case handling. Original discussion/code: https://github.com/openwrt/openwrt/pull/3954.
Tested-by: Stefan Lippers-Hollmann <s.l-h@gmx.de>

luci-app-advanced-reboot: support 5.10 kernel on Zyxel

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

For discussion, refer to [forum thread](https://forum.openwrt.org/t/clarifying-ipv6-luci-terminology-ndp-proxy-ula-prefix-server-mode-relay-mode-hybrid-mode/18743)
Also added some RA parameters for increased GUI based configuration flexibility and help-text.
Until now, some of the IPv6 settings are mysterious or cryptic. They are now
clarified, having referred to odhcpd README and source. 
The information is accessible to IPv6 beginners.

luci-mod-network: Add more comprehensive help text for odhcpd IPv6 parameters, plus introduced RA + NDP options to GUI. 

---

applications/luci-app-transmission/htdocs/luci-static/resources/view/transmission.js

Convert `&nbsp;` to `&#160;` which is both syntactically correct (semicolon present) and XHTML compliant.
Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>

luci-app-transmission: fix '&nbsp' exception in OpenWrt theme

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

Fixes https://github.com/stangri/source.openwrt.melmac.net/issues/131 reported by @wengole. 

luci-app-simple-adblock: bugfix: crash when dnsmasq.ipset selected

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

Fixes https://github.com/stangri/source.openwrt.melmac.net/issues/131 reported by @wengole. 

[21.02] luci-app-simple-adblock: bugfix: crash when dnsmasq.ipset selected

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

Fixes https://github.com/stangri/source.openwrt.melmac.net/issues/131 reported by @wengole. 

[19.07 luci-app-simple-adblock: bugfix: crash when dnsmasq.ipset selected

---

applications/luci-app-fwknopd/htdocs/luci-static/resources/view/fwknopd.js

Add support for execution commands on the fwknopd server.

luci-app-fwknopd: add support for ENABLE_CMD_EXEC

---

applications/luci-app-fwknopd/luasrc/model/cbi/fwknopd.lua

Add support for execution commands on the fwknopd server.

[19.07] luci-app-fwknopd: add support for ENABLE_CMD_EXEC

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The updated ASU api requires `target` within reuqests since the
`profile` or `board_name` is never truely unique. This is especially a
problem for x86 devices which mostly use `generic` as profile name.

luci-app-attendedsysupgrade: add target in reuqest

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The updated ASU api requires `target` within reuqests since the
`profile` or `board_name` is never truely unique. This is especially a
problem for x86 devices which mostly use `generic` as profile name.
(cherry picked from commit c6b4d4ab5a2c57889bcf14fafac17e73d22205c6)

[21.02]luci-app-attendedsysupgrade: add target in reuqest

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cz.nic.odvr.lua

This PR adds IPv6 addresses for CZ.NIC ODVR.
It is based on info from https://www.nic.cz/odvr/
cc @stangri

luci-app-https-dns-proxy: add IPv6 addresses for cz.nic odvr

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Branch updates (e.g. 19.07 to 21.02) are risky and shouldn't be
suggested by default. Hide those unless the advanced mode is enabled.

luci-app-attendedsysupgrade: hide branch update

---

modules/luci-base/luasrc/dispatcher.lua

This PR replaces io.stderr:write with perror in dispatcher.lua and modifies perror in such way, that in can send error messages to stderr or syslog based on value stored in /etc/config/luci
```
luci.main.log='syslog'
or
luci.main.log='stderr'
```
Fixes https://github.com/openwrt/luci/issues/4877
Signed-off-by: Jan Pavlinec <jan.pavlinec@nic.cz>

luci-base: allow direct syslog login for perror

---

modules/luci-base/htdocs/luci-static/resources/ui.js

Change the ~german translation for "Dismiss" to "Abbrechen"~  "Dismiss" button to "Close" to differentiate with "Revert". Currently both are translated to "Verwerfen". This is confusing at least in the uci-apply dialog, which shows "Verwerfen" - "Speichern & Anwenden" - "Verwerfen".

luci-base: rename Dismiss button to Close in UCI-apply changes overview

---

applications/luci-app-mwan3/luasrc/view/mwan/overview_status_interface.htm

This is a followup pullrequest to show the correct status information if tracking is disabled for an mwan3 interface.

luci-app-mwan3: update status page for no tracked interfaces

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

While using channel analysis I noticed an exception. It turned out that center_chan1 is not returned in scan results for a "local_wifi" I use dual band card Compex WLE900VX. This causes that channels chart is not generated. 
Fix it by checking if center_chan1 is  defined.

luci-mod-status: check if center_chan1 is defined

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Hide branch upgrades unless advanced mode is enabled and fix branch detection for versions ending with `-SNAPSHOT`.

[21.02]luci-app-attendedsysupgrade: hide brach updates and correct branch detection

---

applications/luci-app-ddns/root/usr/libexec/rpcd/luci.ddns

Fix https://github.com/openwrt/luci/issues/4506
The removal of "+ force_seconds" is to compare the 18.06 version of ddns.lua (https://github.com/openwrt/luci/blob/openwrt-18.06/applications/luci-app-ddns/luasrc/tools/ddns.lua), this can be fixed The bug of the last time overflow. 
The 114 line is removed because this will cause the bug that the next update time is wrong when the router is just started. 
In addition,I checked dynamic_dns_updater.sh and found that next_update should be "epoch + force_seconds + check_seconds", so I added the variable definition of check_seconds. Through the test, the time displayed by luci matches the time of the log file.

luci-app-ddns: Fix time error

---

themes/luci-theme-material/htdocs/luci-static/material/js/script.js

Before fixed, if we have two nodes: 'services/ddns' and 'services/ddnsto',
click any one of they, will show they all actived.
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

luci-theme-material: fix wrong active state on common prefix node

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea7500v1.json

EA7500-v1 works the same as the other Linksys models except
the name is different. Verified with 21-02 and master.
Signed-off-by: David Adair <djabhead@aol.com>

luci-app-advanced-reboot: add board config for Linksys EA7500-V1

---

applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/collectd.js

Existing javascript did not read a non-default statistics hostname due to
incorrect config ids.
Signed-off-by: Anderson McKinley coyoso@tuta.io

luci-app-statistics: fix read of hostname

---

themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css

When mainmenu submenu is not visible, it still has visible `margin-bottom: .5em` so mixing main menu items with submenu (e.g. System) and without (e.g. Dashboard) causes uneven spaces between menu items.
This little tweek just makes all collapsed main menu items evenly distributed and does not change look of activated/selected items.

luci-theme-openwrt-2020: remove submenu margin-bottom when submenu not visible

---

modules/luci-base/htdocs/luci-static/resources/form.js

Signed-off-by: Nicholas Smith <nicholas@nbembedded.com>
I needed to make a DummyValue completely hidden, but the only way to do that was by using `rawhtml` and setting that UCI value to some HTML.  Bad smell.  So I added a new member called `hidden` to `DummyValue` to allow us to do this quite nicely from anywhere.  I hope this can be accepted in a MR after some review and discussion.
Before
```
o = s.taboption('general', form.DummyValue, 'pukrequired');
o.rawhtml = true;
o = s.taboption('sim1', form.Value, 'puk1', _('PUK (Personal Unlocking Key)'),
_("Your SIM requires a PUK to unlock it."));
o.depends({ pukrequired: "<p hidden>yes</p>", simslot: "1" })
```
After:
```
o = s.taboption('general', form.DummyValue, 'pukrequired');
// the new member
o.hidden = true; 
o = s.taboption('sim1', …
```

luci-base: add new member 'hidden' to DummyValue

---

applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js

https://github.com/fatedier/frp/tree/2406ecdfea62567a576bdb71e38adbafa3b4814a#custom-subdomain-names

luci-app-frpc: correct prop name 'subdomain'

---

libs/rpcd-mod-luci/src/luci.c
modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

This commit adds the ability to configure HE-modes for radios
(HE20 / HE40 / HE80 / HE160) as well as HE rate information in the
assiciation view.
Tested-on: Ubiquiti UniFi 6 Lite / LR
Signed-off-by: David Bauer <mail@david-bauer.net>

luci-mod-network: add 802.11ax HE support

---

luci.mk

Do not run the uci-defaults scripts of a package in the package-postinst, but leave this for the default_postinst() of the OpenWrt base-files package.
Based on https://github.com/openwrt/luci/pull/1635#issuecomment-368266512 and a short test it worked as expected. 
Looks to me like this was added back in 2014 when OpenWrt did not start the uci-defaults automtically.

luci.mk: don't run uci-defaults scripts ourself

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
modules/luci-mod-network/root/usr/share/rpcd/acl.d/luci-mod-network.json

- Condense overly large IPv6 RA/DHCPv6 description texts and get rid of most embedded markup
- Switch ra/ndp/dhcpv6 mode selections to rich dropdown lists and move extended choice
descriptions next to the selection options
- Drop ndproxy_static option which has been removed from odhcpd long ago
- Add format validations to all text input fields
- Add ability to configure master/relay modes for non-static interfaces (#2998)
- Move extended RA configuration options into a new tab
- Prevent enabling master mode on multiple interfaces
- Prevent enabling ra/dhcpv6 server mode on non-static or master interfaces
- Drop ra_management in favor to ra_flags option (#5083)
- Add support for dns_service option
Signed-off-by: Jo-Philipp Wich <jo@mein.io>

luci-mod-network: interfaces: restructure DHCPv6 and IPv6 RA options

---

themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm
themes/luci-theme-material/luasrc/view/themes/material/header.htm
themes/luci-theme-openwrt-2020/luasrc/view/themes/openwrt2020/header.htm
themes/luci-theme-openwrt/luasrc/view/themes/openwrt.org/header.htm

This calls striptags() on the hostname to prevent any XSS over the
hostname. This should fix CVE-2021-33425 as far as I understood it.
If someone adds some Javascript into `system.@system[0].hostname` it would
have been directly added to the page, this prevents the problem.
This can only be exploited by someone being able to modify the uci
configuration, normally a user with such privileges could also just
modify the webpage.
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

themes: Call striptags() on hostname to prevent XSS

---

applications/luci-app-vpn-policy-routing/Makefile
applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot

Support for 21.02.0-rc2 and up where ifname has been renamed to device in network config.

luci-app-vpn-policy-routing: support for 21.02.0-rc2

---

applications/luci-app-vpn-policy-routing/Makefile
applications/luci-app-vpn-policy-routing/luasrc/model/cbi/vpn-policy-routing.lua
applications/luci-app-vpn-policy-routing/po/templates/vpn-policy-routing.pot

Support for 21.02.0-rc2 and up where ifname has been renamed to device in network config.

[21.02] luci-app-vpn-policy-routing: support for 21.02.0-rc2

---

applications/luci-app-adblock/htdocs/luci-static/resources/view/adblock/overview.js

* support the new 'adb_fetchinsecure' option

luci-app-adblock: sync with adblock 4.1.3

---

applications/luci-app-sqm/htdocs/luci-static/resources/view/network/sqm.js
applications/luci-app-sqm/root/usr/share/rpcd/acl.d/luci-app-sqm.json

* fix a 'resource not found error' if the sqm service has been disabled
and the dir '/var/run/sqm/available_qdiscs' not exist
* inform the user about this issue (and how to fix this)

luci-app-sqm: fix JS error if service is disabled

---

applications/luci-app-nlbwmon/root/usr/share/luci/menu.d/luci-app-nlbwmon.json

I'm referring to the discussion with @jow- where we once discussed whether we should rename the service section to app.
Unfortunately I cannot find the thread anymore.
To avoid extending the menu tree the application luci-app-nlbwmon should also be moved to the service section and not get an extra menu entry.

luci-app-nlbwmon: move into menu entry into service section

---

collections/luci-lib-docker/luasrc/docker.lua

commit from https://github.com/lisaac/luci-lib-docker
[lisaac/luci-app-dockerman](https://github.com/lisaac/luci-app-dockerman.git) has been updated to v0.5.19, this version requires luci-lib-docker to be updated .
cc @feckert @lisaac
Signed-off-by: Yu Hua <hue715@gmail.com>

luci-lib-docker: add container export support

---

applications/luci-app-nlbwmon/htdocs/luci-static/resources/view/nlbw/backup.js
applications/luci-app-nlbwmon/htdocs/luci-static/resources/view/nlbw/config.js
applications/luci-app-nlbwmon/htdocs/luci-static/resources/view/nlbw/display.js

When moving this application to the service section, the links were forgotten to be changed.
@jow- Since I messed up, it's up to me to deal with it on my own. 
But in the process I noticed that the change in display.js wasn't right in the first place, was it?
If I had not moved the application, then it should have looked like this.
```
- E('a', { 'href': L.url('admin/nlbw/commit') }, _('Force reload…'))
+ E('a', { 'href': L.url('admin/nlbw/update') }, _('Force reload…'))
```

luci-app-nlbwmon: fix url and clean up the ui buttons

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js

Support for disabling routes in netifd was added in [this] commit. This commit
adds support for disabling routes through the LuCI interface.
Additionally hidden the route options descriptions in the header of the
routes table (they are still available in the modal view).
[this]: https://git.openwrt.org/?p=project/netifd.git;a=commit;h=327da9895327bc56b23413ee91a6e6b6e0e4329d

luci-mod-network: Support for disabling routes

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

@tohojo If multiple certificates are added, then the page is a bit confusing with
all the information's. Therefore the GridSection view would be better
suited here.
**Before:**
**After:**

luci-app-acme: change form view to GridSection

---

applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js

Sometimes, our frp server cannot use a static ip address. 
So perhaps we should allow people to use hostname in server address.
Signed-off-by: SiYao Mo <msylgj@vip.qq.com>

luci-app-frpc: allow hostname in server address

---

applications/luci-app-acl/htdocs/luci-static/resources/view/system/acl.js

This P/R does make two changes
1. luci-app-acl: fix translation function call. The second argument in the translation function makes no sense.
2. luci-app-acl: unset read and write before acl set.  If the setting in the view is set to `denied`, only the read list option is deleted. This is not correct. The write list option must also be deleted. To ensure that the correct configuration is saved, the write and read list options are always deleted beforehand and then rewritten.
**Configuration that is being changed:**
```
config login
option username 'test'
option timeout '300'
option password '$1$$whuMjZj.HMFoaTaZRRtkO0'
list read 'luci-app-acme'
list read 'luci-app-commands'
list read 'luci-app-ddns'
list read 'luci-base'
list read 'unauthenticated'
list write 'luci-app-acme'
list write …
```

luci-app-acl: some fixes

---

modules/luci-base/htdocs/luci-static/resources/form.js

- Change html tag `input` to `button` for adding a named section. Button is then rendert correct for luci-theme-openwrt-2020
- Call validation, because named section is always empty on page load. User must added a name for named sections.
- Remove `btn` css class and also rename them to `button`

luci-base: minor fixes and improvments

---

applications/luci-app-attendedsysupgrade/Makefile
applications/luci-app-attendedsysupgrade/root/etc/uci-defaults/40_luci-attendedsysupgrade

Remove depenedency uhttpd-mod-ubus which is not required.
User may want to work with nginx rather uhttpd.

luci-app-attendedsysupgrade: remove depends uhttpd-mod-ubus

---

applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/luci-app-attendedsysupgrade.json

Fix the ACL file which handles the permissions for the LuCI app.
Suggested-by: Jo-Philipp Wich <jo@mein.io>

luci-app-attendedsysupgrade: fix ACL definition

---

modules/luci-base/htdocs/luci-static/resources/cbi.js

Fix time display error like this:
Running time should display 1h 0m 36s instead of 0h 60m 36s

luci-base:Fix time display error

---

protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js

Signed-off-by: Helge Mader <ma@dev.tdt.de>
This bugfix offers the 'Transmit Hash Policy' parameter with the correct bonding policies.

luci-proto-bonding: bugfix xmit_hash_policy dependencies

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/google.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.adblocker.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/sb.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* add HTTP/2-only supporting providers: Mullvad, Digitale-Gesellschaft, dns.sb and Rubyfish.cn
* switch default provider from Google to Cloudflare
* add IPv6 addresses for bootstrap resolvers for Google DNS
* add secondary bootstrap resolver (Cloudflare's) to all providers with a single bootstrap resolver
* modify model/cbi file to show HTTP/2-only providers (and help texts) on HTTP/2-supporting systems

luci-app-https-dns-proxy: update to 2021-07-29-1

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cz.nic.odvr.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/google.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.adblocker.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/sb.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* add HTTP/2-only supporting providers: Mullvad, Digitale-Gesellschaft, dns.sb and Rubyfish.cn
* switch default provider from Google to Cloudflare
* add IPv6 addresses for bootstrap resolvers for Google DNS
* add secondary bootstrap resolver (Cloudflare's) to all providers with a single bootstrap resolver
* modify model/cbi file to show HTTP/2-only providers (and help texts) on HTTP/2-supporting systems

[21.02] luci-app-https-dns-proxy: update to 2021-07-29-1

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers.disabled/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/ch.digitale-gesellschaft.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cn.rubyfish.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.cloudflare-dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cz.nic.odvr.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/google.dns.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh-ads.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/gr.libredns.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.adblocker.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.mullvad.doh.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-adult.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-family.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/org.cleanbrowsing.doh-security.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/sb.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* add HTTP/2-only supporting providers: Mullvad, Digitale-Gesellschaft, dns.sb and Rubyfish.cn
* switch default provider from Google to Cloudflare
* add IPv6 addresses for bootstrap resolvers for Google DNS
* add secondary bootstrap resolver (Cloudflare's) to all providers with a single bootstrap resolver
* modify model/cbi file to show HTTP/2-only providers (and help texts) on HTTP/2-supporting systems

[19.07] luci-app-https-dns-proxy: update to 2021-07-29-1

---

modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Update "modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json".
Fix incorrect description for "luci-mod-status-channel_analysis".

luci-mod-status: fix description for luci-mod-status-channel_analysis

---

protocols/luci-proto-bonding/htdocs/luci-static/resources/protocol/bonding.js

Signed-off-by: Helge Mader <ma@dev.tdt.de>
This change is necessary as the result of `network.getDevices()` now returns `device` instead of `ifname`,
so the previous version no more works.

luci-proto-bonding: fix member because of API change

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/routes.js
modules/luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Provide comprehensive status information for routing.
Rename the "Status > Routes" page to "Status > Routing".
Unify sorting for the "Status" and "Network" menus.
Add tabs for IPv4 and IPv6 and reorganize the contents.
Display routing rules and their priorities for each protocol.
Policy-based routing is an increasingly popular problem.
Netifd natively supports policy-based routing:
* The interface-specific options "ip4table" and "ip6table".
* The routing rules using the "rule" and "rule6" sections.
LuCI is missing the information about routing rules.

luci-mod-status: status/routing support for pbr

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

If the upgrade server API does not respond, show an error message.
Fix #5222
While at it, minimal code linting

luci-app-attendedsysupgrade: add timeout and catch

---

modules/luci-base/htdocs/luci-static/resources/cbi.js
modules/luci-compat/luasrc/view/cbi/tblsection.htm
modules/luci-compat/luasrc/view/cbi/tsection.htm

Currently it is not checked whether a valid string was entered in the input field when adding a named section.
This commit validates if the input field is empty or not.
If the input field is not empty, then the Add button is displayed.
refs https://github.com/openwrt/luci/pull/5154

luci-base: prevent empty field for adding new entry

---

modules/luci-base/htdocs/luci-static/resources/luci.js

The `timeout` is defined in milliseconds, not seconds.
TIL: My server API does not respond within 8ms.

luci-base: fix request timeout docstring

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/20_memory.js

when buffered could not be read, there is
just a questionmark (on e8450 non-ubi)

status: make buffered conditional

---

applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/ping.js
applications/luci-app-statistics/root/usr/share/luci/statistics/plugins/ping.json

* Add support for MaxMissed, documented in collectd: https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_ping
* Correct the type of hosts entries, they can be hostnames as well as IP addresses
Tested in concert with a change to packages/collectd-mod-ping to manage the collectd configuration for `MaxMissed`, viewable here: https://github.com/openwrt/packages/pull/16362
I tested setting the value to -1 does not re-resolve hosts after pings fail.
Watched DNS traffic with tcpdump to see that setting the value to positive integer results in a DNS re-resolve after that many ping failures. I swapped my phone between two networks reachable from the same router, and saw that after switching networks, collectd switched to pinging the new address after the desired number of …

luci-app-statistics: add support for MaxMissed

---

applications/luci-app-statistics/root/usr/bin/stat-genconfig

If the interrupt names are only numeric
/proc/interrupts
```
CPU0       CPU1       
4:         13          0   IO-APIC   4-edge      ttyS0
8:          0          0   IO-APIC   8-edge      rtc0
9:          2          0   IO-APIC   9-fasteoi   acpi
117:          0       7949   PCI-MSI 32768-edge      i915
118:      47996          0   PCI-MSI 327680-edge      xhci_hcd
119:          1          0   PCI-MSI 524288-edge      eth0
120:          0       5878   PCI-MSI 524289-edge      eth0-rx-0
121:       4947          0   PCI-MSI 524290-edge      eth0-rx-1
122:          0       5316   PCI-MSI 524291-edge      eth0-tx-0
```
the command `/usr/bin/stat-genconfig` does not create a working collectd config.
/etc/config/luci_statistics
```
config statistics 'collectd_irq'
option enable '1'
list Irqs …
```

luci-app-statistics: irq plugin: handle numeric interrupt names

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js

Hide unsupported option when /rom is not used in flash.js

luci-mod-system: hide unsupported option on flash.js

---

modules/luci-base/htdocs/luci-static/resources/tools/widgets.js

Support the "loopback" interface by "widgets.NetworkSelect".
Enable the "loopback" option to include this interface.
Can be used to configure interface binding for services.

luci-base: support loopback by widgets.NetworkSelect

---

protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

From #5307
Honestly, I haven't tested this because I'm not sure how to build openwrt.  In theory it should work because I have tried removing the `AllowedIPs` lines from `/etc/config/network` and the wireguard interface worked fine.  
So I think this commit should fix it without any side effects... but I would appreciate if someone would test it or help me test it.

luci-proto-wireguard: make AllowedIPs optional

---

applications/luci-app-ledtrig-usbport/htdocs/luci-static/resources/view/system/led-trigger/usbport.js

The kernel module `kmod-usb-ledtrig-usbport` allows for multiple selections of
USB ports to trigger a single LED.
See https://www.kernel.org/doc/html/latest/leds/ledtrig-usbport.html
This simplest of fixes allows for selection one or more USB ports to trigger a LED.
The ASUS RT-AC88U router which is getting ported to OpenWrt by arinc9 has got an
USB 3.0 port at the front which will use different internal USB ports, depending
on if you connect an USB 2.0 device or an USB 3.0 device.
This fix/patch was tested on the mentioned router.
Signed-off-by: Thomas Kupper <thomas.kupper@gmail.com>

luci-app-ledtrig-usbport: fix allow multiple selection

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

SNAPSHOTS are not real releases and therefore the app always offers an
upgrade, even if running the latest build. To prevent that all SNAPSHOTS
now check for the running revision and if a newer one is available.
Also do a bunch of refactoring based on JavaScript I learned over the
last week.

luci-app-attendedsysupgrade: support revision checks

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js

Fix the wrong value for the "source" option of the "route6" section.

luci-mod-network: fix route6 source autocomplete

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

Fix the incorrectly displayed value for the option "ip6table".

luci-mod-network: fix option ip6table in network/interfaces

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js

....'Match ICMP type' field.
Signed-off-by: Paul Dee <systemcrash@users.noreply.github.com>
See issue #5213

luci-app-firewall: add ipv6 exclusive ICMP types to firewall

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/switch.js

There are many switch drivers where VLAN functionality is enabled by default.
In this situation, LuCI cannot be used to disable VLAN functionality,
because removing the line from configuration results in VLAN remaining enabled
by the driver.
When enable_vlan is set to 0 by default
by using functions in board.d,
and an unrelated change is made on the Switch webpage,
then the enable_vlan option gets deleted when changes are saved.
Therefore, the option needs to be preserved, whether set to 0 or 1.
Signed-off-by: Michael Pratt <mcpratt@pm.me>

luci-mod-network: do not remove enable_vlan from config

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/configuration.js
applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The previous settings would use spaces which messed up things since LuCI
uses tabs everywhere.
Also removed a stray console.log

luci-app-attendedsysupgrade: use correct linter settings

---

modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status-index.json
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

The ACL file luci-mod-status.json is already quite long.
It is also a separate menu item in LuCI, so in my view it makes sense to
move it to a separate file. An additional positive effect is that the
file then becomes clearer.

luci-mod-status: move index acl into own file

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/configuration.js
applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

SNAPSHOTS are not real releases and therefore the app always offers an
upgrade, even if running the latest build. To prevent that all SNAPSHOTS
now check for the running revision and if a newer one is available.
Also do a bunch of refactoring based on JavaScript I learned over the
last week.

[21.02] luci-app-attendedsysupgrade: support revision checks

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/10_system.js

revealed under:
`ubus call system board`
board.release.target
Useful reminder for what to download
Signed-off-by: Paul Dee <systemcrash@users.noreply.github.com>

luci-mod-status: Add Target Platform (e.g. ath79/ipq806x/etc)

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/sshkeys.js

ECDH is not used for the ed25519. The scheme is called EdDSA.
Curve25519 is a Montgomery curve. ed25519 uses an Edwards curve. The
author recommends X25519 as a replacement for Curve25519 in any form.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

fix wrong ed25519 information

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

Allow to modify the sourcefilter option in the network.interface config.
This is required for custom policy routing with IPv6 MWAN and/or NAT6.

luci-mod-network: support network.interface.sourcefilter

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/uhttpd.js
modules/luci-mod-system/root/usr/share/luci/menu.d/luci-mod-system.json
modules/luci-mod-system/root/usr/share/rpcd/acl.d/luci-mod-system.json
themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css

Add a possibility to control uHTTPd's `redirect_https` config option from LuCI. While at it, add some missing abbreviations found in SSH keys and add missing styling of abbreviations as well.
References: https://lists.infradead.org/pipermail/openwrt-devel/2020-December/032718.html

Allow configuration of HTTPS redirection

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Allow to modify the ipset option in the dhcp.dnsmasq config.
This makes possible to populate IP sets with dnsmasq.

luci-mod-network: support dhcp.dnsmasq.ipset

---

themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm
themes/luci-theme-material/luasrc/view/themes/material/header.htm
themes/luci-theme-openwrt-2020/luasrc/view/themes/openwrt2020/header.htm
themes/luci-theme-openwrt/luasrc/view/themes/openwrt.org/header.htm

Some devices offer a full LuCI interface from their recovery interface.
As it's read-only it should only be used for installing sysupgrades and
therefore warn users that no settings are saved.

themes: warn if booted from initramfs

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/mobile.css

Add a dark theme variant which is enabled by default when
prefers-color-scheme is set to dark.
Signed-off-by: Teoh Han Hui <teohhanhui@gmail.com>

luci-theme-bootstrap: add dark theme variant

---

.github/workflows/build.yml

While all LuCI packages should always build fine, this allows others to
directly install those packages within test setups.

CI: test build LuCI packages

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/diagnostics.js
modules/luci-mod-network/root/usr/share/rpcd/acl.d/luci-mod-network.json

This is a JavaScript rewrite of the PR#5152
It adds the ability to perform ARP scans if the tool `arp-scan` is
installed.

luci-mod-admin-full: add arp-scan to network diagnostic

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Allow configuring ipset sections in the dhcp config:
https://openwrt.org/docs/guide-user/base-system/dhcp#ip_sets
This can also be combined with instance-specific IP sets:
https://github.com/openwrt/luci/pull/5402
However, it makes easier to assign domains to IP sets.

luci-mod-network: support dhcp.ipset as section

---

applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua

maintainer: @EricLuehrsen 
Description: When `odhcpd` `leasetrigger` is not defined - which is by default - the `Unbound` interface crashes because of attempting to concatenate nil value. This fixes it.
Closes #5473

luci-app-unbound: fix error on empty leasetrigger

---

modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js
modules/luci-base/htdocs/luci-static/resources/validation.js

When saving your changes with an invalid input field the message is always generic. I have added the validation message to the validation-failure event and now you get the precise message also in the save error popup.

luci-base: show validation message in save error

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/25_diskfree.js

Since commit https://git.openwrt.org/?p=project/procd.git;a=commit;h=8de12dec298898d133256fdaac584a26adae2cc5 we have the following information from `ubus call system info` for tmp and root filesystem available.
```
"root": {
"total": 175872,
"free": 98896,
"used": 76976,
"avail": 98896
},
"tmp": {
"total": 2010208,
"free": 2008668,
"used": 1540,
"avail": 2008668
}
```
The changes in procd are include with commit https://github.com/openwrt/openwrt/commit/507f50df0771935ee389d383c0543e36f914f949
I have copied the source from the `20_memory.js ` file and adapted it
.

luci-mod-status: add diskfree info

---

protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js
protocols/luci-proto-wireguard/root/usr/libexec/rpcd/luci.wireguard
protocols/luci-proto-wireguard/root/usr/share/rpcd/acl.d/luci-wireguard.json

Signed-off-by: Paul Dee <systemcrash@users.noreply.github.com>
We have private keys, but ***the thing we need to share***, the public key, is completely absent from the `Interface` GUI.
FIXED.
Tested on 21.02.0
Cooperates with the "Generate Key" function below it. 
This PR also implicitly needs #5399

luci-proto-wireguard: display interface public key

---

modules/luci-base/htdocs/luci-static/resources/form.js
protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

This PR introduces two commits;
- the first commit implements support for recursive grid/table section modal edit dialogs
- the second commit utilizes this new facility to turn the wireguard peer configuration into a grid view
Fixes #5489
Cc @lvoegl @feckert since you appear to be most active on the wireguard proto support most recently, I don't really use it
Cc @vchrizz since you requested this change

Implement nested grid section support and use it for wireguard peer config

---

.github/workflows/jsdoc.yml

I noticed this undesired actions running on the forked repository.
As I understand this, generating the 'gh-pages' branch is only meaningful in the official repository. I think this should fix it.

ci: Only run github pages on the official repository

---

modules/luci-base/luasrc/dispatcher.lua

Cherry-picked from https://github.com/openwrt/luci/pull/4925

[21.02] luci-base: send failed/successfull login to syslog

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js

Associated Stations on the status page should also show full HE rate
information which was added by
commit f35e877dc6 ("luci-mod-network: add 802.11ax HE support")
However, it was only added to the Wireless page and not to the summary
on the Status page. Add it there as well.
(It would be nice to move this function to a common include instead of duplicating it, I suppose. I'm not so much into LuCI, so I'd need some advise how that should be done, if at all)

luci-mod-status: display full HE rate information

---

protocols/luci-proto-ipip/htdocs/luci-static/resources/protocol/ipip.js

Add nohostroute configurable to luci-proto-ipip.
Also explicitly set this option, and the previous df configurable, to optional.
linked pr (merged) [openwrt #4970](https://github.com/openwrt/openwrt/pull/4970)

luci-proto-ipip: add nohostroute configurable

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/diagnostics.js

Passing "-6" to ping6 from the iputils package will lead to the
following error:
"ping6: only one -4 or -6 option may be specified"
It does not make sense either.
Fixes: 547776327a71 ("luci-mod-network: diagnostics.js: pass IP version flag to ping/ping6")

luci-mod-network: diagnostics.js: don't pass IP version flag to ping6

---

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js

This PR changes the filter to listen to `input` event instead of `keyup`. The former doesn't work with pasting and has issues with IMEs.

luci-app-opkg: listen to filter `input` event

---

modules/luci-base/htdocs/luci-static/resources/cbi.js
modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js
themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

This PR introduces sortable status tables in LuCI and replaces the old `cbi_update_table()` functon with wrapper logic for backwards compatibility.
In a later step, form `TableSection` and `GridSection` implementations will be rebased on top of the new table facility to provide column sorting for them as well.

Introduce sortable status tables

---

applications/luci-app-shadowsocks-libev/Makefile
applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/rules.js

Options ipt_args and dst_forward_recentrst of ss_rules section are now
deprecated in the transition of ss-rules to using nft

luci-app-shadowsocks-libev: remove refs to now deprecated options

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js
applications/luci-app-attendedsysupgrade/root/usr/share/rpcd/acl.d/luci-app-attendedsysupgrade.json

It is possible to request a specific filesystem so no other filesystems
are used. This speeds up the build process and may prevent failures in
edge cases.
A recent edge case is installing more packages than ext4 can handle
while squashfs works fine due to compression.

luci-app-attendedsysupgrade: request filesystem

---

applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/graphs.js
applications/luci-app-vnstat2/root/usr/share/luci/menu.d/luci-app-vnstat2.json
applications/luci-app-vnstat2/root/usr/share/rpcd/acl.d/luci-app-vnstat2.json

@selanf
@janh 
This is a huge change to the already existing vnstat2 LuCI module with some
improvements and some new features.
"Graphs Page":
- Implementation of refreshing the graphs.
- Only in the UCI configuration existing interfaces will be shown in any
case. Before this change, all interfaces existing in the database were
shown.
- Introduced a button for each interface to clear the statistics (in fact
this is removing and adding again the interface from/to the database).
Attention: This breaks the recently introduced "2x3 Graphs display"
General:
- Updated translations, added missing translations for ./po/de
- Renamed the menu entry from "vnStat Traffic Monitor" to "Traffic Monitor" only
Signed-off-by: Helge Mader <ma@dev.tdt.de>

[WIP] luci-app-vnstat2: refactoring

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js

Added code to display fcdn-name in DHCPv4 lease table.
(based on code in DHCPv6 lease table)
Signed-off-by: Max S Kash <asukms@ya.ru>
Indentation adjused and wrapped commit message
cherry pick from master https://github.com/openwrt/luci/commit/8a46648e5bfb4b8f4d2452c51b5181631d260b6f

[22.03]luci-mod-status,mod-network: Added fqdn-name to DHCPv4 lease table

---

libs/luci-lib-jsonc/src/jsonc.c

Fixes: #3293
Signed-off-by: Justin Klaassen <jck112@users.noreply.github.com>

luci-lib-jsonc: stringify int use json_object_new_int64 instead

---

protocols/luci-proto-batman-adv/Makefile
protocols/luci-proto-batman-adv/htdocs/luci-static/resources/protocol/batadv.js
protocols/luci-proto-batman-adv/htdocs/luci-static/resources/protocol/batadv_hardif.js

Adding support for the  batadv and the batadv_hardif protocols to LuCI.
I could not find support for the batman-adv protocol for LuCI anywhere, hence I wrote this interface. My apologies if anyone had done it before - as I said, I just could not find it.
In order to test/use this, please do the following:
either compile or (easier) copy the two .js files to /www/luci-static/resources/protocol/ on your OpenWrt installation. You will now be able to create/view/edit interfaces with protocols batadv and/or batadv_hardif.
Test/usage scenario:
1) create a Wi-fi mesh network
2) create an interface, e.g. bat0 of type batadv ('B.A.T.M.A.N. advanced') - you can see the new "Mesh Routing" tab where you can set (nearly) all batman-adv options
3) create an interface, e.g. batmesh of type batadv_hardif …

luci-proto-batman-adv: LuCI Support for the batman-adv protocol

---

applications/luci-app-rp-pppoe-server/luasrc/model/cbi/rp-pppoe-server.lua

pppoe-server init script is expecting an OpenWRT interface name. The physical device name is looked up by the init script. 
So config 'interface' should be equal to an interface name e.g LAN not a physical device e.g eth0
This PR fixes the luci application to select Interfaces, not physical devices.

luci-app-rp-pppoe-server: use netlist template

---

applications/luci-app-frpc/htdocs/luci-static/resources/view/frpc.js

In [fatedier/frp](https://github.com/fatedier/frp/blob/0fb6aeef583c59e2d97fa0cf8e02e39868a0fae7/conf/frpc_full.ini#L24), the default value of  disable_log_color is false.

luci-app-frpc: Set the disable_log_color option to false by default

---

applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea7500v2.json

Very similar to the EA7300 v2. Tested and working. Some details,
```
[    0.000000] MIPS: machine is Linksys EA7500 v2
```
```
dev:    size   erasesize  name
mtd0: 00080000 00020000 "boot"
mtd1: 00040000 00020000 "u_env"
mtd2: 00040000 00020000 "factory"
mtd3: 00040000 00020000 "s_env"
mtd4: 00040000 00020000 "devinfo"
mtd5: 00400000 00020000 "kernel1"
mtd6: 02400000 00020000 "rootfs1"
mtd7: 00400000 00020000 "kernel2"
mtd8: 02400000 00020000 "ubi"
mtd9: 00100000 00020000 "sysdiag"
mtd10: 02d00000 00020000 "syscfg"
```
```
{
"kernel": "5.10.111",
"hostname": "OpenWrt",
"system": "MediaTek MT7621 ver:1 eco:3",
"model": "Linksys EA7500 v2",
"board_name": "linksys,ea7500-v2",
"rootfs_type": "squashfs",
"release": {
"distribution": "OpenWrt",
"version": "SNAPSHOT",
"revision": …
```

luci-app-advanced-reboot: Add support for Linksys EA7500 v2

---

applications/luci-app-openvpn/luasrc/controller/openvpn.lua
applications/luci-app-openvpn/luasrc/model/cbi/openvpn-file.lua

Fix openvpn config corruption on upload.
This fixed issue #5731
Corruption was caused by applying trim to the chunks of the file.
Signed-off-by: Anna Tikhomirova <vamp@vampik.ru>

luci-app-openvpn: fix openvpn config corruption on upload

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The text of the progressbar is bigger than the progressbar height. This removes the font-size element that produced that.
Signed-off-by: Miguel Angel Mulero <mcgivergim@gmail.com>
This is a screen capture of the before:
and after:
I've tested it under Chrome in Windows and Android.

luci-theme-material: fix size of progressbar text

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The icon of the logout option overflows the text. This reduces the size of the icon to not overflow.
Signed-off-by: Miguel Angel Mulero <mcgivergim@gmail.com>
This is before:
And this is after:
I've tested it under Chrome in Windows and Android.

luci-material-theme: reduce size of logout icon

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The data-title attribute style depends on the content in the css rule.
When translated to other language, the css rule fails.
This change uses the position and not the content to apply the style.
Signed-off-by: Miguel Angel Mulero <mcgivergim@gmail.com>
This PR reverts my earlier fix https://github.com/openwrt/luci/pull/5788 and adds a new commit to fix the issue in all languages.
Thanks to @castillofrancodamian for noticing that the problem was only with translated UI.
Before any fix for the logout in English:
And Spanish:
With my earlier fix:
Now in Spanish:

luci-material-theme: adjust data-title for logout

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The control-group div does not flex. The buttons overflow the screen.
This change mades them flex.
Signed-off-by: Miguel Angel Mulero Martinez <migmul@gmail.com>
Before:
After:

luci-material-theme: make control-group flex

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The CSS applies a different padding for td elements with 33% width. This
misaligns the text from this td to the others td.
This change modifies the CSS to apply the same padding to all of the
sibling td.
Signed-off-by: Miguel Angel Mulero Martinez <migmul@gmail.com>
This can be easily noted in phones, not in computers. This is before:
And this is after:

luci-material-theme: align td text width 33%

---

applications/luci-app-dockerman/luasrc/controller/dockerman.lua

https://github.com/openwrt/luci/commit/180d39dcd2427e3c32c0ec7ecc3c7bfb48c0d0ab broke dockerman's appearance in the menus
Make a small change to dockerman's index entry to make it play nice with the new architecture, firstchild() was obtained using DAWN's controller/dawn.lua as an example
signed-off

luci-app-dockerman: Update to play nice with recent changes

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The latest fix to fix the logout worked, but it was not applied to all
the resolutions, and I have observed the same problem exists for the
dasboard optional component.
Looking at the code, it seems only the components without submenu, have the
data-title element, so this fix modifies the style for all of them, not
relying on the position or text content.
Signed-off-by: Miguel Angel Mulero Martinez <migmul@gmail.com>
Before:
After:

luci-material-theme: fix localizated left menu

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The text inside the buttons is aligned to the top. This change mades
it aligned to the center.
Signed-off-by: Miguel Angel Mulero Martinez <migmul@gmail.com>
This is before this change:
And this is after:

luci-material-theme: align text buttons center

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

UCI option `interface` for sysntpd server was introduced in
OpenWrt commit 4da60500ebd2. NTP server binds to the specified interface,
or if unspecified, to all.
This patch adds selection widget to LuCI.
Signed-off-by: Alexey Dobrovolsky <dobrovolskiy.alexey@gmail.com>

luci-mod-system: add interface selection for NTPD

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

UCI option `interface` for sysntpd server was introduced in
OpenWrt commit 4da60500ebd2. NTP server binds to the specified interface,
or if unspecified, to all.
This patch adds selection widget to LuCI.
Signed-off-by: Alexey Dobrovolsky <dobrovolskiy.alexey@gmail.com>
(cherry picked from commit 24ac5a2bf6d713c6878cf7be7d4e4516965c2884)

[22.03] luci-mod-system: add interface selection for NTPD

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js

UCI option `interface` for sysntpd server was introduced in
OpenWrt commit 4da60500ebd2. NTP server binds to the specified interface,
or if unspecified, to all.
This patch adds selection widget to LuCI.
Signed-off-by: Alexey Dobrovolsky <dobrovolskiy.alexey@gmail.com>
(cherry picked from commit 24ac5a2bf6d713c6878cf7be7d4e4516965c2884)

[21.02] luci-mod-system: add interface selection for NTPD

---

applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua

Add missed option 'allow anonymous' in mosquitto section.
Signed-off-by: Ptilopsis Leucotis <PtilopsisLeucotis@yandex.com>

luci-app-mosquitto: add option 'allow anonymous'

---

themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm

Restore accidentally removed the initramfs boot warning banner.
Ref: https://github.com/openwrt/luci/commit/8055acc9be89f0bed31b6692ad08e6196611d478#commitcomment-73447330
Fixes: 8055acc9be ("luci-theme-bootstrap: overhaul styles")
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
(cherry picked from commit 56fab648caa78422aac47ab8cec168e8a0999316)
CC: @jow- @dangowrt

luci-theme-bootstrap: restore initramfs warning

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

Commit b0f13ef Changed the color of a CSS element from a bright blue to
a dark blue. This resulted in a modal with difficult-to-read text (black
text on dark blue).
This commit sets the modal text-color to #000, in line with style
guidelines.
---
Before: 
After:
Signed-off-by: Quentin Baker <opensource@quentb.com>

luci-theme-material: CSS Fix for previous update

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Now it's possible to re-install the currently running version in
advanced mode. This can be useful when installing packages via `opkg`
and then requesting the firmware with the packages stored in squashfs.
FIXES: https://github.com/openwrt/luci/issues/5809

luci-app-attendedsysugprade: allow to reinstall image

---

libs/rpcd-mod-luci/src/luci.c

When kernel bonding module is loaded it will create a special
file /sys/class/net/bonding_masters. This is no network device.
Filter it out for getNetworkDevices() call.

rpcd-mod-luci: filter bonding_masters

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/nftables.js
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

On a `LuCI Master (git-22.167.28356-8effea5) / OpenWrt SNAPSHOT r0-ddf5eca`, `125002` subnets in `ipv4_addr` (in any table) cause `nft list ruleset` to eat `>` `100MB` of `RAM` and trigger `OOM`.
Do not retrieve `nftables` `sets` contents, e.g. replace `nft list ruleset` with `nft --terse list ruleset`.
Not expected. `luci-mod-status` does not show `nftables` `sets` contents anyway.
On a `LuCI Master (git-22.167.28356-8effea5) / OpenWrt SNAPSHOT r0-ddf5eca` this fixes issue. Tested as follow:
```
uclient-fetch -O /www/luci-static/resources/view/status/nftables.js https://raw.githubusercontent.com/galeksandrp/luci/status-fix-oom-nftables/modules/luci-mod-status/htdocs/luci-static/resources/view/status/nftables.js
uclient-fetch -O /usr/share/rpcd/acl.d/luci-mod-status.json …
```

luci-mod-status: nftables.js: fix OOM on big nftables IP sets

---

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/css/custom.css

Removing overflow and position, adding padding and increasing font size for the label.
Signed-off-by: Santiago Kozak <santikzk1406@gmail.com>

luci-mod-dashboard: improve label's display

---

applications/luci-app-watchcat/htdocs/luci-static/resources/view/watchcat.js
applications/luci-app-watchcat/po/templates/watchcat.pot

This adds support for run_script mode, which I propose adding in https://github.com/openwrt/packages/pull/18593
I also added support for choosing the address family for the pings
@feckert @nickberry17 
I apologize, I don't know anything about the translated messages and how to deal with those in this package.  Can you point me at some documentation about that?

luci-app-watchcat: add support for run_script mode

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

This allows the backend to track popular app versions and drop support for
unsed version in case of API changes.
Specifically the app sends a version string in the format "luci - GIT_HASH" to
the backend.

luci-app-attendedsysupgrade: report used client version

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The variable was party called `res` or `response`, always call it
`response` from now on. This also solves a typo where
`data.request_hash` is never set to a correct value.

luci-app-attendedsysupgrade: s/res/response/

---

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/10_router.js
modules/luci-mod-dashboard/po/templates/dashboard.pot

Show connection uptime for both IPv4 & IPv6 interfaces.
Rename display field from 'Connected since' to 'Uptime' as this makes
more sense to me.  You could say 'Connected for' or 'Connection
duration'.  After a lot of thought decided that 'Uptime' is what I'm
most comfortable saying.

luci-mod-dashboard: show IPv6 connection uptime

---

applications/luci-app-apinger/Makefile
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/alarm_delay.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/alarm_down.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/alarm_loss.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/graphs.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/interfaces.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/overview.js
applications/luci-app-apinger/htdocs/luci-static/resources/view/apinger/targets.js
applications/luci-app-apinger/root/usr/share/luci/menu.d/luci-app-apinger.json
applications/luci-app-apinger/root/usr/share/rpcd/acl.d/luci-app-apinger.json

A new app for apinger with LuCI Support. This new LuCI app is added on top of the recently merged apinger PR
https://github.com/openwrt/packages/pull/18913, It covers backend UCI configuration information.
**We also need https://github.com/openwrt/packages/pull/19073**
Screenshots from the new Luci App for apinger:
Overview:
Interfaces:
Down Alarm:
Delay Alarm:
Loss Alarm:
Targets:
@feckert

luci-app-apinger: Add LuCI for Apinger

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/mounts.js

luci-mod-system: mount sections are always mounted unless they are explicitly not mounted

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js

Added code to display fcdn-name in DHCPv4 lease table.
(based on code in DHCPv6 lease table)
Signed-off-by: Max S Kash <asukms@ya.ru>
Indentation adjused and wrapped commit message
cherry pick from master https://github.com/openwrt/luci/commit/8a46648e5bfb4b8f4d2452c51b5181631d260b6f

[21.02]luci-mod-status,mod-network: Added fqdn-name to DHCPv4 lease table

---

protocols/luci-proto-openfortivpn/htdocs/luci-static/resources/protocol/openfortivpn.js
protocols/luci-proto-openfortivpn/root/usr/libexec/rpcd/luci.openfortivpn
protocols/luci-proto-openfortivpn/root/usr/share/rpcd/acl.d/luci-openfortivpn.json

Linked packages PR: [#16902](https://github.com/openwrt/packages/pull/16902)
Add support for user cert, key and CA cert in luci. This is largely replicated from luci-proto-anyconnect.
Add support for persistent option, to reconnect after timeout (default 5 minutes)
Finally correct the trusted cert SHA label from SHA1 to SHA256.
Signed-off-by: Matthew Hagan <mnhagan88@gmail.com>

luci-proto-openfortivpn: cert/key PEM support, persistent option, SHA label fix

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/luasrc/model/cbi/simple-adblock.lua
applications/luci-app-simple-adblock/luasrc/view/simple-adblock/buttons.htm
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
applications/luci-app-simple-adblock/root/etc/uci-defaults/40_luci-simple-adblock

* Support for (upcoming) dnsmasq nftset
Depends on https://github.com/openwrt/packages/pull/19246
(cherry picked from commit 9b71a35428e0ddbf0347c8ba62da2f4168ddb21b)

[22.03] luci-app-simple-adblock: update to 1.9.0-1

---

libs/rpcd-mod-luci/src/luci.c

WPA3 added new ciphers, add support for displaying these in the wireless overview page
Signed-off-by: Joerg Werner <schreibubi@gmail.com>

rpc-mod-luci: Add support for ccmp-256/gcmp/gcmp-256 ciphers

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

luci-mod-network: Expose RSN Preauth WPA2-EAP setting.

---

applications/luci-app-upnp/root/usr/libexec/rpcd/luci.upnp

Make luci.upnp rpcd backend plugin compatible with miniupnpd-nftables.
Depends on PR https://github.com/openwrt/packages/pull/19320

luci-app-upnp: make nftables compatible

---

protocols/luci-proto-unet/Makefile
protocols/luci-proto-unet/htdocs/luci-static/resources/protocol/unet.js

I made a small protocol handler to create initial support for the new unetd VPN daemon from @nbd168 
Currently this just enables seeing the VPN interface in the LuCI network overview, plus the keys used.
No relevant config change possibilities, yet, (as I am not sure how unetd would react if options like keys are later change via uci).

luci-proto-unet: initial support

---

applications/luci-app-lorawan-basicstation/Makefile
applications/luci-app-lorawan-basicstation/htdocs/luci-static/resources/view/lorawan-basicstation/advanced.js
applications/luci-app-lorawan-basicstation/htdocs/luci-static/resources/view/lorawan-basicstation/general.js
applications/luci-app-lorawan-basicstation/htdocs/luci-static/resources/view/lorawan-basicstation/log.js
applications/luci-app-lorawan-basicstation/root/usr/share/luci/menu.d/luci-app-lorawan-basicstation.json
applications/luci-app-lorawan-basicstation/root/usr/share/rpcd/acl.d/luci-app-lorawan-basicstation.json

LuCi support for Basicstation
Depends on https://github.com/openwrt/packages/pull/19188
Signed-off-by: Marcus Schref <mschref@web.de>

luci-app-lorawan-basicstation: Add luci-app-lorawan-basicstation

---

applications/luci-app-smartdns/Makefile
applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
applications/luci-app-smartdns/po/de/smartdns.po
applications/luci-app-smartdns/po/es/smartdns.po
applications/luci-app-smartdns/po/pt-BR/smartdns.po
applications/luci-app-smartdns/po/templates/smartdns.pot
applications/luci-app-smartdns/po/zh_Hans/smartdns.po
applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json

Depends on https://github.com/openwrt/packages/pull/19365
screenshot:

luci-app-smartdns: bump to 1.2022.38

---

protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js

Add options proxy server and reconnect timeout
Since commits from openwrt/packages where added:
[99213e631179437c6209b651c97c05511bceda9a](https://github.com/openwrt/packages/commit/99213e631179437c6209b651c97c05511bceda9a)
[614f33a9d7fcd582d2d0d01fedcfbd0ace60c459](https://github.com/openwrt/packages/commit/5c84d8ceba83b7f017f631a2fed1900b5926869a)
Signed-off-by: David Bentham <db260179@gmail.com>

luci-proto-openconnect: Add options proxy server and reconnect timeout

---

modules/luci-base/root/www/index.html

Added more meta headers to ensure proper cache control in Firefox. Before this patch, the `/` url hasn't even been requested when opened in Firefox.
Signed-off-by: Daniel Kucera <daniel.kucera@gmail.com>

proper cache control in firefox

---

applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
applications/luci-app-smartdns/po/de/smartdns.po
applications/luci-app-smartdns/po/es/smartdns.po
applications/luci-app-smartdns/po/pt-BR/smartdns.po
applications/luci-app-smartdns/po/templates/smartdns.pot
applications/luci-app-smartdns/po/zh_Hans/smartdns.po

Maintainer: me
Compile tested: TL-WR703N/OpenWrt 22.03 stable

luci-app-smartdns: fix redirect error message issue

---

applications/luci-app-dawn/luasrc/tools/ieee80211.lua

Sometimes 0 is passed to the frequency. Return 0 in that case.

luci-app-dawn: return 0 in case of weird frequency

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/sshkeys.js

Allow importing SSH public keys of types "ecdsa-sk" and "ed25519-sk" via LuCI.
These key types can be generated via the -t flag in ssh-keygen and are supported in recent versions of dropbear. As ssh-keygen ignores the -b flag when generating ecdsa-sk and ed25519-sk keys, I've set the curve field in the objects returned by the decode function to fixed strings for both ecdsa-sk and ed25519-sk input strings. This is in contrast to ecdsa keys for which various curves can be provided during generation (e.g., NIST P-256, NIST P-384, and NIST P-521).
Signed-off-by: Eric McDonald <eric.mcdonald@protonmail.com>

luci-mod-system: allow ecdsa-sk and ed25519-sk key types

---

applications/luci-app-smartdns/Makefile
applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
applications/luci-app-smartdns/po/de/smartdns.po
applications/luci-app-smartdns/po/es/smartdns.po
applications/luci-app-smartdns/po/pt-BR/smartdns.po
applications/luci-app-smartdns/po/templates/smartdns.pot
applications/luci-app-smartdns/po/zh_Hans/smartdns.po
applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json

Maintainer: me
Compile tested: TL-WR703N/22.03-SNAPSHOT r19160+542-7ea2f3d6e2
Depends on https://github.com/openwrt/packages/pull/19588

luci-app-smartdns: Fix RPC error and add restart button

---

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js

The `service_name` option must be empty for custom services, otherwise an error is raised in `dynamic_dns_updater.sh`.
Signed-off-by: Julien Cassette <julien.cassette@gmail.com>

luci-app-ddns: fix creation of custom service (fix #4926)

---

applications/luci-app-wireguard/htdocs/luci-static/resources/view/wireguard/status.js

Attempts to address issue #6003
Tested on 22.03.0

luci-app-wireguard: trivial fix to separate a peer's multiple IPs

---

applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json

Maintainer: me
Compile tested: TL-WR703N/22.03-SNAPSHOT r19160+542-7ea2f3d6e2
Resolve Review Conversation: https://github.com/openwrt/luci/pull/6018

luci-app-smartdns: remove unnecessary permissions

---

applications/luci-app-smartdns/Makefile
applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
applications/luci-app-smartdns/po/de/smartdns.po
applications/luci-app-smartdns/po/es/smartdns.po
applications/luci-app-smartdns/po/pt-BR/smartdns.po
applications/luci-app-smartdns/po/templates/smartdns.pot
applications/luci-app-smartdns/po/zh_Hans/smartdns.po
applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json

Maintainer: me
Compile tested: TL-WR703N/22.03-SNAPSHOT r19160+542-7ea2f3d6e2
backport [luci-app-smartdns: Fix RPC error and add restart button](https://github.com/openwrt/luci/pull/6012)
Depends on https://github.com/openwrt/packages/pull/19594

[openwrt-22.03] luci-app-smartdns: update to 1.2022.38

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Adds LuCI GUI for dnsmasq DHCP 'relays'.
The helper functions in dnsmasq/files/dnsmasq.init limit behaviour whereby it is not possible to omit server_addr, where to omit it (dnsmasq supported) would result in a broad- or multicast further on.
Tested on 22.03.2

luci-mod-network: 'relay' tab added

---

applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/cn.edu.tsinghua.tuna.dns.lua
applications/luci-app-https-dns-proxy/po/zh_Hans/https-dns-proxy.po

luci-app-https-dns-proxy: add cn.edu.tsinghua.tuna.dns.lua provider
Signed-off-by: Zhang Rui <rui.crater@gmail.com>

luci-app-https-dns-proxy: add cn.edu.tsinghua.tuna.dns.lua provider

---

applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua

@feckert This is the luci part of the PR https://github.com/openwrt/packages/pull/19756
In some situations you need to set the compress param without an algorithm. Compression will be turned off, but the packet framing for compression will still be enabled, allowing a different setting to be pushed later.
As it is not possible to have options with optional values at the moment, I've introduced a pseudo value "frames_only" which will be removed in the init script.

luci-app-openvpn: add possibility to set param "compress" without algorithm

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

* fixes error mentioned in https://github.com/openwrt/luci/pull/6075#issuecomment-1306581739

luci-app-simple-adblock: bugfix: allow empty leds field

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

* fixes error mentioned in https://github.com/openwrt/luci/pull/6075#issuecomment-1306581739
(cherry picked from commit 41fee33c20681d514377666515aad9d3bcbfb7f5)

[22.03] luci-app-simple-adblock: bugfix: allow empty leds field

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock

Depends on https://github.com/openwrt/packages/pull/19901
(cherry picked from commit ec31047e357afc19806b7f3d5781389769fada81)

[22.03] luci-app-simple-adblock: update to 1.9.3-1

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Fixes `--server` validation for:
- `/domain[/domain]`
- `//`
- `/#/`
Fixes hostname validation for:
- `*.domain`
- `*domain`
Changes `..domain` to be an invalid hostname

luci-mod-network: fix address validation

---

applications/luci-app-statistics/root/etc/config/luci_statistics

Change the shortest defined statistics period from 1 hour to 2 hours.
In practice, this only changes the displayed graph for the shortest data period to show 2 hours of data instead of 1 hour.
The underlying database is not changed:
there are currently 288 data items for each period, so with the 30 seconds default step, the shortest data series contains 288 x 0.5 min = 144 min > 2 hours of data.
I authored a PR and did not immediately commit this, as I wondered about the impact:
* From data perspective, the change makes sense as the RRD database already contains that 2 hours data, so just show it.
* On the other hand, showing 2 hours may decrease the visible granularity on the "hourly" graph (as the graph is horizontally drawn more tightly).
You may easily test this by just editing the …

luci-app-statistics: set shortest period data/graph to 2 hours

---

applications/luci-app-natmap/htdocs/luci-static/resources/view/natmap.js
applications/luci-app-natmap/po/templates/natmap.pot

The bind port (-b) can be used with forward port (-p), so expose this option in config file. Requires [this PR](https://github.com/openwrt/packages/pull/20150) to be merged.
`stun_server` option is used in both TCP and UDP mode, so remove that description.

luci-app-natmap: add forward_port option and update stun_server description

---

applications/luci-app-natmap/htdocs/luci-static/resources/view/natmap.js
applications/luci-app-natmap/po/templates/natmap.pot

The bind port (-b) can be used with forward port (-p), so expose this option in config file.
stun_server option is used in both TCP and UDP mode, so remove that description.

[22.03] luci-app-natmap: add forward_port option and update stun_server description

---

applications/luci-app-sqm/htdocs/luci-static/resources/view/network/sqm.js

The field labels contain verbose descriptions which looks terrible in the
UI. Replace them with short labels and move the verbose text into the help
text where it belongs.
Fixes #6161.

luci-app-sqm: Move verbose descriptions into help text

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/routes.js

The neighbour display parses the output of 'ip -4 neigh show' e.g.
192.168.219.95 dev eth1 lladdr 38:b4:d3:c9:b2:0c REACHABLE 192.168.219.200 dev eth1 lladdr 04:c4:61:12:f2:d2 STALE
Using regexp /^([0-9a-f:.]+) (.+) (\S+)$/  Unfortunately there's a space character that sneaks in at the end of line, so let's make this less brittle by accepting lines that may end with spaces e.g.
/^([0-9a-f:.]+) (.+) (\S+) *$/

luci-mod-status: fix neighbour display

---

applications/luci-app-xinetd/htdocs/luci-static/resources/view/xinetd/xinetd.js

This extension is based on the issue https://github.com/openwrt/luci/issues/6151 and implements the requested `redirect` feature.
It (indirectly) depends on PR in another repo (https://github.com/openwrt/packages/pull/20264) to correctly split IP address and port for use with xinetd.

luci-app-xinetd: add processing of redirect option

---

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/sensors.js
applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/sensors.js

This makes a humidity graph appear for the sht3x I have connected to my OpenWrt machine.
However it also shows some artifacts that I don't understand:
If you spot the problem, please advise.

luci-app-statistics: Generate graphs for humidity sensors

---

applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-whw03v2.json

Add support for Linksys WHW03 V2 (Velop)
The device was [merged](https://github.com/openwrt/openwrt/commit/9e4ede8344d60d4837e047e9275c21fd2a8f130b) in openwrt a couple of days ago.
This patch was fully tested on a running device.
Signed-off-by: Vincent Tremblay <vincent@vtremblay.dev>

luci-app-advanced-reboot: add support for Linksys WHW03 v2

---

collections/luci-light/Makefile
collections/luci-ssl-openssl/Makefile
collections/luci-ssl/Makefile
collections/luci/Makefile

The `luci` collection contains package management and attended sysupgrades support, which are not that useful if not even undesired for self-compiled images.
Rework the `luci-light` collection to exclude the two above mentioned features, and make `luci` instead depend on the light collection in additon to those features.
The `luci-ssl` and `luci-ssl-openssl` collections then only need to depend on `luci-light`.
We now have three variants with won't pull in `luci-app-opkg` or `luci-app-attendedsysupgrade`, making everybody happy.

luci-light: rework and reenable

---

libs/luci-lib-httpprotoutils/luasrc/http/mime.lua

Airplay of a statically hosted video file from one Apple device to another fails due to unrecognized content-type. Adding Airplay supported mime types fixes the issue.
Signed-off-by: Sasha Andonov <s.andonnov@gmail.com>

luci-lib-httpprotoutils: add airplay mime types

---

collections/luci-ssl/Makefile

OpenWrt has switched the default SSL library to be mbedtls instead of WolfSSL. To avoid the need of installing both SSL libraries, switch luci-ssl to use the mbedtls variant of libustream and px5g.
PR for CI testing

luci-ssl: switch to mbedtls

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/zones.js

I wasted a little to much time tinkering around with my configuration before realizing I just needed to set the "Masquerading" option. In an attempt to save everyone else this wasted time, I want to suggest to add a tooltip clarifying this option.
I am not sure how the gettext internationalization files are to be edited/generated; If anyone has pointers for this I will gladly make sure that this all works fine with my newly added interface string.

luci-app-firewall: Add clarification to masquerading option

---

modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/graph.js

This adds pilot tones to the bit allocation graph (the data is available via ubus since https://github.com/openwrt/openwrt/commit/b91d7d9d78ea12097de4c518c8cd2215ff286f7a).

luci-mod-dsl: add pilot tones

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/50_dsl.js

This restructures the DSL metrics to make them easier to read, and adds several additional metrics, making use of https://github.com/openwrt/openwrt/commit/b91d7d9d78ea12097de4c518c8cd2215ff286f7a.

luci-mod-status: extend DSL metrics

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns-family.lua
applications/luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/com.adguard.dns.lua
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* Makefile: change dependency from luci-mod-admin-full to luci-base
* Providers: add AdGuard and AdGuard Family
* Bugfix: update field value in CBI, fixes https://github.com/openwrt/luci/issues/6244

luci-app-https-dns-proxy: update to 2022-10-15-11

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* Makefile: change dependency from luci-mod-admin-full to luci-base
* Bugfix: update field value in CBI, fixes https://github.com/openwrt/luci/issues/6244
(cherry picked from commit 6ee377fd4b388e7878ab9bcb7e9c47e994578be2)

[22.03] luci-app-https-dns-proxy: update to 2022-10-15-11

---

modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/stats.js
modules/luci-mod-dsl/po/templates/dsl.pot
modules/luci-mod-dsl/root/usr/share/luci/menu.d/luci-mod-dsl.json
modules/luci-mod-dsl/root/usr/share/rpcd/acl.d/luci-mod-dsl.json
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/50_dsl.js

As discussed in #6224, create a new page for DSL information in luci-mod-dsl, and change luci-mod-status to only show the most important data on the overview page.

Move DSL status to new page in luci-mod-dsl

---

collections/luci/Makefile

The package is only useful when running an official build. The ImageBuilders used for this service can not contain any special compiler flags etc. used by custom builds.
Instead of installing the package whenever `luci` is installed, it should be installed via the buildbots itself, like it's currently done for `luci`.
@ynezz do you mind adding the `loci-app-attendedsysupgrade` package via the buildbots?

luci: remove installation of attendedsysupgrade

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js
applications/luci-app-pbr/po/templates/pbr.pot

* do not remove non-empty custom user files fields
* add provides for vpnbypass and vpn-policy-routing luci apps 
addresses https://github.com/openwrt/luci/pull/6127#pullrequestreview-1311512052
(cherry picked from commit 0d4b675e7062ddc0d1d2b9be2d0962186239c51b)

[22.03] luci-app-pbr: bugfixes

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/nftables.js

Fixes #6264 by adding counter and comment for empty match / "Any packet" in nftables.

luci-mod-status: nftables add counter and comment for empty match

---

protocols/luci-proto-cni/Makefile
protocols/luci-proto-cni/htdocs/luci-static/resources/protocol/cni.js

simple protocol support for *simple protocol* - cni protocol can be used with container networking, but even if it's name is cni protocol, it also works great with netavark (cni replacement for Podman)
cni-protocol is extremely useful when you want to create a firewall zone and manage firewalling of containers with openwrt's own firewall configuration, as it makes it possible to define a zone that doesn't exist yet (container not running yet?). There's not much to do with it at Luci, but with proto package, it at least won't say unsupported protocol or what ever it was that it says on occasions like that.

luci-proto-cni: add package

---

applications/luci-app-openwisp/htdocs/luci-static/resources/view/openwisp.js

Without these changes, saving the form of luci-app-openwisp without doing any change generates a configuration which will not work in most cases.
In this patch I took care of providing the right settings to show the default values, avoid saving default values and show the interface names properly. With these changes it will be possible for a user to edit just 1 field without introducing breaking changes.

luci-app-openwisp: improved schema for usability

---

applications/luci-app-openwisp/htdocs/luci-static/resources/view/openwisp.js

Without these changes, saving the form of luci-app-openwisp without doing any change generates a configuration which will not work in most cases.
In this patch I took care of providing the right settings to show the default values, avoid saving default values and show the interface names properly. With these changes it will be possible for a user to edit just 1 field without introducing breaking changes.
Signed-off-by: Federico Capoano <f.capoano@openwisp.io>
(cherry picked from commit 8727b1cbc8542e06b0b9db7e41366bbbe19d42f5)

[22.03] luci-app-openwisp: improved schema for usability

---

libs/luci-lib-px5g/Makefile

See commit 5c545bdb "treewide: replace PKG_USE_MIPS16:=0 with PKG_BUILD_FLAGS:=no-mips16" on the main repository.

luci-lib-px5g: refactor to use PKG_BUILD_FLAGS:=no-mips16

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

Remove the white background color for the file input elements, this way it'll use the default color defined for input elements, matching the light/dark theme.

luci-theme-bootstrap: File input background color

---

.github/workflows/build.yml

The old version which uses Node.js v12 will be disabled in the end of this year.

CI: update dependencies

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js
applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js

* corrects the view as IPv4 and IPv6 for rules where the family is 'any' and the IP not set (this fixes #9c55500), e.g. a forward rule like that:
```
config redirect 'adblock_lan53'
option name 'Adblock DNS (lan, 53)'
option src 'lan'
option proto 'tcp udp'
option src_dport '53'
option dest_port '53'
option target 'DNAT'
option family 'any'
```
**Old behavior**
Forward:
SNAT:
**New behavior:**
Forward:
SNAT:

luci-app-firewall: fix the IPv6 forwards/snats view

---

applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js
applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/view/shadowsocks-libev/instances.js

Added ability to pass an Access Control List (--acl param) to forbid access to specified IP addresses
Maintainer: @yousong
Compile tested: MediaTek MT7628AN ver:1 eco:2, TP-Link TL-WR841N v13, OpenWrt 22.03.3 r20028-43d71ad93e
Run tested: MediaTek MT7628AN ver:1 eco:2, TP-Link TL-WR841N v13, OpenWrt 22.03.3 r20028-43d71ad93e

luci-app-shadowsocks-libev: ACL support

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot
applications/luci-app-simple-adblock/root/usr/libexec/rpcd/luci.simple-adblock

* update to support corresponding principal package
Depends on https://github.com/openwrt/packages/pull/20769
(cherry picked from commit b7be432ba79e1320661a7a92d2203358bcbde88c)

[22.03] luci-app-simple-adblock: update to 1.9.5

---

applications/luci-app-pbr/Makefile

* Artificial version bump as WebUI compares version number to the principal package
Principal package PR: https://github.com/openwrt/packages/pull/20930

luci-app-pbr: update to 1.1.1-5

---

applications/luci-app-pbr/Makefile

* Artificial version bump as WebUI compares version number to the principal package
Principal package PR: https://github.com/openwrt/packages/pull/20931
(cherry picked from commit 831d05163448a7dabb016caa4c07fa3c122ffe60)

[22.03] luci-app-pbr: update to 1.1.1-5

---

applications/luci-app-smartdns/Makefile
applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
applications/luci-app-smartdns/po/de/smartdns.po
applications/luci-app-smartdns/po/es/smartdns.po
applications/luci-app-smartdns/po/pt-BR/smartdns.po
applications/luci-app-smartdns/po/templates/smartdns.pot
applications/luci-app-smartdns/po/zh_Hans/smartdns.po
applications/luci-app-smartdns/po/zh_Hant/smartdns.po
applications/luci-app-smartdns/root/usr/share/rpcd/acl.d/luci-app-smartdns.json

Maintainer: me / @<github-user> (find it by checking history of the package Makefile)
Compile tested: x86_64 openwrt docker image
Run tested: latest docker image, https://github.com/openwrt/packages/commit/21d02e598a0bf209cebc1c5b8f3e433913329107
Depends on https://github.com/openwrt/packages/pull/20939

luci-app-smartdns: bump to 1.2023.42

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* if curl is not installed, there used to be an error in logs from uhttpd that curl is not found, this commit addresses it

luci-app-https-dns-proxy: fix curl-related error in logs

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/luasrc/model/cbi/https-dns-proxy.lua
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* if curl is not installed, there used to be an error in logs from uhttpd that curl is not found, this commit addresses it
(cherry picked from commit 5553a66903a1889b52aeb2d36e3d9de455e45c2e)

[22.03] luci-app-https-dns-proxy: fix curl-related error in logs

---

protocols/luci-proto-mbim/Makefile
protocols/luci-proto-mbim/htdocs/luci-static/resources/protocol/mbim.js

Introduce support for MBIM protocol to LuCI, based on upstream-accepted implementation in OpenWrt core.
Draft until openwrt#12521 is pending, to finalize the interface.
Supersedes #4360.

luci-proto-mbim: introduce package

---

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/30_wifi.js

Implements feature request #4472.

luci-mod-dashboard: hide wireless pane when there are no radios

---

protocols/luci-proto-qmi/htdocs/luci-static/resources/protocol/qmi.js

To support split-APN dual-stack connections over QMI, add new parameters supported in UCI to LuCI as well. Previously, connection profile wasn't configurable from LuCI at all, so add options to set which APN profile to match for each protocol.
Setting to draft until https://github.com/openwrt/openwrt/pull/10913 is merged, but this is ready for review and testing.

luci-proto-qmi: allow v6apn and (v6)profile configuration

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/rules.js

This adds entries for ICMPv6 MLD types. This fixes the ICMPv6 MLD types to be consistent with fw4. These types were added to fw4 in this [commit](https://github.com/openwrt/firewall4/commit/e6e82a55206cf7017f26b92f7097f779161b5cac) but were omitted from the corresponding luci-app-firewall [commit](https://github.com/openwrt/luci/commit/88a016cbff7eacf3a8248bc4949904abacef6685).

luci-app-firewall: add missing ICMPv6 MLD types

---

applications/luci-app-shadowsocks-libev/htdocs/luci-static/resources/shadowsocks-libev.js

The field `local_address` shows twice on column `Overview` for client components

luci-app-shadowsocks-libev: don't repeat fields

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

Add ability to choose `random` or custom `macaddr` for wifi-iface
(**Updated** screenshot as per latest commit: https://github.com/openwrt/luci/pull/5896/commits/ab73d459ca6a57ba0e5b4898c8eb3dbdc46f252a)
Choosing the new *randomly generated* MAC address option will cause a new MAC address to be generated whenever the WiFi interface is (re-)configured or the system is rebooted.
This will work only if wifi-iface supports `option macaddr 'random'`.
Depends on https://github.com/openwrt/openwrt/pull/10307

luci-mod-network: wireless.js: add wifi-iface macaddr random support

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

Spell out the names of the DSL standards to make the options easier to understand. For modems supporting VDSL, also mention clearly which of the options actually set the bits for VDSL2.
As the items now start with the name of an ADSL standard, use that for ordering. The generic variants including VDSL2 support stay at the top, as they should be a good choice in almost all cases.
(I think ideally it would also be nice to highlight the first few options (especially the A/L/M and the B/J option) in some way, as one of those should be the right choice in almost all cases. But I'm not sure if there is good way to do that.)

luci-mod-network: improve descriptions for DSL annex option values

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/modemmanager_helper.js
protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js
protocols/luci-proto-modemmanager/htdocs/luci-static/resources/view/modemmanager/status.js
protocols/luci-proto-modemmanager/root/usr/share/luci/menu.d/luci-proto-modemmanager.json
protocols/luci-proto-modemmanager/root/usr/share/rpcd/acl.d/luci-proto-modemmanager.json

Adds a ModemManager status page to proto-modemmanager. It gets **general information**, **location** and **SIMs** for all available modems from ModemManager via `mmcli`.
Also uses a new helper for getting available devices as JSON output in the protocol instead of parsing them with Regex.

luci-proto-modemmanager: add status page

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/forwards.js

This allows to to define multiple zones for NAT reflection rules.
Fixes: #1560

luci-app-firewall: add reflection_zone field to forwards

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

When the new result is empty, including when another scan is running in the background, the table was emptied, but the graph persisted. With this change, the list will persist and missing APs will be shown faded.

luci-mod-status: channel_analysis.js: fix stale scan result.

---

applications/luci-app-unbound/luasrc/model/cbi/unbound/configure.lua

I noticed some odd behaviour while setting up Unbound: the [default for `validator_ntp` is `1`](https://github.com/openwrt/packages/blob/master/net/unbound/files/README.md#config-unbound), however luci thought it was `0` and so would clear the uci entry when unchecked, meaning the `validator_ntp` option could never be disabled.
Simply setting the luci default to `true` fixes the issue.

luci-app-unbound: correct default for validator_ntp

---

applications/luci-app-mosquitto/luasrc/model/cbi/mosquitto.lua

1. Fix notifications_local_only flag -  the option wasn't being applied at all because of a typo.
2. Fix invalid XML in option description - trying to add "notifications" option resulted in malformed XML.

luci-app-mosquitto: fixes for notification options

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/29_ports.js
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status-index.json

This commit adds an ethernet port status overview to the main status page.
The design should theoretically scale to many ports. Below is a mock up created by repeating the six original ports multiple times:
Logical network membership and detailled statistics are exposed as tooltips:
Original forum topic:
https://forum.openwrt.org/t/ethernet-port-icons-on-openwrt/130799

luci-mod-status: introduce ethernet port status view

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

* bugfix: move the break tag in front of the unsupported DNS options to pretty up the output
* use pkg.Name in RPCD calls
* slightly change the version display in WebUI to make it consistent with other packages

luci-app-simple-adblock: bugfix: unsupported DNS options display

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

* bugfix: move the break tag in front of the unsupported DNS options to pretty up the output
* use pkg.Name in RPCD calls
* slightly change the version display in WebUI to make it consistent with other packages
(cherry picked from commit 8001cc5f2fce4b54fccca46157d42cbfca9f5894)

[22.03] luci-app-simple-adblock: bugfix: unsupported DNS options display

---

applications/luci-app-simple-adblock/Makefile
applications/luci-app-simple-adblock/htdocs/luci-static/resources/simple-adblock/status.js
applications/luci-app-simple-adblock/htdocs/luci-static/resources/view/simple-adblock/overview.js
applications/luci-app-simple-adblock/po/templates/simple-adblock.pot

* bugfix: move the break tag in front of the unsupported DNS options to pretty up the output
* use pkg.Name in RPCD calls
* slightly change the version display in WebUI to make it consistent with other packages
(cherry picked from commit 8001cc5f2fce4b54fccca46157d42cbfca9f5894)

[23.05] luci-app-simple-adblock: bugfix: unsupported DNS options display

---

applications/luci-app-uhttpd/Makefile
protocols/luci-proto-vpnc/Makefile

The app was migrated to JS so the LUA_TARGET is not needed. Also remove LUCI_PKGARCH:=all which is anyway a default.
Same for luci-proto-vpnc

luci-app-uhttpd: Remove LUA_TARGET

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

I used the MX and SRV tabs as templates to create a new tab where users can create cname records in dnsmasq, using the cname and target options.

luci-mod-network: add support for creating cname records

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Adjust the order of tabs in the DNS/DHCP page.
Based on estimated importance of tabs
* move common (old) tabs to be earlier
* move the less frequently used (new) tabs later
Before:
New:
@jow- 
I actually think that we might prefer to reorganise/group some tabs e.g the new DNS fields (MX, CNAME, SRV) to be subtabs. Possible?

luci-mod-network: Adjust DHCP/DNS tab order

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

Make the new configuration `allowedmode` and `preferredmode` configurable via LuCI.
This depends on the pullrequest https://github.com/openwrt/packages/pull/21766

luci-proto-modemmanager: add allowed and preferred mode

---

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/sensors.js
applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/sensors.js

Added missing graphs for voltage, current, power and fanspeed sensors.
No new or modified translation strings.
Signed-off-by: Carsten Spieß <mail@carsten-spiess.de>

luci-app-statistics: missing sensor types added

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/iptables.js

fix  comments disappeared after this commit https://github.com/openwrt/luci/commit/b3ef7a17eacc6ce2f2385bbb517c67906dd2a753
@jow-

luci-mod-status: fix iptables not showing comments

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

Currently, results from the 2.4 and 6 ghz bands get mixed together, because internally the channel number is used for some checks.
This adds some checks to prevent that, and then adds a new 6g band tab.
This works on my end, but my AP is the only 6g one nearby, so I don't have others in my scan results. Can someone test that please?

luci-mod-status: add support for the 6g band

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

to the bottom of interface IPv6 settings tab

luci-network-interfaces: Add IPv6 lifetime options

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

x86 is the only target that allows you to install either EFI or BIOS images, thereby add an extra check for that.

luci-app-attendedsysupgrade: add x86 efi/bios case

---

protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

If the chosen wireguard Endpoint is an IPv6 address, we currently generate invalid format, as IPv6 addresses with a port appended need escaping with `[]`
Fixes issue #6592

luci-proto-wireguard: Escape IPv6 endpoints with [] in generated wireguard config

---

modules/luci-base/htdocs/luci-static/resources/cbi.js
modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/fs.js
modules/luci-base/htdocs/luci-static/resources/luci.js
modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-base/htdocs/luci-static/resources/rpc.js
modules/luci-base/htdocs/luci-static/resources/uci.js
modules/luci-base/htdocs/luci-static/resources/ui.js

When opening in IntelliJ IDE it checks for grammar and marks a lot of problems.
So I fixed them to avoid distraction next time.

luci-base: Fix typos in JsDocs

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

* bugfix: add missing dl command to RPCD script
* improve output of error messages/link to README
(cherry picked from commit d15a1fb6939684583b327f7388a1473c7d49841d)

[23.05] luci-app-adblock-fast: bugfix: working re-download

---

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/memory.js
applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/memory.js
applications/luci-app-statistics/root/etc/config/luci_statistics

Make hiding/showing the 'free' memory configurable.
Set default as disabled, not hidden.
* If enabled, the graph scales to actually used memory, enabling a more detailed view to memory usage.
* If disabled, the graph always shows the whole memory / 100%.
Example:
Enabled:
Disabled, default (and the only choice previously):
Maintainer: me

luci-app-statistics: memory: make hiding 'free' configurable

---

applications/luci-app-ksmbd/htdocs/luci-static/resources/view/ksmbd.js

`/etc/config/ksmbd` supports multiple interfaces (in `config globals`->`option interface`) but the current UI only supports selecting a single one. This patch adds support for selecting multiple interfaces, based on how `luci-app-samba4` does it.
Closes: #6620
Suggested-by: @AndroKev (let me know if you want your name in the commit)

luci-app-ksmbd: add UI for multiple interfaces

---

applications/luci-app-minidlna/htdocs/luci-static/resources/view/minidlna.js

Also remove o.default = o.enabled
I have no idea why anyone may want to change the cover file name. The big list looks confusing so it's better to move it to advanced tab.

luci-app-minidlna: move album covers to advanced tab

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The conditional is wrong. IndexOf returns a number and not true/false, so it does not work.

luci-app-attendedsysupgrade: fix search for x86 target

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/status/include/70_adblock-fast.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Description:
* bugfix: localizable entries in overview
* update grammar/naming for buttons
* prepare for pause button
* add status include file to show service status

luci-app-adblock-fast: bugfix: localizable entries in overview

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/status/include/70_adblock-fast.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Description:
* bugfix: localizable entries in overview
* update grammar/naming for buttons
* prepare for pause button
* add status include file to show service status
(cherry picked from commit a0574a3ad1c7831705d979ad09b8dcc94bbd4184)

[23.05] luci-app-adblock-fast: bugfix: localizable entries in overview

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* add status->overview include file
* sync version to principal package
* minor code formatting/styling fixes for js files
* improve HTTP/2 and HTTP/3 detection in RPCD script

luci-app-https-dns-proxy: add status->overview include file

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* add status->overview include file
* sync version to principal package
* minor code formatting/styling fixes for js files
* improve HTTP/2 and HTTP/3 detection in RPCD script
(cherry picked from commit dea2f135d7c915d46940e95a49891b945037be29)

[22.03] luci-app-https-dns-proxy: add status->overview include file

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* add status->overview include file
* sync version to principal package
* minor code formatting/styling fixes for js files
* improve HTTP/2 and HTTP/3 detection in RPCD script
(cherry picked from commit dea2f135d7c915d46940e95a49891b945037be29)

[23.05] luci-app-https-dns-proxy: add status->overview include file

---

applications/luci-app-dockerman/luasrc/model/cbi/dockerman/container.lua

I have never saw stats page has any 'stats', maybe dockerd call `ps -aux` or `ps -ef` on openwrt host, which not supported.
`CPU usage` and `Memory usage` does not depends on docker:top, always show on container running (docker:top status code is not 409).

luci-app-dockerman: fix stats page always blank

---

applications/luci-app-statistics/README.md
applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/rrdtool.js
applications/luci-app-statistics/root/etc/init.d/luci_statistics
applications/luci-app-statistics/root/etc/luci_statistics/README.backups
applications/luci-app-statistics/root/lib/upgrade/luci_statistics-add-conffiles.sh

Add a backup/restore capability for rrd data storage in luci_statistics.  The data storage is typically in /tmp and does not survive reboot or sysupgrade.  This adds an option for the administrator to configure the RRD plugin, so that the RRD data are are preserved with a backup copy in the overlay file system.
This works for shutdown/reboot, sysupgrade (backup config files, restore config files, and true sysupgrade).
Also fix a bug where starting luci_statistics for the first time would not get a restart a running collectd

luci-app-statistics: Add backup/restore for RRD statistics

---

applications/luci-app-dawn/htdocs/luci-static/resources/dawn/dawn-common.js
applications/luci-app-dawn/htdocs/luci-static/resources/view/dawn/hearing_map.js

Some bug fixes and a small improvements that were discovered after the initial implementation of the JavaScript version of luci-app-dawn:
* Correctly show multiple APs per client in the hearing map
* Display correct name of all APs in the hearing map
* Show if client is connected to the network in the hearing map. This replaces the column for Stations Connected, which is not a property of a client but of an AP, and is available still in the network overview.
* Display both hostname and MAC address for clients/APs
* Convert spaces to tabs in dawn-common.js for consistency

luci-app-dawn: Bug fixes for JavaScript implementation

---

applications/luci-app-dawn/htdocs/luci-static/resources/dawn/dawn-common.js
applications/luci-app-dawn/htdocs/luci-static/resources/view/dawn/hearing_map.js

Some bug fixes and a small improvements that were discovered after the initial implementation of the JavaScript version of luci-app-dawn:
* Correctly show multiple APs per client in the hearing map
* Display correct name of all APs in the hearing map
* Show if client is connected to the network in the hearing map. This replaces the column for Stations Connected, which is not a property of a client but of an AP, and is available still in the network overview.
* Display both hostname and MAC address for clients/APs
* Convert spaces to tabs in dawn-common.js for consistency
Signed-off-by: Daniel Vijge <danielvijge@gmail.com>
(cherry picked from commit e8029b08287c666a43d5ef25c7ea83ce7d606903)

[23.05] luci-app-dawn: Bug fixes for JavaScript implementation

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

* improve error/warning/status messaging
* trim rpcd script code from functions shared with principal package
* depends on https://github.com/openwrt/packages/pull/22619

luci-app-adblock-fast: sync with adblock-fast 1.0.1-1

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

* improve error/warning/status messaging
* trim rpcd script code from functions shared with principal package
* depends on https://github.com/openwrt/packages/pull/22620
(cherry picked from commit ced38d8fc1d70b0a27dcbd2d567686248e1fbfb3)

[23.05] luci-app-adblock-fast: sync with adblock-fast 1.0.1-1

---

applications/luci-app-statistics/root/etc/init.d/luci_statistics

fixes the output of `/etc/init.d/luci_statistics help`

luci-app-statistics: cleanups of bad spacing

---

applications/luci-app-statistics/root/etc/init.d/luci_statistics

Improve the help for sysupgrade_backup and have it check parameters

luci-app-statistics: harden sysupgrade_backup

---

applications/luci-app-adblock-fast/Makefile

Depends on https://github.com/openwrt/packages/pull/22655

luci-app-adblock-fast: sync version with principal package

---

applications/luci-app-adblock-fast/Makefile

Depends on https://github.com/openwrt/packages/pull/22656
(cherry picked from commit 69eff2535ed25e55f2c62450790f4abd64710e42)

[23.05] luci-app-adblock-fast: sync version with principal package

---

applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js

The currently used command "vnstat --json f 1" can be very slow when the database contains many entries. This can result in an XHR timeout error on the configuration page.
Use the "--dbiflist" option instead, which was added in vnStat 2.7.
Fixes: #6702
---
This should also be cherry-picked for 23.05 and 22.03.

luci-app-vnstat2: use more efficient way to get database interfaces

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/routes.js

Routes inherit metric and table from the relevant interface.
Display route metric and table as `auto` when unspecified.
Consolidate modal view for unspecified options.

luci-mod-network: fix route defaults

---

protocols/luci-proto-vxlan/htdocs/luci-static/resources/protocol/vxlan6.js

The VXLAN6 settings form accepts only CIDR notation for IP addresses, but VXLAN6 does not accept such addresses. Attempting to use an address ending with /128 does not bring up the interface. Also, the form is missing the destination port option, unlike its IPv4 counterpart. This commit fixes both these issues.

luci-proto-vxlan: Enable IPv6 address and port settings

---

applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/mercusys-mr90xv1.json

You might want to see [UBI volume structure](https://openwrt.org/toh/mercusys/mr90x_v1#ubi_sctructure) of this device to understand some changes
I didn't want to intrude into the bash part too much, but I think other devices might benefit from certain changes in the future. It's completely backwards compatible and won't affect previously added devices
~~I will mark it as draft for now for more tests, but pretty sure it's more or less final unless reviewers request any changes :)~~
Tested, works perfectly. To reboot back from OEM firmware one would need to:
1. Connect using ssh to [router ip]:20001
2. Edit `/etc/hotplug.d/iface/65-iptv`, adding `telnetd -l /bin/login.sh` on a newline after `#!/bin/sh`
3. Toggle on `IPTV/VLAN Enable` in the web interface
4. Telnet into the router
5. Check …

luci-app-advanced-reboot: add support for Mercusys MR90X v1

---

applications/luci-app-advanced-reboot/Makefile

Bumps version of `luci-app-advanced-reboot` package in response to changes introduced in #6709, @stangri

luci-app-advanced-reboot: bump version number due to changes in code

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

Added options to luci proto to match Pull request #13009
https://github.com/openwrt/packages/pull/13009

luci-proto-modemmanger: add missing proto options

---

docs/README.md

Link will work with the generated web documentation site as well as the Github README Markdown renderer.

docs: fix Client side JS API docs link

---

applications/luci-app-unbound/luasrc/model/cbi/unbound/zone-details.lua

[luci-app-unbound: zone detail DNS assist lacks a option](https://github.com/openwrt/luci/issues/6524)
here is the detail

luci-app-unbound: dns assist in zone-detail add 'unprotected-loop' option #6524

---

protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

Some clients like iOS require this explicitly, and so this change adds the appropriate config with some sensible defaults. If the intended behavior is at all different from what was agreed upon in the issue, let me know and I will se what I can do.
Addresses issue #6050
Signed-off-by: Nicholaos Mouzourakis <nevumx@gmail.com>

luci-proto-wireguard: adding an Addresses option to the wireguard peer config generator

---

applications/luci-app-sshtunnel/Makefile
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_hosts.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_keys.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_servers.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_tunnels.js
applications/luci-app-sshtunnel/po/ru/sshtunnel.po
applications/luci-app-sshtunnel/po/templates/sshtunnel.pot
applications/luci-app-sshtunnel/root/usr/share/luci/menu.d/luci-app-sshtunnel.json
applications/luci-app-sshtunnel/root/usr/share/rpcd/acl.d/luci-app-sshtunnel.json

@nunojpg please have a look
CC @stweil @kvuorine @kzyapkov you guys also contributed to the sshtunnel.
Notes:
Since in future the Dropbear's `dbclient` will be supported I moved all `openssh-client` only options to advanced tab. And I didn't added some options like Compression Level simply because   their defaults is fine for 99.999% of users.
I added Keys section that allows to generate a key and copy a pub key.
A user may not have `ssh-keygen` if removed the `openssh-client` then Dropbear's keygen will be used instead. It will run a slightly different command but in future they may be same https://github.com/mkj/dropbear/issues/236

New app: luci-app-sshtunnel for SSH tunnels

---

applications/luci-app-tor/Makefile
applications/luci-app-tor/htdocs/luci-static/resources/view/tor/tor-hs.js
applications/luci-app-tor/po/ru/tor.po
applications/luci-app-tor/po/templates/tor.pot
applications/luci-app-tor/root/usr/share/luci/menu.d/luci-app-tor.json
applications/luci-app-tor/root/usr/share/rpcd/acl.d/luci-app-tor.json

There was a PR #711 but it was focused on the Proxy configuration which is not fully yet supported by UCI.
The PR adds an ability to configure Tor Hidden Services as a good option to bypass NAT and have a stable access to a router.
Later once the main Tor package gains a support of a Proxy/Bridge configuration we can add this to the same luci app as a different view.
If you accept the PR please also check this small improvement https://github.com/openwrt/packages/pull/21642
@ja-pa you created the tor-hs package so please check and leave your feedback

luci-app-tor: Manage tor-hs onion services

---

libs/luci-lib-nixio/root/lib/upgrade/luci-add-conffiles.sh

add_luci_conffiles does not check whether the file already exists when adding the file, which may result in redundant backups in the sysupgrade backup.

luci-lib-nixio: Fix add_luci_conffiles adding duplicate files

---

protocols/luci-proto-wireguard/htdocs/luci-static/resources/protocol/wireguard.js

Quality of life improvements. Reduce click amounts. LuCI batches all changes for user-review anyway.
Tested on 23.05.0

luci-proto-wireguard: Remove confirmation dialogue to generate keys

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Backport d7e905e83a11d59ea217cd37189040bd6c9d403e to the 23.05 branch, as armsr targets need this for a functional luci-app-attendedsysupgrade
Tested working on armsr/armv8
(change `DISTRIB_RELEASE` in `/etc/openwrt_release` to exactly either `23.05` or `SNAPSHOT`, as the asu server may not offer 23.05 builds from a -rc or 23.05-SNAPSHOT build)

[23.05] backport "luci-app-attendedsysupgrade: add x86 efi/bios case"

---

applications/luci-app-vnstat2/htdocs/luci-static/resources/view/vnstat2/config.js

The output of the command "vnstat --dbiflist 1" is empty when there are no interfaces in the database. Add a check to avoid a "result.stdout is undefined" error in that case.
Ref: https://forum.openwrt.org/t/error-in-luci-vnstat2-configuration-menu/179700
Fixes: 3ac4f567dfdf ("luci-app-vnstat2: use more efficient way to get database interfaces")
---
This fix is also needed in the openwrt-23.05 and openwrt-22.03 branches.

luci-app-vnstat2: fix configuration page when database is empty

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

* add support for smartdns ipset/nftset-based blocking
Depends on https://github.com/openwrt/packages/pull/22824

luci-app-adblock-fast: sync with principal package

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

* add support for smartdns ipset/nftset-based blocking
Depends on https://github.com/openwrt/packages/pull/22825
(cherry picked from commit 4c3cdcb68e8fec3969d2dec73714e1f11c1c749c)

[23.05] luci-app-adblock-fast: sync with principal package

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

* fix app not working on systems without smartdns
* fix smartdns instances selection dependencies
Thanks @Ansuel !

luci-app-adblock-fast: bugfix: L.uci.load

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

* fix app not working on systems without smartdns
* fix smartdns instances selection dependencies
(cherry picked from commit 0473939fff65384badf6d15f30a0e236f2110b3c)

[23.05] luci-app-adblock-fast: bugfix: L.uci.load

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

Maintainer: me
Description:
* create UI elements with an option to pick multiple instances for dnsmasq and smartdns

luci-app-adblock-fast: improve dnsmasq/smartdns instances selection

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

Maintainer: me
Description:
* create UI elements with an option to pick multiple instances for dnsmasq and smartdns
(cherry picked from commit 061a5dc40487fbe63e4ce2314b3c95e0293c1a4e)

[23.05] luci-app-adblock-fast: improve dnsmasq/smartdns instances selection

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* no longer "require uci" in js files
* use L.resolveDefault when loading configs
* improve DNSMASQ config update selection user experience
* switch from uci.get to L.uci.get
* small code improvement of RPCD script

luci-app-https-dns-proxy: update to 2023-10-25-5

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* no longer "require uci" in js files
* use L.resolveDefault when loading configs
* improve DNSMASQ config update selection user experience
* switch from uci.get to L.uci.get
* small code improvement of RPCD script
(cherry picked from commit 799280877fbe7a43dab9c3af1dd509519e2f542b)

[22.03] luci-app-https-dns-proxy: update to 2023-10-25-5

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Description:
* no longer "require uci" in js files
* use L.resolveDefault when loading configs
* improve DNSMASQ config update selection user experience
* switch from uci.get to L.uci.get
* small code improvement of RPCD script
(cherry picked from commit 799280877fbe7a43dab9c3af1dd509519e2f542b)

[23.05] luci-app-https-dns-proxy: update to 2023-10-25-5

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json

Maintainer: me
Description:
* Final (hopefully) attempt to avoid errors if dhcp/smartdns configs are missing
* New user experience for picking dnsmasq/smartdns instances to enable the adblocking on
* use function from init script to set up output paths
* update paths to run-time files in ACL

luci-app-adblock-fast: update to 1.1.1-1

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast
applications/luci-app-adblock-fast/root/usr/share/rpcd/acl.d/luci-app-adblock-fast.json

* Final (hopefully) attempt to avoid errors if dhcp/smartdns configs are missing
* New user experience for picking dnsmasq/smartdns instances to enable the adblocking on
* use function from init script to set up output paths
* update paths to run-time files in ACL
(cherry picked from commit 8d8ca1c6aace056dbcf4216ca797902c0099c2fb)

[23.05] luci-app-adblock-fast: update to 1.1.1-1

---

applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

remove instance selection for some smartdns options
(cherry picked from commit 97201f8379b5c3237420bf0363263a74a01c6e69)

[23.05] luci-app-adblock-fast: bugfix: remove instance selection 

---

modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Without this fix channel analysis will not work unless write access is also granted to luci-mod-network-config

luci-mod-status: fix ACL for channel analysis

---

modules/luci-mod-status/htdocs/luci-static/resources/svg/channel_analysis.svg
modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

(The reason the strongest station from image 1 is missing in image 2 is simple: it was one of mine, which simply is not there anymore.)
As of now, channel analysis highlights the complete frequency spectrum of a base station (all channels used by the station, which might be more or fewer depending on channel bonding). This means in particular, that in the plot, a station at one main channel might look identical to another station at a different channel, because both might use the same bonded channel spectrum.
One such example is two 80 MHz stations on channels 100 and 108 respectively: both will be plotted from channel 100 up to 115, as both will use those those 80 MHz. This is not incorrect, but it makes it more difficult to see which station is really where, as they might as well switch …

luci-mod-status: highlight primary 20 MHz channel

---

modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-compat/luasrc/model/network.lua

The config dialogue uses "Access Point". 
Fix up a missed translation and some other minor issues.

luci-base: Display 'Access Point' in the wireless page instead of 'Master'

---

protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/dhcpv6.js

Resubmitting #6764 without the change of default behaviour.

luci-proto-ipv6: Add DHCPv6 norelease menu option

---

applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_hosts.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_keys.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_servers.js
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_tunnels.js
applications/luci-app-sshtunnel/po/ru/sshtunnel.po
applications/luci-app-sshtunnel/po/templates/sshtunnel.pot

Maintainer: me (?)
Tested: OpenWrt master on VirtualBox amd64
Description:
The luci-app-sshtunnel has a problem.
I made a button to generate an ssh key. Internally it calls ssh-keygen from openssh.
The ssh-keygen generates two files: an id key like id_ed25519 and its public key id_ed25519.pub.
Then the luci app shows the pub key to a user so it can be copied and pasted on a SSH server.
But then I added the dropbear support. The app checks if the openssh ssh-keygen is installed then calls it but if not then it will call the dropbearkey to generate a key. The problem is that the dropbearkey generates only a private key file without a `.pub`.
That's why luci app can't show the pub key and a user can't copy it. Still the dropbearkey provides a command `dropbearkey -y privatekey` that extracts …

luci-app-sshtunnel: Improve keys

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

Added tooltip while hovering over connected client showing mac, IP(s), hostname in status page

luci-app-usteer: Added tooltip in status page

---

applications/luci-app-sshtunnel/Makefile
applications/luci-app-sshtunnel/htdocs/luci-static/resources/view/sshtunnel/ssh_servers.js
applications/luci-app-sshtunnel/po/ru/sshtunnel.po
applications/luci-app-sshtunnel/po/templates/sshtunnel.pot

A leftover from #6772
Since the https://github.com/openwrt/packages/pull/22975 was merged we can now add the ProxyCommand to the Luci app.
cc @systemcrash

luci-app-sshtunnel: servers: ProxyCommand option

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

See also:
https://github.com/openwrt/openwrt/commit/d7f378796f985c902ff7906767c275c40a15347f
@jow- Is a straight rename safe? Since fw4 is default now.

luci-mod-network: DHCP tab IPsets ( add NFTsets properties )

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/zones.js

Apparently the "Forward" entry of the individual firewall zones controls forwarding within the zone (between the individual interfaces) only, and not the forwarding of packets from the zone to other zones. This is quite confusing, as the meaning is different from the global "Forward" option above, which does control forwarding between zones.
Quote from user jow on the forum:
> The per-zone forward controls forwarding traffic among the ifaces of this
> zone. Traffic from/to other zones is handled by the global forward policy,
> or individual forwardings or rules.
See https://forum.openwrt.org/t/likely-bug-in-openwrt-firewall-rule-generation/18152
Let's try to be a bit more concise with the naming here and rename this entry to "Intra-Zone Forward", which hopefully makes the difference …

luci-mod-firewall: Expand on naming of forwarding rule inside the zone

---

applications/luci-app-irqbalance/Makefile
applications/luci-app-irqbalance/htdocs/luci-static/resources/view/irqbalance.js
applications/luci-app-irqbalance/po/templates/irqbalance.pot
applications/luci-app-irqbalance/po/zh_Hans/irqbalance.po
applications/luci-app-irqbalance/root/etc/uci-defaults/90_luci-irqbalance
applications/luci-app-irqbalance/root/usr/share/luci/menu.d/luci-app-irqbalance.json
applications/luci-app-irqbalance/root/usr/share/rpcd/acl.d/luci-app-irqbalance.json

Adding LuCI interface for irqbalance.
It displays the IRQ snapshot first, then the config options. It also checks whether the input is vaild in the last two options.

luci-app-irqbalance: add new package

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/startup.js
modules/luci-mod-system/htdocs/luci-static/resources/view/system/system.js
modules/luci-mod-system/root/usr/share/rpcd/acl.d/luci-mod-system.json

Convert startup.js and system.js to use the generic ubus rc method to
handle /etc/init.d/ scripts for enable/disable/start/restart/reload/stop
operation.
Signed-off-by: Rafał Miłecki <rafal@milecki.pl>
[ reword commit description, convert system.js ]
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>
---
This comes from an old patch here [1]. I just tested and looks to now work. Also I modified to add some missing part and a cleanup in the acl.d file.
@jow- I'm not really sure why we had the extra permission for uhttpd and ssh... I guess a leftover from old js pages?
I think I will add a change to rc to add support to optionally pass a name so we can return info of just one specific service... This is currently the only difference from the luci implementation... 
Also I notice that …

luci-mod-system: use new "rc" ubus object for init.d scripts

---

protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js

Changes:
* Add an option for 'Array Network SSL VPN' in the protocol select

luci-proto-openconnect: add option for array ssl vpn

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

Maintainer: me
Description:
* fixes https://github.com/openwrt/luci/issues/6811
* previously editing existing provider instance with options would not result in the correct saving of edited parameters

luci-app-https-dns-proxy: bugfix: editing providers with options

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js

Maintainer: me
Description:
* fixes https://github.com/openwrt/luci/issues/6811
* previously editing existing provider instance with options would not result in the correct saving of edited parameters
(cherry picked from commit a83427fefe497fcda92a3f9b59701dc91a6f1df1)

[22.03] luci-app-https-dns-proxy: bugfix: editing providers with options

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js

Maintainer: me
Description:
* fixes https://github.com/openwrt/luci/issues/6811
* previously editing existing provider instance with options would not result in the correct saving of edited parameters
(cherry picked from commit a83427fefe497fcda92a3f9b59701dc91a6f1df1)

[23.05 luci-app-https-dns-proxy: bugfix: editing providers with options

---

themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css

* add the decorations for when the links are included in the field descriptions
Thanks @dibdot!

luci-theme-openwrt-2020: fix anchor decorations

---

themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css

* add the decorations for when the links are included in the field descriptions
Thanks @dibdot, @stokito!
(cherry picked from commit 525c5da356da2c642cd2ebea83a4e303e666c04f)

[22.03] luci-theme-openwrt-2020: fix anchor decorations

---

.github/workflows/formal.yml

This goes in accordance with the Linux Kernel:
> using a known identity (sorry, no anonymous contributions.)
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n442
Identical [pull request](https://github.com/openwrt/packages/pull/23084) has been submitted to `openwrt/packages`.

ci: no longer require real name

---

applications/luci-app-ksmbd/htdocs/luci-static/resources/view/ksmbd.js

Now the kmod version on luci show "?", if we switch from version to vermagic it will show correct version of kmod.

luci-app-ksmbd: update kmod from version to vermagic

---

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

Thank you @hnyman!
(cherry picked from commit f162289fe4de00bf228ab66aaccff1235b41cfd9)

[23.05] luci-app-https-dns-proxy: remove unnecessary translation call

---

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

Thank you @hnyman!
(cherry picked from commit f162289fe4de00bf228ab66aaccff1235b41cfd9)

[22.03] luci-app-https-dns-proxy: remove unnecessary translation call

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

Don't allow enabling 802.11r when using WPA, it needs at least WPA2.
This is because 802.11r advertises FT support in-part through the Authentication and Key Management (AKM) suites in the Robust Security Network (RSN) Information Element, which was included in the 802.11i amendment and WPA2 certification program.
Pre-standard WPA did not include the RSN IE, but the WPA IE. This IE can not advertise the AKM suite for FT.
Also restrict ft_psk_generate_local to psk2 and psk-mixed. Using it with non-psk encryptions breaks roaming.
Same changes sent to OpenWRT's hostapd in this [PR](https://github.com/openwrt/openwrt/pull/14456)

luci-mod-network: wireless.js: fix 802.11r dependencies

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

sourcefilter option should be available for proto like: ppp
pptp
pppoe
pppoa
ncm
mbim
qmi
...and more

luci-mod-network: let sourcefilter option available for most proto

---

applications/luci-app-upnp/root/usr/share/luci/menu.d/luci-app-upnp.json
applications/luci-app-upnp/root/usr/share/rpcd/acl.d/luci-app-upnp.json

give upnp a unique acl name that does not conflict with the one of ddns.

 luci-app-upnp: fix name of access-control-list

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

Better structure the DHCP general and advanced tabs from a wall of options and add some more config options to control dnsmasq behaviour.
See individual commit messages.
Tested on 22.03.5 and 23.05.0
Preview:
https://github.com/openwrt/luci/assets/647633/3c81e285-225f-4fea-857d-204ea5c8131f

luci-mod-network: DHCP redesign;  phase1

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js
applications/luci-app-usteer/root/usr/share/rpcd/acl.d/luci-app-usteer.json

luci-app-usteer: added nslookup of AP name

---

applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js

Before the fix:
After the fix:
@pymumu

luci-app-smartdns: Fix The list has multiple headers.

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

If a non-EFI image comes first in the list of images, it would have been selected even on an EFI system.
Closes: openwrt/luci#6884
@aparcar

luci-app-attendedsysupgrade: Fix logic error in EFI image selection

---

applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot

(cherry picked from commit 00960d522d3ee296db58960560a177fd8e6a688a)

[23.05] luci-app-adblock-fast: bugfix: prevent runtime errors on empty strings

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

This commit retrieves the list of SSIDs availables to prepopulate the ssid_list UI element of the config.
In this way the possibility of typo error disappears.

luci-app-usteer: retrieve SSIDs to be used in the config

---

applications/luci-app-openvpn/luasrc/model/cbi/openvpn-advanced.lua

Perhaps a user might want to disable DCO support: let's add this option.
This PR depends on https://github.com/openwrt/packages/pull/23207

luci-app-openvpn: add OpenVPN option disable-dco

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/dmesg.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js

My log files can grow rather big, typically if i look at the log files then i want to look at the bottom, not the top, so I was missing a scroll down button. 
So I added these:
Please let me know if you have any comments or suggestions.

luci-mod-status: Adding scroll buttons on syslog and kernellog status pages

---

applications/luci-app-tor/Makefile
applications/luci-app-tor/htdocs/luci-static/resources/view/tor/tor.js
applications/luci-app-tor/root/usr/share/luci/menu.d/luci-app-tor.json
applications/luci-app-tor/root/usr/share/rpcd/acl.d/luci-app-tor.json

Maintainer: me
CC: @ja-pa
The PR contains a fix for luci-app-tor when list of hidden services didn't worked well.
For a user it just didn't show an onion domain.
Additionally I added a separate tab to configure the Tor itself.
But we have only one option: list of configs to include.
Let's configure at least this.
Additionally I added an upload field to upload a custom config and add it to a list of includes.
This will allow to a user to change the Tor settings without SSH.
For example by just downloading a sample conf from a tutorial, edit and upload. Still this is not convenient but at least something for today.

luci-app-tor: allow to upload custom config

---

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js

* Show Disk space graph consistent with the Status->Overview page
* Brought up in https://forum.openwrt.org/t/software-space-is-going-to-full/187112
* Leading whitespaces reformatted by vscode
* Localizable disk space progress bar title
* Kudos to https://forum.openwrt.org/u/psherman for coming up with final design
I'm attaching screenshot of the change, which is consistent how space is displayed in Status->Overview

luci-app-opkg: show disk space consistent with overview

---

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js

* Show Disk space graph consistent with the Status->Overview page
* Brought up in https://forum.openwrt.org/t/software-space-is-going-to-full/187112
* Localizable disk space progress bar title
* Kudos to https://forum.openwrt.org/u/psherman for coming up with final design
(cherry picked from commit c80ca79e05dbb19a4d97c48a90730d24f306f7f2)

[23.05] luci-app-opkg: show disk space consistent with overview

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

Some users use the usteer app in a "non wireless" device. With the current code it crashes because there is no SSID defined. Making the ui element a DynamicList fixes the issue because it allows free text input.

luci-app-usteer: Fix no wireless defined setup

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

When the SSID name was the same in different radio, they appear repeated in the options. This commit filter them.
Signed-off-by: Miguel Angel Mulero Martinez
This change was after a discussion in of https://github.com/openwrt/luci/pull/6908

luci-app-usteer: filter repeated SSIDs in config

---

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

(cherry picked from commit ffc0ffe6697bb315b96a75ab7807cecdd95f7314)

[22.03] luci-app-https-dns-proxy: bugfix: dnsmasq_instance parsing

---

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

(cherry picked from commit ffc0ffe6697bb315b96a75ab7807cecdd95f7314)

[23.05] luci-app-https-dns-proxy: bugfix: dnsmasq_instance parsing

---

modules/luci-base/root/www/index.html

Some browsers apparently act on fixed dates only, so add that too.
Tested on firefox.

luci-base: extend Expires directive to prevent caching

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

Fixes #6922 
The inherited nowrap of white-space causes the interface boxes to not line break, resulting in a horizontal scroll bar when many interfaces are present.
Tested on Chrome and Firefox.
Before:
After:
Another solution I found was to remove the `white-space: nowrap` from the [ifacebox](https://github.com/openwrt/luci/blob/master/themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css#L2111) and [ifacebadge](https://github.com/openwrt/luci/blob/master/themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css#L2150) classes, however I'm not familiar enough with the code base to know what side-effects this might have so I added a specific CSS selector override for the fix.
First contribution so any and all feedback is greatly appreciated!

luci-theme-bootstrap: allow network interfaces to line break

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/routes.js

Adds a missing closing bracket.
Bugfix for PR #6917

luci-mod-status: BUGFIX: routes: help strings to clarify column titles

---

applications/luci-app-cloudflared/Makefile
applications/luci-app-cloudflared/htdocs/luci-static/resources/view/cloudflared/tunnels.js
applications/luci-app-cloudflared/po/templates/cloudflared.pot

I overhauled tunnels.js to make it more organized. And upgraded it to version 1.2
Some changes are:
1. Make data from tunnel into a table
2. Add a class for the table structure
3. Wrap each table with a class section

luci-app-cloudflared: Overhaul tunnels.js

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css
themes/luci-theme-material/htdocs/luci-static/material/custom.css

This changed spawned from trying to make certain text colors readable (such as white text on white background in many dialogs) introduced by commit 4ee2bc6 (ref: #5841) which made obvious the need to improve the color and contrast situation in the theme.
Alot of colors were duplicated in cascade.css and made for a hard time to align colors across different elements. This commit tries to rectify that by introducing variables for all commonly used colors.
* All base colors (white, blue, red, green, blue, yellow, etc) has been consolidated and moved to common variables
* Introduced more specific selectors for info levels to avoid colors bleeding over to other elements
* Removed duplicated properties which were overriden at the next row
Before:
After:
The slight change in the red color for …

luci-theme-material: improve theming system colors and contrasts

---

libs/rpcd-mod-luci/Makefile
libs/rpcd-mod-luci/src/luci.c

The musl libc only implements POSIX basename() but provided a GNU header kludge in <string.h>, which is removed in musl 1.2.5 [1]. Use the standard <libgen.h> header to avoid compilation errors like:
luci.c: In function 'rpc_luci_parse_network_device_sys': luci.c:676:53: error: implicit declaration of function 'basename' [-Werror=implicit-function-declaration]
676 |                 blobmsg_add_string(&blob, "master", basename(link));
|                                                     ^~~~~~~~
luci.c:676:53: error: passing argument 3 of 'blobmsg_add_string' makes pointer from integer without a cast [-Werror=int-conversion]
676 |                 blobmsg_add_string(&blob, "master", basename(link));
|                                                     ^~~~~~~~~~~~~~
| …

rpcd-mod-luci: use standard POSIX header for basename()

---

modules/luci-base/htdocs/luci-static/resources/validation.js

Before this change, values further in time than 23:59:59 was allowed, such as 24:00:00 and 23:60:00. Leap seconds is accounted for so 60 is allowed in the seconds parameter.
First reported in https://github.com/openwrt/luci/issues/6965 and https://forum.openwrt.org/t/openwrt-23-05-2-service-release/177709/303
After fix:

luci-base: use correct regex for time validation

---

applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/mqtt.js
applications/luci-app-statistics/root/usr/libexec/stat-genconfig
applications/luci-app-statistics/root/usr/share/luci/statistics/plugins/mqtt.json

This commit adds UI to configure the Mqtt plugin of the luci-app-statistics.
This PR https://github.com/openwrt/packages/pull/20662 added the possibility of use UCI commands some time ago, now this PR adds the LuCi way. Some screen captures:
The UCI part was based on the cURL plugin, so I did the same in the UI part.
~~I've tested it and one thing is not working: the mandatory fields (not optional) are not being validated, so the user can left this fields empty. I don't know why it not works, maybe someone can point me to the bug.~~ I've fixed it but I'm not too sure if it's the correct way: to be mandatory it needs to have `optional = false` AND `rmempty = false`.

luci-app-statistics: Add UI to configure Mqtt

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

Currently, the realtime graphs, under Status > Realtime Graphs are always white, even in Bootstrap Dark theme.
This change will make the graphs dark in darkmode.  I wanted to get some guidance on whether this is the right direction.
I used !important to set the color because I needed to override the JS which is setting the background white directly. I looked at fixing this in the javascript but there doesn't seem to be common variables among the different themes, so this way seemed the simplest. 
This is my first PR so please be patient if I have done anything incorrectly.
Example of dark graph.
Currently the graph lines do not show up well, I can work on that if requested.

Make Realtime Graphs Respect Bootstrap Dark Mode

---

modules/luci-mod-network/htdocs/luci-static/resources/tools/network.js

This resulted in the sysfs parameter to be invalid as it contained a space.
Fixes #6983.

luci-mod-network: drop trailing whitespace

---

applications/luci-app-statistics/htdocs/luci-static/resources/statistics/rrdtool/definitions/users.js
applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/plugins/users.js

The users plugin is functional and useful, but requires usage of custom
built packages of busybox, dropbear, openssh, or other console/shell
access mechanisms.
Signed-off-by: Joel Johnson <mrjoel@lixil.net>

luci-app-statistics: add users plugin support

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

With this addition to the body tag, on desktop browsers the vertical scrollbar
is always visible and the content will not be shifted by changing tabs (like
at System/Software when the update tab has no to little content).
I couldn't see any negative side effects with Chromium browsers or Firefox
under Windows/Linux and Android, but I don't have access to Apple devices
for tests.

luci-theme-bootstrap: Always show scrollbar

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

This is a continuation of https://github.com/openwrt/luci/pull/6982 
This adds the wireless and channel analysis graphs to be dark in bootstrap dark theme,  and makes the gridlines white so they are visible against the dark background. 
See the below image for an example. 
Note, I was not able to test the wireless and channel analysis graphs because I don't have wireless in my build so if someone could test and confirm that would be helpful.

luci-theme-bootstrap: darkmode graphs

---

modules/luci-base/Makefile

Mention: @jow- @Ansuel 
Description:
During the update of luasrcdiet with commit b5d5e5bf13e572af7f1589a01bfd338691d5f063 the license was incorrectly changed from 'Apache-2.0' to 'MIT'.
As the name implies, this is the basic package that must be installed on the target for the LuCI to work at all. So changing the license from 'Apache-2.0' to 'MIT' should not have happend, because this information belongs to the package 'luci-base' and to the 'luasrcdiet'.
Therefore, with commit b0d8fff3e40568af633032aacb0624da16f4266c the 'luasrcdiet' was moved to its own package. However, it was forgotten to adapt the licence to 'Apache-2.0' again.
While we are at it, also set the 'PKG_LICENSE_FILES' to 'LICENSE' and 'NOTICE'.

luci-base: fix license

---

modules/luci-base/po/ja/base.po
modules/luci-base/po/zh_Hans/base.po
modules/luci-compat/luasrc/model/network/proto_4x6.lua
protocols/luci-proto-ipv6/Makefile
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/ipip6.js

Add Generic Packet Tunneling in IPv6 Specification (RFC 2473) support.
(For NTT Broadband V6Plus/transix/Xpass Fixed IP)
[depends on other PRs: openwrt/openwrt](https://github.com/openwrt/openwrt/pull/14516)

luci-proto-ipv6: Add support for IPIP6(RFC2473) tunnel 

---

modules/luci-base/htdocs/luci-static/resources/ui.js

The call function was based on the legacy XHR interface and it has not been updated to comply with the new request interface which passes the duration as part of the response object rather than as a separate argument. This resulted in polling in a tight loop in certain cases since the duration was undefined.
In addition there is no need to adjust apply_holdoff based on elapsed time as no significant amount of time has elapsed at this point.

luci-base: ui.js: avoid polling in a tight loop on confirm/rollback

---

applications/luci-app-dockerman/Makefile
applications/luci-app-dockerman/luasrc/model/cbi/dockerman/networks.lua

Fixes #6973 
This was added in upstream with https://github.com/lisaac/luci-app-dockerman/commit/7292955a1b415bb60fa2e403bb3a437b4b7f7846 so should be fine for us to add it.
Networks tab works again after fix. I'm not entirely sure how to test this properly as I don't use Docker via LuCI myself so any test would be appreciated.
Ping @leobsky @Joee-D

luci-app-dockerman: check for existing IPAM config

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

Fine tuning #6991
Bugfix for the wireless graphs, reorder everything to the same level as displayed in the menu and make the spaces even.
At the realtime graph pages, the brighter lines for Wi-Fi where missing, as well for the channel analysis page:
@JimMatthew: As you are unable to test this changes with your wired build, here are some bugfixes for it.

luci-theme-bootstrap: darkmode graphs fine-tuning

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

The current implementation made the commands from the app luci-app-commands absolutely positioned which resulted in hiding elements which was underneath it, ie. the buttons. This implementation removes the absolutely positioned behavior making the buttons visible again and as an upside aligns it with how the Bootstrap theme handles commands.
Spawned from https://github.com/openwrt/luci/pull/6936#issuecomment-2006720954. Ping @DittelHome
Before: 
After:

luci-theme-material: make luci-app-commands command box align with Bootstrap theme

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js
applications/luci-app-pbr/htdocs/luci-static/resources/view/pbr/overview.js
applications/luci-app-pbr/htdocs/luci-static/resources/view/status/include/72_pbr.js
applications/luci-app-pbr/po/templates/pbr.pot
applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr
applications/luci-app-pbr/root/usr/share/rpcd/acl.d/luci-app-pbr.json

Maintainer: me
Description:
* sync with the principal package
* add the status include file
Depends on https://github.com/openwrt/packages/pull/23684

luci-app-pbr: update to 1.1.4-5

---

protocols/luci-proto-nebula/Makefile

luci-proto-nebula: prepare migration to APK

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/dlink-fgs1210-28.json
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea8100v1.json

luci-app-advanced-reboot: prepare migration to APK

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

luci-app-https-dns-proxy: prepare migration to APK

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

(cherry picked from commit 1efb3cd5f898e41148b298ae6ecdec4a7ae558f8)

[23.05] luci-app-https-dns-proxy: prepare migration to APK

---

protocols/luci-proto-qmi/htdocs/luci-static/resources/protocol/qmi.js

[Backport to openwrt-23.05 branch - I forgot to open this after core changes were merged into 23.05-rc3]
To support split-APN dual-stack connections over QMI, add new parameters supported in UCI to LuCI as well. Previously, connection profile wasn't configurable from LuCI at all, so add options to set which APN profile to match for each protocol.
(cherry picked from commit c682e530e2b95af7768b6a0c74c942222e0cd78d)
Original PR #6426

[23.05] luci-proto-qmi: allow v6apn and (v6)profile configuration

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/dmesg.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js

The actual code moves the scroll in the window. This works for the bootstrap theme, because the scroll is at window level. But this does not work for other themes, like material.
This commit changes the move of the scroll by "focusing" the window in the opposite button element in the syslog page. In this way the move is automatically done by the browser.
Another solution is to "search" in the parent until we find the scroll and move it, but seems less solid.
This fixes https://github.com/openwrt/luci/issues/7027
This has been tested on Chrome and Edge, any other test will be appreciated. I've tested too the solution "searching" for the scroll in the parent, and it works, but I'm not too sure where to stop the search if the scroll does not exist or if it can find a different scroll at …

luci-mod-status: fix syslog scroll for some themes

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

Better readability for pages that use textarea, similar to `admin/status/logs`.
The pages below use textarea today:
- Startup -> Local Startup
- Flash Firmware -> Configuration
- Diagnostics
Signed-off-by: Kristian Skramstad <kristian+github@83.no>

luci-theme-bootstrap: Change textarea font-family to monospace

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js

Similar to commit 6039925 from @jow-
Add an ID attribute to the dynamically generated Wi-Fi associated stations table to persist row ordering choice across reloads.
At the luci-mod-network view, the Wi-Fi associated stations table already has the same ID.

luci-mod-status: persist sorting of Wi-Fi associated stations table

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

I hardened up the code a bit. I do not think this is strictly needed as those strings should be clean to start (mostly numbers, mac, IP addresses etc.) but cant hurt either and will make it more resistant to code changes in the future.

luci-app-usteer: Escaped more strings to harden

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.adguard.dns.json

AdGuard seems to have drastically changed their DoH servers URLs, so this change updates the root/usr/share/https-dns-proxy/providers/com.adguard.dns.json file. Fixes https://github.com/openwrt/luci/issues/7038
Also include minor Makefile changes for better menuconfig presence.

luci-app-https-dns-proxy: bugfix: AdGuard servers URLs

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/snats.js

ping @jow- 
If one sets a SNAT rule via the GUI as 'automatic', the 'family' remains empty. In fw4.uc code, this is interpreted as:
```
/* default to IPv4 only for backwards compatibility,
unless an explicit family any was configured */
```
'any' is handled by fw4 as IPv4+6.
Also prevent 'any' from triggering a validation error (non-SNAT targets hide 'snat_ip' which remains empty, and triggered an error).

luci-app-firewall: Add 'any' choice for SNAT 'family' option

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.adguard.dns.json

AdGuard seems to have drastically changed their DoH servers URLs, so this change updates the root/usr/share/https-dns-proxy/providers/com.adguard.dns.json file. Fixes https://github.com/openwrt/luci/issues/7038
Also include minor Makefile changes for better menuconfig presence.
(cherry picked from commit 8f92f8b40369c4a2fc0cd358969e9278920d6d18)

[23.05] luci-app-https-dns-proxy: bugfix: AdGuard servers URLs

---

luci.mk

The initial commit did not take care of corner cases which could happen if building under build conditions other than using Git.
There are three cases for the `findrev` function:
- git -> `24.079.58964~7943616` (remove prefixed `git-`)
APK can't handle `git-` as prefix, it could be `0_git<integer>` but this seems rather confusing.
- date -> `0.240326.34906` ( add leading 0)
Add a leading zero so the version is always lower compared to using Git. This makes it easier to distinguish from a Git based version.
- unknown -> `0` (instead of `unknown`)
APK can't handle `unknown` so set it to a simple zero instead.

luci.mk: more APK version compatibility changes

---

applications/luci-app-filebrowser/Makefile
applications/luci-app-filebrowser/htdocs/luci-static/resources/view/system/filebrowser.js
applications/luci-app-filebrowser/po/templates/filebrowser.pot
applications/luci-app-filebrowser/root/usr/share/luci/menu.d/luci-app-filebrowser.json
applications/luci-app-filebrowser/root/usr/share/rpcd/acl.d/luci-app-filebrowser.json
modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js

Luci [needs for a file manager](https://forum.openwrt.org/t/adding-a-file-browser-file-text-editor-and-tty-command-shell-for-luci-openwrt/138930/).
The FileUpload CBI element allows to browse files and directories on a router, delete and upload. This already covers a basic needs. The only really missing features are:
* Download a file. Required.
* Edit right in a browser. Highly improves UX but not necessary. User can download, edit with a Notepad and upload.
* See and change permissions. Important.
* Copy\Move. Good to have.
* Compress, extract and browse archive. Often used.
So we can extend the FileUpload and add a "browser mode" when you don't select a file but just walking on directories. The PR is PoC of the idea: it adds a new menu item System / File Browser that opens a page with …

Add File Manager / File Browser based on form.FileUpload

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

This fix prevents iteration over empty/null array of instances (and the type error) if there are no instances found.
Fixes https://github.com/openwrt/packages/issues/23868

luci-app-https-dns-proxy: bugfix: status/overview page include

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

This fix prevents iteration over empty/null array of instances (and the type error) if there are no instances found.
Fixes https://github.com/openwrt/packages/issues/23868
(cherry picked from commit f19647536440f93a16612d4746508f9ff7d49161)

[23.05] luci-app-https-dns-proxy: bugfix: status/overview page include

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.adguard.dns.json

This contains 3 cherry-picks from master, bringing this up to date with recent bugfixes.

[22.03] luci-app-https-dns-proxy: 3 cherry-picks to bring up to date with bugfixes.

---

applications/luci-app-pbr/Makefile

bump to sync version with principal package.
corresponds to https://github.com/openwrt/packages/pull/23925

luci-app-pbr: sync with principal package

---

applications/luci-app-lldpd/Makefile
applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd.js
applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/details_hide.svg
applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/details_show.svg
applications/luci-app-lldpd/htdocs/luci-static/resources/lldpd/lldpd.css
applications/luci-app-lldpd/htdocs/luci-static/resources/view/lldpd/config.js
applications/luci-app-lldpd/htdocs/luci-static/resources/view/lldpd/status.js
applications/luci-app-lldpd/po/ru/lldpd.po
applications/luci-app-lldpd/po/templates/lldpd.pot
applications/luci-app-lldpd/root/etc/uci-defaults/40_luci-lldpd
applications/luci-app-lldpd/root/usr/share/luci/menu.d/luci-app-lldpd.json
applications/luci-app-lldpd/root/usr/share/rpcd/acl.d/luci-app-lldpd.json
applications/luci-app-lldpd/root/usr/share/rpcd/ucode/lldpd

This is a customized copy of TanoWrt's fork, which you can find at https://github.com/tano-systems/luci-app-tn-lldpd, which is under the MIT license. For the app to work, https://github.com/openwrt/openwrt/pull/14193/ must be accepted.

luci-app-lldpd: Create based on TanoWrt's app

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/bandwidth.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/connections.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/load.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/wireless.js
modules/luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json

desciption:
@jow- This shortcomings are not noticeable when using the `luci-theme-boostrap`. However, I use the `luci-theme-material `and the realtime graph pages do not look clean. The pullrequest fixes this by adding missing `cbi- `css classes
bandwith (old/new) luci-theme-material:
connections (old/new) luci-theme-material:
load (old/new) luci-theme-material:
wlan (old/new) luci-theme-material:

luci-mod-status: unify of the appearance of the real-time graphic display.

---

modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/spectrum.js
modules/luci-mod-dsl/htdocs/luci-static/resources/view/status/dsl/stats.js

Description:
@jow- This shortcomings are not noticeable when using the luci-theme-boostrap. However, I use the luci-theme-material and the luci-mod-dsl sub pages do not look clean. The pullrequest fixes this by adding missing cbi- css classes and adds also cbi-section-descr
luci-mod-dsl(spectrum) (old/new) luci-theme-material:
luci-mod-dsl(statistics) (old/new) luci-theme-material:

luci-mod-dsl: improve view for the luci-theme-material

---

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/10_router.js

The Internet section in Dashboard shows a gateway and WAN IP, but it doesn't care whether it actually displays the WAN that is used according to metric or a different WAN interface.
This PR changes the behavior so that it always shows the properties of the WAN interface with the lowest metric.
Actually, the for loop in the source code this PR replaces was a bit weird. It was looping through all WAN interfaces, but overwriting the values by the contents from the last loop iteration. Not sure what was meant by that.
@ZoZhang could you please review?

luci-mod-dashboard: Fill gateway info with the connection with lowest metric

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

An user can insert a strange value right now, with this commit, only integer value can be insert.
Tested working ok

luci-mod-network: steering flow - permit only integer value

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

Apparently, an invalid parameter stop usteer from starting.  This PR allows the editing of parameters while usteer is stopped. In that case the status tab is not shown.

luci-app-usteer: Allow editing of settings if usteer is not running

---

applications/luci-app-lxc/luasrc/controller/lxc.lua
applications/luci-app-lxc/luasrc/model/cbi/lxc.lua

Fixes #7098. Ping @xaviergr. 
Since https://github.com/lxc/lxc/commit/58520263041b6864cadad96278848f9b8ce78ee9 which is part of LXC 5.0, not being able to bypass GPG validation anymore has been enforced by upstream in lxc-download. When LXC was bumped to 5.0.1 in https://github.com/openwrt/packages/commit/d957a2293b2a21b1edca1aa92e141bad8292251a this broke passing the --no-validate option to lxc-download, which resulted in getting the output of the --help command line option as the RPC output of lxc-download as it doesn't understand the --no-validate option. This in turn broke the string parsing for compatible distributions and their versions.
To solve this, this commit removes the --no-validate option entirely as it has been removed by upstream.
I've put it as RFC as I don't use LXC …

[RFC] luci-app-lxc: remove bypassing GPG validation

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/overview.js
applications/luci-app-keepalived/root/usr/share/luci/menu.d/luci-app-keepalived.json

@jempatel 
The main change her is moving the overview page to the status menu entry.
So the status page of keepalived is new under the status menu pages.
Old:
New:
While we are at it also add the missing cbi CSS class so it looks better on luci-theme-material and add a missing cbi-descr.

luci-app-keepalived: move status page to status menu

---

applications/luci-app-sqm/root/usr/share/ucitrack/luci-app-sqm.json

Package sqm-scripts already uses procd to manage uci config change triggers, so ucitrack is not necessary.

luci-app-sqm: remove deprecated ucitrack

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/dmesg.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js

Implements #5568. See attached video. I have by design not implemented any "follow tail" logic for the log as I was unsure how it should interact with the "Scroll to tail" and "Scroll to head" buttons that are already there (should it follow the tail even if the user hasn't clicked "Scroll to tail" yet?), but any suggestion how and if we should handle that is welcome.
I was a bit unsure if PKG_RELEASE should be incremented for modules; luci-mod-status hasn't received any since 938e54df17d6a48fc8d84fe5893ff67ffe4a3e6e even though the diff since that commit is quite big.
https://github.com/openwrt/luci/assets/7290072/815a0dea-fa35-4146-bba0-b0cfa2fdb87b

luci-mod-status: auto-refresh system log and kernel log

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Description:
* update license
* update PKG_VERSION/PKG_RELEASE
* improve visibility in menuconfig
* add warning for compatiblity check fails with principal package
* report compatiblity check fails with principal package from RPCD script
Depends on https://github.com/openwrt/packages/pull/24138

luci-app-adblock-fast: update to 1.1.2-1

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Run tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Description:
* update license
* update PKG_VERSION/PKG_RELEASE
* improve visibility in menuconfig
* add warning for compatiblity check fails with principal package
* report compatiblity check fails with principal package from RPCD script
(cherry picked from commit d18f58b4317f2207cb4964f29fdb25a08ea99646)
Depends on https://github.com/openwrt/packages/pull/24139

[23.05] luci-app-adblock-fast: update to 1.1.2-1

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js

When you download a partition, the name is `hostname+mtdX.bin` and that can be confusing if you go back and try to remember what `mtdX` was if you have 10+ partitions.
So let us add the partition name to the filename like: 
```
hostname.mtdX.boot.bin
hostname.mtdX.firmware.bin
```
Note: If there is a better, easier and simpler way to do the same thing, please let me know.
Signed-off-by: Kristian Skramstad <kristian+github@83.no>

luci-mod-system: flash.js: add mtdblock name to filename

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-whw03.json

```
root@OpenWrt:~# ubus call system board
{
"kernel": "6.6.30",
"hostname": "OpenWrt",
"system": "ARMv7 Processor rev 5 (v7l)",
"model": "Linksys WHW03 (Velop)",
"board_name": "linksys,whw03",
"rootfs_type": "squashfs",
"release": {
"distribution": "OpenWrt",
"version": "SNAPSHOT",
"revision": "r26207-ce4da3cf41",
"target": "ipq40xx/generic",
"description": "OpenWrt SNAPSHOT r26207-ce4da3cf41"
}
}
root@OpenWrt:~# cat /tmp/sysinfo/board_name
linksys,whw03
root@OpenWrt:~# fw_printenv
altkern=48022
auto_recovery=yes
baudrate=115200
boot_part_ready=3
boot_ver=0.0.22
bootargs=console=ttyMSM0,115200n8
bootcmd=if test $boot_part = 1; then run bootpart1; else run bootpart2; fi
bootdelay=2
bootpart1=set bootargs $partbootargs && mmc read $loadaddr $prikern 4000 && bootm $loadaddr
bootpart2=set …
```

luci-app-advanced-reboot: add support for Linksys WHW03 V1

---

modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/30_network.js

This pull request introduces a streamlined method for retrieving lease time information on IPv6 interfaces. While IPv4 interfaces typically have a single lease time (available in the interface `data`), IPv6 interfaces commonly feature multiple lease times due to factors like multiple delegated prefixes or multiple standard /64 subnet.
Users typically receive only one prefix delegation from their ISP, leading this PR to the retrieval of lease time from the first available prefix or IPv6 address.
To enhance usability and provide users with a more comprehensive view of lease time information, however, alternative approaches should be discussed.
Suggestions include returning an array of lease times or aggregating the various possible values using methods like finding the minimum or maximum. …

luci-mod-status: Lease Time Retrieval for IPv6 Interfaces

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/flash.js

The previous change did not work as intended for
partitions with `_` in the name. I.e `0:qsee_1`.
It would output an error `Invalid characters in filename`.
So fix this by matching and replacing any
character except for `a-z` and `0-9` with `-`.
Example `0:qsee_1` = `0-qsee-1`.
Tested on WAX620 with partition name `0:qsee_1`.
Signed-off-by: Kristian Skramstad <kristian+github@83.no>

luci-mod-system: flash.js: fix mtdname on download

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

Maintainer: @tohojo
The `use_staging` option was renamed to `staging`.
Also removed `use_acme_server` option since it's ignored by acme. The option is not often used so it's easeir to remove the flag for simplicity.

luci-app-acme: replace deprecated use_staging with staging

---

protocols/luci-proto-openconnect/htdocs/luci-static/resources/protocol/openconnect.js

This enables using luci-proto-openconnect to connect using a URI that enables user-groups and camouflage mode in ocserv. It further adds new protocols that are available in openconnect.

luci-proto-openconnect: several updates to sync with latest package

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/dropbear.js

Instead of saving 'on' or 'off' for flag values, use the default 1 and 0.
This makes code simpler.
See related https://github.com/openwrt/openwrt/pull/15579

luci-mod-system: Dropbear: remove custom flag values

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

By passing the version_code parameter, we can error out if the imagebuilder that responded to the request isn't the same, mirroring the current behavior of auc.
This is spawned from a recent issue with the Attended Sysupgrade server as can be seen in later entries of https://forum.openwrt.org/t/auc-sysupgrade-does-not-work-for-me/196782, https://github.com/openwrt/asu/issues/848 and with the probable root cause in https://github.com/openwrt/asu/issues/853. Due to the LuCI app not having this check, the incorrect version of the imagebuilder may be used for a request, and still be returned to the user as a valid request, which (I guess?) in worst case could downgrade a user's systems instead. 
Adding this check mirrors the behaviour that `auc` currently has, see image below. The relevant …

luci-app-attendedsysupgrade: enforce correct imagebuilder version

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/script.js

luci-app-keepalived: Fix option name for script falls. 

---

protocols/luci-proto-nebula/Makefile

Maintainer: me
Compile tested: x86_64, Sophos XG-135r3, OpenWrt 23.05.3
Run tested: n/a
Description:
* update license
* improve package's presence in make menuconfig
* drop maintainership

luci-proto-nebula: drop maintainership

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/29_ports.js

The Status page of my device (a GL.iNet MT3000) displays a port status of "-1 MbE (H)" when no cable is connected. It seems port.netdev.getSpeed() is returning -1. This change displays a sane status of "no link" in this situation.

luci-mod-status: Display link status as "no link" when the speed is reported as -1

---

protocols/luci-proto-yggdrasil/Makefile
protocols/luci-proto-yggdrasil/htdocs/luci-static/resources/protocol/yggdrasil.js

Show latency measurement among other peering information. Latency field was added to yggdrasil admin api in v0.5.6.
Depends on: openwrt/packages#24411 (merged)
cc: @wfleurant

luci-proto-yggdrasil: show peer latency

---

modules/luci-base/htdocs/luci-static/resources/ui.js

Currently the wrap flag of textarea doesn't works properly, this PR fix it. [Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#wrap)

luci-base: Correct how textarea's wrap works

---

applications/luci-app-opkg/htdocs/luci-static/resources/view/opkg.js
modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js
themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
themes/luci-theme-material/htdocs/luci-static/material/cascade.css
themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css

Base on the discussion with @systemcrash @jow- on PR https://github.com/openwrt/luci/pull/7152, I have added the suggested css class `button-row`.
New view for the connectivity change that I originally wanted to change.
I have tested the changes for the themes `luci-theme-material` and `luci-theme-bootstrap`.
* Interface stop
* OPKG update/feeds
* Upload
When comparing the `Save & Apply` I noticed a problem that looks right with `luci-theme-material` but not so right with `luci-theme-bootstrap`.
**luci-theme-bootstrap (NOK):**
**luci-theme-material (OK):**
I think the problem is with the CSS! Unfortunately I have no idea how to solve this.

treewide: add new css class button-row

---

modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

This should fix the regression that was introduced by https://github.com/openwrt/luci/pull/7153

luci-base: fix regression add by button-row class

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js
modules/luci-mod-status/root/usr/libexec/syslog-wrapper
modules/luci-mod-status/root/usr/share/rpcd/acl.d/luci-mod-status.json

Commit includes wrapper syslog in /usr/libexec. If a log file is configured, the output of this file is displayed. Otherwise the output of logread is displayed.

luci-mod-status: display log_file in status if defined

---

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js

Seems like it should be optional as we have global 'cacert' setting above

luci-app-ddns: make service-specific 'cacert' optional

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

This has never worked because the option 'auth' is not known to the modemmanger proto handler. The correct uci name is 'allowedauth' and is also a uci list option, so that several options can be selected.
See https://openwrt.org/docs/guide-user/network/wan/wwan/modemmanager#use

luci-proto-modemmanger: fix auth handling

---

libs/rpcd-mod-luci/src/luci.c

Dnsmasq DHCPv6 use colons in the generated duid present in the lease file. Strip the colon as this is not supported by the OpenWrt config and follow the same way odhcpd use to display duid.
@jow- 
Fixes: #4543

rpcd-mod-luci: strip colon from dnsmasq duid

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/README.md
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.opendns.doh.json

* bugfix: update OpenDNS family filter URL
* update copyright/license
* update PKG_RELEASE to avoid double `r` on snapshots
* add LUCI_URL to upstream repository
* update README URL to upstream documentation
* update pkg.URL property to allow linking to a specific version of README
* remove duplicates of pkg object from overview.js/status include js files

luci-app-https-dns-proxy: bugfix: OpenDNS family filter URL update

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/README.md
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/status/include/71_https-dns-proxy.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/com.opendns.doh.json

* bugfix: update OpenDNS family filter URL
* update copyright/license
* update PKG_RELEASE to avoid double `r` on snapshots
* add LUCI_URL to upstream repository
* update README URL to upstream documentation
* update pkg.URL property to allow linking to a specific version of README
* remove duplicates of pkg object from overview.js/status include js files
(cherry picked from commit 9c836d14734f069421a459a63436d07cc91dd760)

[23.05] luci-app-https-dns-proxy: bugfix: OpenDNS family filter URL update

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/README.md
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/status/include/70_adblock-fast.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

This PR syncs luci app with the principal package: https://github.com/openwrt/packages/pull/24739

luci-app-adblock-fast: sync with 1.1.2-3 principal package

---

applications/luci-app-natmap/htdocs/luci-static/resources/view/natmap.js

This commit changes the data type of bind port from `port` to `portrange`, supporting [sequential allocation of ports](https://github.com/heiher/natmap/blob/master/README.md?plain=1#L54-L57).
cc @ysc3839

luci-app-natmap: change bind port data type from port to portrange

---

applications/luci-app-natmap/htdocs/luci-static/resources/view/natmap.js

This commit changes the data type of bind port from `port` to `portrange`, supporting [sequential allocation of ports](https://github.com/heiher/natmap/blob/master/README.md?plain=1#L54-L57).
cc @ysc3839

[23.05] luci-app-natmap: change bind port data type from port to portrange

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

The pull request https://github.com/openwrt/openwrt/pull/15965 adds four new options to configure EDNS0 upstream support. This patch adds the new settings to DNSMASQ web UI.

dnsmasq: Add options for new EDNS0 options

---

protocols/luci-proto-3g/htdocs/luci-static/resources/protocol/3g.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/ppp.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoa.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoe.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pptp.js
protocols/luci-proto-pppossh/htdocs/luci-static/resources/protocol/pppossh.js

The default PPP keepalive value in OpenWRT is actually `5 1` not `0 5`.

luci-proto-3g/ppp/pppossh: fix default keepalive values

---

applications/luci-app-babeld/htdocs/luci-static/resources/babeld.js

luci-app-babeld: use an array for routing lists

---

modules/luci-base/htdocs/luci-static/resources/tools/widgets.js

This is potentially either a fix or a workaround for Batman-adv interfaces that are not bound to a device but linked to an wireless device.
Probably it is cleaner to make a `batadv_vlan.js` that returns an empty list or return the empty list if the js file looked up is missing.

luci-base: Do not error out if getDevices returns null

---

applications/luci-app-udpxy/htdocs/luci-static/resources/view/udpxy.js
applications/luci-app-udpxy/po/templates/udpxy.pot

luci-app-udpxy: fix luci-app-udpxy

---

themes/luci-theme-openwrt/ucode/template/themes/openwrt.org/header.ut

luci-theme-openwrt: change to HTML (like all other themes) instead of XML to fix incompatibility
see also https://github.com/openwrt/luci/issues/7229

luci-theme-openwrt: change to HTML (like all other themes) instead of XML to fix incompatibility

---

applications/luci-app-commands/ucode/template/commands.ut

Commit 702c007 changed the request to be invoked via the Request.get function instead of the deprecated XHR one. The request options object requires the query string to be located inside of the subobject "query", otherwise they are not picked up. This resulted in breaking the custom arguments functionality as the input would simply be ignored.
Fixes #7255
Before:
After:

luci-app-commands: correctly pass custom arguments as query string

---

modules/luci-base/htdocs/luci-static/resources/form.js

luci-base: form.js: decode HTML entities in AbstractElement.stripTags()

---

applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot

* better description/link for force_dns in WebUI
(cherry picked from commit c70ec6f8c7e2fbf6c66697117914313289f0a14f)

[23.05] luci-app-https-dns-proxy: better description/link for force_dns

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

The previous implementation of binding the protocol validation to the name validation caused problems when creating a new interface where an already existing interface had the new one's protocol as its name, as the protocol would be used when validating if an interface of that name already existed.
Consider the following case:
1. Interface 'gre' with protocol PPPoE is created
2. Interface 'foo' with protocol GRE tunnel over IPv4 (which resolves to 'gre') tries to be created
Creating interface 'foo' would error out during protocol validation as 'gre' would be passed to the name validation, which in turn would check if an interface with name 'gre' already exists, which it does.
Instead of reusing the validation logic, simply trigger the name validation manually as the protocol changes to …

luci-mod-network: split interface name and protocol validation

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js

Maintainer: me
Description:
* sync with the principal version & update README version

luci-app-pbr: update to 1.1.7-21

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

hsl lightness values are being unnecessarily calculated using `calc(n / 255 * 100%)`. This PR replaces all instances of `calc(n / 255 * 100%)` with their calculated percentage values to 2 decimal points (e.g. `calc(6 / 255 * 100%)` -> `2.35%`).
> "You don’t need to use calc() to do math on numbers that you could do the math for." - https://jdsteinbach.com/css/where-to-use-css-calc-real-world/#for-math-on-compatible-numbers

luci-theme-boostrap: cascade.css: Refactor unnecessary calc()

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Maintainer: @aparcar
Tested on: x86/64 SNAPSHOT build
The reported status values have changed on the ASU server several times since the 'steps' list has been updated, so update it to include all possible values.  Although some of the values in the list are no longer presented by the official OpenWrt ASU server, they may still be produced by other ASU servers, so leave them in for now.
Percentages have been adjusted based upon measurement of the build phases for several build configurations (ath79 vs x86, few packages vs many...).  The numbers are still (very) rough estimates, but are more representative than the old values.

luci-app-attendedsysupgrade: update status keys and messages

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

ModemManager protocol has supported setting initial EPS bearer since package commit [1], so lets expose the same support via LuCI as well.
[1] https://github.com/openwrt/packages/commit/af12147f8c54ac3a44d32c5c1bd95099bc9a6c74

luci-proto-modemmanager: add initial EPS bearer support

---

applications/luci-app-statistics/htdocs/luci-static/resources/view/statistics/graphs.js

In the past, a summary page would usually be generated for the data, but this did not occur when there was only a single instance (e.g., a single Wi-Fi interface). As a result, the refresh mistakenly requested the summary instead of the available data.
i.e. graphs would mysteriously disappear on refresh.
See #6468 for more context.

luci-app-statistics: render all graphs on refresh if no summary

---

applications/luci-app-package-manager/Makefile
collections/luci-nginx/Makefile

Rename luci-app-opkg to luci-app-package-manager.
See openwrt/luci#7345 for more context.

luci-nginx: rename luci-app-opkg to luci-app-package-manager

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea6350v4.json

Maintainer: me
Run tested: ramips/mt7621, Linksys EA6350v4, OpenWrt 23.05.5 (by [Seraphin84](https://github.com/Seraphin84))
Description:
* add support for Linksys EA6350v4

luci-app-advanced-reboot: update to 1.0.1-15

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/README.md
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-ea6350v4.json
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4200v1.json
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4200v2.json
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mx4300.json
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-whw03.json

Maintainer: me
Run tested: ramips/mt7621, Linksys EA6350v4, OpenWrt 23.05.5 (by [Seraphin84](https://github.com/Seraphin84))
Update to the most recent version, this update includes:
* copyright & license updates
* better package definitions in Makefile
* better presence in make menuconfig
* better version/release information compatible with both opkg/apk
* updated link to upstream code
* updated README link wording
* add support for Linksys MX4200v1
* add support for Linksys MX4200v2
* add support for Linksys MX4300
* add support for Linksys WHW03
* add support for Linksys EA6350v4

[23.05] luci-app-advanced-reboot: update to 1.0.1-15

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js
applications/luci-app-pbr/po/templates/pbr.pot
applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr

Maintainer: me
Description:
* bump luci-compat to match principal package
* bump compatible README version
* remove unneeded stops from recently added warning messages
* add warningDhcpLanForce warning message
* fix div class for error and warning messages so that URLs are properly decorated

luci-app-pbr: Sync with pbr 1.1.7-29

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js

revert hwval null check by removing ax/be check that were misplaced - this check only applies to 5g/2g 
ping @Shine-

luci-mod-network: add 11be support - revert hwval null check 

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js
applications/luci-app-pbr/po/templates/pbr.pot
applications/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr

Maintainer: me
Depends on https://github.com/openwrt/packages/pull/25235

luci-app-pbr: update to sync with principal package

---

applications/luci-app-package-manager/htdocs/luci-static/resources/view/package-manager.js
applications/luci-app-package-manager/root/usr/share/rpcd/acl.d/luci-app-package-manager.json

cc @Ansuel @aparcar 
Fix upgrade action for apk by passing an attribute via 'handleInstall' to set correctly the command for 'handlePkg' in order to differentiate between install and upgrade actions.  (Note: 'handleManualInstall' sets always 'install')
Adjust acl accordingly.
Remove extra whitespace.
Tested on live system for 
* both apk & opkg enables systems, 
* both install (single package and packages with dependencies to install) and upgrade.
apk
```
Executing package manager
(1/1) Upgrading luci-app-adblock (24.284.61488~02f2d47 -> 24.304.46082~f9899fd)
OK: 70 MiB in 307 packages
```
opkg
```
Executing package manager
Upgrading ca-bundle on root from 20230311-1 to 20240203-r1...
Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/ca-bundle_20240203-r1 …
```

luci-app-package-manager: Fix upgrade action for apk

---

applications/luci-app-package-manager/htdocs/luci-static/resources/view/package-manager.js
applications/luci-app-package-manager/root/usr/libexec/package-manager-call

Clarify the output of the LuCI package manager actions: 
show also the exact command passed to apk & opkg
(in addition to output & errors from the command)
That will help debugging.
Examples:
installation:
removal:

luci-app-package-manager: Show the executed command

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

Implement a workaround to detect an 160MHz capable AP. It was introduced in the mac80211 in 2016 with 802.11ac Wave 2. APs capable of 160 MHz are detected by the shift of central frequencies. More detailed description in the link [1]. Every AP I have seen presents support for 160 MHz this way.
[1] https://github.com/torvalds/linux/commit/23665aaf9170ae6328cc4f68250c529a628af2ab
Fixes: #6262
Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>

luci-mod-status: channel_analysis: detect 160 MHz capable AP

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

At the moment, 40 MHz detection works only for some APs. HT (802.11n) exposes the 40 MHz capability of APs in two ways. The first way is a continuous 40 Mhz band. The second way is two 20MHz bonded channels. Linux detects the presence of 40 MHz by checking the presence of the second channel. It is always absent when the AP supports only 20 MHz. This PR fixes this issue and both ways are supported.
Fixes: #6839
Example:
~~~
Cell 28 - Address: 5C:7B:5C:6F:51:CB
ESSID: unknown
Mode: Master  Frequency: 2.442 GHz  Band: 2.4 GHz  Channel: 7
Signal: -88 dBm  Quality: 22/70
Encryption: WPA2 PSK (CCMP)
HT Operation:
Primary Channel: 7
Secondary Channel Offset: above
Channel Width: 40 MHz or higher
Cell 32 - Address: 54:A6:5C:56:11:B5
ESSID: "2.4G-Vectra-WiFi-5611B0"
Mode: Master  Frequency: 2.437 …

luci-mod-status: channel_analysis: detect 40 MHz (20+20 bonded) APs

---

.github/workflows/build.yml

See separate commits for details. The first commit should fix all the recent build errors for the task `Test x86_64` ([1](https://github.com/openwrt/luci/actions/runs/11852952401/job/33032096379?pr=7394), [2](https://github.com/openwrt/luci/actions/runs/11764799075/job/32770355810), [3](https://github.com/openwrt/luci/actions/runs/11795975811/job/32856854484)). For reviewers, make sure to check that the workflow run is green and produces the expected results.
* ci: upgrade openwrt/gh-action-sdk workflow to v7
With the change of the Docker container not including pre-built
binaries [1], the previous version of the workflow fails as it still
expects those to be present in the upstream container while the new
versions runs a file called setup.sh if present to configure the
container.
By …

ci: fix build error and account for APK as default

---

applications/luci-app-package-manager/htdocs/luci-static/resources/view/package-manager.js
applications/luci-app-package-manager/root/usr/share/rpcd/acl.d/luci-app-package-manager.json

Support new APK repositories.d configs following OPKG was to better split distfeeds and customfeeds.
Support for ""legacy"" repositories is kept to support migration period and to support custom scenario where user use this file instead.

luci-app-package-manager: support new APK repositories.d configs

---

libs/luci-lib-ip/src/Makefile
libs/luci-lib-jsonc/src/Makefile
libs/luci-lib-nixio/src/Makefile
modules/luci-lua-runtime/src/Makefile

Add $(FPIC) build flags to fix building with CONFIG_USE_LTO enabled.

Add $(FPIC) build flags to fix LTO builds.

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/notification.js
applications/luci-app-keepalived/root/usr/share/luci/menu.d/luci-app-keepalived.json
applications/luci-app-keepalived/root/usr/share/rpcd/acl.d/luci-app-keepalived.json

This commit adds a tab to modify keepalived.user file. With this commit it is possible to specify notifications.
Maintainer: @jempatel

luci-app-keepalived: add notification tab

---

collections/luci-ssl-openssl/Makefile
collections/luci-ssl/Makefile

Currently, the regular and nginx collections include package manager by default but SSL collections dont, so lets include package manager on SSL collections as well.

collections: select package manager for SSL collections

---

modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js
themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
themes/luci-theme-material/htdocs/luci-static/material/cascade.css
themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css

This PR makes items in UIDynamicList drag-sortable. 
Should work as is, but could use two improvements:
1) does not work on mobile. Maybe this can be fixed in CSS?  --> Update: Basic touch functionality added with last commit
2) Click detection is pixel width based, as the `::after` is not  accessable from js (or at least i do not know a method).  To fix this would require a lot of code refactoring.
Any suggestions, comments, or improvements appreciated,

luci-base: make items of UIDynamicList drag-sortable

---

applications/luci-app-upnp/htdocs/luci-static/resources/view/status/include/80_upnp.js
applications/luci-app-upnp/htdocs/luci-static/resources/view/upnp/upnp.js
applications/luci-app-upnp/po/cs/upnp.po
applications/luci-app-upnp/po/da/upnp.po
applications/luci-app-upnp/po/de/upnp.po
applications/luci-app-upnp/po/es/upnp.po
applications/luci-app-upnp/po/fi/upnp.po
applications/luci-app-upnp/po/fr/upnp.po
applications/luci-app-upnp/po/ga/upnp.po
applications/luci-app-upnp/po/it/upnp.po
applications/luci-app-upnp/po/ja/upnp.po
applications/luci-app-upnp/po/lt/upnp.po
applications/luci-app-upnp/po/nb_NO/upnp.po
applications/luci-app-upnp/po/pl/upnp.po
applications/luci-app-upnp/po/pt/upnp.po
applications/luci-app-upnp/po/pt_BR/upnp.po
applications/luci-app-upnp/po/ro/upnp.po
applications/luci-app-upnp/po/ru/upnp.po
applications/luci-app-upnp/po/sv/upnp.po
applications/luci-app-upnp/po/tr/upnp.po
applications/luci-app-upnp/po/uk/upnp.po
applications/luci-app-upnp/po/vi/upnp.po
applications/luci-app-upnp/po/zh_Hans/upnp.po
applications/luci-app-upnp/po/zh_Hant/upnp.po

Leftovers from #7407
CC @Self-Hosting-Group

luci-app-upnp: restore some i18n keys

---

applications/luci-app-uhttpd/htdocs/luci-static/resources/view/uhttpd/uhttpd.js

The code style of Luci declares three vars for map, section and option and reuses them. This makes code clearer and better to compress.
Maintainer: @danielfdickinson
CC @Ayushmanwebdeveloper

luci-app-uhttpd: rename all non-reused vars to m, s, o

---

protocols/luci-proto-wireguard/root/usr/share/rpcd/ucode/luci.wireguard

This commit fixes incorrect peer detection when using IP v6 by deleting all the square the square brackets from the wgHost variable.
Signed-off-by: Tom Haley <this_username_has_been_taken2@proton.me>

luci-proto-wireguard: Fix incorrect peer detection for IP v6

---

protocols/luci-proto-wireguard/root/usr/share/rpcd/ucode/luci.wireguard

This PR fixes a vulnerability when a random code can be passed into the `configHost` variable and then it will be executed by  the `popen` command.
To fix the issue the variable is sanitized via `shellquote` method.
For a more detailed description please refer to #7452 
Signed-off-by: Tom Haley <this_username_has_been_taken2@proton.me>

luci-proto-wireguard: fixed a vulnerability in the checkPeerHost method

---

applications/luci-app-hd-idle/htdocs/luci-static/resources/view/hd_idle.js

Result of `lsblk` may have some null values, check it before trim.
```
[root@OpenWrt ~]# /usr/bin/lsblk -n -J -do "NAME,TRAN,ROTA,RM,VENDOR,MODEL"
{
"blockdevices": [
{
"name": "sda",
"tran": null,
"rota": true,
"rm": false,
"vendor": "QEMU      ",
"model": "QEMU HARDDISK   "
},
{
"name": "zram0",
"tran": null,
"rota": false,
"rm": false,
"vendor": null,
"model": null
}
]
}
```

luci-app-hd-idle: Check disk opt value

---

modules/luci-base/po/templates/base.pot
protocols/luci-proto-ipv6/htdocs/luci-static/resources/protocol/dhcpv6.js

add missing `extendprefix` option for DHCPv6 client (see https://openwrt.org/docs/guide-user/network/ipv6/configuration#protocol_dhcpv6)
Allow the DHCPv6 client to accept /64 prefix via SLAAC and extend it on downstream interface (RFC 7278) 
useful for ISPs that only distribute /64 IPv6 prefixes through SLAAC:
```
Internet Control Message Protocol v6
Type: Router Advertisement (134)
Code: 0
Checksum: 0x453d [correct]
[Checksum Status: Good]
Cur hop limit: 64
Flags: 0x40, Other configuration, Prf (Default Router Preference): Medium
Router lifetime (s): 1800
Reachable time (ms): 300000
Retrans timer (ms): 10000
ICMPv6 Option (Source link-layer address : **:**:**:**:**:**)
ICMPv6 Option (Prefix information : 240b:10:****:****::/64)
Type: Prefix information (3)
Length: 4 (32 bytes)
Prefix …
```

luci-proto-ipv6: add missing extendprefix option for DHCPv6 client

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Image selection for `armsr` and `loongarch` is currently broken, as they are not recognized as a "combined" image target.  Add a list of the appropriate targets to make maintenance easy.
The "depends on" below is only partial as 12963 is only needed for the `armsr` target.  The `loongarch` target will be fixed by this PR, regardless of the inclusion of 12963 (`armsr` is broken now and will remain so until that PR is merged).
Tested on: x86/64 snapshot
Depends on: openwrt/openwrt#12963

luci-app-attendedsysupgrade: make image selection consistent across all EFI targets

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

Without validation, `dnsmasq` can fail silently if users enter invalid leasetime input. This change adds input validation to align user input with the backend parsing logic. Whilst it does not enforce the >120 seconds requirement, this is documented in the field description and handled by `dnsmasq`'s `option.c`, which adjusts values <120 to meet this minimum.

luci-mod-network: validate DHCP leasetime input

---

applications/luci-app-pbr/Makefile
applications/luci-app-pbr/htdocs/luci-static/resources/pbr/status.js

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc2
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc2
Description:
* match version with principal package
* update README version
* use var instead of const for RPCD objects

luci-app-pbr: update to 1.1.8

---

CONTRIBUTING.md
README.md

To help users to find a right place where to translate.
Because some users trying to edit the po files directly. This also should be acceptable because we shouldn't force users to register on a third party tool and learn it.
Ideally we should add a link to translations, github and dourm into the Luci itself. This must increase contributions from regular users.

treewide: Add a link to Weblate

---

modules/luci-base/htdocs/luci-static/resources/uci.js

follow-up for c2fc96cc4c6b35f19638f8c54599041ce6e39da4

luci-base: follow-up fix for ES6 changes

---

applications/luci-app-squid/htdocs/luci-static/resources/view/squid.js

Since 22d4830 the form variables m, s, and o was changed to be declared with let instead of var, but the o variable was redeclared in the app, resulting in a redeclaration error when it was changed to instead be declared with let.
See https://forum.openwrt.org/t/openwrt-24-10-0-rc4-fourth-release-candidate/219368/81?u=dannil
Before
After

luci-app-squid: remove variable redeclaration

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/connections.js

This commit adds a simple filtering input text into the connections status page. You can type some filtering like:
- '100.15' -> Will show only connections that include this '100.15' onto the IP.
- 'UDP 100.15' -> Will show only UDP connections that include this '100.15' onto the IP.
You can use a part of the IP or part of the name if the DNS resolution button is enabled.
It's a very simple filter that can grow in the future if it deserves some interest, maybe adding some regular expression support.

luci-mod-status: add simple filtering for connections

---

applications/luci-app-filemanager/po/zh_Hans/filemanager.po
applications/luci-app-filemanager/po/zh_Hant/filemanager.po

luci-app-filemanager: update chinese translations

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

luci-app-acme: DNS API store all params

---

modules/luci-base/htdocs/luci-static/resources/form.js

Commit 234e1315073595771a7397d74a039d0eb4c1a89d changed the "val" variable to be a constant, but it's value is reassigned later. Change the variable to be declared with let instead so it can be reassigned.
Before: sorting on zone forwardings fails (applies to all GridSections)
After: sorting on zone forwardings works correctly (applies to all GridSections)

luci-base: allow sort value to be reassigned

---

applications/luci-app-filemanager/htdocs/luci-static/resources/view/system/filemanager.js

- Description: 
Now the 'Toggle ASCII' button is disabled if the file is hex.

luci-app-filemanager: Editing hex files improvements

---

applications/luci-app-dawn/htdocs/luci-static/resources/dawn/dawn-common.js

~~- [ ] \( Preferred ) Mention: @ the original code author for feedback~~
~~- [ ] \( Optional ) Closes: e.g. openwrt/luci#issue-number~~
~~- [ ] \( Optional ) Depends on: e.g. openwrt/packages#pr-number in sister repo~~
The calculation is as follows:
(6GHz freq - 5950) / 5
i.e. (6135 - 5950) / 5 = 185 / 5 = 33

luci-app-dawn: Fix getChannelFromFrequency for 6GHz

---

modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js

If the value returned from UCI was falsy, it became an empty array instead of an empty string, which crashed the UI when trying to invoke the non-existing replace instance function on the value.
First observed here https://forum.openwrt.org/t/openwrt-24-10-0-rc4-fourth-release-candidate/219368/145?u=dannil
Before:
https://github.com/user-attachments/assets/5549cf24-7aae-4a01-9e6c-00184a4054b2
```
root@labmouse:~# cat /etc/config/dhcp
config dnsmasq
option domainneeded '1'
option localise_queries '1'
option rebind_protection '1'
option rebind_localhost '1'
option local '/lan/'
option domain 'lan'
option expandhosts '1'
option cachesize '1000'
option authoritative '1'
option readethers '1'
option leasefile '/tmp/dhcp.leases'
option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
option …
```

luci-mod-network: handle missing dnsrr hexdata as empty string

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js

Maintainer: @tohojo
Some cleanup of the code.
The changes are from the other PR #7515

luci-app-acme Migrate to ES6

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/script.js
applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/servers.js

luci-app-keepalived: add missing variable declarations

---

modules/luci-base/htdocs/luci-static/resources/ui.js

This PR will add generation of the cbi-dynlist-change event after drag/touch end. 
As discussed here: https://github.com/openwrt/luci/pull/7415
I regression tested it and no impact. I do not have progression testing code. so @muink Please test it!
I did validate that it does not generate console errors.

luci-base: Generate cbi-dynlist-change event after drag/touch end

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/29_ports.js

This adds more cases for a few link speeds beyond 40 GbE, i.e. for 50 GbE, 100 GbE and 200 GbE in speed formatting for luci-mod-status. While there are currently only a few devices where this may be useful, we actually operate some 200G switches and x86 devices with 200G/100G NICs.
**required to bump PKG_VERSION ?**

luci-mod-status: 29_ports.js: improve speed formatting

---

protocols/luci-proto-3g/htdocs/luci-static/resources/protocol/3g.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/ppp.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoa.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pppoe.js
protocols/luci-proto-ppp/htdocs/luci-static/resources/protocol/pptp.js
protocols/luci-proto-pppossh/htdocs/luci-static/resources/protocol/pppossh.js

Fix regressions from previous fix:
1) It is no longer possible to leave the keepalive option empty. Then
it becomes keepalive='0 1'
2) In case the interval is different from 1 it is necessary to
explicitly set the option even if failures is left empty.

luci-proto-3g/ppp/pppossh: fix setting of keepalive

---

modules/luci-base/htdocs/luci-static/resources/tools/widgets.js

luci-base: Enforce maximal firewall zone length in the Create / Assign scenario as well.

---

modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/20_lan.js
modules/luci-mod-dashboard/htdocs/luci-static/resources/view/dashboard/include/30_wifi.js

luci-mod-dashboard: make the DHCP Devices and Wireless proper tables with headers.

---

applications/luci-app-nlbwmon/htdocs/luci-static/resources/view/nlbw/config.js

```
#option database_compress 1
```
With this change, the no option situation is matched in the UI.

luci-app-nlbwmon: the default of database_compress is 1, match that behaviour in UI.

---

modules/luci-base/htdocs/luci-static/resources/form.js
modules/luci-base/htdocs/luci-static/resources/ui.js

Add member `allowduplicates` to `DynamicList` to allow duplicate underlying form values.
`allowduplicates` defaults is `null`, `DynamicList` will keep the same behavior as before.
If `o.allowduplicates = true`, the underlying form value will not be checked for duplication.

luci-base: add member `allowduplicates` to `DynamicList`

---

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js

luci-app-ddns: show the URL which will be used.

---

applications/luci-app-ddns/htdocs/luci-static/resources/view/ddns/overview.js

luci-app-ddns: avoid Absent Interface: "wan" when the physical device does not exist

---

modules/luci-base/htdocs/luci-static/resources/tools/widgets.js

luci-base: Enforce maximal firewall zone length in the Create / Assign scenario as well (take 2).

---

modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/interfaces.js

The protocol defaults to 'none' in netifd if unspecified.

luci-base/luci-mod-network: handle default protocol for UCI interfaces

---

modules/luci-base/htdocs/luci-static/resources/protocol/static.js

luci-base: expose static IPv6 configuration even if IPv6-PD is enabled.

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

The Attended Sysupgrade app requires that the array of latest versions be in order from newest release to oldest.  Ensure that this is true even when upstream presents them in arbitrary order.

luci-app-attendedsysupgrade: sort latest version array

---

applications/luci-app-pbr/Makefile

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* depends on https://github.com/openwrt/packages/pull/25842

luci-app-pbr: version bump to sync with principal package

---

applications/luci-app-adblock-fast/Makefile

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Description:
* version bump to sync with principal package

luci-app-adblock-fast: version bump

---

applications/luci-app-https-dns-proxy/Makefile

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0-rc6

luci-app-https-dns-proxy: version bump

---

modules/luci-base/htdocs/luci-static/resources/tools/widgets.js

luci-base: Allow "*" (== Any zone) in the firewall zone selection.

---

applications/luci-app-antiblock/Makefile
applications/luci-app-antiblock/htdocs/luci-static/resources/view/antiblock/domains.js
applications/luci-app-antiblock/htdocs/luci-static/resources/view/antiblock/form.js
applications/luci-app-antiblock/root/usr/libexec/rpcd/luci.antiblock
applications/luci-app-antiblock/root/usr/share/luci/menu.d/luci-app-antiblock.json
applications/luci-app-antiblock/root/usr/share/rpcd/acl.d/luci-app-antiblock.json

Maintainer: me
Compile tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Run tested: ASUS RT-AX59U 23.05.5, ASUS RT-AX53U 23.05.5, OpenWrt x86
Description:
LuCI web interface for antiblock package

luci-app-antiblock: Add new package

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Utilize the 'package_changes' from the ASU server to update the package list for the build request.
Links: https://github.com/openwrt/asu/commit/2bff208387d69a5a1723032a45e672650c17de62
---
@aparcar @systemcrash Please critique these changes thoroughly, my JS experience is grossly outdated and I'm not at all confident about the stylistic choices I've made.  The new function feels solid to me (except for some missing error checking), but the call sequence at the bottom seems kind of ugly.

luci-app-attendedsysupgrade: apply changes to package list

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Fix bug in applyPackageChanges, it was using the installed version as the target, resulting in no changes being applied.
@aparcar

luci-app-attendedsysupgrade: supply proper version to package changes

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/overview.js
applications/luci-app-keepalived/htdocs/luci-static/resources/view/status/include/35_keepalived.js

Upstream only handles state according to whether the machine was in BACKUP or MASTER. FAULT state is not handled but upstream keepalived does support that by exporting json  with `state` which reflects the state (FAULT included).
This is included to luci-app-keepalived via `ubus call keepalived dump`.
The second commit separates the two states that are defined into separate columns.

luci-app-keepalived: include FAULT state to state

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/lu.restena.dnspub.json

* bugfix: restna.lu URL (thanks @giantplaceholder)
* version bump to sync with principal package

luci-app-https-dns-proxy: bugfix and version bump

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/lu.restena.dnspub.json

* bugfix: restna.lu URL (thanks @giantplaceholder)
* version bump to sync with principal package

[24.10] luci-app-https-dns-proxy: bugfix and version bump

---

modules/luci-base/htdocs/luci-static/resources/network.js
modules/luci-mod-network/htdocs/luci-static/resources/view/network/wireless.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/60_wifi.js

luci: show wifi vlan interface instead of base interface

---

applications/luci-app-firewall/htdocs/luci-static/resources/view/firewall/zones.js

This PR changes the zone log checkbox to a multivalue selection.
From the [documentation](https://openwrt.org/docs/guide-user/firewall/firewall_configuration#zones):

luci-app-firewall: fix zone log option

---

applications/luci-app-lxc/luasrc/controller/lxc.lua
applications/luci-app-lxc/luasrc/view/lxc.htm

The backend code is: 
```local lxc_configuration = luci.http.formvalue("lxc_conf")```
but frontend do not send formvalue with key "lxc_conf": 
```new XHR().post('<%=luci.dispatcher.build_url("admin", "services")%>/lxc_configuration_set/' + lxc_name, "lxc_conf=" + encodeURIComponent(lxc_conf)```
The fix is: 
```
new XHR().post('<%=luci.dispatcher.build_url("admin", "services")%>/lxc_configuration_set/' + lxc_name, {"lxc_conf": encodeURIComponent(lxc_conf)}
```
and decoded string is required for LXC
```
lxc_configuration = luci.http.urldecode(lxc_configuration, true)
```

luci-app-lxc: fix configure lxc container POST request

---

modules/luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/netdev.js

Many devices have LEDs to signal a specific link speed. They are incorrectly displayed in LUCI when they are deﬁned. This commit adds the missing speed and duplex triggers.
Tested on: mediatek/filogic/ex5601, snapshot, Firefox

luci-mod-system: add LED speed and duplex triggers

---

modules/luci-base/htdocs/luci-static/resources/form.js

Related: #7326
It may not fix, but at least it shouldn't harm

luci-base: forms.js safe call on this.map.data.remove()

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

The channel width for WiFi 802.11be displays incorrectly on the graph and this commit fixes it.
Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>
~~~
root@OpenWrt:/# iwinfo
phy0.2-ap0 ESSID: "OpenWrt"
Access Point: 00:58:28:29:C1:D2
Mode: Master  Channel: 33 (6.115 GHz)  HT Mode: EHT320
Center Channel 1: 31 2: unknown
Tx-Power: 23 dBm  Link Quality: unknown/70
Signal: unknown  Noise: -85 dBm
Bit Rate: unknown
Encryption: WPA3 OWE (CCMP)
Type: nl80211  HW Mode(s): 802.11ac/ax/b/be/g/n
Hardware: 14C3:7990 14C3:6639 [MediaTek MT7996E]
TX power offset: none
Frequency offset: none
Supports VAPs: yes  PHY name: phy0
~~~

luci-mod-status: channel_analysis: fix 802.11be local interface channel width

---

themes/luci-theme-material/htdocs/luci-static/material/cascade.css

My PR is a slight improvement, where the upstream version works fine, but my downstream version benefits heavily from it, so made the request:
On theme material it is barely possible to see the possible options in
the dropdown from my version of luci-theme-material. 
If the dropdown is switched to `--black-color` (EDIT: not `--gray-color-high`) it improves distinguishing the colors in my GUI.
*Before downstream version*
*After downstream version*
In the upstream version the dropdown is fine and also distinguishable with my modified version:
*Before upstream version*
*After upstream version*
On both versions (upstream/downstream) the button is no ideal as a display so I changed that also:
*Before*
*After*

luci-theme-material: change dropdown button for better visibility

---

applications/luci-app-acl/htdocs/luci-static/resources/view/system/acl.js

If a new user is created, 'luci-mod-status-index' should also be selected, as this is the start page after login. If a user is created without this, only  a 404 is displayed. To fix this also grand read access to the 'luci-mod-status-index' page. Once you log in and see this page, you can't log out either

luci-app-acl: also grand read access to luci-mod-status-index

---

applications/luci-app-keepalived/root/usr/share/luci/menu.d/luci-app-keepalived.json

Because no ACL has been set for luci-app-keepalived in menu.d, the menu entry is always displayed, even if access is disabled in the '/etc/config/rpcd' file. Add the missing information to the menu.d file fixes this issue.

luci-app-keepalived: set acl dependency

---

modules/luci-base/htdocs/luci-static/resources/ui.js
themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
themes/luci-theme-material/htdocs/luci-static/material/cascade.css
themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css

luci-themes-*: improve look and feel on small screens for modal overview

---

modules/luci-base/htdocs/luci-static/resources/ui.js

The function signature changed and all function call to addNotification that add a CSS class does not work anymore. A direct revert is not possible.
If this feature is needed than a new function musst be added, that does not break the function signature.
Fixes: 53e36e3293bee2ea2ce0fbc1250074c44cfe8335
See discussion for an other solution #7670

luci-base: revert timeout function argument for addNotification

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Do not hide upcoming versions behind the 'advanced_mode' setting, always show them.
Fixes: https://github.com/openwrt/asu/issues/1202

luci-app-attendedsysupgrade: show upcoming versions when available

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Do not hide upcoming versions behind the 'advanced_mode' setting, always show them.
Fixes: https://github.com/openwrt/asu/issues/1202
(cherry picked from commit 8b00d023b0335783dc459a738a1b1e9c2be9cacc)

[24.10] luci-app-attendedsysupgrade: show upcoming versions when available

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

Do not hide upcoming versions behind the 'advanced_mode' setting, always show them.
Fixes: https://github.com/openwrt/asu/issues/1202
(cherry picked from commit 8b00d023b0335783dc459a738a1b1e9c2be9cacc)

[23.05] luci-app-attendedsysupgrade: show upcoming versions when available

---

modules/luci-base/htdocs/luci-static/resources/uci.js

Any number of apps read boolean values from configuration files, then use various inconsistent means for checking truth values.  The get_bool function allows app authors to fetch the value without regard for how it is represented in the config file.
For example, this
```
let enabled = uci.get('system', 'ntp', 'enable_server');
if (enabled == '1') ...
```
could become the more natural
```
let enabled = uci.get_bool('system', 'ntp', 'enable_server');
if (enabled) ...
```

luci-base: add uci.get_bool to allow cleanup of app code

---

modules/luci-base/htdocs/luci-static/resources/uci.js

Any number of apps read boolean values from configuration files, then use various inconsistent means for checking truth values.  The get_bool function allows app authors to fetch the value without regard for how it is represented in the config file.
For example, this
let enabled = uci.get('system', 'ntp', 'enable_server');
if (enabled == '1') ...
could become the more natural
let enabled = uci.get_bool('system', 'ntp', 'enable_server');
if (enabled) ...
(cherry picked from commit dea8d79888f862c82953b775e55f4d0c672cc897)

[24.10] luci-base: add uci.get_bool to allow cleanup of app code

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/channel_analysis.js

This commit fixes  wrong channel width in the 6 GHz band. Now all APs don't show a 20 MHz channel width.
Tested on ZyXEL EX5601 with MT7921 USB adapter.
Depends on: https://github.com/openwrt/rpcd/pull/11.
Signed-off-by: Aleksander Jan Bajkowski <olek2@wp.pl>
~~~
Cell 15 - Address: 00:58:28:29:C1:D2
ESSID: "OpenWrt"
Mode: Master  Frequency: 5.955 GHz  Band: 6 GHz  Channel: 1
Signal: -22 dBm  Quality: 70/70
Encryption: WPA3 SAE (CCMP)
HE Operation:
Center Frequency 1: 7
Center Frequency 2: 15
Channel Width: 160 MHz
EHT Operation:
Center Frequency 1: 15
Center Frequency 2: 31
Channel Width: 320 MHz
~~~

luci-mod-status: channel_analysis: fix 6 GHz support

---

applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/net.ffmuc.doh.json

this updates the ffmuc bootstrap_dns to ffmuc dns servers instead of google or cloudflare dns
Signed-off-by: Tobias <git@t0biii.de>
(cherry picked from commit 29187d4e2b3e184c9b0bd6baf343ec3d2a3b384d)

[24.10] luci-app-https-dns-proxy: Update: ffmuc bootstrap_dns servers

---

applications/luci-app-keepalived/htdocs/luci-static/resources/view/keepalived/notification.js

The content of the file is executed at the next event, so it is not necessary to reload `/etc/init.d/keepalived` if the user notification has changed.
Fixes: #7685

luci-app-keepalived: do not restart keepalived on user notification change

---

applications/luci-app-xinetd/htdocs/luci-static/resources/view/xinetd/xinetd.js

* make the server configuration option mandatory
* do not show description in table overview (Bind address)
Fixes: 7664

luci-app-xinetd: fixes

---

modules/luci-base/htdocs/luci-static/resources/ui.js

Password managers (like LastPass etc) tend to add additional elements into the DOM for their own context menus. If this happens between the hide/reveal button and the password input, then the logic to reveal the password breaks.
This change updates the onclick handler to look backward in the DOM for the first sibling that is an input, and to then toggle the password/text type on that element.

luci: Make password reveal work with password managers

---

protocols/luci-proto-wireguard/root/usr/share/rpcd/ucode/luci.wireguard

Added the legacy peer name detection algorithm.
If the new algorithm fails to find a peer's name (e.g. when the IP address has been changed) then the legacy value will be used.

luci-proto-wireguard: fixed incorrect peer name detection when peer IP has been changed

---

modules/luci-base/Makefile

Hardcode 'openwrt-24.10' release branch as the branch name to avoid `LuCI (HEAD detached at 2ac26e56) branch` being shown as the branch.
Feeds are since March 2025 cloned shallow if cloned from a specific commit, like done with a release tag. Change in OpenWrt: https://github.com/openwrt/openwrt/commit/32d0a57dc10811a24816e51f10e55963f40fe462
As the only cloned commit of a release tag is without history, the branch can't be identified.
So, hardcode the branch name to get the proper branch name `LuCI openwrt-24.10 branch` into version.uc.
Fixes #7737
Similar change should likely be done also for 23.05 (into where the same feeds logic has been backported).
Note that the change will only have impact from 24.10.2 onward, as 24.10.1 tag is naturally unimpacted by this.
The change is …

[24.10] luci-base: Hardcode 'openwrt-24.10' as the branch name

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/README.md
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Description:
* fixes https://github.com/openwrt/luci/issues/7763
* fixes https://github.com/stangri/luci-app-https-dns-proxy/issues/9
* fix README link

luci-app-https-dns-proxy: update to 2025.05.11

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/README.md
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/libexec/rpcd/luci.https-dns-proxy

Maintainer: me
Compile tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Run tested: x86_64, Dell EMC Edge620, OpenWrt 24.10.0
Description:
* fixes https://github.com/openwrt/luci/issues/7763
* fixes https://github.com/stangri/luci-app-https-dns-proxy/issues/9
* fix README link
(cherry picked from commit bd5cb1dd66c5a79e36e7fd2960bfc70e73fad686)

[24.10] luci-app-https-dns-proxy: update to 2025.05.11

---

modules/luci-mod-network/htdocs/luci-static/resources/tools/network.js

- [?] Incremented :up: any `PKG_VERSION` in the Makefile
This fixes the missing `policy` option in UCI when selecting 'active-backup'
as the required policy in a bonding device.

luci-mod-network: fix default policy for bonding device

---

applications/luci-app-wol/htdocs/luci-static/resources/view/wol.js

- Architecture: mvebu/cortexa9 (Turris Omnia)
- OpenWrt version: 24.10.0-rc5
- Browser: Google Chrome 135.0.7049.114
@Damrod

luci-app-wol: Show additional possibly powered off hosts in dropdown menu

---

modules/luci-base/htdocs/luci-static/resources/form.js

This Unicode character is intended to be followed by 2 more characters which are combined. It's entirely unnecessary, so just remove it.

luci-base: remove bad Unicode on clone button

---

modules/luci-base/htdocs/luci-static/resources/form.js

The `hidden` class was being set to the wrong element.

luci-base: fix table option does not show in non-Bootstrap themes when it has depends

---

applications/luci-app-attendedsysupgrade/htdocs/luci-static/resources/view/attendedsysupgrade/overview.js

When users add an extraneous slash to the server url, then the ASU server redirects GET requests.  But, this causes an error on POST requests as the ASU server does not redirect those, so the LuCI client failed inappropriately with an unhandled error.
Fix both of these by first trimming trailing slashes from the server url as it is loaded to avoid the redirects.  Then, also handle all unexpected responses, instead of just a select few.
Links: efahl/owut@724c990d6cc0

luci-app-attendedsysupgrade: avoid redirects, handle redirect errors

---

applications/luci-app-usteer/htdocs/luci-static/resources/view/usteer/usteer.js

When you directly load the usteer page "/cgi-bin/luci/admin/network/usteer"  then somehow the wifi networks do not get populated, this throws an error. 
I added extra checking to prevent this. The result is that the  SSID list is empty: 
while normally you get the list of all wifi networks. 
It would be better to additionally fix `network.js`, but to be honest I am not sure why it will not  show, maybe its a timing issue?
Also fixed a console error related to the hostnames by additional error checking.

luci-app-usteer: Extra error checking

---

protocols/luci-proto-modemmanager/htdocs/luci-static/resources/protocol/modemmanager.js

luci-proto-modemmanager: fix username and password show if allowedauth is configured

---

applications/luci-app-package-manager/htdocs/luci-static/resources/view/package-manager.js

In HTML, the following lines of code are equivalent:
```
<input disabled />
<input disabled="true" />
<input disabled="false" />
<input disabled="any" />
```
If you want to cancel the 'disabled' flag, you must completely remove it from the HTML instead of assigning a value.

luci-app-package-manager: fix 'autoremove' checkbox uneditable

---

modules/luci-mod-status/htdocs/luci-static/resources/view/status/syslog.js

Fixed bug in syslog.js where lines could be hidden even when "any" was selected, and simplified code a bit.
When clicking on "Not" they appear:
@systemcrash: Can you have a look? 
Also is there a way to check which logger is used (im using syslog-ng). That does not use a "." between, so the functionallity actually does not fully work? If so I can easily add this to the code. Alternative would be to remove the "."

luci-mod-status: Cleanup and fix syslog.js bug

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css

This is a continuation of #6991.
Instead of enumerating each SVG graph that the dark mode is applicable to, apply `--background-color-high` to each SVG element that is a child of `<div style="…">` and `--text-color-highest` to each LINE inside such SVG.
This allows dark mode to work in all SVG widgets by default, in any current or future LuCI component.
Note: `luci-lib-uqr` explicitly fills the entire area with `whiteColor` and `backColor`; it will be unaffected by this.

luci-theme-bootstrap: global darkmode graphs

---

applications/luci-app-csshnpd/Makefile
applications/luci-app-csshnpd/htdocs/luci-static/resources/view/sshnpd/config.js
applications/luci-app-csshnpd/htdocs/luci-static/resources/view/sshnpd/enroll.js
applications/luci-app-csshnpd/root/usr/share/luci/menu.d/luci-app-csshnpd.json
applications/luci-app-csshnpd/root/usr/share/rpcd/acl.d/luci-app-csshnpd.json

Maintainer: @cpswan
Compile tested: x86_64 (snapshot r29619, 24.10.0), aarch64_cortex-a53 (snapshot, 23.05.5)
Run tested: x86_64 (snapshot r29619, 24.10.0), aarch64_cortex-a53 (23.05.5)
Description:
Adding LuCI web interface for [csshnpd package](https://github.com/openwrt/packages/tree/master/net/csshnpd) (thanks @feckert and @BKPepe for shepherding https://github.com/openwrt/packages/pull/26518 through to being merged).
Video walk through at [NoPorts OpenWrt Installation Guide](https://docs.noports.com/installation/openwrt-installation-guide) (NB predates csshnpd being accepted upstream so starts with LuCI based installation of downloaded .ipks).

luci-app-csshnpd: Add new package

---

libs/luci-lib-nixio/Makefile

Depends on: https://github.com/openwrt/openwrt/pull/19293

treewide: adjust packages against glibc 2.41

---

modules/luci-base/htdocs/luci-static/resources/ui.js

Update ui.js to allow submitting from dropdown on android chromium.
Fixes: [https://github.com/openwrt/luci/issues/7819](https://github.com/openwrt/luci/issues/7819)
P.S. maybe we should also fix the `ev.keyCode` as this may also be unreliable (and using e.g. ev.key is more readable)

luci-base: allow submitting new value in dropdown lists in android chromium

---

applications/luci-app-https-dns-proxy/Makefile
applications/luci-app-https-dns-proxy/README.md
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/https-dns-proxy/status.js
applications/luci-app-https-dns-proxy/htdocs/luci-static/resources/view/https-dns-proxy/overview.js
applications/luci-app-https-dns-proxy/po/templates/https-dns-proxy.pot
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/eu.joindns4.json
applications/luci-app-https-dns-proxy/root/usr/share/https-dns-proxy/providers/org.opennameserver.json

Maintainer: me
Description:
* update license ID and copyright in Makefile
* add a short README with link to full documentation
* switch doc link from melmac.net to melmac.ca
* add donate text/URL
* attempt to fix bootstrap DNS loading/saving from json
* add DNS4EU provider (thanks @rikroe)
* add OpenNameServer provider (thanks @Phoenix616)

luci-app-https-dns-proxy: update to 2025.05.11-4

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/adblock-fast/status.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Description:
* add Donate section/URL to status
* improve visibility with the RPCD return variable names (thanks @systemcrash)
* improve LEDs detection in RPCD script
(cherry picked from commit 68a315f5ad0bffce4ba708d942178281e7661441)

[24.10] luci-app-adblock-fast: update to 1.1.4-6

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/README.md
applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js
applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mr7350.json

Maintainer: me
Run tested: qualcommax, Linksys MX4200v1, OpenWrt 24.10.2
Description:
Makefile:
- update SPDX license identified and copyright
- update documentation link
README:
- add short README with the link to full documentation
System View javascript:
- switch from single to double quotes
- update documentation link
- more readable translateTable
- better code readability for
- callPowerOff
- handlePowerOff
- handleReboot
- handleTogglePartition
- handleAlternativeReboot
- parsePartitions
- some visual elements
RPCD Script:
- more resilient to unexpected CLI output
- add debugger function to ease development/debugging
- better check if `/var/alt_rom` is mounted before calling umount
- better handling of MTD indices
Device …

luci-app-advanced-reboot: update to 1.1.0-1

---

applications/luci-app-advanced-reboot/Makefile
applications/luci-app-advanced-reboot/README.md
applications/luci-app-advanced-reboot/htdocs/luci-static/resources/view/system/advanced_reboot.js
applications/luci-app-advanced-reboot/root/usr/libexec/rpcd/luci.advanced_reboot
applications/luci-app-advanced-reboot/root/usr/share/advanced-reboot/devices/linksys-mr7350.json

Maintainer: me
Description:
Makefile:
- update SPDX license identified and copyright
- update documentation link
README:
- add short README with the link to full documentation
System View javascript:
- switch from single to double quotes
- update documentation link
- more readable translateTable
- better code readability for
- callPowerOff
- handlePowerOff
- handleReboot
- handleTogglePartition
- handleAlternativeReboot
- parsePartitions
- some visual elements
RPCD Script:
- more resilient to unexpected CLI output
- add debugger function to ease development/debugging
- better check if `/var/alt_rom` is mounted before calling umount
- better handling of MTD indices
Device …

[24.10] luci-app-advanced-reboot: update to 1.1.0-1

---

applications/luci-app-acme/htdocs/luci-static/resources/view/acme.js
applications/luci-app-acme/htdocs/luci-static/resources/view/dnsapi.js
applications/luci-app-acme/root/usr/libexec/acmesh-dnsinfo.sh
applications/luci-app-acme/root/usr/share/rpcd/acl.d/luci-app-acme.json

Maintainer: @tohojo
To show fields specific to a DNS API provider I made a list of all options and included them directly into the JS file.
In the upcoming ACME.sh release all scripts now contains a [Structured Info](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Structural-Info-description) with list of options:
```
dns_alviy
Alviy.com
Site: Alviy.com
Docs: github.com/acmesh-official/acme.sh/wiki/dnsapi2#dns_alviy
Options:
Alviy_token API token. Get it from the https://cloud.alviy.com/token
Issues: github.com/acmesh-official/acme.sh/issues/5115
```
So once release we can make an RPC call to gather the info for all providers right from scripts and render it.
The PR adds the parsing and rendering part. Once the acmesh will be updated in the OpenWrt we can include the script and …

luci-app-acme: render DNS API fields from the Structured Info 

---

libs/rpcd-mod-luci/src/luci.c
modules/luci-mod-network/htdocs/luci-static/resources/view/network/dhcp.js
modules/luci-mod-status/htdocs/luci-static/resources/view/status/include/40_dhcp.js

The IAID is important information as it allows the user to know which interface on the client device a given DHCPv6 lease corresponds to. odhcpd already exposes this information (e.g. via "ubus call dhcp ipv6leases"), but it would be good to have access to the same information via the web interface, especially since odhcpd does take the IAID into account when allocating addresses.

luci-mod-network,-status: show DHCPv6 lease IAID

---

applications/luci-app-adblock-fast/Makefile
applications/luci-app-adblock-fast/htdocs/luci-static/resources/view/adblock-fast/overview.js
applications/luci-app-adblock-fast/po/templates/adblock-fast.pot
applications/luci-app-adblock-fast/root/usr/libexec/rpcd/luci.adblock-fast

Maintainer: me
Compile tested: x86_64, Dell EMC Edge 620, OpenWrt 24.10.3
Run tested: x86_64, Dell EMC Edge 620, OpenWrt 24.10.3
Description:
* version sync with principal package
* remove empty led option
(cherry picked from commit c7e9948dcb08370f4c447ba42233e95987c203a3)

[24.10] luci-app-adblock-fast: update to 1.2.0

---

themes/luci-theme-bootstrap/htdocs/luci-static/bootstrap/cascade.css
themes/luci-theme-material/htdocs/luci-static/material/cascade.css
themes/luci-theme-openwrt-2020/htdocs/luci-static/openwrt2020/cascade.css
themes/luci-theme-openwrt/htdocs/luci-static/openwrt.org/cascade.css

Many LuCI icons doubled in size during migration to vector graphics in commit ae5d91da903b6f1d3086d6082ca622231e34f555 (16px to 32px).
Sizing of their instances is mostly controlled by CSS, but there's an exception - network interface boxes of *Interfaces* page in LuCI. Current CSS doesn't specify any particular size requirements to follow, so the icons just scale with the images served, thus effectively doubling in width and height compared to state before the vectorization commit. Such a big icons look odd and take up too much space, especially for bridge interfaces with many ports.
Instead of reverting to the original 16×16px, this commit proposes compromise of 24×24px as most of other icons within LuCI became a bit bigger as well.
Changes were tested on all 4 themes using OpenWrt …

themes: scale down icons for network interfaces

---

applications/luci-app-usteer/root/usr/share/luci/menu.d/luci-app-usteer.json

Currently menu entry is always shown even at the login screen.
Fix this by setting acl dependency.
Aslo fix the indent.

luci-app-usteer: fix menu showing on login screen

---

modules/luci-base/htdocs/luci-static/resources/luci.js

Because the setupDOM/initDOM methods do strange things related to the old lua server rendered templates
(like remove all the elements currently hidden by dependencies...), we want to be sure that these have finished before the view itself renders.
This also ensures that any caching (e.g. from probeSystemFeatures) is finished before the view render.
This is a hacky fix that we've been using on 23.05, but it's not clear to me what the best one is. I'm raising it as a draft for comment; if someone thinks this is an acceptable solution, I'll add a simple reproduction of a bug and test on master.

luci-base: don't render until luci-loaded is done

---

modules/luci-base/htdocs/luci-static/resources/ui.js

* [luci: Make password reveal work with passsword managers](https://github.com/openwrt/luci/commit/fc8ad20bbb7d7df16aeda37e8c3bf8495bedc6c3)
* [luci-base: allow submitting new value in android chromium](https://github.com/openwrt/luci/commit/5cb2eb619e16e8de247c193ab7d320743491107e)
* [luci-base: standards compliant dropdown fix for mobile keyboards](https://github.com/openwrt/luci/commit/77e01d3d8cf9d2cf66368f4dd02ab691d67654ba)
* [luci-base: replace css right class with button-row](https://github.com/openwrt/luci/commit/959fd4479580ddbe0f86de351d06226027a351a0)

[openwrt-24.10] luci-base: backport fixes from master
